# Liner Regression amaliy

In [99]:
import pandas as pd 
df=pd.read_csv('Student_Placement_Career_Prediction_Dataset.csv')

In [100]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  10000 non-null  int64
 1   age                         10000 non-null  int64
 2   gender                      10000 non-null  str
 3   branch                      10000 non-null  str
 4   cgpa                        10000 non-null  float64
 5   internship_count            10000 non-null  int64
 6   project_count               10000 non-null  int64
 7   certifications_count        10000 non-null  int64
 8   coding_skills_score         10000 non-null  int64
 9   communication_skills_score  10000 non-null  int64
 10  soft_skills_score           10000 non-null  int64
 11  hackathon_participation     10000 non-null  str
 12  placement_status            10000 non-null  str
dtypes: float64(1), int64(8), str(4)
memory usage: 1015.8 KB

# Data bilan tanishuv

In [101]:
df.head()

,student_id,age,gender,branch,cgpa,internship_count,project_count,certifications_count,coding_skills_score,communication_skills_score,soft_skills_score,hackathon_participation,placement_status
0,1,23,Male,IT,8.99,4,6,2,41,71,59,Yes,Placed
1,2,24,Female,Mechanical,8.36,4,7,5,42,64,97,No,Placed
2,3,22,Female,EEE,7.18,4,5,2,84,98,51,No,Placed
3,4,24,Female,Mechanical,6.28,0,2,4,60,100,92,No,Not Placed
4,5,24,Female,IT,5.30,3,4,1,78,61,77,No,Not Placed

In [102]:
df = df.drop('student_id', axis=1)

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         10000 non-null  int64
 1   gender                      10000 non-null  str
 2   branch                      10000 non-null  str
 3   cgpa                        10000 non-null  float64
 4   internship_count            10000 non-null  int64
 5   project_count               10000 non-null  int64
 6   certifications_count        10000 non-null  int64
 7   coding_skills_score         10000 non-null  int64
 8   communication_skills_score  10000 non-null  int64
 9   soft_skills_score           10000 non-null  int64
 10  hackathon_participation     10000 non-null  str
 11  placement_status            10000 non-null  str
dtypes: float64(1), int64(7), str(4)
memory usage: 937.6 KB

# Data preprocessing

In [104]:
df.isnull().sum()

age                           0
gender                        0
branch                        0
cgpa                          0
internship_count              0
project_count                 0
certifications_count          0
coding_skills_score           0
communication_skills_score    0
soft_skills_score             0
hackathon_participation       0
placement_status              0
dtype: int64

# Encoding

In [105]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'str':
        if df[col].nunique() <= 5:
            dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
            df = pd.concat([df.drop(columns=[col]), dummies], axis=1)
        else:
            df[col] = encoder.fit_transform(df[col])

In [106]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   age                          10000 non-null  int64
 1   branch                       10000 non-null  int64
 2   cgpa                         10000 non-null  float64
 3   internship_count             10000 non-null  int64
 4   project_count                10000 non-null  int64
 5   certifications_count         10000 non-null  int64
 6   coding_skills_score          10000 non-null  int64
 7   communication_skills_score   10000 non-null  int64
 8   soft_skills_score            10000 non-null  int64
 9   gender_Female                10000 non-null  int64
 10  gender_Male                  10000 non-null  int64
 11  hackathon_participation_No   10000 non-null  int64
 12  hackathon_participation_Yes  10000 non-null  int64
 13  placement_status_Not Placed  10000 non-null  int64
 14  placement_status_Placed      10000 non-null  int64
dtypes: float64(1), int64(14)
memory usage: 1.1 MB

# Scaling

In [107]:
df.head()

,age,branch,cgpa,internship_count,project_count,certifications_count,coding_skills_score,communication_skills_score,soft_skills_score,gender_Female,gender_Male,hackathon_participation_No,hackathon_participation_Yes,placement_status_Not Placed,placement_status_Placed
0,23,4,8.99,4,6,2,41,71,59,0,1,0,1,0,1
1,24,5,8.36,4,7,5,42,64,97,1,0,1,0,0,1
2,22,3,7.18,4,5,2,84,98,51,1,0,1,0,0,1
3,24,5,6.28,0,2,4,60,100,92,1,0,1,0,1,0
4,24,4,5.30,3,4,1,78,61,77,1,0,1,0,1,0

In [108]:
from sklearn.preprocessing import MinMaxScaler 
scaler=MinMaxScaler()

In [109]:
num_col=df.select_dtypes(include=['int64','float64']).columns

In [110]:
num_col

Index(['age', 'branch', 'cgpa', 'internship_count', 'project_count',
       'certifications_count', 'coding_skills_score',
       'communication_skills_score', 'soft_skills_score', 'gender_Female',
       'gender_Male', 'hackathon_participation_No',
       'hackathon_participation_Yes', 'placement_status_Not Placed',
       'placement_status_Placed'],
      dtype='str')

In [111]:
df[num_col]=scaler.fit_transform(df[num_col])

In [112]:
df.head()

,age,branch,cgpa,internship_count,project_count,certifications_count,coding_skills_score,communication_skills_score,soft_skills_score,gender_Female,gender_Male,hackathon_participation_No,hackathon_participation_Yes,placement_status_Not Placed,placement_status_Placed
0,0.6,0.8,0.798,1.00,0.833333,0.4,0.016667,0.516667,0.316667,0.0,1.0,0.0,1.0,0.0,1.0
1,0.8,1.0,0.672,1.00,1.000000,1.0,0.033333,0.400000,0.950000,1.0,0.0,1.0,0.0,0.0,1.0
2,0.4,0.6,0.436,1.00,0.666667,0.4,0.733333,0.966667,0.183333,1.0,0.0,1.0,0.0,0.0,1.0
3,0.8,1.0,0.256,0.00,0.166667,0.8,0.333333,1.000000,0.866667,1.0,0.0,1.0,0.0,1.0,0.0
4,0.8,0.8,0.060,0.75,0.500000,0.2,0.633333,0.350000,0.616667,1.0,0.0,1.0,0.0,1.0,0.0

# Model selection

In [113]:
from sklearn.linear_model import LinearRegression

In [114]:
lr=LinearRegression()

In [115]:
lr

LinearRegression()

# Training

In [116]:
x=df.drop('cgpa',axis=1)

In [117]:
y=df['cgpa']

In [118]:
from sklearn.model_selection import train_test_split

In [119]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [120]:
lr.fit(x_train,y_train)

LinearRegression()

# Prediction

In [121]:
y_pred=lr.predict(x_test)

In [122]:
y_pred[0]

np.float64(0.44029761054771843)

# Evaluation

In [123]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [124]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [125]:
print('MAE:', mae)
print('MSE:', mse)
print('R2:', r2)

MAE: 0.18284691679864648
MSE: 0.05022345480143985
R2: 0.4141906465598112