For loop orqali missing qiymatlarni tozalang(5 tasini ishlatishga xarakat qiling)

In [96]:
import pandas as pd

In [97]:
df=pd.read_csv('student_dataset.csv')

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   float64
 1   Attendance                  6528 non-null   float64
 2   Parental_Involvement        3365 non-null   str
 3   Access_to_Resources         3349 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6606 non-null   float64
 6   Previous_Scores             6555 non-null   float64
 7   Motivation_Level            3386 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Final_Exam_Score            6541 non-null   float64
dtypes: float64(5), int64(1), str(5)
memory usage: 567.9 KB

In [99]:
df.isnull().sum()

Hours_Studied                    0
Attendance                      79
Parental_Involvement          3242
Access_to_Resources           3258
Extracurricular_Activities       0
Sleep_Hours                      1
Previous_Scores                 52
Motivation_Level              3221
Internet_Access                  0
Tutoring_Sessions                0
Final_Exam_Score                66
dtype: int64

MEAN VA MODE USULLARI

In [100]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype == 'str':
            df[col]=df[col].fillna(df[col].mode()[0])
        else:
            df[col]=df[col].fillna(df[col].mean())

In [101]:
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Final_Exam_Score              0
dtype: int64

drop va fixed usullari

In [102]:
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Final_Exam_Score              0
dtype: int64

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   float64
 1   Attendance                  6607 non-null   float64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   float64
 6   Previous_Scores             6607 non-null   float64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Final_Exam_Score            6607 non-null   float64
dtypes: float64(5), int64(1), str(5)
memory usage: 567.9 KB

In [104]:
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Final_Exam_Score              0
dtype: int64

In [105]:
for col in df.columns:
    if df[col].isnull().sum() > 3000:
        df = df.drop(col, axis=1)

In [106]:
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Final_Exam_Score              0
dtype: int64

In [107]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   float64
 1   Attendance                  6607 non-null   float64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   float64
 6   Previous_Scores             6607 non-null   float64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Final_Exam_Score            6607 non-null   float64
dtypes: float64(5), int64(1), str(5)
memory usage: 567.9 KB

In [108]:
#fixed va median orqali to'ldirish
for col in df.columns:
     if df[col].isnull().any():
        if df[col].dtype == 'str': 
              df[col]=df[col].fillna('yes') #fixed usuli
        if df[col].dtype == 'float64':
             df[col]=df[col].fillna(df[col].median())

In [109]:
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Final_Exam_Score              0
dtype: int64

For loop orqali encoding qiling

In [110]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   float64
 1   Attendance                  6607 non-null   float64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   float64
 6   Previous_Scores             6607 non-null   float64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Final_Exam_Score            6607 non-null   float64
dtypes: float64(5), int64(1), str(5)
memory usage: 567.9 KB

In [111]:
df.nunique()

Hours_Studied                 352
Attendance                    397
Parental_Involvement            1
Access_to_Resources             1
Extracurricular_Activities      2
Sleep_Hours                    62
Previous_Scores               497
Motivation_Level                1
Internet_Access                 2
Tutoring_Sessions               9
Final_Exam_Score              474
dtype: int64

In [113]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

In [114]:
encoder

LabelEncoder()

In [115]:
for col in df.columns:
    if df[col].dtype=='str':
        if df[col].nunique()<=5:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [116]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hours_Studied                   6607 non-null   float64
 1   Attendance                      6607 non-null   float64
 2   Sleep_Hours                     6607 non-null   float64
 3   Previous_Scores                 6607 non-null   float64
 4   Tutoring_Sessions               6607 non-null   int64
 5   Final_Exam_Score                6607 non-null   float64
 6   Parental_Involvement_Medium     6607 non-null   int64
 7   Access_to_Resources_Medium      6607 non-null   int64
 8   Extracurricular_Activities_No   6607 non-null   int64
 9   Extracurricular_Activities_Yes  6607 non-null   int64
 10  Motivation_Level_Medium         6607 non-null   int64
 11  Internet_Access_No              6607 non-null   int64
 12  Internet_Access_Yes             6607 non-null   int64
dtypes: float64(5), int64(8)
memory usage: 671.2 KB

Scaling 3ta usulda

In [30]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [31]:
df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Final_Exam_Score,Parental_Involvement_Medium,Access_to_Resources_Medium,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Motivation_Level_Medium,Internet_Access_No,Internet_Access_Yes
0,23.5,84.2,7.4,50.3,1,54.3,1,1,0,1,1,0,1
1,19.7,63.6,6.7,83.1,2,59.4,1,1,0,1,1,0,1
2,24.4,98.4,8.0,63.5,0,63.8,1,1,0,1,1,0,1
3,29.6,88.6,6.3,57.5,2,61.0,1,1,0,1,1,0,1
4,19.1,91.5,6.2,66.0,2,60.7,1,1,0,1,1,0,1

In [32]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Final_Exam_Score')   # izoh: Target qiymat scalimng qilinmaydi

In [33]:
num_col

Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Parental_Involvement_Medium',
       'Access_to_Resources_Medium', 'Extracurricular_Activities_No',
       'Extracurricular_Activities_Yes', 'Motivation_Level_Medium',
       'Internet_Access_No', 'Internet_Access_Yes'],
      dtype='str')

STANDART SCALER

StandardScaler bu affected by outliers da ko'proq ishlatiladi va bu ham manfiy ham musbat qiymatlarga o'tkazib scaling qilib beradi

In [35]:
scaler=StandardScaler()

In [36]:
scaler

StandardScaler()

In [37]:
df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Final_Exam_Score,Parental_Involvement_Medium,Access_to_Resources_Medium,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Motivation_Level_Medium,Internet_Access_No,Internet_Access_Yes
0,23.5,84.2,7.4,50.3,1,54.3,1,1,0,1,1,0,1
1,19.7,63.6,6.7,83.1,2,59.4,1,1,0,1,1,0,1
2,24.4,98.4,8.0,63.5,0,63.8,1,1,0,1,1,0,1
3,29.6,88.6,6.3,57.5,2,61.0,1,1,0,1,1,0,1
4,19.1,91.5,6.2,66.0,2,60.7,1,1,0,1,1,0,1

In [39]:
df['Attendance']=scaler.fit_transform(df[['Attendance']])

In [40]:
df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Final_Exam_Score,Parental_Involvement_Medium,Access_to_Resources_Medium,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Motivation_Level_Medium,Internet_Access_No,Internet_Access_Yes
0,23.5,0.365830,7.4,50.3,1,54.3,1,1,0,1,1,0,1
1,19.7,-1.425579,6.7,83.1,2,59.4,1,1,0,1,1,0,1
2,24.4,1.600685,8.0,63.5,0,63.8,1,1,0,1,1,0,1
3,29.6,0.748462,6.3,57.5,2,61.0,1,1,0,1,1,0,1
4,19.1,1.000650,6.2,66.0,2,60.7,1,1,0,1,1,0,1

MIN MAX SCALER

MIN MAX SCALER bu compress qilib faqat 0dan 1gacha bo'lgan qiymatlarni orasiga tushurib beradi

In [41]:
scaler=MinMaxScaler()

In [42]:
df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Final_Exam_Score,Parental_Involvement_Medium,Access_to_Resources_Medium,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Motivation_Level_Medium,Internet_Access_No,Internet_Access_Yes
0,23.5,0.365830,7.4,50.3,1,54.3,1,1,0,1,1,0,1
1,19.7,-1.425579,6.7,83.1,2,59.4,1,1,0,1,1,0,1
2,24.4,1.600685,8.0,63.5,0,63.8,1,1,0,1,1,0,1
3,29.6,0.748462,6.3,57.5,2,61.0,1,1,0,1,1,0,1
4,19.1,1.000650,6.2,66.0,2,60.7,1,1,0,1,1,0,1

In [43]:
df['Hours_Studied']=scaler.fit_transform(df[['Hours_Studied']])

In [44]:
df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Final_Exam_Score,Parental_Involvement_Medium,Access_to_Resources_Medium,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Motivation_Level_Medium,Internet_Access_No,Internet_Access_Yes
0,0.522145,0.365830,7.4,50.3,1,54.3,1,1,0,1,1,0,1
1,0.433566,-1.425579,6.7,83.1,2,59.4,1,1,0,1,1,0,1
2,0.543124,1.600685,8.0,63.5,0,63.8,1,1,0,1,1,0,1
3,0.664336,0.748462,6.3,57.5,2,61.0,1,1,0,1,1,0,1
4,0.419580,1.000650,6.2,66.0,2,60.7,1,1,0,1,1,0,1

Robust Scaler simmetrik data setlar uchun, bitta simmetriyadan chiqib ketgan datalarni scaling qilishda ishlatiladi

In [49]:
scaler=RobustScaler()

In [50]:
df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Final_Exam_Score,Parental_Involvement_Medium,Access_to_Resources_Medium,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Motivation_Level_Medium,Internet_Access_No,Internet_Access_Yes
0,0.522145,0.365830,0.566667,50.3,1,54.3,1,1,0,1,1,0,1
1,0.433566,-1.425579,0.450000,83.1,2,59.4,1,1,0,1,1,0,1
2,0.543124,1.600685,0.666667,63.5,0,63.8,1,1,0,1,1,0,1
3,0.664336,0.748462,0.383333,57.5,2,61.0,1,1,0,1,1,0,1
4,0.419580,1.000650,0.366667,66.0,2,60.7,1,1,0,1,1,0,1

In [51]:
df['Sleep_Hours']=scaler.fit_transform(df[['Sleep_Hours']])

In [52]:
df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Final_Exam_Score,Parental_Involvement_Medium,Access_to_Resources_Medium,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Motivation_Level_Medium,Internet_Access_No,Internet_Access_Yes
0,0.522145,0.365830,0.111111,50.3,1,54.3,1,1,0,1,1,0,1
1,0.433566,-1.425579,-0.277778,83.1,2,59.4,1,1,0,1,1,0,1
2,0.543124,1.600685,0.444444,63.5,0,63.8,1,1,0,1,1,0,1
3,0.664336,0.748462,-0.500000,57.5,2,61.0,1,1,0,1,1,0,1
4,0.419580,1.000650,-0.555556,66.0,2,60.7,1,1,0,1,1,0,1

# For Loop + Scaling

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   float64
 1   Attendance                  6607 non-null   float64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   float64
 6   Previous_Scores             6607 non-null   float64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Final_Exam_Score            6607 non-null   float64
dtypes: float64(5), int64(1), str(5)
memory usage: 567.9 KB

In [117]:
#1-usul
scaler=MinMaxScaler()
for col in df.columns:
    if df[col].dtype!='str':
        df[col]=scaler.fit_transform(df[[col]])
        num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Final_Exam_Score')

In [118]:
df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Final_Exam_Score,Parental_Involvement_Medium,Access_to_Resources_Medium,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Motivation_Level_Medium,Internet_Access_No,Internet_Access_Yes
0,0.522145,0.6050,0.566667,0.006,0.125,0.375573,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0.433566,0.0900,0.450000,0.662,0.250,0.453435,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.543124,0.9600,0.666667,0.270,0.000,0.520611,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.664336,0.7150,0.383333,0.150,0.250,0.477863,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.419580,0.7875,0.366667,0.320,0.250,0.473282,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [119]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Final_Exam_Score')   # izoh: Final_Exam_Score ustunini target qilib oldim va Target qiymat scalimng qilinmaydi

In [120]:
df[num_col]=scaler.fit_transform(df[num_col])

In [121]:

df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Final_Exam_Score,Parental_Involvement_Medium,Access_to_Resources_Medium,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Motivation_Level_Medium,Internet_Access_No,Internet_Access_Yes
0,0.522145,0.6050,0.566667,0.006,0.125,0.375573,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0.433566,0.0900,0.450000,0.662,0.250,0.453435,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.543124,0.9600,0.666667,0.270,0.000,0.520611,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.664336,0.7150,0.383333,0.150,0.250,0.477863,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.419580,0.7875,0.366667,0.320,0.250,0.473282,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [124]:
#2-usul
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Final_Exam_Score') 
for col in num_col:
    df[col]=scaler.fit_transform(df[[col]])

In [125]:
df.head()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Final_Exam_Score,Parental_Involvement_Medium,Access_to_Resources_Medium,Extracurricular_Activities_No,Extracurricular_Activities_Yes,Motivation_Level_Medium,Internet_Access_No,Internet_Access_Yes
0,0.522145,0.6050,0.566667,0.006,0.125,0.375573,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0.433566,0.0900,0.450000,0.662,0.250,0.453435,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.543124,0.9600,0.666667,0.270,0.000,0.520611,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.664336,0.7150,0.383333,0.150,0.250,0.477863,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.419580,0.7875,0.366667,0.320,0.250,0.473282,0.0,0.0,0.0,1.0,0.0,0.0,1.0