# Classification dataset yuklab (Tabulate)

In [65]:
import pandas as pd
df=pd.read_csv("Social_media_impact_on_life.csv")

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    1704 non-null   float64
 1   Age                           1705 non-null   int64
 2   Gender                        1703 non-null   str
 3   Academic_Level                1704 non-null   str
 4   Country                       1704 non-null   str
 5   Avg_Daily_Usage_Hours         1705 non-null   float64
 6   Most_Used_Platform            1705 non-null   str
 7   Affects_Academic_Performance  1704 non-null   str
 8   Sleep_Hours_Per_Night         1705 non-null   float64
 9   Mental_Health_Score           1705 non-null   float64
 10  Overall_Impact                1705 non-null   str
dtypes: float64(4), int64(1), str(6)
memory usage: 146.7 KB

In [67]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Overall_Impact'],
      dtype='str')

In [68]:
df.drop('Student_ID',inplace=True,axis=1)

In [69]:
df.isnull().sum()

Age                             0
Gender                          2
Academic_Level                  1
Country                         1
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    1
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Overall_Impact                  0
dtype: int64

In [70]:
# Missinfg value
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return df

In [71]:
df=toldir(df)

In [72]:
df.isna().any()

Age                             False
Gender                          False
Academic_Level                  False
Country                         False
Avg_Daily_Usage_Hours           False
Most_Used_Platform              False
Affects_Academic_Performance    False
Sleep_Hours_Per_Night           False
Mental_Health_Score             False
Overall_Impact                  False
dtype: bool

In [73]:
df.nunique()

Age                               7
Gender                            2
Academic_Level                    3
Country                         111
Avg_Daily_Usage_Hours            71
Most_Used_Platform               12
Affects_Academic_Performance      2
Sleep_Hours_Per_Night            59
Mental_Health_Score              51
Overall_Impact                    3
dtype: int64

In [74]:
# Encoding
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=="str":
            if df[col].nunique()<=3:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [75]:
df=encodla(df)

In [76]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Age                               1705 non-null   int64
 1   Country                           1705 non-null   int64
 2   Avg_Daily_Usage_Hours             1705 non-null   float64
 3   Most_Used_Platform                1705 non-null   int64
 4   Sleep_Hours_Per_Night             1705 non-null   float64
 5   Mental_Health_Score               1705 non-null   float64
 6   Gender_Female                     1705 non-null   int64
 7   Gender_Male                       1705 non-null   int64
 8   Academic_Level_Graduate           1705 non-null   int64
 9   Academic_Level_High School        1705 non-null   int64
 10  Academic_Level_Undergraduate      1705 non-null   int64
 11  Affects_Academic_Performance_No   1705 non-null   int64
 12  Affects_Academic_Performance_Yes  1705 non-null   int64
 13  Overall_Impact_Negative           1705 non-null   int64
 14  Overall_Impact_Neutral            1705 non-null   int64
 15  Overall_Impact_Positive           1705 non-null   int64
dtypes: float64(3), int64(13)
memory usage: 213.3 KB

In [77]:
df.drop(['Affects_Academic_Performance_No','Gender_Female'],axis=1,inplace=True)

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Age                               1705 non-null   int64
 1   Country                           1705 non-null   int64
 2   Avg_Daily_Usage_Hours             1705 non-null   float64
 3   Most_Used_Platform                1705 non-null   int64
 4   Sleep_Hours_Per_Night             1705 non-null   float64
 5   Mental_Health_Score               1705 non-null   float64
 6   Gender_Male                       1705 non-null   int64
 7   Academic_Level_Graduate           1705 non-null   int64
 8   Academic_Level_High School        1705 non-null   int64
 9   Academic_Level_Undergraduate      1705 non-null   int64
 10  Affects_Academic_Performance_Yes  1705 non-null   int64
 11  Overall_Impact_Negative           1705 non-null   int64
 12  Overall_Impact_Neutral            1705 non-null   int64
 13  Overall_Impact_Positive           1705 non-null   int64
dtypes: float64(3), int64(11)
memory usage: 186.6 KB

In [79]:
df.head()

,Age,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score,Gender_Male,Academic_Level_Graduate,Academic_Level_High School,Academic_Level_Undergraduate,Affects_Academic_Performance_Yes,Overall_Impact_Negative,Overall_Impact_Neutral,Overall_Impact_Positive
0,21,73,4.0,0,6.7,6.8,1,0,0,1,0,0,1,0
1,23,73,1.6,4,8.6,7.6,0,0,0,1,0,0,0,1
2,22,18,4.6,1,6.7,7.0,1,1,0,0,0,0,1,0
3,18,73,7.0,5,5.4,5.3,1,0,0,1,1,1,0,0
4,24,73,7.5,0,5.0,4.4,1,0,1,0,1,1,0,0

In [80]:
# Scaling
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
def scal_qil(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Affects_Academic_Performance_Yes')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [81]:
df=scal_qil(df)

In [82]:
# cols = ['Age', 'City', 'Daily_Usage_Hours']  ---> bizda uchta ustunni scaling qilish uchun
# df = scale_columns(df, cols)

In [83]:
# from sklearn.preprocessing import MinMaxScaler
# def scale_columns_minmax(df, cols):
#    scaler = MinMaxScaler()   
#    df[cols] = scaler.fit_transform(df[cols])   
#    return df

In [84]:
df.head()

,Age,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score,Gender_Male,Academic_Level_Graduate,Academic_Level_High School,Academic_Level_Undergraduate,Affects_Academic_Performance_Yes,Overall_Impact_Negative,Overall_Impact_Neutral,Overall_Impact_Positive
0,0.500000,0.663636,0.357143,0.000000,0.500000,0.56,1.0,0.0,0.0,1.0,0,0.0,1.0,0.0
1,0.833333,0.663636,0.014286,0.363636,0.827586,0.72,0.0,0.0,0.0,1.0,0,0.0,0.0,1.0
2,0.666667,0.163636,0.442857,0.090909,0.500000,0.60,1.0,1.0,0.0,0.0,0,0.0,1.0,0.0
3,0.000000,0.663636,0.785714,0.454545,0.275862,0.26,1.0,0.0,0.0,1.0,1,1.0,0.0,0.0
4,1.000000,0.663636,0.857143,0.000000,0.206897,0.08,1.0,0.0,1.0,0.0,1,1.0,0.0,0.0

In [85]:
# Input va Output qiymatlarga ajratin olamiz
x=df.drop('Affects_Academic_Performance_Yes',axis=1)
y=df['Affects_Academic_Performance_Yes']

In [86]:
# Model_selection ya'ni train, test va splitga ajratib olish
from sklearn.model_selection import train_test_split

In [87]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# Logistic Regression

In [88]:
# Model(algorithm) chaqirish
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [89]:
lr

LogisticRegression()

In [90]:
# Modelni o'qitish
lr.fit(x_train,y_train)

LogisticRegression()

In [91]:
# Predict qilish
y_pred=lr.predict(x_test)

In [92]:
# Evaluation yani metrics orqali tekshirish
from sklearn.metrics import classification_report, confusion_matrix

In [93]:
log_cr=classification_report(y_test,y_pred)
log_cm=confusion_matrix(y_test,y_pred)

In [94]:
print(log_cr)
print(log_cm)

#  ---> bu test_size=0.3 qilgan holatimiz

#        precision    recall  f1-score   support 

#           0       0.82      0.76      0.79       209
#           1       0.84      0.89      0.86       303

#    accuracy                           0.84       512
#   macro avg       0.83      0.82      0.83       512
#weighted avg       0.84      0.84      0.83       512

#[[159  50]
# [ 34 269]]

              precision    recall  f1-score   support

           0       0.80      0.73      0.77       141
           1       0.82      0.88      0.85       200

    accuracy                           0.82       341
   macro avg       0.81      0.80      0.81       341
weighted avg       0.81      0.82      0.81       341

[[103  38]
 [ 25 175]]

# K-Fold cross validation

In [95]:
from sklearn.model_selection import KFold, cross_val_score

In [96]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [97]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [98]:
scores=cross_val_score(lr,x,y,cv=kf,scoring="accuracy")

In [99]:
print(scores)

[0.81524927 0.85337243 0.82111437 0.81524927 0.82111437]

In [100]:
for i in scores:
    print(i)

0.8152492668621701
0.8533724340175953
0.8211143695014663
0.8152492668621701
0.8211143695014663

In [101]:
import numpy as np

In [102]:
np.mean(scores)   # accuracy --->   0.82

np.float64(0.8252199413489736)

In [103]:
np.std(scores)

np.float64(0.014318540311711075)

# Decision tree

In [104]:
from sklearn.tree import DecisionTreeClassifier

In [105]:
dtc=DecisionTreeClassifier()
dtc

DecisionTreeClassifier()

In [106]:
# modelni o'qitish
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [107]:
# Predict qilish
y_predict=lr.predict(x_test)

In [108]:
from sklearn.metrics import classification_report, confusion_matrix

In [109]:
decision_class_report=classification_report(y_test,y_predict)
decision_con_mat=confusion_matrix(y_test,y_predict)

In [110]:
print(decision_class_report)
print(decision_con_mat)

              precision    recall  f1-score   support

           0       0.80      0.73      0.77       141
           1       0.82      0.88      0.85       200

    accuracy                           0.82       341
   macro avg       0.81      0.80      0.81       341
weighted avg       0.81      0.82      0.81       341

[[103  38]
 [ 25 175]]

# Random Forest

In [111]:
from sklearn.ensemble import RandomForestClassifier   # RandomForestClassifier -> ensemble oilasiga ham kiradi
rfc=RandomForestClassifier()

In [112]:
rfc

RandomForestClassifier()

In [113]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [114]:
y_predition=rfc.predict(x_test)

In [115]:
from sklearn.metrics import classification_report, confusion_matrix

In [116]:
random_clsr=classification_report(y_test,y_predition)
random_con_mat=confusion_matrix(y_test,y_predition)

In [117]:
print(random_clsr)
print(random_con_mat)

              precision    recall  f1-score   support

           0       0.83      0.75      0.79       141
           1       0.84      0.90      0.86       200

    accuracy                           0.84       341
   macro avg       0.84      0.82      0.83       341
weighted avg       0.84      0.84      0.83       341

[[106  35]
 [ 21 179]]

# Tabulate orqali solishtirib chiroyli ko'rinishga keltirish

In [118]:
# Tabulateni import qilib olamiz
from tabulate import tabulate

In [119]:
results = [
    ['Logistic Regression',0.82,0.80,0.73,0.77],
    ['Decision Tree',0.82,0.80,0.73,0.77],
    ['Random Forest',0.84,0.86,0.77,0.81]
]
headers=['Algorithm nomlari','accuracy','Precision', 'Recall', 'F1-Score']
table=tabulate(results,headers=headers,tablefmt='grid',floatfmt='.2f')

In [120]:
print(table)

+---------------------+------------+-------------+----------+------------+
| Algorithm nomlari   |   accuracy |   Precision |   Recall |   F1-Score |
+=====================+============+=============+==========+============+
| Logistic Regression |       0.82 |        0.80 |     0.73 |       0.77 |
+---------------------+------------+-------------+----------+------------+
| Decision Tree       |       0.82 |        0.80 |     0.73 |       0.77 |
+---------------------+------------+-------------+----------+------------+
| Random Forest       |       0.84 |        0.86 |     0.77 |       0.81 |
+---------------------+------------+-------------+----------+------------+