 # ?Scaling

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/Users/a1/Desktop/MLFoundation/Bank_Personal_Loan_Modelling(1).csv')

In [3]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1/60,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1/50,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1/00,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2/70,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1/00,2,0,0,0,0,0,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: int64(13), object(1)
memory usage: 547.0+ KB

In [6]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object': 
            df[col].fillna(df[col].mode()[0], inplace=True)
        else:
            df[col].fillna(df[col].mean(), inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: int64(13), object(1)
memory usage: 547.0+ KB

In [8]:
df.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

# Encoding

# Scaling

In [9]:
# Object qiymatlar bo`maganligi uchun bu bosqichni tashlab ketamiz`

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: int64(13), object(1)
memory usage: 547.0+ KB

In [12]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1/60,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1/50,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1/00,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2/70,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1/00,2,0,0,0,0,0,1

In [23]:
num_col = df.select_dtypes(include=['int64', 'float64']).columns.drop('Personal Loan')

In [22]:
num_col

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'Education',
       'Mortgage', 'Personal Loan', 'Securities Account', 'CD Account',
       'Online', 'CreditCard'],
      dtype='object')

In [24]:
num_col

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'Education',
       'Mortgage', 'Securities Account', 'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [15]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

# Standard Scaler

In [25]:
scaler=StandardScaler()

In [26]:
scaler

StandardScaler()

In [27]:
df['Age']=scaler.fit_transform(df[['Age']])

In [28]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,-1.774417,1,49,91107,4,1/60,1,0,0,1,0,0,0
1,2,-0.029524,19,34,90089,3,1/50,1,0,0,1,0,0,0
2,3,-0.552992,15,11,94720,1,1/00,1,0,0,0,0,0,0
3,4,-0.901970,9,100,94112,1,2/70,2,0,0,0,0,0,0
4,5,-0.901970,8,45,91330,4,1/00,2,0,0,0,0,0,1

In [29]:
scaler = MinMaxScaler()

In [30]:
scaler

MinMaxScaler()

In [31]:
df['ZIP Code']=scaler.fit_transform(df[['ZIP Code']])

In [32]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,-1.774417,1,49,0.936527,4,1/60,1,0,0,1,0,0,0
1,2,-0.029524,19,34,0.924872,3,1/50,1,0,0,1,0,0,0
2,3,-0.552992,15,11,0.977892,1,1/00,1,0,0,0,0,0,0
3,4,-0.901970,9,100,0.970931,1,2/70,2,0,0,0,0,0,0
4,5,-0.901970,8,45,0.939080,4,1/00,2,0,0,0,0,0,1

# Robust Scaler

In [33]:
scaler = RobustScaler()

In [34]:
scaler

RobustScaler()

In [35]:
df['Family'] = scaler.fit_transform(df[['Family']])

In [36]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,-1.774417,1,49,0.936527,1.0,1/60,1,0,0,1,0,0,0
1,2,-0.029524,19,34,0.924872,0.5,1/50,1,0,0,1,0,0,0
2,3,-0.552992,15,11,0.977892,-0.5,1/00,1,0,0,0,0,0,0
3,4,-0.901970,9,100,0.970931,-0.5,2/70,2,0,0,0,0,0,0
4,5,-0.901970,8,45,0.939080,1.0,1/00,2,0,0,0,0,0,1

# for loop + scaling

In [41]:
scaler = MinMaxScaler()
for col in df.columns:
    if df[col].dtype != 'object':
        df[col] = scaler.fit_transform(df[[col]])

In [39]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,0.0000,0.045455,0.086957,0.189815,0.936527,1.000000,1/60,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0002,0.500000,0.478261,0.120370,0.924872,0.666667,1/50,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0004,0.363636,0.391304,0.013889,0.977892,0.000000,1/00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0006,0.272727,0.260870,0.425926,0.970931,0.000000,2/70,0.5,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0008,0.272727,0.239130,0.171296,0.939080,1.000000,1/00,0.5,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
num_col = df.select_dtypes(include=['int64', 'float64']).columns.drop('Personal Loan')

In [42]:
num_col

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'Education',
       'Mortgage', 'Securities Account', 'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [44]:
df[num_col]=scaler.fit_transform(df[num_col])

In [45]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,0.0000,0.045455,0.086957,0.189815,0.936527,1.000000,1/60,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0002,0.500000,0.478261,0.120370,0.924872,0.666667,1/50,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0004,0.363636,0.391304,0.013889,0.977892,0.000000,1/00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0006,0.272727,0.260870,0.425926,0.970931,0.000000,2/70,0.5,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0008,0.272727,0.239130,0.171296,0.939080,1.000000,1/00,0.5,0.0,0.0,0.0,0.0,0.0,1.0

In [49]:
for col in num_col:
    df[col]=scaler.fit_transform(df[[col]])

In [50]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,0.0000,0.045455,0.086957,0.189815,0.936527,1.000000,1/60,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0002,0.500000,0.478261,0.120370,0.924872,0.666667,1/50,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0004,0.363636,0.391304,0.013889,0.977892,0.000000,1/00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0006,0.272727,0.260870,0.425926,0.970931,0.000000,2/70,0.5,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0008,0.272727,0.239130,0.171296,0.939080,1.000000,1/00,0.5,0.0,0.0,0.0,0.0,0.0,1.0