# Dataset

In [1]:
import pandas as pd
df=pd.read_csv("dataset (1).csv")

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62288 entries, 0 to 62287
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    62284 non-null  float64
 1   Age                   62282 non-null  float64
 2   Agency                62281 non-null  str
 3   Agency Type           62284 non-null  str
 4   Commision (in value)  62275 non-null  float64
 5   Destination           62279 non-null  str
 6   Distribution Channel  62283 non-null  str
 7   Duration              62279 non-null  float64
 8   Gender                22709 non-null  str
 9   Net Sales             62283 non-null  float64
 10  Product Name          62283 non-null  str
 11  Claim                 62288 non-null  int64
dtypes: float64(5), int64(1), str(6)
memory usage: 5.7 MB

# Missing value

In [3]:
df.isnull().sum()

ID                          4
Age                         6
Agency                      7
Agency Type                 4
Commision (in value)       13
Destination                 9
Distribution Channel        5
Duration                    9
Gender                  39579
Net Sales                   5
Product Name                5
Claim                       0
dtype: int64

In [4]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=="str":
            df[col] = df[col].fillna(df[col].mode()[0])
        else:
            df[col] = df[col].fillna(df[col].mean())

# Funcion + Missing value

In [5]:
def missing_value(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=="str":
                df[col] = df[col].fillna(df[col].mode()[0])
            else:
                df[col] = df[col].fillna(df[col].mean())
    return df

In [6]:
df = missing_value(df)

In [7]:
missing_value(df)

,ID,Age,Agency,Agency Type,Commision (in value),Destination,Distribution Channel,Duration,Gender,Net Sales,Product Name,Claim
0,45341.0,28.0,C2B,Airlines,28.130000,SINGAPORE,Online,34.0,F,112.5,Silver Plan,1
1,12958.0,37.0,JZI,Airlines,12.950000,SINGAPORE,Online,53.0,F,37.0,Basic Plan,0
2,18233.0,27.0,EPX,Travel Agency,12.828865,UNITED STATES,Online,28.0,F,13.0,Cancellation Plan,0
3,31742.0,36.0,EPX,Travel Agency,0.000000,SAUDI ARABIA,Online,1.0,F,34.0,Cancellation Plan,0
4,14381.0,26.0,CWT,Travel Agency,12.828865,THAILAND,Online,33.0,F,39.6,Rental Vehicle Excess Insurance,0
...,...,...,...,...,...,...,...,...,...,...,...,...
62283,36315.0,36.0,EPX,Travel Agency,0.000000,HONG KONG,Online,17.0,F,28.0,2 way Comprehensive Plan,0
62284,2511.0,56.0,JZI,Airlines,9.100000,AUSTRALIA,Online,9.0,F,26.0,Basic Plan,0
62285,16874.0,36.0,EPX,Travel Agency,0.000000,ITALY,Online,216.0,F,20.0,2 way Comprehensive Plan,1
62286,14801.0,29.0,CWT,Travel Agency,11.880000,AUSTRALIA,Online,37.0,F,19.8,Rental Vehicle Excess Insurance,1
62287,5550.0,44.0,EPX,Travel Agency,0.000000,THAILAND,Online,70.0,F,20.0,Cancellation Plan,0

In [8]:
df.isnull().any()

ID                      False
Age                     False
Agency                  False
Agency Type             False
Commision (in value)    False
Destination             False
Distribution Channel    False
Duration                False
Gender                  False
Net Sales               False
Product Name            False
Claim                   False
dtype: bool

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62288 entries, 0 to 62287
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    62288 non-null  float64
 1   Age                   62288 non-null  float64
 2   Agency                62288 non-null  str
 3   Agency Type           62288 non-null  str
 4   Commision (in value)  62288 non-null  float64
 5   Destination           62288 non-null  str
 6   Distribution Channel  62288 non-null  str
 7   Duration              62288 non-null  float64
 8   Gender                62288 non-null  str
 9   Net Sales             62288 non-null  float64
 10  Product Name          62288 non-null  str
 11  Claim                 62288 non-null  int64
dtypes: float64(5), int64(1), str(6)
memory usage: 5.7 MB

# Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
encoder=LabelEncoder()

In [12]:
encoder

LabelEncoder()

In [13]:
df.nunique()

ID                      50755
Age                        90
Agency                     16
Agency Type                 2
Commision (in value)      941
Destination               102
Distribution Channel        2
Duration                  444
Gender                      2
Net Sales                1038
Product Name               25
Claim                       2
dtype: int64

In [14]:
#for col in df.columns:
    #if df[col].dtype=="String":
        #if df[col].nunique()<=3:
            #dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            #df=pd.concat([df.drop(columns=[col]), dummies], axis=1)
        #else:
            #df[col]=encoder.fit_transfor(df[col])

# Funcion + Encoding

In [25]:
def encodla(df):
    for col in df.columns:
        if df[col].dtypes=="object":
            if df[col].nunique() <= 3:
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                df = pd.concat([df.drop(columns=[col]), dummies], axis=1)
            else:
                df[col] = encoder.fit_transform(df[col])
    return df

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62288 entries, 0 to 62287
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            62288 non-null  float64
 1   Age                           62288 non-null  float64
 2   Agency                        62288 non-null  int64
 3   Commision (in value)          62288 non-null  float64
 4   Destination                   62288 non-null  int64
 5   Duration                      62288 non-null  float64
 6   Net Sales                     62288 non-null  float64
 7   Product Name                  62288 non-null  int64
 8   Claim                         62288 non-null  int64
 9   Agency Type_Airlines          62288 non-null  int64
 10  Agency Type_Travel Agency     62288 non-null  int64
 11  Distribution Channel_Offline  62288 non-null  int64
 12  Distribution Channel_Online   62288 non-null  int64
 13  Gender_F                      62288 non-null  int64
 14  Gender_M                      62288 non-null  int64
dtypes: float64(5), int64(10)
memory usage: 7.1 MB

In [27]:
df = encodla(df)

In [28]:
df

,ID,Age,Agency,Commision (in value),Destination,Duration,Net Sales,Product Name,Claim,Agency Type_Airlines,Agency Type_Travel Agency,Distribution Channel_Offline,Distribution Channel_Online,Gender_F,Gender_M
0,45341.0,28.0,2,28.130000,79,34.0,112.5,17,1,1,0,0,1,1,0
1,12958.0,37.0,9,12.950000,79,53.0,37.0,8,0,1,0,0,1,1,0
2,18233.0,27.0,7,12.828865,96,28.0,13.0,10,0,0,1,0,1,1,0
3,31742.0,36.0,7,0.000000,78,1.0,34.0,10,0,0,1,0,1,1,0
4,14381.0,26.0,6,12.828865,88,33.0,39.6,16,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62283,36315.0,36.0,7,0.000000,34,17.0,28.0,1,0,0,1,0,1,1,0
62284,2511.0,56.0,9,9.100000,1,9.0,26.0,8,0,1,0,0,1,1,0
62285,16874.0,36.0,7,0.000000,42,216.0,20.0,1,1,0,1,0,1,1,0
62286,14801.0,29.0,6,11.880000,1,37.0,19.8,16,1,0,1,0,1,1,0
62287,5550.0,44.0,7,0.000000,88,70.0,20.0,10,0,0,1,0,1,1,0

# Logistic Regression tekshirish

In [29]:
from sklearn.linear_model import LogisticRegression

In [44]:
lr=LogisticRegression()
lr

LogisticRegression()

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62288 entries, 0 to 62287
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            62288 non-null  float64
 1   Age                           62288 non-null  float64
 2   Agency                        62288 non-null  int64
 3   Commision (in value)          62288 non-null  float64
 4   Destination                   62288 non-null  int64
 5   Duration                      62288 non-null  float64
 6   Net Sales                     62288 non-null  float64
 7   Product Name                  62288 non-null  int64
 8   Claim                         62288 non-null  int64
 9   Agency Type_Airlines          62288 non-null  int64
 10  Agency Type_Travel Agency     62288 non-null  int64
 11  Distribution Channel_Offline  62288 non-null  int64
 12  Distribution Channel_Online   62288 non-null  int64
 13  Gender_F                      62288 non-null  int64
 14  Gender_M                      62288 non-null  int64
dtypes: float64(5), int64(10)
memory usage: 7.1 MB

In [32]:
num_col = df.select_dtypes(include=['int64', 'float64']).columns.drop('Claim',errors='ignore')
# errors="ignore" -> errors='ignore' → kodni xavfsiz qiladi
# Ayniqsa:
# ustun bor-yo‘qligiga ishonching bo‘lmasa

In [33]:
num_col

Index(['ID', 'Age', 'Agency', 'Commision (in value)', 'Destination',
       'Duration', 'Net Sales', 'Product Name', 'Agency Type_Airlines',
       'Agency Type_Travel Agency', 'Distribution Channel_Offline',
       'Distribution Channel_Online', 'Gender_F', 'Gender_M'],
      dtype='str')

In [34]:
x = df.drop('Claim',axis=1)
y = df['Claim']

In [35]:
# train_test_split
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [37]:
x_train.shape

(49830, 14)

In [38]:
y_train.shape

(49830,)

In [39]:
x_test.shape

(12458, 14)

In [40]:
y_test.shape

(12458,)

In [ ]:
lr=LogisticRegression()
lr

LogisticRegression()

In [50]:
lr.fit(x_train,y_train) # scaling qilinmagani uchun hali to'liq o'rganolmagan

C:\Users\WIN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Prediction

In [51]:
y_pred=lr.predict(x_test)

In [54]:
y_pred[1:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0])

# Evaluation

In [55]:
from sklearn.metrics import confusion_matrix, classification_report

In [56]:
# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

In [57]:
cm

array([[9595,  385],
       [1895,  583]])

In [59]:
# Classification Report
class_report = classification_report(y_test, y_pred)

In [60]:
class_report

'              precision    recall  f1-score   support\n\n           0       0.84      0.96      0.89      9980\n           1       0.60      0.24      0.34      2478\n\n    accuracy                           0.82     12458\n   macro avg       0.72      0.60      0.62     12458\nweighted avg       0.79      0.82      0.78     12458\n'

In [61]:
print(class_report)

              precision    recall  f1-score   support

           0       0.84      0.96      0.89      9980
           1       0.60      0.24      0.34      2478

    accuracy                           0.82     12458
   macro avg       0.72      0.60      0.62     12458
weighted avg       0.79      0.82      0.78     12458