# Data bilan tanishuv

In [61]:
import pandas as pd 
df=pd.read_csv('job_salary_prediction_dataset.csv')

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 19.1 MB

In [63]:
df.isnull().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [64]:
df.drop(['job_title', 'location'], axis=1)

,experience_years,education_level,skills_count,industry,company_size,remote_work,certifications,salary
0,10,Bachelor,2,Healthcare,Medium,Hybrid,2,109413
1,5,Bachelor,17,Telecom,Small,No,0,93764
2,18,PhD,4,Media,Medium,No,1,148123
3,19,PhD,13,Retail,Medium,Yes,0,189123
4,15,Bachelor,7,Manufacturing,Large,Yes,0,165069
...,...,...,...,...,...,...,...,...
249995,17,PhD,2,Telecom,Enterprise,No,1,127791
249996,20,PhD,7,Telecom,Startup,No,2,154593
249997,1,Bachelor,12,Retail,Enterprise,Yes,0,75988
249998,0,High School,2,Consulting,Small,Hybrid,5,90467
249999,16,Diploma,2,Technology,Medium,No,5,133084

# Data preprocessing

# Encoding

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 19.1 MB

In [66]:
from sklearn.preprocessing import LabelEncoder 
encoder=LabelEncoder()

In [67]:
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [68]:
df=encodla(df)

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   job_title           250000 non-null  int64
 1   experience_years    250000 non-null  int64
 2   education_level     250000 non-null  int64
 3   skills_count        250000 non-null  int64
 4   industry            250000 non-null  int64
 5   company_size        250000 non-null  int64
 6   location            250000 non-null  int64
 7   certifications      250000 non-null  int64
 8   salary              250000 non-null  int64
 9   remote_work_Hybrid  250000 non-null  int64
 10  remote_work_No      250000 non-null  int64
 11  remote_work_Yes     250000 non-null  int64
dtypes: int64(12)
memory usage: 22.9 MB

# Scaling

In [70]:
from sklearn.preprocessing import MinMaxScaler

In [71]:
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col = df.select_dtypes(include=['int64','float64']).columns
    df[num_col]=scaler.fit_transform(df[num_col]) 
    return df

In [72]:
df=scaling_qil(df)

In [73]:
df.sample(8)

,job_title,experience_years,education_level,skills_count,industry,company_size,location,certifications,salary,remote_work_Hybrid,remote_work_No,remote_work_Yes
26407,0.000000,0.80,0.25,0.611111,0.555556,0.50,0.444444,0.2,0.476365,0.0,0.0,1.0
42674,0.909091,0.75,0.00,0.388889,0.888889,1.00,0.555556,0.8,0.370172,0.0,0.0,1.0
201878,0.727273,0.70,1.00,0.222222,0.666667,0.00,0.888889,0.4,0.589616,1.0,0.0,0.0
24047,1.000000,0.10,0.50,0.722222,0.777778,0.25,0.444444,0.4,0.227104,1.0,0.0,0.0
128462,0.090909,0.40,0.50,0.333333,0.222222,0.50,0.222222,0.0,0.315414,0.0,0.0,1.0
47450,0.545455,0.15,0.50,0.111111,0.888889,0.75,0.000000,0.8,0.218601,0.0,0.0,1.0
117795,0.545455,0.00,0.25,0.277778,0.555556,0.25,0.555556,0.8,0.268362,1.0,0.0,0.0
137876,0.272727,0.35,0.75,0.500000,0.777778,0.50,0.333333,0.0,0.201870,0.0,0.0,1.0

# Train,Test split

In [74]:
X=df.drop('salary',axis=1)

In [75]:
y=df['salary']

In [76]:
y

0         0.257475
1         0.205516
2         0.386003
3         0.522135
4         0.442269
            ...
249995    0.318495
249996    0.407485
249997    0.146494
249998    0.194569
249999    0.336069
Name: salary, Length: 250000, dtype: float64

In [77]:
from sklearn.model_selection import train_test_split

In [78]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Model Selection

In [79]:
from sklearn.linear_model import LinearRegression

In [80]:
lr=LinearRegression()

In [81]:
lr.fit(X_train, y_train)

LinearRegression()

# Prediction

In [82]:
y_pred=lr.predict(X_test)
y_pred

array([0.23581855, 0.3219477 , 0.25920915, ..., 0.4761369 , 0.43301276,
       0.20906463], shape=(50000,))

# Evaluatin

In [83]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [84]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=pow(mse,(1/2))
mae=mean_absolute_error(y_test,y_pred)

In [85]:
print(r2)
print(mse)
print(rmse)
print(mae)

0.4571856773442967
0.008317141995299123
0.09119836618766326
0.0721035622568045

# Decision Tree

In [108]:
from sklearn.tree import DecisionTreeRegressor

In [109]:
dr=DecisionTreeRegressor()

In [110]:
dr

DecisionTreeRegressor()

In [111]:
dr.fit(X_train,y_train)

DecisionTreeRegressor()

# Pridict

In [113]:
y_pred=dr.predict(X_test)

In [114]:
y_pred

array([0.44517048, 0.23267891, 0.15594713, ..., 0.39450958, 0.39010024,
       0.27994648], shape=(50000,))

In [115]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [117]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [118]:
print('r2:',r2)
print('mae:',mae)
print('mse:',mse)

r2: 0.930834575180775
mae: 0.025263483144575154
mse: 0.0010597705981158433