In [41]:
pip install kagglehub

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kagglehub in /Users/sherzodbeksharobiddinov/Library/Python/3.9/lib/python/site-packages (0.3.13)
Requirement already satisfied: pyyaml in /Users/sherzodbeksharobiddinov/Library/Python/3.9/lib/python/site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: packaging in /Users/sherzodbeksharobiddinov/Library/Python/3.9/lib/python/site-packages (from kagglehub) (26.0)
Requirement already satisfied: requests in /Users/sherzodbeksharobiddinov/Library/Python/3.9/lib/python/site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in /Users/sherzodbeksharobiddinov/Library/Python/3.9/lib/python/site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/sherzodbeksharobiddinov/Library/Python/3.9/lib/python/site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/sherzodbeksharobiddinov/Library/Python/3.9/lib/python/site-packages (from requests->kagglehub) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /Users/sherzodbeksharobiddinov/Library/Python/3.9/lib/python/site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /Users/sherzodbeksharobiddinov/Library/Python/3.9/lib/python/site-packages (from requests->kagglehub) (2026.2.25)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [42]:
import pandas as pd 

import kagglehub

# Download latest version
path = kagglehub.dataset_download("camnugent/california-housing-prices")

df = pd.read_csv(f"{path}/housing.csv")
df.head()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [43]:
print("Datanin Null qiymatlari")
print(df.isnull().any())
print(df.isnull().sum())

Datanin Null qiymatlari
longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [44]:
print("Dataning Columnslari")
print(df.columns)

Dataning Columnslari
Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [46]:
df = df.drop(columns=["total_bedrooms"])
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [47]:
def toldir(df):
	for col in df.columns:
		if df[col].isnull().any():
			if df[col].dtype == "object":
				df[col] = df[col].fillna(df[col].mode()[0], inplace = True)
			else:
				df[col] = df[col].fillna(df[col].median(), inplace = True)
	return df
df = toldir(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   population          20640 non-null  float64
 5   households          20640 non-null  float64
 6   median_income       20640 non-null  float64
 7   median_house_value  20640 non-null  float64
 8   ocean_proximity     20640 non-null  object
dtypes: float64(8), object(1)
memory usage: 1.4+ MB

In [48]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
df['ocean_proximity'] = label.fit_transform(df['ocean_proximity'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   population          20640 non-null  float64
 5   households          20640 non-null  float64
 6   median_income       20640 non-null  float64
 7   median_house_value  20640 non-null  float64
 8   ocean_proximity     20640 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.4 MB

In [49]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
num_cols = df.select_dtypes(include = ["float64","int64"]).columns
print(num_cols)
df[num_cols] = minmax.fit_transform(df[num_cols])
df.head()

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'population', 'households', 'median_income', 'median_house_value',
       'ocean_proximity'],
      dtype='object')

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,median_house_value,ocean_proximity
0,0.211155,0.567481,0.784314,0.022331,0.008941,0.020556,0.539668,0.902266,0.75
1,0.212151,0.565356,0.392157,0.180503,0.067210,0.186976,0.538027,0.708247,0.75
2,0.210159,0.564293,1.000000,0.037260,0.013818,0.028943,0.466028,0.695051,0.75
3,0.209163,0.564293,1.000000,0.032352,0.015555,0.035849,0.354699,0.672783,0.75
4,0.209163,0.564293,1.000000,0.041330,0.015752,0.042427,0.230776,0.674638,0.75

In [50]:
from sklearn.model_selection import train_test_split
x = df.drop(["median_house_value"], axis = 1)
y = df["median_house_value"]


x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

print("Train hajmi", x_train.shape)
print("Test hajmi", x_test.shape)

Train hajmi (16512, 8)
Test hajmi (4128, 8)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import pandas as pd
linearRegression = LinearRegression()
linearRegression.fit(x_train,y_train)
y_pred = linearRegression.predict(x_test)

# modelni aniqroq korish uchun qoshimcha qilindi
comparison_df = pd.DataFrame({
    'Asl qiymat (y_test)': y_test.values,
    'Bashorat (y_pred)': y_pred,
    'Xatolik farqi': y_test.values - y_pred
})
print("--- Model baholash metrikalari ---")
print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

--- Model baholash metrikalari ---
R2 Score: 0.6204380147295053
MAE: 0.10652356384383005
MSE: 0.021144747846013664

In [52]:
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
treeClassifier = DecisionTreeClassifier()
treeRegressor = DecisionTreeRegressor()
treeRegressor.fit(x_train,y_train)
y_pred = treeRegressor.predict(x_test) 

comparison_df = pd.DataFrame({
    'Asl qiymat (y_test)': y_test.values,
    'Bashorat (y_pred)': y_pred,
    'Xatolik farqi': y_test.values - y_pred
})

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

R2 Score: 0.6622423220115324
MAE: 0.08754263378487148
MSE: 0.01881590151614268