# Data bn tanishuv

In [35]:
import pandas as pd 
df=pd.read_csv('airport_traffic_2025.csv')

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 116020 entries, 0 to 116019
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   YEAR           116020 non-null  int64
 1   MONTH_NUM      116020 non-null  int64
 2   MONTH_MON      116020 non-null  str
 3   FLT_DATE       116020 non-null  str
 4   APT_ICAO       116020 non-null  str
 5   APT_NAME       116020 non-null  str
 6   STATE_NAME     116020 non-null  str
 7   FLT_DEP_1      116020 non-null  int64
 8   FLT_ARR_1      116020 non-null  int64
 9   FLT_TOT_1      116020 non-null  int64
 10  FLT_DEP_IFR_2  34128 non-null   float64
 11  FLT_ARR_IFR_2  34128 non-null   float64
 12  FLT_TOT_IFR_2  34128 non-null   float64
dtypes: float64(3), int64(5), str(5)
memory usage: 11.5 MB

In [37]:
df.isnull().sum()

YEAR                 0
MONTH_NUM            0
MONTH_MON            0
FLT_DATE             0
APT_ICAO             0
APT_NAME             0
STATE_NAME           0
FLT_DEP_1            0
FLT_ARR_1            0
FLT_TOT_1            0
FLT_DEP_IFR_2    81892
FLT_ARR_IFR_2    81892
FLT_TOT_IFR_2    81892
dtype: int64

In [38]:
df.sample(5)

,YEAR,MONTH_NUM,MONTH_MON,FLT_DATE,APT_ICAO,APT_NAME,STATE_NAME,FLT_DEP_1,FLT_ARR_1,FLT_TOT_1,FLT_DEP_IFR_2,FLT_ARR_IFR_2,FLT_TOT_IFR_2
25995,2025,3,MAR,2025-03-24,LEVT,Vitoria,Spain,17,14,31,NaN,NaN,NaN
52529,2025,6,JUN,2025-06-15,EGNX,East Midlands,United Kingdom,74,76,150,NaN,NaN,NaN
88321,2025,10,OCT,2025-10-05,EGPH,Edinburgh,United Kingdom,193,192,385,192.0,191.0,383.0
101197,2025,11,NOV,2025-11-15,UGSB,Batumi,Georgia,10,7,17,NaN,NaN,NaN
52717,2025,6,JUN,2025-06-16,ENKR,Kirkenes Høybuktmoen,Norway,10,10,20,NaN,NaN,NaN

# Encoding

In [39]:
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [40]:
df=encodla(df)

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 116020 entries, 0 to 116019
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   YEAR           116020 non-null  int64
 1   MONTH_NUM      116020 non-null  int64
 2   MONTH_MON      116020 non-null  int64
 3   FLT_DATE       116020 non-null  int64
 4   APT_ICAO       116020 non-null  int64
 5   APT_NAME       116020 non-null  int64
 6   STATE_NAME     116020 non-null  int64
 7   FLT_DEP_1      116020 non-null  int64
 8   FLT_ARR_1      116020 non-null  int64
 9   FLT_TOT_1      116020 non-null  int64
 10  FLT_DEP_IFR_2  34128 non-null   float64
 11  FLT_ARR_IFR_2  34128 non-null   float64
 12  FLT_TOT_IFR_2  34128 non-null   float64
dtypes: float64(3), int64(10)
memory usage: 11.5 MB

In [42]:
df = df.drop([
    'FLT_DEP_IFR_2',
    'FLT_ARR_IFR_2',
    'FLT_TOT_IFR_2'
], axis=1)

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 116020 entries, 0 to 116019
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   YEAR        116020 non-null  int64
 1   MONTH_NUM   116020 non-null  int64
 2   MONTH_MON   116020 non-null  int64
 3   FLT_DATE    116020 non-null  int64
 4   APT_ICAO    116020 non-null  int64
 5   APT_NAME    116020 non-null  int64
 6   STATE_NAME  116020 non-null  int64
 7   FLT_DEP_1   116020 non-null  int64
 8   FLT_ARR_1   116020 non-null  int64
 9   FLT_TOT_1   116020 non-null  int64
dtypes: int64(10)
memory usage: 8.9 MB

# Scaling

In [44]:
from sklearn.preprocessing import MinMaxScaler

In [45]:
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col = df.select_dtypes(include=['int64','float64']).columns
    df[num_col]=scaler.fit_transform(df[num_col]) 
    return df

In [46]:
df=scaling_qil(df)

In [47]:
df.sample(8)

,YEAR,MONTH_NUM,MONTH_MON,FLT_DATE,APT_ICAO,APT_NAME,STATE_NAME,FLT_DEP_1,FLT_ARR_1,FLT_TOT_1
3099,0.0,0.000000,0.363636,0.027473,0.875758,0.715152,0.195122,0.125296,0.126777,0.126185
40901,0.0,0.363636,0.727273,0.354396,0.336364,0.769697,0.731707,0.027187,0.027251,0.027251
68278,0.0,0.636364,0.090909,0.590659,0.021212,0.248485,0.341463,0.027187,0.028436,0.027844
98009,0.0,0.909091,0.818182,0.846154,0.800000,0.403030,0.365854,0.018913,0.020142,0.019550
9517,0.0,0.000000,0.363636,0.082418,0.224242,0.327273,0.707317,0.022459,0.022512,0.022512
92463,0.0,0.818182,0.909091,0.796703,0.957576,0.045455,0.975610,0.147754,0.151659,0.149882
112102,0.0,1.000000,0.181818,0.967033,0.851515,0.748485,0.487805,0.535461,0.528436,0.532583
66523,0.0,0.545455,0.454545,0.574176,0.475758,0.427273,0.902439,0.021277,0.020142,0.020735

In [48]:
import os

# Train

In [49]:
X = df.drop('FLT_TOT_1', axis=1) 
y = df['FLT_TOT_1']

In [50]:
y

0         0.074645
1         0.065758
2         0.007701
3         0.029028
4         0.001185
            ...
116015    0.065758
116016    0.040284
116017    0.085900
116018    0.162322
116019    0.261848
Name: FLT_TOT_1, Length: 116020, dtype: float64

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Liner R

In [53]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [54]:
y_pred = model.predict(X_test)

In [55]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2:", r2)

MAE: 1.8605054471504743e-16
MSE: 5.040162192883349e-32
R2: 1.0

# random f

In [56]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, y_train)

RandomForestRegressor()

In [57]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2:", r2)

MAE: 1.8605054471504743e-16
MSE: 5.040162192883349e-32
R2: 1.0

# Deci

In [58]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(random_state=42)
model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [59]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [60]:
y_pred = model.predict(X_test)

In [61]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2:", r2)

MAE: 0.00011052290379746692
MSE: 2.8890054638599214e-07
R2: 0.9999869294890616

In [62]:
X_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

svr = SVR()

svr.fit(x_train, y_train)

y_pred = svr.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(mae)
print(mse)
print(rmse)
print(r2)

NameError: name 'x' is not defined

In [ ]:
from tabulate import tabulate

result = [
    ['Logistic Regression',1.860, 5.040,1.0],
    ['Random Forest',1.860,5.040,1.0],
    ['DecisionTreeRegressor',0.000,2.889,0.999]
]

headers = ['Algorithm', 'MAE','MSE','R2']

table = tabulate(result, headers=headers, tablefmt='grid')

print(table)

+-----------------------+-------+-------+-------+
| Algorithm             |   MAE |   MSE |    R2 |
+=======================+=======+=======+=======+
| Logistic Regression   |  1.86 | 5.04  | 1     |
+-----------------------+-------+-------+-------+
| Random Forest         |  1.86 | 5.04  | 1     |
+-----------------------+-------+-------+-------+
| DecisionTreeRegressor |  0    | 2.889 | 0.999 |
+-----------------------+-------+-------+-------+