# Algorithms

In [157]:
import pandas as pd 
df=pd.read_csv('user_music_listen_data.csv')

In [158]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   User_ID       453 non-null    str
 1   T_Swift       444 non-null    float64
 2   Drake         439 non-null    float64
 3   Queen         441 non-null    float64
 4   The_Weeknd    442 non-null    float64
 5   Eminem        444 non-null    float64
 6   Nirvana       435 non-null    float64
 7   Ed_Sheeran    449 non-null    float64
 8   T_Scott       441 non-null    float64
 9   Linkin_Park   443 non-null    float64
 10  Dua_Lipa      445 non-null    float64
 11  K_Lamar       438 non-null    float64
 12  Imag_Dragons  439 non-null    float64
 13  Ariana_G      440 non-null    float64
dtypes: float64(13), str(1)
memory usage: 49.7 KB

In [159]:
from sklearn.preprocessing import LabelEncoder 
encoder=LabelEncoder

In [160]:
encoder

sklearn.preprocessing._label.LabelEncoder

In [161]:
from sklearn.linear_model import LinearRegression, LogisticRegression

In [162]:
Ir=LinearRegression()

In [163]:
Ir

LinearRegression()

In [164]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

In [165]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

In [166]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   User_ID       453 non-null    str
 1   T_Swift       444 non-null    float64
 2   Drake         439 non-null    float64
 3   Queen         441 non-null    float64
 4   The_Weeknd    442 non-null    float64
 5   Eminem        444 non-null    float64
 6   Nirvana       435 non-null    float64
 7   Ed_Sheeran    449 non-null    float64
 8   T_Scott       441 non-null    float64
 9   Linkin_Park   443 non-null    float64
 10  Dua_Lipa      445 non-null    float64
 11  K_Lamar       438 non-null    float64
 12  Imag_Dragons  439 non-null    float64
 13  Ariana_G      440 non-null    float64
dtypes: float64(13), str(1)
memory usage: 49.7 KB

In [167]:
df.drop('Nirvana',axis=1,inplace=True)

In [168]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   User_ID       453 non-null    str
 1   T_Swift       444 non-null    float64
 2   Drake         439 non-null    float64
 3   Queen         441 non-null    float64
 4   The_Weeknd    442 non-null    float64
 5   Eminem        444 non-null    float64
 6   Ed_Sheeran    449 non-null    float64
 7   T_Scott       441 non-null    float64
 8   Linkin_Park   443 non-null    float64
 9   Dua_Lipa      445 non-null    float64
 10  K_Lamar       438 non-null    float64
 11  Imag_Dragons  439 non-null    float64
 12  Ariana_G      440 non-null    float64
dtypes: float64(12), str(1)
memory usage: 46.1 KB

In [169]:
df.head()

,User_ID,T_Swift,Drake,Queen,The_Weeknd,Eminem,Ed_Sheeran,T_Scott,Linkin_Park,Dua_Lipa,K_Lamar,Imag_Dragons,Ariana_G
0,User_1001,53.0,0.0,87.0,102.0,0.0,112.0,79.0,64.0,0.0,49.0,212.0,112.0
1,User_1002,144.0,NaN,53.0,194.0,31.0,150.0,47.0,45.0,213.0,47.0,232.0,157.0
2,User_1003,0.0,47.0,64.0,203.0,75.0,213.0,93.0,19.0,180.0,103.0,199.0,176.0
3,User_1004,136.0,45.0,0.0,97.0,40.0,NaN,62.0,15.0,105.0,73.0,190.0,111.0
4,User_1005,110.0,33.0,52.0,127.0,51.0,57.0,0.0,0.0,98.0,66.0,124.0,66.0

# Scaling

In [170]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_numeric = df.drop('User_ID', axis=1)
df[df_numeric.columns] = scaler.fit_transform(df_numeric)

In [171]:
df.head()

,User_ID,T_Swift,Drake,Queen,The_Weeknd,Eminem,Ed_Sheeran,T_Scott,Linkin_Park,Dua_Lipa,K_Lamar,Imag_Dragons,Ariana_G
0,User_1001,0.141711,0.000000,0.283388,0.303571,0.000000,0.358974,0.372642,0.212625,0.000000,0.174377,0.452026,0.449799
1,User_1002,0.385027,NaN,0.172638,0.577381,0.121569,0.480769,0.221698,0.149502,0.702970,0.167260,0.494670,0.630522
2,User_1003,0.000000,0.116625,0.208469,0.604167,0.294118,0.682692,0.438679,0.063123,0.594059,0.366548,0.424307,0.706827
3,User_1004,0.363636,0.111663,0.000000,0.288690,0.156863,NaN,0.292453,0.049834,0.346535,0.259786,0.405117,0.445783
4,User_1005,0.294118,0.081886,0.169381,0.377976,0.200000,0.182692,0.000000,0.000000,0.323432,0.234875,0.264392,0.265060

In [172]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   User_ID       453 non-null    str
 1   T_Swift       444 non-null    float64
 2   Drake         439 non-null    float64
 3   Queen         441 non-null    float64
 4   The_Weeknd    442 non-null    float64
 5   Eminem        444 non-null    float64
 6   Ed_Sheeran    449 non-null    float64
 7   T_Scott       441 non-null    float64
 8   Linkin_Park   443 non-null    float64
 9   Dua_Lipa      445 non-null    float64
 10  K_Lamar       438 non-null    float64
 11  Imag_Dragons  439 non-null    float64
 12  Ariana_G      440 non-null    float64
dtypes: float64(12), str(1)
memory usage: 46.1 KB

x----> inputs
y----> outputs

In [173]:
num_col=df.select_dtypes(include=['float64']).columns

In [174]:
num_col

Index(['T_Swift', 'Drake', 'Queen', 'The_Weeknd', 'Eminem', 'Ed_Sheeran',
       'T_Scott', 'Linkin_Park', 'Dua_Lipa', 'K_Lamar', 'Imag_Dragons',
       'Ariana_G'],
      dtype='str')

In [175]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   User_ID       453 non-null    str
 1   T_Swift       444 non-null    float64
 2   Drake         439 non-null    float64
 3   Queen         441 non-null    float64
 4   The_Weeknd    442 non-null    float64
 5   Eminem        444 non-null    float64
 6   Ed_Sheeran    449 non-null    float64
 7   T_Scott       441 non-null    float64
 8   Linkin_Park   443 non-null    float64
 9   Dua_Lipa      445 non-null    float64
 10  K_Lamar       438 non-null    float64
 11  Imag_Dragons  439 non-null    float64
 12  Ariana_G      440 non-null    float64
dtypes: float64(12), str(1)
memory usage: 46.1 KB

In [176]:
x = df.drop(['Ariana_G', 'Imag_Dragons'], axis=1)

In [177]:
y=df['T_Scott']

In [178]:
y

0      0.372642
1      0.221698
2      0.438679
3      0.292453
4      0.000000
         ...
448    0.429245
449    0.193396
450    0.000000
451    0.094340
452    0.311321
Name: T_Scott, Length: 453, dtype: float64

In [179]:
x

,User_ID,T_Swift,Drake,Queen,The_Weeknd,Eminem,Ed_Sheeran,T_Scott,Linkin_Park,Dua_Lipa,K_Lamar
0,User_1001,0.141711,0.000000,0.283388,0.303571,0.000000,0.358974,0.372642,0.212625,0.000000,0.174377
1,User_1002,0.385027,NaN,0.172638,0.577381,0.121569,0.480769,0.221698,0.149502,0.702970,0.167260
2,User_1003,0.000000,0.116625,0.208469,0.604167,0.294118,0.682692,0.438679,0.063123,0.594059,0.366548
3,User_1004,0.363636,0.111663,0.000000,0.288690,0.156863,NaN,0.292453,0.049834,0.346535,0.259786
4,User_1005,0.294118,0.081886,0.169381,0.377976,0.200000,0.182692,0.000000,0.000000,0.323432,0.234875
...,...,...,...,...,...,...,...,...,...,...,...
448,User_1449,0.176471,0.000000,0.267101,0.342262,0.180392,0.455128,0.429245,0.431894,0.270627,0.078292
449,User_1450,0.556150,0.000000,0.130293,0.428571,0.078431,0.570513,0.193396,0.156146,0.567657,0.167260
450,User_1451,0.096257,0.099256,0.136808,0.044643,0.360784,0.044872,0.000000,0.196013,0.000000,0.046263
451,User_1452,0.197861,0.047146,0.205212,0.345238,0.262745,0.000000,0.094340,0.398671,0.442244,0.138790
452,User_1453,0.000000,NaN,0.000000,0.208333,0.243137,0.076923,0.311321,0.000000,0.125413,0.459075

In [180]:
from sklearn.model_selection import train_test_split

In [181]:
x_tarin,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [182]:
x_tarin.shape

(317, 11)

In [183]:
x_test.shape

(136, 11)

In [184]:
y_train.shape

(317,)

In [185]:

y_test.shape

(136,)

In [186]:
from sklearn.linear_model import LogisticRegression

In [187]:
log_reg = LogisticRegression()

In [188]:
log_reg

LogisticRegression()

In [189]:
log_reg. fit(x_tarin , y_train)

ValueError: could not convert string to float: 'User_1413'

In [ ]:
X = df.drop(['User_ID', 'Ariana_G'], axis=1)
y = df['Ariana_G']

In [ ]:
X = X.fillna(X.mean())
y = y.fillna(y.mean())

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

y_pred = lin_reg.predict(X_test)

In [ ]:
y_pred[1:5]

array([-0.00341642,  0.80382093,  0.53182619,  0.10247825])

In [ ]:
from sklearn.metrics import accuracy_score
mse = mean_squared_error(y_test, y_pred)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# regression metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("MAE:", mae)
print("R2:", r2)

MSE: 0.02464631859129488
MAE: 0.10646814410280571
R2: 0.46663451838436665