FOR  LOOP ni organish

In [50]:
a=[1,2,3]
for i in a:
    print(i)

1
2
3

In [51]:
for i in a:
    print(i+1)

2
3
4

In [52]:
for i in a:
    print(i*2)

2
4
6

In [53]:
for element in a:
    
    print(element/2)

0.5
1.0
1.5

In [54]:
b=['Hello','Hi','Bye']
for i in b:
    print(len(i))

5
2
3

In [55]:
s=['Salom','Assalomu alaykum','xayr']
for i in s:
    print(len(i))

5
16
4

In [56]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10

In [57]:
for i in range(1,10):
    if i%2!=0:
        print(i)

1
3
5
7
9

In [58]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9

In [59]:
for i in range(2,11,2):
    print(i)

2
4
6
8
10

In [27]:
import pandas as pd
df=pd.read_csv("online_learning_platform_usage_dataset.csv")

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  420 non-null    int64
 1   age_group                420 non-null    str
 2   role                     420 non-null    str
 3   primary_platform         420 non-null    str
 4   learning_device          202 non-null    str
 5   hours_per_week           419 non-null    float64
 6   learning_purpose         419 non-null    str
 7   content_type_preference  273 non-null    str
 8   completion_rate_percent  415 non-null    float64
 9   satisfaction_score       414 non-null    float64
dtypes: float64(3), int64(1), str(6)
memory usage: 32.9 KB

In [62]:
df.head()

,user_id,age_group,role,primary_platform,learning_device,hours_per_week,learning_purpose,content_type_preference,completion_rate_percent,satisfaction_score
0,1,35-44,Working Professional,edX,NaN,10.0,Career Growth,Text,34.0,5.0
1,2,45+,Other,edX,NaN,12.0,Career Growth,Text,17.0,3.0
2,3,25-34,Freelancer,Skillshare,Desktop,2.0,Academic,Text,67.0,9.0
3,4,45+,Working Professional,Udemy,NaN,3.0,Career Growth,Mixed,25.0,5.0
4,5,45+,Working Professional,Khan Academy,NaN,10.0,Hobby,NaN,81.0,5.0

For loopdan foydalangan xolda va foydalanmagan xolda missing qiymatlarni 5 ta usulda to’ldiring

MEAN USULIDA TO'LDIRISH.
 hours_per_week man shu ustun int da ekan shuninng uchun mean da to'ldirib oldim

In [ ]:
df['hours_per_week']=df['hours_per_week'].fillna(df['hours_per_week'].mean())

In [ ]:
df.isnull().sum()

user_id                      0
age_group                    0
role                         0
primary_platform             0
learning_device            218
hours_per_week               1
learning_purpose             1
content_type_preference    147
completion_rate_percent      5
satisfaction_score           6
dtype: int64

In [70]:
df.isnull().sum()

user_id                      0
age_group                    0
role                         0
primary_platform             0
learning_device            218
hours_per_week               0
learning_purpose             1
content_type_preference    147
completion_rate_percent      5
satisfaction_score           6
dtype: int64

MODE USULIDA TO'LDIRISH

In [72]:
df['learning_device']=df['learning_device'].fillna(df['learning_device'].mode()[0])

In [73]:
df.isnull().sum()

user_id                      0
age_group                    0
role                         0
primary_platform             0
learning_device              0
hours_per_week               0
learning_purpose             1
content_type_preference    147
completion_rate_percent      5
satisfaction_score           6
dtype: int64

MEDIAN USULIDA TO'LDIRISH

In [74]:
df['completion_rate_percent']=df['completion_rate_percent'].fillna(df['completion_rate_percent'].median())

In [ ]:
df.isnull().sum()

user_id                      0
age_group                    0
role                         0
primary_platform             0
learning_device              0
hours_per_week               0
learning_purpose             1
content_type_preference    147
completion_rate_percent      0
satisfaction_score           6
dtype: int64

In [79]:
df.head()

,user_id,age_group,role,primary_platform,learning_device,hours_per_week,learning_purpose,content_type_preference,completion_rate_percent,satisfaction_score
0,1,35-44,Working Professional,edX,Tablet,10.0,Career Growth,Text,34.0,5.0
1,2,45+,Other,edX,Tablet,12.0,Career Growth,Text,17.0,3.0
2,3,25-34,Freelancer,Skillshare,Desktop,2.0,Academic,Text,67.0,9.0
3,4,45+,Working Professional,Udemy,Tablet,3.0,Career Growth,Mixed,25.0,5.0
4,5,45+,Working Professional,Khan Academy,Tablet,10.0,Hobby,NaN,81.0,5.0

FIXED USULIDA TO'LDIRISH

In [84]:

df['content_type_preference'] = df['content_type_preference'].fillna('text')

In [85]:
df.isnull().sum()

user_id                    0
age_group                  0
role                       0
primary_platform           0
learning_device            0
hours_per_week             0
learning_purpose           1
content_type_preference    0
completion_rate_percent    0
satisfaction_score         6
dtype: int64

DROP USULIDA TASHLAB YUBORISH

In [91]:
df.drop('user_id',axis=1,inplace=True)

In [ ]:
df.isnull().sum()

age_group                  0
role                       0
primary_platform           0
learning_device            0
hours_per_week             0
learning_purpose           1
content_type_preference    0
completion_rate_percent    0
satisfaction_score         6
dtype: int64

Data Preprocessing + for loop

 Missing + for loop

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user_id                  420 non-null    int64
 1   age_group                420 non-null    str
 2   role                     420 non-null    str
 3   primary_platform         420 non-null    str
 4   learning_device          202 non-null    str
 5   hours_per_week           419 non-null    float64
 6   learning_purpose         419 non-null    str
 7   content_type_preference  273 non-null    str
 8   completion_rate_percent  415 non-null    float64
 9   satisfaction_score       414 non-null    float64
dtypes: float64(3), int64(1), str(6)
memory usage: 32.9 KB

In [5]:
df.isnull().sum()

user_id                      0
age_group                    0
role                         0
primary_platform             0
learning_device            218
hours_per_week               1
learning_purpose             1
content_type_preference    147
completion_rate_percent      5
satisfaction_score           6
dtype: int64

In [6]:
df.columns

Index(['user_id', 'age_group', 'role', 'primary_platform', 'learning_device',
       'hours_per_week', 'learning_purpose', 'content_type_preference',
       'completion_rate_percent', 'satisfaction_score'],
      dtype='str')

In [ ]:
# for loop+missing

for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype == 'str':
            df[col] = df[col].fillna(df[col].mode()[0])
        else:
            df[col]=df[col].fillna(df[col].mean())

In [29]:
df.isnull().sum()

user_id                    0
age_group                  0
role                       0
primary_platform           0
learning_device            0
hours_per_week             0
learning_purpose           0
content_type_preference    0
completion_rate_percent    0
satisfaction_score         0
dtype: int64