2 ta usulda encoding qiling

In [94]:
import pandas as pd 
df=pd.read_csv('sleep_health_dataset.csv')

In [95]:
df.head(10)

,person_id,age,gender,occupation,bmi,country,sleep_duration_hrs,sleep_quality_score,rem_percentage,deep_sleep_percentage,...,heart_rate_resting_bpm,sleep_aid_used,shift_work,room_temperature_celsius,weekend_sleep_diff_hrs,season,day_type,cognitive_performance_score,sleep_disorder_risk,felt_rested
0,1,29,Female,Driver,25.7,Japan,6.19,6.6,22.5,19.3,...,63,0,0,20.1,1.84,Autumn,Weekday,73.4,Healthy,0
1,2,55,Female,Software Engineer,22.0,USA,8.32,6.9,26.9,14.9,...,52,1,0,18.0,0.13,Winter,Weekend,99.4,Healthy,1
2,3,42,Male,Nurse,25.0,India,3.74,1.0,20.2,16.2,...,72,0,1,17.9,1.67,Spring,Weekend,2.5,Severe,0
3,4,37,Female,Student,29.5,India,6.79,6.4,17.7,17.7,...,71,0,0,19.1,2.37,Summer,Weekend,67.8,Healthy,0
4,5,23,Male,Lawyer,23.6,Spain,5.02,3.2,23.3,18.3,...,71,0,0,19.7,1.26,Summer,Weekday,38.1,Mild,0
5,6,23,Female,Driver,25.5,Brazil,8.16,5.7,17.3,20.1,...,71,1,0,22.7,0.70,Summer,Weekend,49.9,Mild,1
6,7,20,Female,Software Engineer,18.2,Netherlands,7.27,5.1,17.5,18.8,...,79,0,0,17.6,0.73,Spring,Weekend,57.9,Mild,1
7,8,48,Female,Freelancer,31.5,UK,8.04,6.5,25.3,22.3,...,60,1,0,21.6,0.47,Winter,Weekend,92.0,Mild,0
8,9,37,Male,Manager,29.9,USA,6.04,5.4,18.9,15.7,...,74,0,0,17.8,1.80,Autumn,Weekend,53.6,Mild,0
9,10,41,Female,Nurse,34.8,USA,6.22,4.9,21.4,15.5,...,80,1,0,24.4,1.51,Autumn,Weekday,67.8,Mild,1

In [96]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   gender                       100000 non-null  str
 3   occupation                   100000 non-null  str
 4   bmi                          100000 non-null  float64
 5   country                      100000 non-null  str
 6   sleep_duration_hrs           100000 non-null  float64
 7   sleep_quality_score          100000 non-null  float64
 8   rem_percentage               100000 non-null  float64
 9   deep_sleep_percentage        100000 non-null  float64
 10  sleep_latency_mins           100000 non-null  int64
 11  wake_episodes_per_night      100000 non-null  int64
 12  caffeine_mg_before_bed       100000 non-null  int64
 13  alcohol_units_before_bed     100000 non-null  float64
 14  screen_time_before_bed_mins  100000 non-null  int64
 15  exercise_day                 100000 non-null  int64
 16  steps_that_day               100000 non-null  int64
 17  nap_duration_mins            100000 non-null  int64
 18  stress_score                 100000 non-null  float64
 19  work_hours_that_day          100000 non-null  float64
 20  chronotype                   100000 non-null  str
 21  mental_health_condition      100000 non-null  str
 22  heart_rate_resting_bpm       100000 non-null  int64
 23  sleep_aid_used               100000 non-null  int64
 24  shift_work                   100000 non-null  int64
 25  room_temperature_celsius     100000 non-null  float64
 26  weekend_sleep_diff_hrs       100000 non-null  float64
 27  season                       100000 non-null  str
 28  day_type                     100000 non-null  str
 29  cognitive_performance_score  100000 non-null  float64
 30  sleep_disorder_risk          100000 non-null  str
 31  felt_rested                  100000 non-null  int64
dtypes: float64(11), int64(13), str(8)
memory usage: 24.4 MB

In [97]:
df.nunique()

person_id                      100000
age                                52
gender                              3
occupation                         12
bmi                               277
country                            15
sleep_duration_hrs                750
sleep_quality_score                89
rem_percentage                    201
deep_sleep_percentage             251
sleep_latency_mins                 56
wake_episodes_per_night             9
caffeine_mg_before_bed              8
alcohol_units_before_bed            7
screen_time_before_bed_mins       179
exercise_day                        2
steps_that_day                  15200
nap_duration_mins                 108
stress_score                       91
work_hours_that_day               180
chronotype                          3
mental_health_condition             4
heart_rate_resting_bpm             53
sleep_aid_used                      2
shift_work                          2
room_temperature_celsius          131
weekend_sleep_diff_hrs            401
season                              4
day_type                            2
cognitive_performance_score      1001
sleep_disorder_risk                 4
felt_rested                         2
dtype: int64

In [98]:
df.isnull().sum()

person_id                      0
age                            0
gender                         0
occupation                     0
bmi                            0
country                        0
sleep_duration_hrs             0
sleep_quality_score            0
rem_percentage                 0
deep_sleep_percentage          0
sleep_latency_mins             0
wake_episodes_per_night        0
caffeine_mg_before_bed         0
alcohol_units_before_bed       0
screen_time_before_bed_mins    0
exercise_day                   0
steps_that_day                 0
nap_duration_mins              0
stress_score                   0
work_hours_that_day            0
chronotype                     0
mental_health_condition        0
heart_rate_resting_bpm         0
sleep_aid_used                 0
shift_work                     0
room_temperature_celsius       0
weekend_sleep_diff_hrs         0
season                         0
day_type                       0
cognitive_performance_score    0
sleep_disorder_risk            0
felt_rested                    0
dtype: int64

ENCODING

In [99]:
#ONE-HOT USULIDA
df.nunique()

person_id                      100000
age                                52
gender                              3
occupation                         12
bmi                               277
country                            15
sleep_duration_hrs                750
sleep_quality_score                89
rem_percentage                    201
deep_sleep_percentage             251
sleep_latency_mins                 56
wake_episodes_per_night             9
caffeine_mg_before_bed              8
alcohol_units_before_bed            7
screen_time_before_bed_mins       179
exercise_day                        2
steps_that_day                  15200
nap_duration_mins                 108
stress_score                       91
work_hours_that_day               180
chronotype                          3
mental_health_condition             4
heart_rate_resting_bpm             53
sleep_aid_used                      2
shift_work                          2
room_temperature_celsius          131
weekend_sleep_diff_hrs            401
season                              4
day_type                            2
cognitive_performance_score      1001
sleep_disorder_risk                 4
felt_rested                         2
dtype: int64

In [100]:
dummies=pd.get_dummies(df['gender'],prefix='ust',dtype=int)

In [101]:
dummies

       ust_Female  ust_Male  ust_Other
0               1         0          0
1               1         0          0
2               0         1          0
3               1         0          0
4               0         1          0
...           ...       ...        ...
99995           1         0          0
99996           1         0          0
99997           0         1          0
99998           1         0          0
99999           0         1          0

[100000 rows x 3 columns]

In [102]:
df=pd.concat([df.drop(columns=['gender']),dummies],axis=1)

In [103]:
df.nunique()

person_id                      100000
age                                52
occupation                         12
bmi                               277
country                            15
sleep_duration_hrs                750
sleep_quality_score                89
rem_percentage                    201
deep_sleep_percentage             251
sleep_latency_mins                 56
wake_episodes_per_night             9
caffeine_mg_before_bed              8
alcohol_units_before_bed            7
screen_time_before_bed_mins       179
exercise_day                        2
steps_that_day                  15200
nap_duration_mins                 108
stress_score                       91
work_hours_that_day               180
chronotype                          3
mental_health_condition             4
heart_rate_resting_bpm             53
sleep_aid_used                      2
shift_work                          2
room_temperature_celsius          131
weekend_sleep_diff_hrs            401
season                              4
day_type                            2
cognitive_performance_score      1001
sleep_disorder_risk                 4
felt_rested                         2
ust_Female                          2
ust_Male                            2
ust_Other                           2
dtype: int64

Label Encoding

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   occupation                   100000 non-null  str
 3   bmi                          100000 non-null  float64
 4   country                      100000 non-null  str
 5   sleep_duration_hrs           100000 non-null  float64
 6   sleep_quality_score          100000 non-null  float64
 7   rem_percentage               100000 non-null  float64
 8   deep_sleep_percentage        100000 non-null  float64
 9   sleep_latency_mins           100000 non-null  int64
 10  wake_episodes_per_night      100000 non-null  int64
 11  caffeine_mg_before_bed       100000 non-null  int64
 12  alcohol_units_before_bed     100000 non-null  float64
 13  screen_time_before_bed_mins  100000 non-null  int64
 14  exercise_day                 100000 non-null  int64
 15  steps_that_day               100000 non-null  int64
 16  nap_duration_mins            100000 non-null  int64
 17  stress_score                 100000 non-null  float64
 18  work_hours_that_day          100000 non-null  float64
 19  chronotype                   100000 non-null  str
 20  mental_health_condition      100000 non-null  str
 21  heart_rate_resting_bpm       100000 non-null  int64
 22  sleep_aid_used               100000 non-null  int64
 23  shift_work                   100000 non-null  int64
 24  room_temperature_celsius     100000 non-null  float64
 25  weekend_sleep_diff_hrs       100000 non-null  float64
 26  season                       100000 non-null  str
 27  day_type                     100000 non-null  str
 28  cognitive_performance_score  100000 non-null  float64
 29  sleep_disorder_risk          100000 non-null  str
 30  felt_rested                  100000 non-null  int64
 31  ust_Female                   100000 non-null  int64
 32  ust_Male                     100000 non-null  int64
 33  ust_Other                    100000 non-null  int64
dtypes: float64(11), int64(16), str(7)
memory usage: 25.9 MB

In [105]:
from sklearn.preprocessing import LabelEncoder

In [106]:
encoder=LabelEncoder

In [107]:
encoder

sklearn.preprocessing._label.LabelEncoder

In [108]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['occupation'] = encoder.fit_transform(df['occupation'])

In [109]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   occupation                   100000 non-null  int64
 3   bmi                          100000 non-null  float64
 4   country                      100000 non-null  str
 5   sleep_duration_hrs           100000 non-null  float64
 6   sleep_quality_score          100000 non-null  float64
 7   rem_percentage               100000 non-null  float64
 8   deep_sleep_percentage        100000 non-null  float64
 9   sleep_latency_mins           100000 non-null  int64
 10  wake_episodes_per_night      100000 non-null  int64
 11  caffeine_mg_before_bed       100000 non-null  int64
 12  alcohol_units_before_bed     100000 non-null  float64
 13  screen_time_before_bed_mins  100000 non-null  int64
 14  exercise_day                 100000 non-null  int64
 15  steps_that_day               100000 non-null  int64
 16  nap_duration_mins            100000 non-null  int64
 17  stress_score                 100000 non-null  float64
 18  work_hours_that_day          100000 non-null  float64
 19  chronotype                   100000 non-null  str
 20  mental_health_condition      100000 non-null  str
 21  heart_rate_resting_bpm       100000 non-null  int64
 22  sleep_aid_used               100000 non-null  int64
 23  shift_work                   100000 non-null  int64
 24  room_temperature_celsius     100000 non-null  float64
 25  weekend_sleep_diff_hrs       100000 non-null  float64
 26  season                       100000 non-null  str
 27  day_type                     100000 non-null  str
 28  cognitive_performance_score  100000 non-null  float64
 29  sleep_disorder_risk          100000 non-null  str
 30  felt_rested                  100000 non-null  int64
 31  ust_Female                   100000 non-null  int64
 32  ust_Male                     100000 non-null  int64
 33  ust_Other                    100000 non-null  int64
dtypes: float64(11), int64(17), str(6)
memory usage: 25.9 MB

ENCODING+FOR LOOP

In [114]:
for col in df.columns:
    if df[col].dtype=='str':
        if df[col].nunique()<=5:
            dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
            df=pd.concat([df.drop(columns=col),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])

In [115]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 46 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   person_id                           100000 non-null  int64
 1   age                                 100000 non-null  int64
 2   occupation                          100000 non-null  int64
 3   bmi                                 100000 non-null  float64
 4   country                             100000 non-null  int64
 5   sleep_duration_hrs                  100000 non-null  float64
 6   sleep_quality_score                 100000 non-null  float64
 7   rem_percentage                      100000 non-null  float64
 8   deep_sleep_percentage               100000 non-null  float64
 9   sleep_latency_mins                  100000 non-null  int64
 10  wake_episodes_per_night             100000 non-null  int64
 11  caffeine_mg_before_bed              100000 non-null  int64
 12  alcohol_units_before_bed            100000 non-null  float64
 13  screen_time_before_bed_mins         100000 non-null  int64
 14  exercise_day                        100000 non-null  int64
 15  steps_that_day                      100000 non-null  int64
 16  nap_duration_mins                   100000 non-null  int64
 17  stress_score                        100000 non-null  float64
 18  work_hours_that_day                 100000 non-null  float64
 19  heart_rate_resting_bpm              100000 non-null  int64
 20  sleep_aid_used                      100000 non-null  int64
 21  shift_work                          100000 non-null  int64
 22  room_temperature_celsius            100000 non-null  float64
 23  weekend_sleep_diff_hrs              100000 non-null  float64
 24  cognitive_performance_score         100000 non-null  float64
 25  felt_rested                         100000 non-null  int64
 26  ust_Female                          100000 non-null  int64
 27  ust_Male                            100000 non-null  int64
 28  ust_Other                           100000 non-null  int64
 29  chronotype_Evening                  100000 non-null  int64
 30  chronotype_Morning                  100000 non-null  int64
 31  chronotype_Neutral                  100000 non-null  int64
 32  mental_health_condition_Anxiety     100000 non-null  int64
 33  mental_health_condition_Both        100000 non-null  int64
 34  mental_health_condition_Depression  100000 non-null  int64
 35  mental_health_condition_Healthy     100000 non-null  int64
 36  season_Autumn                       100000 non-null  int64
 37  season_Spring                       100000 non-null  int64
 38  season_Summer                       100000 non-null  int64
 39  season_Winter                       100000 non-null  int64
 40  day_type_Weekday                    100000 non-null  int64
 41  day_type_Weekend                    100000 non-null  int64
 42  sleep_disorder_risk_Healthy         100000 non-null  int64
 43  sleep_disorder_risk_Mild            100000 non-null  int64
 44  sleep_disorder_risk_Moderate        100000 non-null  int64
 45  sleep_disorder_risk_Severe          100000 non-null  int64
dtypes: float64(11), int64(35)
memory usage: 35.1 MB