# Vazifalar

Github/Kaggledan dataset toping:

For loop bn to’liq data preprocessing qiling

Logistic Regression bn model yasang

Kodlarni xar bir bosqich uchun mustaqil yozing

# Data Preprocessing + for loop

In [298]:
import pandas as pd

In [299]:
df=pd.read_csv('IMDB_Movies_Dataset.csv')

# 1. Handling missing values + for loop

In [300]:
df.isnull().sum()

Unnamed: 0              0
Title                   0
Average Rating          2
Director                0
Writer                  1
Metascore            1934
Cast                    7
Release Date            0
Country of Origin       3
Languages              21
Budget               2338
Worldwide Gross      1094
Runtime                 0
Writer.1                1
Average Rating.1        0
dtype: int64

In [301]:
df.drop(['Budget'],axis=1,inplace=True)
df.drop(['Worldwide Gross'],axis=1,inplace=True)
df.drop(['Metascore'],axis=1,inplace=True)
df.drop(['Title'],axis=1,inplace=True)

In [302]:
df.isnull().sum()

Unnamed: 0            0
Average Rating        2
Director              0
Writer                1
Cast                  7
Release Date          0
Country of Origin     3
Languages            21
Runtime               0
Writer.1              1
Average Rating.1      0
dtype: int64

In [303]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4991 entries, 0 to 4990
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4991 non-null   str
 1   Average Rating     4989 non-null   float64
 2   Director           4991 non-null   str
 3   Writer             4990 non-null   str
 4   Cast               4984 non-null   str
 5   Release Date       4991 non-null   str
 6   Country of Origin  4988 non-null   str
 7   Languages          4970 non-null   str
 8   Runtime            4991 non-null   str
 9   Writer.1           4990 non-null   str
 10  Average Rating.1   4991 non-null   float64
dtypes: float64(2), str(9)
memory usage: 429.0 KB

In [304]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='str':
            df[col]=df[col].fillna(df[col].mode()[0])
        else:
            df[col]=df[col].fillna(df[col].mean())

In [305]:
df.isnull().sum()

Unnamed: 0           0
Average Rating       0
Director             0
Writer               0
Cast                 0
Release Date         0
Country of Origin    0
Languages            0
Runtime              0
Writer.1             0
Average Rating.1     0
dtype: int64

In [306]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4991 entries, 0 to 4990
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4991 non-null   str
 1   Average Rating     4991 non-null   float64
 2   Director           4991 non-null   str
 3   Writer             4991 non-null   str
 4   Cast               4991 non-null   str
 5   Release Date       4991 non-null   str
 6   Country of Origin  4991 non-null   str
 7   Languages          4991 non-null   str
 8   Runtime            4991 non-null   str
 9   Writer.1           4991 non-null   str
 10  Average Rating.1   4991 non-null   float64
dtypes: float64(2), str(9)
memory usage: 429.0 KB

# 2. Encoding + for loop

In [307]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()

for col in df.columns:
    if df[col].dtype=='str':
        df[col]=encoder.fit_transform(df[col])

In [308]:
print(df.dtypes)

Unnamed: 0             int64
Average Rating       float64
Director               int64
Writer                 int64
Cast                   int64
Release Date           int64
Country of Origin      int64
Languages              int64
Runtime                int64
Writer.1               int64
Average Rating.1     float64
dtype: object

In [309]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4991 entries, 0 to 4990
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4991 non-null   int64
 1   Average Rating     4991 non-null   float64
 2   Director           4991 non-null   int64
 3   Writer             4991 non-null   int64
 4   Cast               4991 non-null   int64
 5   Release Date       4991 non-null   int64
 6   Country of Origin  4991 non-null   int64
 7   Languages          4991 non-null   int64
 8   Runtime            4991 non-null   int64
 9   Writer.1           4991 non-null   int64
 10  Average Rating.1   4991 non-null   float64
dtypes: float64(2), int64(9)
memory usage: 429.0 KB

# 3. Scaling + for loop

In [310]:
df.head()

,Unnamed: 0,Average Rating,Director,Writer,Cast,Release Date,Country of Origin,Languages,Runtime,Writer.1,Average Rating.1
0,0,9.3,711,3851,4504,3606,678,87,74,3851,9.3
1,1,9.3,2620,2884,3367,3504,384,801,77,2884,9.3
2,112,9.2,703,2592,3002,17,678,317,110,2592,9.2
3,224,9.2,661,4123,3312,47,568,1064,18,4123,9.2
4,335,9.2,1962,3286,396,4337,303,87,66,3286,9.2

In [311]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [312]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Average Rating.1')   # izoh: Target qiymat scalimng qilinmaydi

In [313]:
scaler=MinMaxScaler()

In [314]:
scaler

MinMaxScaler()

In [315]:
scaler=MinMaxScaler()
for col in df.columns:
    if df[col].dtype!='object':
        df[col]=scaler.fit_transform(df[[col]])

In [316]:
df.head()

,Unnamed: 0,Average Rating,Director,Writer,Cast,Release Date,Country of Origin,Languages,Runtime,Writer.1,Average Rating.1
0,0.000,1.000000,0.268606,0.871070,0.904418,0.798671,0.836005,0.080332,0.408840,0.871070,1.000000
1,0.002,1.000000,0.989800,0.652341,0.676104,0.776080,0.473490,0.739612,0.425414,0.652341,1.000000
2,0.224,0.952381,0.265584,0.586293,0.602811,0.003765,0.836005,0.292705,0.607735,0.586293,0.952381
3,0.448,0.952381,0.249717,0.932594,0.665060,0.010410,0.700370,0.982456,0.099448,0.932594,0.952381
4,0.670,0.952381,0.741216,0.743271,0.079518,0.960576,0.373613,0.080332,0.364641,0.743271,0.952381

In [317]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4991 entries, 0 to 4990
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4991 non-null   float64
 1   Average Rating     4991 non-null   float64
 2   Director           4991 non-null   float64
 3   Writer             4991 non-null   float64
 4   Cast               4991 non-null   float64
 5   Release Date       4991 non-null   float64
 6   Country of Origin  4991 non-null   float64
 7   Languages          4991 non-null   float64
 8   Runtime            4991 non-null   float64
 9   Writer.1           4991 non-null   float64
 10  Average Rating.1   4991 non-null   float64
dtypes: float64(11)
memory usage: 429.0 KB

# Data Preprocessing done

# Logistic Regression bn model yasang

In [318]:
x----inputlar
y--output

NameError: name 'inputlar' is not defined

In [319]:
num_col=df.select_dtypes(include=['float64']).columns

In [320]:
num_col

Index(['Unnamed: 0', 'Average Rating', 'Director', 'Writer', 'Cast',
       'Release Date', 'Country of Origin', 'Languages', 'Runtime', 'Writer.1',
       'Average Rating.1'],
      dtype='str')

In [321]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4991 entries, 0 to 4990
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4991 non-null   float64
 1   Average Rating     4991 non-null   float64
 2   Director           4991 non-null   float64
 3   Writer             4991 non-null   float64
 4   Cast               4991 non-null   float64
 5   Release Date       4991 non-null   float64
 6   Country of Origin  4991 non-null   float64
 7   Languages          4991 non-null   float64
 8   Runtime            4991 non-null   float64
 9   Writer.1           4991 non-null   float64
 10  Average Rating.1   4991 non-null   float64
dtypes: float64(11)
memory usage: 429.0 KB

In [322]:
x=df.drop('Average Rating.1',axis=1)

In [323]:
y=df['Average Rating.1'].astype(int)

In [324]:
y

0       1
1       1
2       0
3       0
4       0
       ..
4986    0
4987    0
4988    0
4989    1
4990    1
Name: Average Rating.1, Length: 4991, dtype: int64

In [325]:
x

,Unnamed: 0,Average Rating,Director,Writer,Cast,Release Date,Country of Origin,Languages,Runtime,Writer.1
0,0.000,1.000000,0.268606,0.871070,0.904418,0.798671,0.836005,0.080332,0.408840,0.871070
1,0.002,1.000000,0.989800,0.652341,0.676104,0.776080,0.473490,0.739612,0.425414,0.652341
2,0.224,0.952381,0.265584,0.586293,0.602811,0.003765,0.836005,0.292705,0.607735,0.586293
3,0.448,0.952381,0.249717,0.932594,0.665060,0.010410,0.700370,0.982456,0.099448,0.932594
4,0.670,0.952381,0.741216,0.743271,0.079518,0.960576,0.373613,0.080332,0.364641,0.743271
...,...,...,...,...,...,...,...,...,...,...
4986,0.886,0.000000,0.890064,0.358064,0.841365,0.017719,0.473490,0.739612,0.353591,0.358064
4987,0.888,0.000000,0.797884,0.794390,0.768273,0.053378,0.178792,0.576177,0.132597,0.794390
4988,0.890,0.000000,0.513034,0.527030,0.988153,0.601329,0.604192,0.763620,0.270718,0.527030
4989,0.000,1.000000,0.268606,0.871070,0.904418,0.798671,0.836005,0.080332,0.408840,0.871070
4990,0.000,1.000000,0.268606,0.871070,0.904418,0.798671,0.836005,0.080332,0.408840,0.871070

# Modelimizni train qilamiz

In [326]:
from sklearn.model_selection import train_test_split

In [327]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [328]:
x_train.shape

(3493, 10)

In [329]:
x_test.shape

(1498, 10)

In [330]:
y_train.shape

(3493,)

In [331]:
y_test.shape

(1498,)

In [332]:
from sklearn.linear_model import LogisticRegression

In [333]:
log_reg=LogisticRegression()

In [334]:
log_reg

LogisticRegression()

In [335]:
log_reg.fit(x_train,y_train)

LogisticRegression()

In [336]:
y_pred=log_reg.predict(x_test)

# Evaluation

In [337]:
from sklearn.metrics import accuracy_score

In [338]:
score=accuracy_score(y_test,y_pred)

In [339]:
print('Modelning aniqlik darajasi:',score) # bu hamma structurelarni ishlatgan holatidagi natija

Modelning aniqlik darajasi: 0.9993324432576769

In [ ]:
print('Modelning aniqlik darajasi:',score) # bu Encoding qilinmagan holatida

Modelning aniqlik darajasi: 0.0

In [ ]:
print('Modelning aniqlik darajasi:',score) # bu Scaling qilinmagan holatida

Modelning aniqlik darajasi: 0.794392523364486