In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/Users/a1/Desktop/MLFoundation/autos.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  object
 2   name                 371528 non-null  object
 3   seller               371528 non-null  object
 4   offerType            371528 non-null  object
 5   price                371528 non-null  int64
 6   abtest               371528 non-null  object
 7   vehicleType          333659 non-null  object
 8   yearOfRegistration   371528 non-null  int64
 9   gearbox              351319 non-null  object
 10  powerPS              371528 non-null  int64
 11  model                351044 non-null  object
 12  kilometer            371528 non-null  int64
 13  monthOfRegistration  371528 non-null  int64
 14  fuelType             338142 non-null  object
 15  brand                371528 non-null  object
 16  notRepairedDamage    299468 non-null  object
 17  dateCreated          371528 non-null  object
 18  nrOfPictures         371528 non-null  int64
 19  postalCode           371528 non-null  int64
 20  lastSeen             371528 non-null  object
dtypes: int64(8), object(13)
memory usage: 59.5+ MB

In [4]:
for col in df.columns:
    if df[col].nunique() <=10:
        print(col, df[col].unique())

seller ['privat' 'gewerblich']
offerType ['Angebot' 'Gesuch']
abtest ['test' 'control']
vehicleType [nan 'coupe' 'suv' 'kleinwagen' 'limousine' 'cabrio' 'bus' 'kombi'
 'andere']
gearbox ['manuell' 'automatik' nan]
fuelType ['benzin' 'diesel' nan 'lpg' 'andere' 'hybrid' 'cng' 'elektro']
notRepairedDamage [nan 'ja' 'nein']
nrOfPictures [0]

In [5]:
df.head()

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

In [9]:


# 1. Simple list of column names
print("Column names:")
print(df.columns.tolist())

Column names:
['index', 'dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest', 'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model', 'kilometer', 'monthOfRegistration', 'fuelType', 'brand', 'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode', 'lastSeen']

In [10]:
df["price"].describe()

count    3.715280e+05
mean     1.729514e+04
std      3.587954e+06
min      0.000000e+00
25%      1.150000e+03
50%      2.950000e+03
75%      7.200000e+03
max      2.147484e+09
Name: price, dtype: float64

In [11]:
df = df[(df["price"] > 100) & (df["price"] > 100000)]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 403 entries, 996 to 368656
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                403 non-null    int64
 1   dateCrawled          403 non-null    object
 2   name                 403 non-null    object
 3   seller               403 non-null    object
 4   offerType            403 non-null    object
 5   price                403 non-null    int64
 6   abtest               403 non-null    object
 7   vehicleType          361 non-null    object
 8   yearOfRegistration   403 non-null    int64
 9   gearbox              336 non-null    object
 10  powerPS              403 non-null    int64
 11  model                294 non-null    object
 12  kilometer            403 non-null    int64
 13  monthOfRegistration  403 non-null    int64
 14  fuelType             338 non-null    object
 15  brand                403 non-null    object
 16  notRepairedDamage    339 non-null    object
 17  dateCreated          403 non-null    object
 18  nrOfPictures         403 non-null    int64
 19  postalCode           403 non-null    int64
 20  lastSeen             403 non-null    object
dtypes: int64(8), object(13)
memory usage: 69.3+ KB

In [13]:
df.isnull().sum()

index                    0
dateCrawled              0
name                     0
seller                   0
offerType                0
price                    0
abtest                   0
vehicleType             42
yearOfRegistration       0
gearbox                 67
powerPS                  0
model                  109
kilometer                0
monthOfRegistration      0
fuelType                65
brand                    0
notRepairedDamage       64
dateCreated              0
nrOfPictures             0
postalCode               0
lastSeen                 0
dtype: int64

In [16]:
df.drop(columns=["index", "nrOfPictures", "postalCode"], inplace=True)

# Data Preprocessing

Handling Missing VAlues

In [17]:
df.isnull().sum()

dateCrawled              0
name                     0
seller                   0
offerType                0
price                    0
abtest                   0
vehicleType             42
yearOfRegistration       0
gearbox                 67
powerPS                  0
model                  109
kilometer                0
monthOfRegistration      0
fuelType                65
brand                    0
notRepairedDamage       64
dateCreated              0
lastSeen                 0
dtype: int64

In [19]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype == "object":
            df[col].fillna(df[col].mode()[0], inplace=True)
        else:
                df[coll].fillnadf([col].mean())

/var/folders/5h/9l3v88x94dgfs7159k0nvb2w0000gn/T/ipykernel_18977/1347267251.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 403 entries, 996 to 368656
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dateCrawled          403 non-null    object
 1   name                 403 non-null    object
 2   seller               403 non-null    object
 3   offerType            403 non-null    object
 4   price                403 non-null    int64
 5   abtest               403 non-null    object
 6   vehicleType          403 non-null    object
 7   yearOfRegistration   403 non-null    int64
 8   gearbox              403 non-null    object
 9   powerPS              403 non-null    int64
 10  model                403 non-null    object
 11  kilometer            403 non-null    int64
 12  monthOfRegistration  403 non-null    int64
 13  fuelType             403 non-null    object
 14  brand                403 non-null    object
 15  notRepairedDamage    403 non-null    object
 16  dateCreated          403 non-null    object
 17  lastSeen             403 non-null    object
dtypes: int64(5), object(13)
memory usage: 59.8+ KB

In [21]:
df.isnull().sum()

dateCrawled            0
name                   0
seller                 0
offerType              0
price                  0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dateCreated            0
lastSeen               0
dtype: int64

# Encoding

In [22]:
df.nunique()

dateCrawled            403
name                   366
seller                   1
offerType                1
price                  212
abtest                   2
vehicleType              8
yearOfRegistration      74
gearbox                  2
powerPS                140
model                   45
kilometer               13
monthOfRegistration     13
fuelType                 6
brand                   24
notRepairedDamage        2
dateCreated             35
lastSeen               402
dtype: int64

In [25]:
for col in df.columns:
 if df[col].nunique() <= 5:
    print(col, df[col].unique())

seller ['privat']
offerType ['Angebot']
abtest ['test' 'control']
gearbox ['manuell' 'automatik']
notRepairedDamage ['nein' 'ja']

In [30]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        if df[col].nunique() <= 5:
            dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
            df = pd.concat([df.drop(columns=[col]), dummies], axis=1)
        else:
            df[col] = encoder.fit_transform(df[col])

In [31]:
df.head()

,dateCrawled,name,price,vehicleType,yearOfRegistration,powerPS,model,kilometer,monthOfRegistration,fuelType,...,dateCreated,lastSeen,seller_privat,offerType_Angebot,abtest_control,abtest_test,gearbox_automatik,gearbox_manuell,notRepairedDamage_ja,notRepairedDamage_nein
996,235,276,139997,3,2010,435,5,20000,3,1,...,21,307,1,1,0,1,0,1,0,1
1846,55,33,579000,3,1980,277,11,20000,12,1,...,6,86,1,1,1,0,0,1,0,1
2735,114,66,120000,2,2012,666,5,20000,7,1,...,12,71,1,1,0,1,1,0,0,1
4359,263,161,185000,2,1971,170,37,5000,7,1,...,23,259,1,1,0,1,1,0,0,1
5907,190,183,119000,2,1973,140,5,150000,4,1,...,17,104,1,1,1,0,0,1,0,1

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 403 entries, 996 to 368656
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   dateCrawled             403 non-null    int64
 1   name                    403 non-null    int64
 2   price                   403 non-null    int64
 3   vehicleType             403 non-null    int64
 4   yearOfRegistration      403 non-null    int64
 5   powerPS                 403 non-null    int64
 6   model                   403 non-null    int64
 7   kilometer               403 non-null    int64
 8   monthOfRegistration     403 non-null    int64
 9   fuelType                403 non-null    int64
 10  brand                   403 non-null    int64
 11  dateCreated             403 non-null    int64
 12  lastSeen                403 non-null    int64
 13  seller_privat           403 non-null    int64
 14  offerType_Angebot       403 non-null    int64
 15  abtest_control          403 non-null    int64
 16  abtest_test             403 non-null    int64
 17  gearbox_automatik       403 non-null    int64
 18  gearbox_manuell         403 non-null    int64
 19  notRepairedDamage_ja    403 non-null    int64
 20  notRepairedDamage_nein  403 non-null    int64
dtypes: int64(21)
memory usage: 69.3 KB

# Scaling

In [33]:
from sklearn.preprocessing import MinMaxScaler

In [34]:
scaler=MinMaxScaler()

In [35]:
scaler

MinMaxScaler()

In [36]:
num_cols=df.select_dtypes(include=["int64"]).columns.drop("price")

In [37]:
num_cols

Index(['dateCrawled', 'name', 'vehicleType', 'yearOfRegistration', 'powerPS',
       'model', 'kilometer', 'monthOfRegistration', 'fuelType', 'brand',
       'dateCreated', 'lastSeen', 'seller_privat', 'offerType_Angebot',
       'abtest_control', 'abtest_test', 'gearbox_automatik', 'gearbox_manuell',
       'notRepairedDamage_ja', 'notRepairedDamage_nein'],
      dtype='object')

In [38]:
 df[num_cols]=scaler.fit_transform(df[num_cols])

In [39]:
df.head()

,dateCrawled,name,price,vehicleType,yearOfRegistration,powerPS,model,kilometer,monthOfRegistration,fuelType,...,dateCreated,lastSeen,seller_privat,offerType_Angebot,abtest_control,abtest_test,gearbox_automatik,gearbox_manuell,notRepairedDamage_ja,notRepairedDamage_nein
996,0.584577,0.756164,139997,0.428571,0.112235,0.037435,0.113636,0.103448,0.250000,0.2,...,0.617647,0.765586,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
1846,0.136816,0.090411,579000,0.428571,0.108901,0.023838,0.250000,0.103448,1.000000,0.2,...,0.176471,0.214464,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
2735,0.283582,0.180822,120000,0.285714,0.112457,0.057315,0.113636,0.103448,0.583333,0.2,...,0.352941,0.177057,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4359,0.654229,0.441096,185000,0.285714,0.107901,0.014630,0.840909,0.000000,0.583333,0.2,...,0.676471,0.645885,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
5907,0.472637,0.501370,119000,0.285714,0.108123,0.012048,0.113636,1.000000,0.333333,0.2,...,0.500000,0.259352,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0

# Model Selection

In [40]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [41]:
lr

LinearRegression()

# Training

In [42]:
x=df.drop("price", axis=1)

In [43]:
y=df["price"]

In [45]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=42)

In [46]:
x_train.shape

(322, 20)

In [47]:
y_train.shape

(322,)

In [48]:
x_test.shape

(81, 20)

In [49]:
y_test.shape

(81,)

In [50]:
lr.fit(x_train, y_train)

LinearRegression()

# Prediction

In [51]:
y_predict=lr.predict(x_test)

In [52]:
y_predict

array([11360396.15562418,  1089799.69991119, 11591840.98919784,
       21098673.08782574,  3797363.16776165, -2447258.28862765,
        6929497.37466177, -1159243.17975003,  5736316.69710627,
        4140020.27768034,   748239.57003935,  2582254.25256958,
       -3861940.40107554, 17019493.18135817, 12100935.04487339,
       13202038.82004445,  9627999.11539226, 11370469.43180241,
        8049633.60116049,  6320149.50768773, 17388693.61962637,
       12718901.71804399,  7519164.92526291, 11668191.17397875,
       11742568.45491788, -1450836.04704414, 10844567.96769169,
       -2053511.16325022,  2292942.20674351, 23003567.32463808,
        -338875.43906557, 10692265.51895601,  2789803.71616962,
        1908755.0546637 , 11405453.14821279,   668481.76887577,
        9584569.20480388, -4859585.73783953, -3718085.38353717,
        1239322.55938353,  6150019.57238326,  3041398.65095134,
        5818920.08136862, 21842910.96651295, -5247340.19851787,
         817457.87967972, -4438679.62008677,   792094.51469885,
         847260.45882901, 16448102.51524523, -3063134.90218492,
       -2911753.62763645,  3549209.18168386,  9481282.39692095,
       -2147441.90208766,  1278736.61408598,   912335.44111079,
        2443679.66774389,  2323992.83214039,  6821414.92660262,
       13004749.39761658, -2743459.96444876,  1323072.05097853,
       14101133.02734562, 12393979.1393949 , -4197833.51771579,
        5921913.94411155,  -542812.87563319, -2308322.11003791,
       21205559.98881478,  5621685.2476742 ,  3925462.57483357,
        4100175.80261974,  4122126.95393356,  1211047.14036368,
        6154287.86618212,  -174339.35740366, 10022757.58087052,
       22490120.21798448,  -182875.59370735, 22520982.97249388])

# Evaluation

In [54]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [56]:
mae=mean_absolute_error(y_test, y_predict)
mse=mean_squared_error(y_test, y_predict)
r2=r2_score(y_test, y_predict)

In [57]:
print("mae", mae)
print("mse", mse)
print("r2", r2)

mae 35223533.47444835
mse 5.653944080600999e+16
r2 -0.003913192067276805