# 4 xil algoritm

In [406]:
import pandas as pd
df=pd.read_csv('Smartphone_Usage_Productivity_Dataset_50000.csv')

In [407]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    49996 non-null  str
 1   Age                        49991 non-null  float64
 2   Gender                     49988 non-null  str
 3   Occupation                 49991 non-null  str
 4   Device_Type                49991 non-null  str
 5   Daily_Phone_Hours          49983 non-null  float64
 6   Social_Media_Hours         49983 non-null  float64
 7   Work_Productivity_Score    49988 non-null  float64
 8   Sleep_Hours                49986 non-null  float64
 9   Stress_Level               49993 non-null  float64
 10  App_Usage_Count            49993 non-null  float64
 11  Caffeine_Intake_Cups       49994 non-null  float64
 12  Weekend_Screen_Time_Hours  49994 non-null  float64
dtypes: float64(9), str(4)
memory usage: 5.0 MB

In [408]:
df.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
0,NaN,58.0,Male,Professional,Android,1.3,6.7,6.0,8.8,4.0,42.0,1.0,8.7
1,NaN,25.0,Male,Professional,Android,1.2,1.5,5.0,6.4,1.0,51.0,3.0,5.1
2,NaN,19.0,Male,Student,iOS,5.3,5.7,5.0,9.0,4.0,14.0,5.0,6.3
3,NaN,NaN,Female,Business Owner,iOS,5.8,2.5,2.0,5.7,3.0,36.0,6.0,12.8
4,U5,NaN,NaN,NaN,Android,7.9,1.3,4.0,5.7,3.0,37.0,5.0,9.9

In [409]:
df.tail()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
49995,U49996,44.0,Male,Business Owner,Android,5.9,5.4,5.0,6.6,1.0,11.0,5.0,3.0
49996,U49997,42.0,Other,Business Owner,Android,2.9,7.4,9.0,6.3,2.0,20.0,4.0,6.2
49997,U49998,27.0,Female,Freelancer,iOS,1.4,2.5,4.0,6.7,9.0,39.0,4.0,5.1
49998,U49999,41.0,Female,Business Owner,iOS,8.9,3.0,6.0,5.5,2.0,51.0,0.0,9.2
49999,U50000,46.0,Other,Freelancer,Android,8.8,2.8,3.0,5.4,1.0,54.0,5.0,6.9

In [410]:
df.drop('User_ID',axis=1,inplace=True)

In [411]:
df.head()

,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
0,58.0,Male,Professional,Android,1.3,6.7,6.0,8.8,4.0,42.0,1.0,8.7
1,25.0,Male,Professional,Android,1.2,1.5,5.0,6.4,1.0,51.0,3.0,5.1
2,19.0,Male,Student,iOS,5.3,5.7,5.0,9.0,4.0,14.0,5.0,6.3
3,NaN,Female,Business Owner,iOS,5.8,2.5,2.0,5.7,3.0,36.0,6.0,12.8
4,NaN,NaN,NaN,Android,7.9,1.3,4.0,5.7,3.0,37.0,5.0,9.9

# Data Preprocessing

In [412]:
df.isnull().sum()

Age                           9
Gender                       12
Occupation                    9
Device_Type                   9
Daily_Phone_Hours            17
Social_Media_Hours           17
Work_Productivity_Score      12
Sleep_Hours                  14
Stress_Level                  7
App_Usage_Count               7
Caffeine_Intake_Cups          6
Weekend_Screen_Time_Hours     6
dtype: int64

# `Missing + Function`

In [413]:
def toldir_missing(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=="str":
                df[col] = df[col].fillna(df[col].mode()[0])
            else:
                df[col] = df[col].fillna(df[col].mean())
    return df

In [414]:
df=toldir_missing(df)

# `Encoding + Function`

In [415]:
df.nunique()

Age                           44
Gender                         3
Occupation                     4
Device_Type                    2
Daily_Phone_Hours            112
Social_Media_Hours            77
Work_Productivity_Score       11
Sleep_Hours                   52
Stress_Level                  11
App_Usage_Count               57
Caffeine_Intake_Cups           8
Weekend_Screen_Time_Hours    122
dtype: int64

In [416]:
from sklearn.preprocessing import LabelEncoder

In [417]:
# Encoding + Function
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=="str":
            if df[col].nunique()<4:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [418]:
df=encodla(df)

In [419]:
df.head()

,Age,Occupation,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Gender_Female,Gender_Male,Gender_Other,Device_Type_Android,Device_Type_iOS
0,58.000000,2,1.3,6.7,6.0,8.8,4.0,42.0,1.0,8.7,0,1,0,1,0
1,25.000000,2,1.2,1.5,5.0,6.4,1.0,51.0,3.0,5.1,0,1,0,1,0
2,19.000000,3,5.3,5.7,5.0,9.0,4.0,14.0,5.0,6.3,0,1,0,0,1
3,39.036207,0,5.8,2.5,2.0,5.7,3.0,36.0,6.0,12.8,1,0,0,0,1
4,39.036207,2,7.9,1.3,4.0,5.7,3.0,37.0,5.0,9.9,0,1,0,1,0

In [420]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        50000 non-null  float64
 1   Occupation                 50000 non-null  int64
 2   Daily_Phone_Hours          50000 non-null  float64
 3   Social_Media_Hours         50000 non-null  float64
 4   Work_Productivity_Score    50000 non-null  float64
 5   Sleep_Hours                50000 non-null  float64
 6   Stress_Level               50000 non-null  float64
 7   App_Usage_Count            50000 non-null  float64
 8   Caffeine_Intake_Cups       50000 non-null  float64
 9   Weekend_Screen_Time_Hours  50000 non-null  float64
 10  Gender_Female              50000 non-null  int64
 11  Gender_Male                50000 non-null  int64
 12  Gender_Other               50000 non-null  int64
 13  Device_Type_Android        50000 non-null  int64
 14  Device_Type_iOS            50000 non-null  int64
dtypes: float64(9), int64(6)
memory usage: 5.7 MB

# `Scaling + Function`

In [421]:
#Scaling
from sklearn.preprocessing import MinMaxScaler

In [422]:
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Work_Productivity_Score')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [423]:
df=scaling_qil(df)

# `Training`

In [424]:
x=df.drop('Work_Productivity_Score',axis=1)

In [425]:
y=df['Work_Productivity_Score']

In [426]:
# Model selection
from sklearn.model_selection import train_test_split

In [427]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [428]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        50000 non-null  float64
 1   Occupation                 50000 non-null  float64
 2   Daily_Phone_Hours          50000 non-null  float64
 3   Social_Media_Hours         50000 non-null  float64
 4   Work_Productivity_Score    50000 non-null  float64
 5   Sleep_Hours                50000 non-null  float64
 6   Stress_Level               50000 non-null  float64
 7   App_Usage_Count            50000 non-null  float64
 8   Caffeine_Intake_Cups       50000 non-null  float64
 9   Weekend_Screen_Time_Hours  50000 non-null  float64
 10  Gender_Female              50000 non-null  float64
 11  Gender_Male                50000 non-null  float64
 12  Gender_Other               50000 non-null  float64
 13  Device_Type_Android        50000 non-null  float64
 14  Device_Type_iOS            50000 non-null  float64
dtypes: float64(15)
memory usage: 5.7 MB

In [429]:
df.head()

,Age,Occupation,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Gender_Female,Gender_Male,Gender_Other,Device_Type_Android,Device_Type_iOS
0,0.952381,0.666667,0.027273,0.826667,6.0,0.96,0.333333,0.672727,0.166667,0.558333,0.0,1.0,0.0,1.0,0.0
1,0.166667,0.666667,0.018182,0.133333,5.0,0.48,0.000000,0.836364,0.500000,0.258333,0.0,1.0,0.0,1.0,0.0
2,0.023810,1.000000,0.390909,0.693333,5.0,1.00,0.333333,0.163636,0.833333,0.358333,0.0,1.0,0.0,0.0,1.0
3,0.500862,0.000000,0.436364,0.266667,2.0,0.34,0.222222,0.563636,1.000000,0.900000,1.0,0.0,0.0,0.0,1.0
4,0.500862,0.666667,0.627273,0.106667,4.0,0.34,0.222222,0.581818,0.833333,0.658333,0.0,1.0,0.0,1.0,0.0

# Decision Tree Regression

In [430]:
from sklearn.tree import DecisionTreeRegressor

In [431]:
dt_model=DecisionTreeRegressor()

In [432]:
dt_model

DecisionTreeRegressor()

In [433]:
# Fit
dt_model.fit(x_train,y_train)

DecisionTreeRegressor()

In [434]:
# Predict
y_pred=dt_model.predict(x_test)

In [435]:
y_pred

array([6., 5., 5., ..., 8., 4., 6.], shape=(10000,))

In [436]:
# Model evaluation
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [437]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [438]:
print('r2: ', r2)
print('mae: ', mae)
print('mse: ', mse)
print('rmse: ', rmse)

r2:  -1.0725794850308557
mae:  3.3740496159078175
mse:  17.21002385509979
rmse:  4.148496577689295

# Linear Regression

In [439]:
from sklearn.linear_model import LinearRegression
lr_model=LinearRegression()

In [440]:
lr_model.fit(x_train,y_train)

LinearRegression()

In [441]:
y_pred=lr_model.predict(x_test)

In [442]:
y_pred

array([5.5908921 , 5.40450928, 5.44809847, ..., 5.64214688, 5.63908159,
       5.50385535], shape=(10000,))

In [443]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [444]:
print('r2: ', r2)
print('mae: ', mae)
print('mse: ', mse)
print('rmse: ', rmse)

r2:  -0.0004779755694255261
mae:  2.509448414041401
mse:  8.30764269858409
rmse:  2.882298162679234

In [445]:
y.nunique()

11

# Decision Tree Classifier

In [446]:
from sklearn.tree import DecisionTreeClassifier

In [447]:
dt_cl=DecisionTreeClassifier()

In [448]:
y_train=y_train.astype(int) #classifierga y_train ni intga o'tkazib olishimiz kerak
y_test=y_test.astype(int)

In [449]:
dt_cl.fit(x_train,y_train)

DecisionTreeClassifier()

In [450]:
y_pred=dt_cl.predict(x_test)

In [451]:
# Classification uchun umumiy hisobot
from sklearn.metrics import classification_report

In [452]:
class_report=classification_report(y_test,y_pred)

In [453]:
print(class_report)

              precision    recall  f1-score   support

           1       0.10      0.10      0.10      1012
           2       0.10      0.11      0.10       988
           3       0.09      0.09      0.09       990
           4       0.12      0.12      0.12       993
           5       0.10      0.10      0.10       986
           6       0.10      0.10      0.10       983
           7       0.11      0.10      0.11      1050
           8       0.11      0.11      0.11       953
           9       0.10      0.10      0.10      1025
          10       0.11      0.11      0.11      1020

    accuracy                           0.10     10000
   macro avg       0.10      0.10      0.10     10000
weighted avg       0.10      0.10      0.10     10000

In [454]:
y.value_counts()

Work_Productivity_Score
9.000000     5125
5.000000     5079
2.000000     5075
6.000000     5073
10.000000    5026
1.000000     4972
4.000000     4959
7.000000     4937
3.000000     4909
8.000000     4833
5.503841       12
Name: count, dtype: int64

# Logistic Regression

In [455]:
from sklearn.linear_model import LogisticRegression

In [456]:
lg_reg=LogisticRegression()

In [457]:
lg_reg.fit(x_train,y_train)

LogisticRegression()

In [458]:
y_pred=lg_reg.predict(x_test)

In [459]:
from sklearn.metrics import classification_report

In [460]:
class_report=classification_report(y_test,y_pred)

In [461]:
from sklearn.metrics import accuracy_score

In [462]:
acc_score=accuracy_score(y_test,y_pred)

In [463]:
print(acc_score)

0.099

In [464]:
# Linear Regression yaxshi natija ko'rsatdi lekin baribir yomon