# Data bilan tanishuv

In [114]:
import pandas  as pd 
df=pd.read_csv('autos.csv')

In [115]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  str
 2   name                 371528 non-null  str
 3   seller               371528 non-null  str
 4   offerType            371528 non-null  str
 5   price                371528 non-null  int64
 6   abtest               371528 non-null  str
 7   vehicleType          333659 non-null  str
 8   yearOfRegistration   371528 non-null  int64
 9   gearbox              351319 non-null  str
 10  powerPS              371528 non-null  int64
 11  model                351044 non-null  str
 12  kilometer            371528 non-null  int64
 13  monthOfRegistration  371528 non-null  int64
 14  fuelType             338142 non-null  str
 15  brand                371528 non-null  str
 16  notRepairedDamage    299468 non-null  str
 17  dateCreated          371528 non-null  str
 18  nrOfPictures         371528 non-null  int64
 19  postalCode           371528 non-null  int64
 20  lastSeen             371528 non-null  str
dtypes: int64(8), str(13)
memory usage: 59.5 MB

In [116]:
df.head()

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

In [117]:
df = df.drop(columns=['index','dateCrawled','name','dateCreated','lastSeen'])

# Data preprocessing

In [118]:
df.isnull().sum()

seller                     0
offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
nrOfPictures               0
postalCode                 0
dtype: int64

# Encoding

In [119]:
df.nunique()

seller                    2
offerType                 2
price                  5597
abtest                    2
vehicleType               8
yearOfRegistration      155
gearbox                   2
powerPS                 794
model                   251
kilometer                13
monthOfRegistration      13
fuelType                  7
brand                    40
notRepairedDamage         2
nrOfPictures              1
postalCode             8150
dtype: int64

In [120]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'str':
        if df[col].nunique() <= 10:
            dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
            df = pd.concat([df.drop(columns=[col]), dummies], axis=1)
        else:
            df[col] = encoder.fit_transform(df[col])

In [121]:
df.isnull().sum()

price                     0
yearOfRegistration        0
powerPS                   0
model                     0
kilometer                 0
monthOfRegistration       0
brand                     0
nrOfPictures              0
postalCode                0
seller_gewerblich         0
seller_privat             0
offerType_Angebot         0
offerType_Gesuch          0
abtest_control            0
abtest_test               0
vehicleType_andere        0
vehicleType_bus           0
vehicleType_cabrio        0
vehicleType_coupe         0
vehicleType_kleinwagen    0
vehicleType_kombi         0
vehicleType_limousine     0
vehicleType_suv           0
gearbox_automatik         0
gearbox_manuell           0
fuelType_andere           0
fuelType_benzin           0
fuelType_cng              0
fuelType_diesel           0
fuelType_elektro          0
fuelType_hybrid           0
fuelType_lpg              0
notRepairedDamage_ja      0
notRepairedDamage_nein    0
dtype: int64

In [122]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 34 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   price                   371528 non-null  int64
 1   yearOfRegistration      371528 non-null  int64
 2   powerPS                 371528 non-null  int64
 3   model                   371528 non-null  int64
 4   kilometer               371528 non-null  int64
 5   monthOfRegistration     371528 non-null  int64
 6   brand                   371528 non-null  int64
 7   nrOfPictures            371528 non-null  int64
 8   postalCode              371528 non-null  int64
 9   seller_gewerblich       371528 non-null  int64
 10  seller_privat           371528 non-null  int64
 11  offerType_Angebot       371528 non-null  int64
 12  offerType_Gesuch        371528 non-null  int64
 13  abtest_control          371528 non-null  int64
 14  abtest_test             371528 non-null  int64
 15  vehicleType_andere      371528 non-null  int64
 16  vehicleType_bus         371528 non-null  int64
 17  vehicleType_cabrio      371528 non-null  int64
 18  vehicleType_coupe       371528 non-null  int64
 19  vehicleType_kleinwagen  371528 non-null  int64
 20  vehicleType_kombi       371528 non-null  int64
 21  vehicleType_limousine   371528 non-null  int64
 22  vehicleType_suv         371528 non-null  int64
 23  gearbox_automatik       371528 non-null  int64
 24  gearbox_manuell         371528 non-null  int64
 25  fuelType_andere         371528 non-null  int64
 26  fuelType_benzin         371528 non-null  int64
 27  fuelType_cng            371528 non-null  int64
 28  fuelType_diesel         371528 non-null  int64
 29  fuelType_elektro        371528 non-null  int64
 30  fuelType_hybrid         371528 non-null  int64
 31  fuelType_lpg            371528 non-null  int64
 32  notRepairedDamage_ja    371528 non-null  int64
 33  notRepairedDamage_nein  371528 non-null  int64
dtypes: int64(34)
memory usage: 96.4 MB

# Scaling

In [123]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [124]:
num_cols=df.select_dtypes(include=["int64"]).columns.drop('price')

In [125]:
num_cols

Index(['yearOfRegistration', 'powerPS', 'model', 'kilometer',
       'monthOfRegistration', 'brand', 'nrOfPictures', 'postalCode',
       'seller_gewerblich', 'seller_privat', 'offerType_Angebot',
       'offerType_Gesuch', 'abtest_control', 'abtest_test',
       'vehicleType_andere', 'vehicleType_bus', 'vehicleType_cabrio',
       'vehicleType_coupe', 'vehicleType_kleinwagen', 'vehicleType_kombi',
       'vehicleType_limousine', 'vehicleType_suv', 'gearbox_automatik',
       'gearbox_manuell', 'fuelType_andere', 'fuelType_benzin', 'fuelType_cng',
       'fuelType_diesel', 'fuelType_elektro', 'fuelType_hybrid',
       'fuelType_lpg', 'notRepairedDamage_ja', 'notRepairedDamage_nein'],
      dtype='str')

In [126]:
df[num_cols] = scaler.fit_transform(df[num_cols])

In [127]:
df.head()

,price,yearOfRegistration,powerPS,model,kilometer,monthOfRegistration,brand,nrOfPictures,postalCode,seller_gewerblich,...,gearbox_manuell,fuelType_andere,fuelType_benzin,fuelType_cng,fuelType_diesel,fuelType_elektro,fuelType_hybrid,fuelType_lpg,notRepairedDamage_ja,notRepairedDamage_nein
0,480,-0.124674,-0.601384,0.112846,0.607827,-1.544670,1.295374,0.0,0.760274,-0.002842,...,0.595721,-0.023668,0.812199,-0.039233,-0.639114,-0.016733,-0.027365,-0.121194,-0.328996,-1.558553
1,18300,0.069153,0.387482,1.824633,-0.015424,-0.197835,-1.473469,0.0,0.625346,-0.002842,...,0.595721,-0.023668,-1.231226,-0.039233,1.564667,-0.016733,-0.027365,-0.121194,3.039553,-1.558553
2,9800,-0.006224,0.246959,0.125716,-0.015424,0.610266,-0.500632,0.0,1.537240,-0.002842,...,-1.678638,-0.023668,-1.231226,-0.039233,1.564667,-0.016733,-0.027365,-0.121194,-0.328996,-1.558553
3,1500,-0.038528,-0.211042,0.112846,0.607827,0.071532,1.295374,0.0,1.560264,-0.002842,...,0.595721,-0.023668,0.812199,-0.039233,-0.639114,-0.016733,-0.027365,-0.121194,-0.328996,0.641621
4,3600,0.036849,-0.242269,-0.080213,-0.887975,0.340899,0.771539,0.0,0.372740,-0.002842,...,0.595721,-0.023668,-1.231226,-0.039233,1.564667,-0.016733,-0.027365,-0.121194,-0.328996,0.641621

# Model Selection

In [128]:
from sklearn.linear_model import LinearRegression

In [129]:
lr=LinearRegression()

In [130]:
lr

LinearRegression()

# Training

In [131]:
X = df.drop('price', axis=1)

In [132]:
y = df['price']

In [133]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [134]:
X_train.shape

(297222, 33)

In [135]:
X_test.shape

(74306, 33)

In [136]:
y_train.shape

(297222,)

In [137]:
y_test.shape

(74306,)

In [138]:
df.isnull().sum()

price                     0
yearOfRegistration        0
powerPS                   0
model                     0
kilometer                 0
monthOfRegistration       0
brand                     0
nrOfPictures              0
postalCode                0
seller_gewerblich         0
seller_privat             0
offerType_Angebot         0
offerType_Gesuch          0
abtest_control            0
abtest_test               0
vehicleType_andere        0
vehicleType_bus           0
vehicleType_cabrio        0
vehicleType_coupe         0
vehicleType_kleinwagen    0
vehicleType_kombi         0
vehicleType_limousine     0
vehicleType_suv           0
gearbox_automatik         0
gearbox_manuell           0
fuelType_andere           0
fuelType_benzin           0
fuelType_cng              0
fuelType_diesel           0
fuelType_elektro          0
fuelType_hybrid           0
fuelType_lpg              0
notRepairedDamage_ja      0
notRepairedDamage_nein    0
dtype: int64

# Prediction

In [141]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [143]:
lr.fit(X_train, y_train)

LinearRegression()

In [145]:
y_predict

array([-21367.20788922, -23623.26774746,  17372.55593668, ...,
       -16648.97371329, -12503.13297281,  31695.82907964], shape=(74306,))

# Evaluation

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [ ]:
y_pred=lr.predict(X_test)

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2:", r2)

MAE: 44171.146325570764
MSE: 544864977397.0554
R2: -0.30318381080498513