# Kaggledan/Githubdan dataset toping:
# Funksiya+Missing+Encoding
# Logistic Regression tekshiring
# Classification Report

In [15]:
import pandas as pd

In [16]:
df=pd.read_csv('logistic_regression (1).csv')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 396030 entries, 0 to 396029
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   loan_amnt             396030 non-null  float64
 1   term                  396030 non-null  str
 2   int_rate              396030 non-null  float64
 3   installment           396030 non-null  float64
 4   grade                 396030 non-null  str
 5   sub_grade             396030 non-null  str
 6   emp_title             373103 non-null  str
 7   emp_length            377729 non-null  str
 8   home_ownership        396030 non-null  str
 9   annual_inc            396030 non-null  float64
 10  verification_status   396030 non-null  str
 11  issue_d               396030 non-null  str
 12  loan_status           396030 non-null  str
 13  purpose               396030 non-null  str
 14  title                 394274 non-null  str
 15  dti                   396030 non-null  float64
 16  earliest_cr_line      396030 non-null  str
 17  open_acc              396030 non-null  float64
 18  pub_rec               396030 non-null  float64
 19  revol_bal             396030 non-null  float64
 20  revol_util            395754 non-null  float64
 21  total_acc             396030 non-null  float64
 22  initial_list_status   396030 non-null  str
 23  application_type      396030 non-null  str
 24  mort_acc              358235 non-null  float64
 25  pub_rec_bankruptcies  395495 non-null  float64
 26  address               396030 non-null  str
dtypes: float64(12), str(15)
memory usage: 81.6 MB

In [18]:
df.isnull().sum()

loan_amnt                   0
term                        0
int_rate                    0
installment                 0
grade                       0
sub_grade                   0
emp_title               22927
emp_length              18301
home_ownership              0
annual_inc                  0
verification_status         0
issue_d                     0
loan_status                 0
purpose                     0
title                    1756
dti                         0
earliest_cr_line            0
open_acc                    0
pub_rec                     0
revol_bal                   0
revol_util                276
total_acc                   0
initial_list_status         0
application_type            0
mort_acc                37795
pub_rec_bankruptcies      535
address                     0
dtype: int64

In [19]:
df.drop(['emp_title'], axis=1, inplace=True)
df.drop(['title'], axis=1, inplace=True)
df.drop(['address'], axis=1, inplace=True)
df.drop(['sub_grade'], axis=1, inplace=True)
df.drop(['issue_d'], axis=1, inplace=True)
df.drop(['installment'], axis=1, inplace=True)

In [20]:
df.isnull().sum()

loan_amnt                   0
term                        0
int_rate                    0
grade                       0
emp_length              18301
home_ownership              0
annual_inc                  0
verification_status         0
loan_status                 0
purpose                     0
dti                         0
earliest_cr_line            0
open_acc                    0
pub_rec                     0
revol_bal                   0
revol_util                276
total_acc                   0
initial_list_status         0
application_type            0
mort_acc                37795
pub_rec_bankruptcies      535
dtype: int64

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 396030 entries, 0 to 396029
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   loan_amnt             396030 non-null  float64
 1   term                  396030 non-null  str
 2   int_rate              396030 non-null  float64
 3   grade                 396030 non-null  str
 4   emp_length            377729 non-null  str
 5   home_ownership        396030 non-null  str
 6   annual_inc            396030 non-null  float64
 7   verification_status   396030 non-null  str
 8   loan_status           396030 non-null  str
 9   purpose               396030 non-null  str
 10  dti                   396030 non-null  float64
 11  earliest_cr_line      396030 non-null  str
 12  open_acc              396030 non-null  float64
 13  pub_rec               396030 non-null  float64
 14  revol_bal             396030 non-null  float64
 15  revol_util            395754 non-null  float64
 16  total_acc             396030 non-null  float64
 17  initial_list_status   396030 non-null  str
 18  application_type      396030 non-null  str
 19  mort_acc              358235 non-null  float64
 20  pub_rec_bankruptcies  395495 non-null  float64
dtypes: float64(11), str(10)
memory usage: 63.5 MB

# Funksiya+Missing+Encoding

In [22]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return (df)

In [23]:
toldir(df)

,loan_amnt,term,int_rate,grade,emp_length,home_ownership,annual_inc,verification_status,loan_status,purpose,...,earliest_cr_line,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies
0,10000.0,36 months,11.44,B,10+ years,RENT,117000.0,Not Verified,Fully Paid,vacation,...,Jun-1990,16.0,0.0,36369.0,41.8,25.0,w,INDIVIDUAL,0.000000,0.0
1,8000.0,36 months,11.99,B,4 years,MORTGAGE,65000.0,Not Verified,Fully Paid,debt_consolidation,...,Jul-2004,17.0,0.0,20131.0,53.3,27.0,f,INDIVIDUAL,3.000000,0.0
2,15600.0,36 months,10.49,B,< 1 year,RENT,43057.0,Source Verified,Fully Paid,credit_card,...,Aug-2007,13.0,0.0,11987.0,92.2,26.0,f,INDIVIDUAL,0.000000,0.0
3,7200.0,36 months,6.49,A,6 years,RENT,54000.0,Not Verified,Fully Paid,credit_card,...,Sep-2006,6.0,0.0,5472.0,21.5,13.0,f,INDIVIDUAL,0.000000,0.0
4,24375.0,60 months,17.27,C,9 years,MORTGAGE,55000.0,Verified,Charged Off,credit_card,...,Mar-1999,13.0,0.0,24584.0,69.8,43.0,f,INDIVIDUAL,1.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396025,10000.0,60 months,10.99,B,2 years,RENT,40000.0,Source Verified,Fully Paid,debt_consolidation,...,Nov-2004,6.0,0.0,1990.0,34.3,23.0,w,INDIVIDUAL,0.000000,0.0
396026,21000.0,36 months,12.29,C,5 years,MORTGAGE,110000.0,Source Verified,Fully Paid,debt_consolidation,...,Feb-2006,6.0,0.0,43263.0,95.7,8.0,f,INDIVIDUAL,1.000000,0.0
396027,5000.0,36 months,9.99,B,10+ years,RENT,56500.0,Verified,Fully Paid,debt_consolidation,...,Mar-1997,15.0,0.0,32704.0,66.9,23.0,f,INDIVIDUAL,0.000000,0.0
396028,21000.0,60 months,15.31,C,10+ years,MORTGAGE,64000.0,Verified,Fully Paid,debt_consolidation,...,Nov-1990,9.0,0.0,15704.0,53.8,20.0,f,INDIVIDUAL,5.000000,0.0
396029,2000.0,36 months,13.61,C,10+ years,RENT,42996.0,Verified,Fully Paid,debt_consolidation,...,Sep-1998,3.0,0.0,4292.0,91.3,19.0,f,INDIVIDUAL,1.813991,0.0

In [24]:
df.isnull().sum()

loan_amnt               0
term                    0
int_rate                0
grade                   0
emp_length              0
home_ownership          0
annual_inc              0
verification_status     0
loan_status             0
purpose                 0
dti                     0
earliest_cr_line        0
open_acc                0
pub_rec                 0
revol_bal               0
revol_util              0
total_acc               0
initial_list_status     0
application_type        0
mort_acc                0
pub_rec_bankruptcies    0
dtype: int64

# Funksiya+Encoding

In [37]:
def encodla(df):
    from sklearn.preprocessing import LabelEncoder
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique()<=6:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
        else:
            encoder=LabelEncoder()
            df[col]=encoder.fit_transform(df[col])
    return df

In [38]:
encodla(df)

,loan_amnt,term,int_rate,grade,emp_length,home_ownership,annual_inc,verification_status,loan_status,purpose,...,earliest_cr_line,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies
0,367,0,131,1,1,5,24266,0,1,12,...,378,16,0,35796,468,23,1,1,0,0
1,287,0,152,1,4,1,15078,0,1,2,...,336,17,0,20131,587,25,0,1,4,0
2,591,0,104,1,10,5,7491,1,1,1,...,106,13,0,11987,988,24,0,1,0,0
3,255,0,10,0,6,5,11536,0,1,1,...,676,6,0,5472,245,11,0,1,0,0
4,942,1,344,2,9,1,11886,2,0,1,...,440,13,0,24577,758,41,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396025,367,1,118,1,2,5,6332,1,1,2,...,560,6,0,1990,388,21,1,1,0,0
396026,807,0,162,2,5,1,23666,1,1,2,...,217,6,0,41098,1024,6,0,1,1,0
396027,167,0,88,1,1,5,12398,2,1,2,...,438,15,0,32477,729,21,0,1,0,0
396028,807,1,287,2,1,1,14805,2,1,2,...,546,9,0,15704,593,18,0,1,6,0
396029,47,0,213,2,1,5,7468,2,1,2,...,668,3,0,4292,979,17,0,1,2,0

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 396030 entries, 0 to 396029
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   loan_amnt             396030 non-null  int64
 1   term                  396030 non-null  int64
 2   int_rate              396030 non-null  int64
 3   grade                 396030 non-null  int64
 4   emp_length            396030 non-null  int64
 5   home_ownership        396030 non-null  int64
 6   annual_inc            396030 non-null  int64
 7   verification_status   396030 non-null  int64
 8   loan_status           396030 non-null  int64
 9   purpose               396030 non-null  int64
 10  dti                   396030 non-null  int64
 11  earliest_cr_line      396030 non-null  int64
 12  open_acc              396030 non-null  int64
 13  pub_rec               396030 non-null  int64
 14  revol_bal             396030 non-null  int64
 15  revol_util            396030 non-null  int64
 16  total_acc             396030 non-null  int64
 17  initial_list_status   396030 non-null  int64
 18  application_type      396030 non-null  int64
 19  mort_acc              396030 non-null  int64
 20  pub_rec_bankruptcies  396030 non-null  int64
dtypes: int64(21)
memory usage: 63.5 MB

# Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [43]:
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('loan_status')
    for col in num_col:
        df[col]=scaler.fit_transform(df[[col]])
    return df

In [44]:
scaling_qil(df)

,loan_amnt,term,int_rate,grade,emp_length,home_ownership,annual_inc,verification_status,loan_status,purpose,...,earliest_cr_line,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies
0,0.262894,0.0,0.231858,0.166667,0.1,1.0,0.892264,0.0,1,0.923077,...,0.553441,0.266667,0.0,0.643570,0.381729,0.196581,1.0,0.5,0.000000,0.0
1,0.205587,0.0,0.269027,0.166667,0.4,0.2,0.554420,0.0,1,0.153846,...,0.491947,0.283333,0.0,0.361932,0.478793,0.213675,0.0,0.5,0.121212,0.0
2,0.423352,0.0,0.184071,0.166667,1.0,1.0,0.275445,0.5,1,0.076923,...,0.155198,0.216667,0.0,0.215512,0.805873,0.205128,0.0,0.5,0.000000,0.0
3,0.182665,0.0,0.017699,0.000000,0.6,1.0,0.424180,0.0,1,0.076923,...,0.989751,0.100000,0.0,0.098380,0.199837,0.094017,0.0,0.5,0.000000,0.0
4,0.674785,1.0,0.608850,0.333333,0.9,0.2,0.437050,1.0,0,0.076923,...,0.644217,0.216667,0.0,0.441865,0.618271,0.350427,0.0,0.5,0.030303,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396025,0.262894,1.0,0.208850,0.166667,0.2,1.0,0.232828,0.5,1,0.153846,...,0.819912,0.100000,0.0,0.035778,0.316476,0.179487,1.0,0.5,0.000000,0.0
396026,0.578080,0.0,0.286726,0.333333,0.5,0.2,0.870202,0.5,1,0.153846,...,0.317716,0.100000,0.0,0.738894,0.835237,0.051282,0.0,0.5,0.030303,0.0
396027,0.119628,0.0,0.155752,0.166667,0.1,1.0,0.455876,1.0,1,0.153846,...,0.641288,0.250000,0.0,0.583898,0.594617,0.179487,0.0,0.5,0.000000,0.0
396028,0.578080,1.0,0.507965,0.333333,0.1,0.2,0.544382,1.0,1,0.153846,...,0.799414,0.150000,0.0,0.282339,0.483687,0.153846,0.0,0.5,0.181818,0.0
396029,0.033668,0.0,0.376991,0.333333,0.1,1.0,0.274599,1.0,1,0.153846,...,0.978038,0.050000,0.0,0.077165,0.798532,0.145299,0.0,0.5,0.060606,0.0

# Model

In [45]:
x=df.drop('loan_status',axis=1)

In [48]:
y=df['loan_status'].astype(int)

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [51]:
x_train.shape

(277221, 20)

In [53]:
x_test.shape

(118809, 20)

In [52]:
y_train.shape

(277221,)

In [54]:
y_test.shape

(118809,)

In [55]:
from sklearn.linear_model import LogisticRegression

In [58]:
log_reg=LogisticRegression()

In [59]:
log_reg

LogisticRegression()

In [61]:
log_reg.fit(x_train,y_train)

LogisticRegression()

In [62]:
y_pred=log_reg.predict(x_test)

In [68]:
from sklearn.metrics import classification_report, accuracy_score

In [65]:
class_report=classification_report(y_test,y_pred)

In [67]:
print(class_report)

              precision    recall  f1-score   support

           0       0.52      0.08      0.13     23370
           1       0.81      0.98      0.89     95439

    accuracy                           0.80    118809
   macro avg       0.67      0.53      0.51    118809
weighted avg       0.76      0.80      0.74    118809