Linear Regression va Decision Tree Regressorlarni qo'llab loyiha qilib koramiz

In [53]:
import pandas as pd

In [54]:
df=pd.read_csv("genz_social_media_usage_1M.csv")

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   age                       1000000 non-null  int64
 1   gender                    1000000 non-null  str
 2   country                   1000000 non-null  str
 3   daily_usage_hours         1000000 non-null  float64
 4   primary_platform          1000000 non-null  str
 5   num_platforms_used        1000000 non-null  int64
 6   purpose                   1000000 non-null  str
 7   avg_session_minutes       1000000 non-null  float64
 8   night_usage               1000000 non-null  int64
 9   mental_health_score       1000000 non-null  float64
 10  addiction_level           1000000 non-null  str
 11  screen_time_before_sleep  1000000 non-null  float64
dtypes: float64(4), int64(3), str(5)
memory usage: 91.6 MB

# Missing

In [56]:
df.isnull().sum()

age                         0
gender                      0
country                     0
daily_usage_hours           0
primary_platform            0
num_platforms_used          0
purpose                     0
avg_session_minutes         0
night_usage                 0
mental_health_score         0
addiction_level             0
screen_time_before_sleep    0
dtype: int64

# Encoding

In [57]:
from sklearn.preprocessing import LabelEncoder

def encodla(df):
    encoder=LabelEncoder()

    for col in df.columns:
        if df[col].dtype == 'str':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col], prefix=col, dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [58]:
df=encodla(df)

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 24 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   age                         1000000 non-null  int64
 1   country                     1000000 non-null  int64
 2   daily_usage_hours           1000000 non-null  float64
 3   num_platforms_used          1000000 non-null  int64
 4   avg_session_minutes         1000000 non-null  float64
 5   night_usage                 1000000 non-null  int64
 6   mental_health_score         1000000 non-null  float64
 7   screen_time_before_sleep    1000000 non-null  float64
 8   gender_Female               1000000 non-null  int64
 9   gender_Male                 1000000 non-null  int64
 10  gender_Other                1000000 non-null  int64
 11  primary_platform_Instagram  1000000 non-null  int64
 12  primary_platform_Snapchat   1000000 non-null  int64
 13  primary_platform_TikTok     1000000 non-null  int64
 14  primary_platform_Twitter    1000000 non-null  int64
 15  primary_platform_YouTube    1000000 non-null  int64
 16  purpose_Content Creation    1000000 non-null  int64
 17  purpose_Education           1000000 non-null  int64
 18  purpose_Entertainment       1000000 non-null  int64
 19  purpose_News                1000000 non-null  int64
 20  purpose_Socializing         1000000 non-null  int64
 21  addiction_level_High        1000000 non-null  int64
 22  addiction_level_Low         1000000 non-null  int64
 23  addiction_level_Medium      1000000 non-null  int64
dtypes: float64(4), int64(20)
memory usage: 183.1 MB

# Scaler

In [13]:
df.head()

,age,country,daily_usage_hours,num_platforms_used,avg_session_minutes,night_usage,mental_health_score,screen_time_before_sleep,gender_Female,gender_Male,...,primary_platform_Twitter,primary_platform_YouTube,purpose_Content Creation,purpose_Education,purpose_Entertainment,purpose_News,purpose_Socializing,addiction_level_High,addiction_level_Low,addiction_level_Medium
0,19,0,2.658617,4,29.222443,0,6.705830,15.779443,0,1,...,0,0,0,1,0,0,0,0,0,1
1,16,6,5.685387,3,32.464726,1,6.633111,47.714864,1,0,...,1,0,0,0,0,0,1,1,0,0
2,25,4,2.782420,2,18.170204,1,6.035397,62.524625,1,0,...,0,0,0,0,0,0,1,0,0,1
3,27,4,3.486598,4,22.493804,1,8.110861,31.935102,0,1,...,0,1,0,1,0,0,0,0,0,1
4,23,4,3.748829,1,27.358410,1,6.658598,29.466046,1,0,...,0,0,0,0,1,0,0,0,0,1

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
def scale_qil(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('mental_health_score')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [16]:
df=scale_qil(df)

In [17]:
df.head()

,age,country,daily_usage_hours,num_platforms_used,avg_session_minutes,night_usage,mental_health_score,screen_time_before_sleep,gender_Female,gender_Male,...,primary_platform_Twitter,primary_platform_YouTube,purpose_Content Creation,purpose_Education,purpose_Entertainment,purpose_News,purpose_Socializing,addiction_level_High,addiction_level_Low,addiction_level_Medium
0,0.428571,0.000000,0.227223,0.75,0.321841,0.0,6.705830,0.114345,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.214286,1.000000,0.545830,0.50,0.364920,1.0,6.633111,0.345763,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.857143,0.666667,0.240255,0.25,0.174991,1.0,6.035397,0.453081,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,1.000000,0.666667,0.314379,0.75,0.232438,1.0,8.110861,0.231416,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.714286,0.666667,0.341982,0.00,0.297073,1.0,6.658598,0.213524,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

# Model

In [60]:
x=df.drop('mental_health_score',axis=1)

In [61]:
y=df['mental_health_score']

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# LinearRegression

In [23]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [24]:
lr

LinearRegression()

In [25]:
lr.fit(x_train,y_train)

LinearRegression()

In [70]:
y_pred=lr.predict(x_test)

# Model Evaluation(Regression)

In [71]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [29]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [30]:
print(r2)
print(mae)
print(mse)
print(rmse)

0.5819563136497768
0.7797517003731866
0.9474934348347088
0.9733927443918559

# DecisionTreeRegressor

In [77]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()

In [78]:
dt

DecisionTreeRegressor()

In [79]:
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [80]:
y_pred=lr.predict(x_test)

In [81]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [82]:
print(r2)
print(mae)
print(mse)
print(rmse)

-280.2231843078816
23.315674842948273
637.7649701845845
25.25400899232802

In [ ]:
# # bu LinearREgressionda chiqqan natija 
# 0.5819563136497768
# 0.7797517003731866
# 0.9474934348347088
# 0.9733927443918559