# Encoding

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/Users/sunnatabdurayimov/Downloads/Machine_Learning/ShahRukh_Khan.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             193 non-null    str
 1    Type             6 non-null      str
 2    Country Origin   161 non-null    str
 3    Director         193 non-null    str
 4    Languages        193 non-null    str
 5    Plot             193 non-null    str
 6    Metascore        193 non-null    str
 7    Genre            193 non-null    str
 8    Rating           193 non-null    str
 9    Relese Date      193 non-null    str
 10   Rated            193 non-null    str
 11   Awards           193 non-null    str
 12   Actors           193 non-null    str
 13   Poster link      193 non-null    str
dtypes: str(14)
memory usage: 21.2 KB

#drop
#1-holat

In [4]:
df.columns.tolist()

['Title ',
 ' Type ',
 ' Country Origin ',
 ' Director ',
 ' Languages ',
 ' Plot ',
 ' Metascore ',
 ' Genre ',
 ' Rating  ',
 ' Relese Date ',
 ' Rated ',
 ' Awards ',
 ' Actors ',
 ' Poster link']

In [5]:
df.drop(' Director ', axis=1, inplace=True, errors='ignore')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             193 non-null    str
 1    Type             6 non-null      str
 2    Country Origin   161 non-null    str
 3    Languages        193 non-null    str
 4    Plot             193 non-null    str
 5    Metascore        193 non-null    str
 6    Genre            193 non-null    str
 7    Rating           193 non-null    str
 8    Relese Date      193 non-null    str
 9    Rated            193 non-null    str
 10   Awards           193 non-null    str
 11   Actors           193 non-null    str
 12   Poster link      193 non-null    str
dtypes: str(13)
memory usage: 19.7 KB

#drop
#2-holat .qator bo'yicha

In [7]:
#df.dropna(inplace=True)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             193 non-null    str
 1    Type             6 non-null      str
 2    Country Origin   161 non-null    str
 3    Languages        193 non-null    str
 4    Plot             193 non-null    str
 5    Metascore        193 non-null    str
 6    Genre            193 non-null    str
 7    Rating           193 non-null    str
 8    Relese Date      193 non-null    str
 9    Rated            193 non-null    str
 10   Awards           193 non-null    str
 11   Actors           193 non-null    str
 12   Poster link      193 non-null    str
dtypes: str(13)
memory usage: 19.7 KB

In [9]:
df.isnull().sum()

Title                 0
 Type               187
 Country Origin      32
 Languages            0
 Plot                 0
 Metascore            0
 Genre                0
 Rating               0
 Relese Date          0
 Rated                0
 Awards               0
 Actors               0
 Poster link          0
dtype: int64

In [10]:
df.fillna({' Type ':df[' Type '].mode()[0]},inplace=True)

,Title,Type,Country Origin,Languages,Plot,Metascore,Genre,Rating,Relese Date,Rated,Awards,Actors,Poster link
0,Don 3,movie,India,Hindi,N/A,N/A,Action& Thriller,N/A,N/A,N/A,N/A,Shah Rukh Khan& Farhan Akhtar& Boman Irani& K...,N/A
1,Rocketry: The Nambi Effect,movie,India,Hindi& Tamil& Telugu,Based by the life of ISRO Scientist Nambi Nara...,N/A,N/A,N/A,N/A,N/A,N/A,Madhavan& Rajeev Ravindranathan& Simran& Bijo...,https://m.media-amazon.com/images/M/MV5BNDNlYT...
2,Koochie Koochie Hota Hai,movie,India,Hindi,The film is an animated take on Kuch Kuch Hota...,N/A,Animation& Family& Musical& Romance,N/A,N/A,N/A,N/A,Shah Rukh Khan& Kajol& Rani Mukerji& Sanjay D...,https://m.media-amazon.com/images/M/MV5BNzU3ZT...
3,Zero,movie,India,Hindi,The story revolves around Bauua Singh (Shah R...,N/A,Comedy& Drama& Romance,5.5,21 Dec 2018,Not Rated,4 wins & 10 nominations.,Shah Rukh Khan& Anushka Sharma& Katrina Kaif&...,https://m.media-amazon.com/images/M/MV5BNzg5Yj...
4,Titu Talks,series,India,Hindi,Bhuvan Bam plays his famous character 'Titu M...,N/A,Comedy& Talk-Show,7.7,15 Dec 2018,N/A,N/A,Bhuvan Bam,https://m.media-amazon.com/images/M/MV5BNWEzMG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,Pehla Nasha,movie,India,Hindi,"Uncredited remake of Brian De Palma's ""Body D...",N/A,Mystery& Drama& Thriller,5.3,13 Aug 1993,N/A,N/A,Deepak Tijori& Pooja Bhatt& Raveena Tandon& M...,https://m.media-amazon.com/images/M/MV5BZWYyZD...
189,Rajani,movie,India,Hindi,N/A,N/A,Comedy,N/A,01 Jan 1993,N/A,N/A,Shah Rukh Khan& Prashant Narayanan& Rajiv Pau...,N/A
190,Umang Tarang,movie,India,Hindi,N/A,N/A,Game-Show,9.7,29 Aug 1989,N/A,N/A,Shah Rukh Khan& Kumar Sanu,N/A
191,Golmaal Again,movie,India,Hindi,The gang encounters with some spiritual bodie...,N/A,Action& Comedy& Fantasy& Horror,4.9,20 Oct 2017,Not Rated,4 wins & 7 nominations.,Ajay Devgn& Arshad Warsi& Tusshar Kapoor& Shr...,https://m.media-amazon.com/images/M/MV5BYmI5Y2...
192,101 Sexiest Celebrity Bodies,movie,USA,English,N/A,N/A,N/A,7.3,22 Nov 2005,N/A,N/A,50 Cent& Jessica Alba& Pamela Anderson& Jennif...,https://m.media-amazon.com/images/M/MV5BODIyM2...

In [11]:
df.isnull().sum()

Title                0
 Type                0
 Country Origin     32
 Languages           0
 Plot                0
 Metascore           0
 Genre               0
 Rating              0
 Relese Date         0
 Rated               0
 Awards              0
 Actors              0
 Poster link         0
dtype: int64

In [12]:
df.fillna({' Country Origin ':df[' Country Origin '].mode()[0]},inplace=True)

,Title,Type,Country Origin,Languages,Plot,Metascore,Genre,Rating,Relese Date,Rated,Awards,Actors,Poster link
0,Don 3,movie,India,Hindi,N/A,N/A,Action& Thriller,N/A,N/A,N/A,N/A,Shah Rukh Khan& Farhan Akhtar& Boman Irani& K...,N/A
1,Rocketry: The Nambi Effect,movie,India,Hindi& Tamil& Telugu,Based by the life of ISRO Scientist Nambi Nara...,N/A,N/A,N/A,N/A,N/A,N/A,Madhavan& Rajeev Ravindranathan& Simran& Bijo...,https://m.media-amazon.com/images/M/MV5BNDNlYT...
2,Koochie Koochie Hota Hai,movie,India,Hindi,The film is an animated take on Kuch Kuch Hota...,N/A,Animation& Family& Musical& Romance,N/A,N/A,N/A,N/A,Shah Rukh Khan& Kajol& Rani Mukerji& Sanjay D...,https://m.media-amazon.com/images/M/MV5BNzU3ZT...
3,Zero,movie,India,Hindi,The story revolves around Bauua Singh (Shah R...,N/A,Comedy& Drama& Romance,5.5,21 Dec 2018,Not Rated,4 wins & 10 nominations.,Shah Rukh Khan& Anushka Sharma& Katrina Kaif&...,https://m.media-amazon.com/images/M/MV5BNzg5Yj...
4,Titu Talks,series,India,Hindi,Bhuvan Bam plays his famous character 'Titu M...,N/A,Comedy& Talk-Show,7.7,15 Dec 2018,N/A,N/A,Bhuvan Bam,https://m.media-amazon.com/images/M/MV5BNWEzMG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,Pehla Nasha,movie,India,Hindi,"Uncredited remake of Brian De Palma's ""Body D...",N/A,Mystery& Drama& Thriller,5.3,13 Aug 1993,N/A,N/A,Deepak Tijori& Pooja Bhatt& Raveena Tandon& M...,https://m.media-amazon.com/images/M/MV5BZWYyZD...
189,Rajani,movie,India,Hindi,N/A,N/A,Comedy,N/A,01 Jan 1993,N/A,N/A,Shah Rukh Khan& Prashant Narayanan& Rajiv Pau...,N/A
190,Umang Tarang,movie,India,Hindi,N/A,N/A,Game-Show,9.7,29 Aug 1989,N/A,N/A,Shah Rukh Khan& Kumar Sanu,N/A
191,Golmaal Again,movie,India,Hindi,The gang encounters with some spiritual bodie...,N/A,Action& Comedy& Fantasy& Horror,4.9,20 Oct 2017,Not Rated,4 wins & 7 nominations.,Ajay Devgn& Arshad Warsi& Tusshar Kapoor& Shr...,https://m.media-amazon.com/images/M/MV5BYmI5Y2...
192,101 Sexiest Celebrity Bodies,movie,USA,English,N/A,N/A,N/A,7.3,22 Nov 2005,N/A,N/A,50 Cent& Jessica Alba& Pamela Anderson& Jennif...,https://m.media-amazon.com/images/M/MV5BODIyM2...

In [13]:
df.isnull().sum()

Title               0
 Type               0
 Country Origin     0
 Languages          0
 Plot               0
 Metascore          0
 Genre              0
 Rating             0
 Relese Date        0
 Rated              0
 Awards             0
 Actors             0
 Poster link        0
dtype: int64

In [14]:
df.nunique()

Title               164
 Type                 3
 Country Origin      14
 Languages           30
 Plot               135
 Metascore           11
 Genre               80
 Rating              55
 Relese Date        149
 Rated               12
 Awards              57
 Actors             161
 Poster link        135
dtype: int64

# One-Hot encoding

In [15]:
dummies=pd.get_dummies(df[' Type '],prefix='col',dtype=int)

In [16]:
dummies

     col_   col_ movie   col_ series
0        0            1             0
1        0            1             0
2        0            1             0
3        0            1             0
4        0            0             1
..     ...          ...           ...
188      0            1             0
189      0            1             0
190      0            1             0
191      0            1             0
192      0            1             0

[193 rows x 3 columns]

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             193 non-null    str
 1    Type             193 non-null    str
 2    Country Origin   193 non-null    str
 3    Languages        193 non-null    str
 4    Plot             193 non-null    str
 5    Metascore        193 non-null    str
 6    Genre            193 non-null    str
 7    Rating           193 non-null    str
 8    Relese Date      193 non-null    str
 9    Rated            193 non-null    str
 10   Awards           193 non-null    str
 11   Actors           193 non-null    str
 12   Poster link      193 non-null    str
dtypes: str(13)
memory usage: 19.7 KB

In [18]:
df=pd.concat([df.drop(columns=[' Type ']),dummies])

In [19]:
df.info()

<class 'pandas.DataFrame'>
Index: 386 entries, 0 to 192
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             193 non-null    str
 1    Country Origin   193 non-null    str
 2    Languages        193 non-null    str
 3    Plot             193 non-null    str
 4    Metascore        193 non-null    str
 5    Genre            193 non-null    str
 6    Rating           193 non-null    str
 7    Relese Date      193 non-null    str
 8    Rated            193 non-null    str
 9    Awards           193 non-null    str
 10   Actors           193 non-null    str
 11   Poster link      193 non-null    str
 12  col_              193 non-null    float64
 13  col_ movie        193 non-null    float64
 14  col_ series       193 non-null    float64
dtypes: float64(3), str(12)
memory usage: 48.2 KB

# df=pd.concat(df_1,df_2)- 2ta datasetni birlashtiruvchi kod

# Label encoding

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 386 entries, 0 to 192
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             193 non-null    str
 1    Country Origin   193 non-null    str
 2    Languages        193 non-null    str
 3    Plot             193 non-null    str
 4    Metascore        193 non-null    str
 5    Genre            193 non-null    str
 6    Rating           193 non-null    str
 7    Relese Date      193 non-null    str
 8    Rated            193 non-null    str
 9    Awards           193 non-null    str
 10   Actors           193 non-null    str
 11   Poster link      193 non-null    str
 12  col_              193 non-null    float64
 13  col_ movie        193 non-null    float64
 14  col_ series       193 non-null    float64
dtypes: float64(3), str(12)
memory usage: 48.2 KB

In [30]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [32]:
from sklearn.preprocessing import LabelEncoder

In [41]:
encoder=LabelEncoder()

In [42]:
encoder

LabelEncoder()

In [43]:
df[' Country Origin ']=encoder.fit_transform(df[' Country Origin '])

In [44]:
df.head()

,Title,Country Origin,Languages,Plot,Metascore,Genre,Rating,Relese Date,Rated,Awards,Actors,Poster link,col_,col_ movie,col_ series
0,Don 3,5,Hindi,N/A,N/A,Action& Thriller,N/A,N/A,N/A,N/A,Shah Rukh Khan& Farhan Akhtar& Boman Irani& K...,N/A,NaN,NaN,NaN
1,Rocketry: The Nambi Effect,5,Hindi& Tamil& Telugu,Based by the life of ISRO Scientist Nambi Nara...,N/A,N/A,N/A,N/A,N/A,N/A,Madhavan& Rajeev Ravindranathan& Simran& Bijo...,https://m.media-amazon.com/images/M/MV5BNDNlYT...,NaN,NaN,NaN
2,Koochie Koochie Hota Hai,5,Hindi,The film is an animated take on Kuch Kuch Hota...,N/A,Animation& Family& Musical& Romance,N/A,N/A,N/A,N/A,Shah Rukh Khan& Kajol& Rani Mukerji& Sanjay D...,https://m.media-amazon.com/images/M/MV5BNzU3ZT...,NaN,NaN,NaN
3,Zero,5,Hindi,The story revolves around Bauua Singh (Shah R...,N/A,Comedy& Drama& Romance,5.5,21 Dec 2018,Not Rated,4 wins & 10 nominations.,Shah Rukh Khan& Anushka Sharma& Katrina Kaif&...,https://m.media-amazon.com/images/M/MV5BNzg5Yj...,NaN,NaN,NaN
4,Titu Talks,5,Hindi,Bhuvan Bam plays his famous character 'Titu M...,N/A,Comedy& Talk-Show,7.7,15 Dec 2018,N/A,N/A,Bhuvan Bam,https://m.media-amazon.com/images/M/MV5BNWEzMG...,NaN,NaN,NaN

In [45]:
df[' Languages ']=encoder.fit_transform(df[' Languages '])

In [47]:
df[' Actors ']=encoder.fit_transform(df[' Actors '])

In [48]:
df.head()

,Title,Country Origin,Languages,Plot,Metascore,Genre,Rating,Relese Date,Rated,Awards,Actors,Poster link,col_,col_ movie,col_ series
0,Don 3,5,6,N/A,N/A,Action& Thriller,N/A,N/A,N/A,N/A,111,N/A,NaN,NaN,NaN
1,Rocketry: The Nambi Effect,5,17,Based by the life of ISRO Scientist Nambi Nara...,N/A,N/A,N/A,N/A,N/A,N/A,67,https://m.media-amazon.com/images/M/MV5BNDNlYT...,NaN,NaN,NaN
2,Koochie Koochie Hota Hai,5,6,The film is an animated take on Kuch Kuch Hota...,N/A,Animation& Family& Musical& Romance,N/A,N/A,N/A,N/A,122,https://m.media-amazon.com/images/M/MV5BNzU3ZT...,NaN,NaN,NaN
3,Zero,5,6,The story revolves around Bauua Singh (Shah R...,N/A,Comedy& Drama& Romance,5.5,21 Dec 2018,Not Rated,4 wins & 10 nominations.,105,https://m.media-amazon.com/images/M/MV5BNzg5Yj...,NaN,NaN,NaN
4,Titu Talks,5,6,Bhuvan Bam plays his famous character 'Titu M...,N/A,Comedy& Talk-Show,7.7,15 Dec 2018,N/A,N/A,28,https://m.media-amazon.com/images/M/MV5BNWEzMG...,NaN,NaN,NaN

In [49]:
df.info()

<class 'pandas.DataFrame'>
Index: 386 entries, 0 to 192
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             193 non-null    str
 1    Country Origin   386 non-null    int64
 2    Languages        386 non-null    int64
 3    Plot             193 non-null    str
 4    Metascore        193 non-null    str
 5    Genre            193 non-null    str
 6    Rating           193 non-null    str
 7    Relese Date      193 non-null    str
 8    Rated            193 non-null    str
 9    Awards           193 non-null    str
 10   Actors           386 non-null    int64
 11   Poster link      193 non-null    str
 12  col_              193 non-null    float64
 13  col_ movie        193 non-null    float64
 14  col_ series       193 non-null    float64
dtypes: float64(3), int64(3), str(9)
memory usage: 48.2 KB