# Machine Learning + Function

In [306]:
# Data Preprocessing
# Missing value

In [307]:
import pandas as pd
df=pd.read_csv('titanic.csv')

In [308]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     886 non-null    float64
 2   Pclass       886 non-null    float64
 3   Name         887 non-null    str
 4   Sex          887 non-null    str
 5   Age          709 non-null    float64
 6   SibSp        887 non-null    float64
 7   Parch        887 non-null    float64
 8   Ticket       891 non-null    str
 9   Fare         887 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(6), int64(1), str(5)
memory usage: 83.7 KB

In [309]:
df.isnull().sum()

PassengerId      0
Survived         5
Pclass           5
Name             4
Sex              4
Age            182
SibSp            4
Parch            4
Ticket           0
Fare             4
Cabin          687
Embarked         2
dtype: int64

In [310]:
# Missing value + for loop
# for col in df.columns:
#     if df[col].isnull().any():
#        if df[col].dtype=='str':
#            df[col] = df[col].fillna(df[col].mode()[0])
#        else:
#            df[col] = df[col].fillna(df[col].mean())

In [311]:
df.isnull().sum()

PassengerId      0
Survived         5
Pclass           5
Name             4
Sex              4
Age            182
SibSp            4
Parch            4
Ticket           0
Fare             4
Cabin          687
Embarked         2
dtype: int64

In [312]:
df.drop("Name",axis=1,inplace=True)

In [313]:
# function + missing value + for loop
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df[col] = df[col].fillna(df[col].mode()[0])
            else:
                df[col] = df[col].fillna(df[col].mean())
    return df

In [314]:
toldir(df)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3.000000,male,22.000000,1.0,0.0,A/5 21171,7.2500,B96 B98,S
1,2,1.0,1.000000,female,38.000000,1.0,0.0,PC 17599,71.2833,C85,C
2,3,1.0,2.309255,female,26.000000,0.0,0.0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1.0,2.309255,female,35.000000,1.0,0.0,113803,53.1000,C123,S
4,5,0.0,2.309255,male,35.000000,0.0,0.0,373450,8.0500,B96 B98,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0.0,2.000000,male,27.000000,0.0,0.0,211536,13.0000,B96 B98,S
887,888,1.0,1.000000,female,19.000000,0.0,0.0,112053,30.0000,B42,S
888,889,0.0,3.000000,female,29.716742,1.0,2.0,W./C. 6607,23.4500,B96 B98,S
889,890,1.0,1.000000,male,26.000000,0.0,0.0,111369,30.0000,C148,C
890,891,0.0,3.000000,male,32.000000,0.0,0.0,370376,7.7500,B96 B98,Q

In [315]:
# encoding
# scaling
# training

In [316]:
# encoding + for loop
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [317]:
encoder

LabelEncoder()

In [318]:
df.nunique()

PassengerId    891
Survived         3
Pclass           4
Sex              2
Age             89
SibSp            8
Parch            8
Ticket         681
Fare           249
Cabin          147
Embarked         3
dtype: int64

In [319]:
# encoding + for loop
#for col in df.columns:
#    if df[col].dtype == 'str':
#        if df[col].nunique() <= 5:
#            dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
#            df = pd.concat([df.drop(columns=col), dummies], axis=1)
#        else: 
#            df[col] = encoder.fit_transform(df[col])

In [320]:
# function + encoding + for loop
def raqamlash(df):
    for col in df.columns:
        if df[col].dtype == 'str':
            if df[col].nunique() <= 2:
                dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                df = pd.concat([df.drop(columns=col), dummies], axis=1)
            else: 
                df[col] = encoder.fit_transform(df[col])
    return df
df=raqamlash(df)

In [321]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Age          891 non-null    float64
 4   SibSp        891 non-null    float64
 5   Parch        891 non-null    float64
 6   Ticket       891 non-null    int64
 7   Fare         891 non-null    float64
 8   Cabin        891 non-null    int64
 9   Embarked     891 non-null    int64
 10  Sex_female   891 non-null    int64
 11  Sex_male     891 non-null    int64
dtypes: float64(6), int64(6)
memory usage: 83.7 KB

In [322]:
# scaling + for loop
df.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,1,0.0,3.000000,22.0,1.0,0.0,523,7.2500,47,2,0,1
1,2,1.0,1.000000,38.0,1.0,0.0,596,71.2833,81,0,1,0
2,3,1.0,2.309255,26.0,0.0,0.0,669,7.9250,47,2,1,0
3,4,1.0,2.309255,35.0,1.0,0.0,49,53.1000,55,2,1,0
4,5,0.0,2.309255,35.0,0.0,0.0,472,8.0500,47,2,0,1

In [323]:
num_col = df.select_dtypes(include=['int64', 'float64']).columns.drop('Survived')

In [324]:
num_col

Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare',
       'Cabin', 'Embarked', 'Sex_female', 'Sex_male'],
      dtype='str')

In [325]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler

MinMaxScaler()

In [326]:
# scaling + for loop
#scaler=MinMaxScaler()
#df[num_col]=scaler.fit_transform(df[num_col])
#num_col=df.select_dtypes(include=['int64', 'float64']).columns.drop('Value')

In [327]:
# function + scaling + for loop 
def moslashtirish(df, num_col):
    scaler=MinMaxScaler()
    df[num_col]=scaler.fit_transform(df[num_col])
    return df
    num_col=df.select_dtypes(include=['float64']).columns.drop('Sex')
moslashtirish(df, num_col)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_female,Sex_male
0,0.000000,0.0,1.000000,0.271174,0.125,0.000000,0.769118,0.014151,0.321918,1.0,0.0,1.0
1,0.001124,1.0,0.000000,0.472229,0.125,0.000000,0.876471,0.139136,0.554795,0.0,1.0,0.0
2,0.002247,1.0,0.654628,0.321438,0.000,0.000000,0.983824,0.015469,0.321918,1.0,1.0,0.0
3,0.003371,1.0,0.654628,0.434531,0.125,0.000000,0.072059,0.103644,0.376712,1.0,1.0,0.0
4,0.004494,0.0,0.654628,0.434531,0.000,0.000000,0.694118,0.015713,0.321918,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0.995506,0.0,0.500000,0.334004,0.000,0.000000,0.148529,0.025374,0.321918,1.0,0.0,1.0
887,0.996629,1.0,0.000000,0.233476,0.000,0.000000,0.020588,0.058556,0.205479,1.0,1.0,0.0
888,0.997753,0.0,1.000000,0.368142,0.125,0.333333,0.992647,0.045771,0.321918,1.0,1.0,0.0
889,0.998876,1.0,0.000000,0.321438,0.000,0.000000,0.011765,0.058556,0.410959,0.0,0.0,1.0
890,1.000000,0.0,1.000000,0.396833,0.000,0.000000,0.685294,0.015127,0.321918,0.5,0.0,1.0

In [328]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    float64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Age          891 non-null    float64
 4   SibSp        891 non-null    float64
 5   Parch        891 non-null    float64
 6   Ticket       891 non-null    float64
 7   Fare         891 non-null    float64
 8   Cabin        891 non-null    float64
 9   Embarked     891 non-null    float64
 10  Sex_female   891 non-null    float64
 11  Sex_male     891 non-null    float64
dtypes: float64(12)
memory usage: 83.7 KB

# Classification + algorithm

In [329]:
from sklearn.linear_model import LogisticRegression

In [330]:
lr = LogisticRegression()
lr

LogisticRegression()

In [331]:
x = df.drop('Survived', axis=1)
y = df['Survived'].astype(int)

In [332]:
from sklearn.model_selection import train_test_split

In [333]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3,random_state = 42)

In [334]:
x_train.shape

(623, 11)

In [335]:
x_test.shape

(268, 11)

In [336]:
y_train.shape

(623,)

In [337]:
y_test.shape

(268,)

In [338]:
lr.fit(x_train,y_train)

LogisticRegression()

In [339]:
y_pred = lr.predict(x_test)

In [340]:
y_pred[1:10]

array([0, 0, 1, 0, 1, 1, 0, 1, 1])

In [341]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [342]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [343]:
print("mae: ", mae)
print("mse: ", mse)
print("r2_score: ",r2)

mae:  0.2126865671641791
mse:  0.2126865671641791
r2_score:  0.12105868814729603