# Vazifa 
Yangi dataset toping va classification va regressionga alohida alohida k-foldni tekshiring

In [65]:
import pandas as pd

In [ ]:
df=pd.read_csv('amazon-fashion-800k+-user-reviews-dataset.csv')
# Amazon Fashion 800k+ User Reviews Dataset
# Large Fashion Review Dataset for Sentiment Analysis and Rating Prediction

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 867310 entries, 0 to 867309
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   rating              867310 non-null  float64
 1   title               867107 non-null  str
 2   text                867012 non-null  str
 3   images              867310 non-null  str
 4   asin                867310 non-null  str
 5   parent_asin         867310 non-null  str
 6   user_id             867310 non-null  str
 7   timestamp           867310 non-null  int64
 8   helpful_vote        867310 non-null  int64
 9   verified_purchases  867310 non-null  bool
 10  target              867310 non-null  int64
dtypes: bool(1), float64(1), int64(3), str(6)
memory usage: 67.0 MB

# Data Preprocessing

In [68]:
df.isnull().sum()

rating                  0
title                 203
text                  298
images                  0
asin                    0
parent_asin             0
user_id                 0
timestamp               0
helpful_vote            0
verified_purchases      0
target                  0
dtype: int64

In [69]:
df.drop('title', axis=1, inplace=True) # bu predict qilishimiz uchun keraksiz column

In [70]:
# Missing 
df['text']=df['text'].fillna(df['text'].mode()[0])

In [71]:
df.isnull().sum()

rating                0
text                  0
images                0
asin                  0
parent_asin           0
user_id               0
timestamp             0
helpful_vote          0
verified_purchases    0
target                0
dtype: int64

In [72]:
# Encoding 
from sklearn.preprocessing import LabelEncoder
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 867310 entries, 0 to 867309
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   rating              867310 non-null  float64
 1   text                867310 non-null  str
 2   images              867310 non-null  str
 3   asin                867310 non-null  str
 4   parent_asin         867310 non-null  str
 5   user_id             867310 non-null  str
 6   timestamp           867310 non-null  int64
 7   helpful_vote        867310 non-null  int64
 8   verified_purchases  867310 non-null  bool
 9   target              867310 non-null  int64
dtypes: bool(1), float64(1), int64(3), str(5)
memory usage: 60.4 MB

In [73]:
def encodla(df):
    encoder = LabelEncoder()

    for col in df.columns:

        if df[col].dtype == 'bool':
            df[col] = df[col].astype(int)

        elif df[col].dtype == 'str':

            if df[col].nunique() <= 5:
                dummies = pd.get_dummies(df[col], prefix=col)
                df = pd.concat([df.drop(columns=[col]), dummies], axis=1)

            else:
                df[col] = encoder.fit_transform(df[col])

    return df

In [74]:
df=encodla(df)

In [75]:
df.head()

,rating,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchases,target
0,1.0,273321,0,277702,265064,628690,1565088068852,0,1,-1
1,1.0,343838,0,186838,178066,7550,1622416429592,0,1,-1
2,1.0,481030,0,248412,237055,600954,1565284666220,0,1,-1
3,1.0,671504,0,191796,182726,260400,1581963636172,0,0,-1
4,1.0,755377,0,413991,345846,550803,1640895438476,0,1,-1

In [76]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 867310 entries, 0 to 867309
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   rating              867310 non-null  float64
 1   text                867310 non-null  int64
 2   images              867310 non-null  int64
 3   asin                867310 non-null  int64
 4   parent_asin         867310 non-null  int64
 5   user_id             867310 non-null  int64
 6   timestamp           867310 non-null  int64
 7   helpful_vote        867310 non-null  int64
 8   verified_purchases  867310 non-null  int64
 9   target              867310 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 66.2 MB

In [77]:
# scaling 
from sklearn.preprocessing import MinMaxScaler

def scale_qil(df):
    scaler= MinMaxScaler()
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('target')
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [78]:
df=scale_qil(df)

In [79]:
df.head()

,rating,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchases,target
0,0.0,0.337142,0.0,0.620594,0.623985,0.802970,0.808372,0.0,1.0,-1
1,0.0,0.424125,0.0,0.417536,0.419184,0.009643,0.893505,0.0,1.0,-1
2,0.0,0.593351,0.0,0.555138,0.558050,0.767545,0.808664,0.0,1.0,-1
3,0.0,0.828301,0.0,0.428615,0.430154,0.332586,0.833432,0.0,0.0,-1
4,0.0,0.931759,0.0,0.925165,0.814154,0.703492,0.920947,0.0,1.0,-1

# Model

In [80]:
x=df.drop('target', axis=1)

In [81]:
y=df['target']

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [84]:
# linear regression
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()

# Logistic Regrassion

In [85]:
log_reg

LogisticRegression()

In [86]:
log_reg.fit(x_train,y_train)

LogisticRegression()

In [87]:
y_pred=log_reg.predict(x_test)

In [88]:
from sklearn.metrics import accuracy_score, classification_report

In [89]:
score=accuracy_score(y_test,y_pred)
class_report=classification_report(y_test,y_pred)

In [90]:
print('Modelning aniqlik darajasi:',score)

Modelning aniqlik darajasi: 0.9999769401943942

# k_Fold validation

In [91]:
from sklearn.model_selection import  KFold, cross_val_score
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [92]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [93]:
scores=cross_val_score(log_reg,x,y,cv=kf,scoring='accuracy')
print(scores)

[0.99997694 1.         1.         1.         0.99998847]

In [94]:
for i in scores:
    print(i)

0.9999769401943942
1.0
1.0
1.0
0.999988470097197

In [95]:
import numpy as np
np.mean(scores)

np.float64(0.9999930820583183)

In [96]:
np.std(scores)

np.float64(9.223922242324044e-06)