# Data bn tanishuv

In [32]:
import pandas as pd 
df=pd.read_csv('Warehouse_and_Retail_Sales.csv')

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 307645 entries, 0 to 307644
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307645 non-null  int64
 1   MONTH             307645 non-null  int64
 2   SUPPLIER          307478 non-null  str
 3   ITEM CODE         307645 non-null  str
 4   ITEM DESCRIPTION  307645 non-null  str
 5   ITEM TYPE         307644 non-null  str
 6   RETAIL SALES      307642 non-null  float64
 7   RETAIL TRANSFERS  307645 non-null  float64
 8   WAREHOUSE SALES   307645 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 21.1 MB

In [34]:
df.dropna(inplace=True)

In [35]:
df.isnull().sum()

YEAR                0
MONTH               0
SUPPLIER            0
ITEM CODE           0
ITEM DESCRIPTION    0
ITEM TYPE           0
RETAIL SALES        0
RETAIL TRANSFERS    0
WAREHOUSE SALES     0
dtype: int64

In [36]:
df['RETAIL SALES'].fillna(df['RETAIL SALES'].median(), inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_7108\3792260164.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['RETAIL SALES'].fillna(df['RETAIL SALES'].median(), inplace=True)

0          0.00
1          0.00
2          0.00
3          0.00
4          0.82
          ...
307639     5.50
307640     0.00
307641    66.12
307642     2.25
307643    20.50
Name: RETAIL SALES, Length: 307477, dtype: float64

In [37]:
df.sample(5)

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
211808,2019,5,GLOBAL OCEAN AND AIR CARGO SERVICES,319051,ENAT HONEY WINE - 750ML,WINE,0.00,0.0,10.0
6517,2020,1,JIM BEAM BRANDS CO,38628,SAUZA CONMEMORATIVO - 750ML,LIQUOR,5.18,4.0,0.0
213745,2019,5,LEGENDS LTD,347323,TWO ROADS BEER BUS VARIETY - 12OZ CAN,BEER,0.00,0.0,4.0
285673,2019,11,NORTH LOCK LLC DBA PORT CITY BREWING CO,25104,PORT CITY OKTOBERFEST 4/6 12OZ,BEER,1.00,0.0,0.0
482,2020,1,KYSELA PERE ET FILS LTD,139467,CORTENOVA PULGIA SANG - 750ML,WINE,0.00,0.0,1.0

# Encoding

In [38]:
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [39]:
df=encodla(df)

In [40]:
df.info()

<class 'pandas.DataFrame'>
Index: 307477 entries, 0 to 307643
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307477 non-null  int64
 1   MONTH             307477 non-null  int64
 2   SUPPLIER          307477 non-null  int64
 3   ITEM CODE         307477 non-null  int64
 4   ITEM DESCRIPTION  307477 non-null  int64
 5   ITEM TYPE         307477 non-null  int64
 6   RETAIL SALES      307477 non-null  float64
 7   RETAIL TRANSFERS  307477 non-null  float64
 8   WAREHOUSE SALES   307477 non-null  float64
dtypes: float64(3), int64(6)
memory usage: 23.5 MB

# Scaling

In [41]:
from sklearn.preprocessing import MinMaxScaler

In [42]:
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col = df.select_dtypes(include=['int64','float64']).columns
    df[num_col]=scaler.fit_transform(df[num_col]) 
    return df

In [43]:
df=scaling_qil(df)

In [44]:
df.sample(8)

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
78660,0.000000,0.727273,0.691139,0.284946,0.482818,1.000000,0.005667,0.020445,0.214387
102304,0.000000,0.909091,0.192405,0.012985,0.817866,0.428571,0.009808,0.024880,0.214301
267844,0.666667,0.727273,0.686076,0.886274,0.043731,0.571429,0.004931,0.019952,0.214516
258350,0.666667,0.727273,0.815190,0.053293,0.869354,0.428571,0.004953,0.019460,0.214301
210432,0.666667,0.363636,0.483544,0.246430,0.386680,0.000000,0.003560,0.018967,0.215073
303086,1.000000,0.727273,0.493671,0.681268,0.678428,1.000000,0.003560,0.018967,0.214558
24283,1.000000,0.181818,0.686076,0.093719,0.450839,0.000000,0.003560,0.018967,0.214344
115611,0.000000,0.909091,0.273418,0.960720,0.083870,1.000000,0.013083,0.027837,0.216746

# Train

In [45]:
X = df.drop('RETAIL SALES', axis=1)
y = df['RETAIL SALES']

In [46]:
y

0         0.003560
1         0.003560
2         0.003560
3         0.003560
4         0.004010
            ...
307639    0.006577
307640    0.003560
307641    0.039830
307642    0.004794
307643    0.014805
Name: RETAIL SALES, Length: 307477, dtype: float64

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Linear r

In [49]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [50]:
y_pred = model.predict(X_test)

In [51]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2:", r2)

MAE: 0.000921557945533613
MSE: 1.1624143891990526e-05
R2: 0.9550087122867011

# Random fo

In [52]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, y_train)

RandomForestRegressor()

In [53]:
y_pred = model.predict(X_test)

In [54]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2:", r2)

MAE: 0.0008564758235415589
MSE: 1.1149373195873977e-05
R2: 0.9568463138499045

# Decision T

In [55]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(random_state=42)
model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [56]:
y_pred = model.predict(X_test)

In [57]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2:", r2)

MAE: 0.0011717928182764423
MSE: 2.0687237607283336e-05
R2: 0.9199299778262398

In [58]:
from tabulate import tabulate

result = [
    ['Logistic Regression',0.000,1.162,0.955],
    ['Random Forest',0.000,1.114,0.956],
    ['DecisionTreeRegressor',0.001,2.068,0.919]
]

headers = ['Algorithm', 'MAE','MSE','R2']

table = tabulate(result, headers=headers, tablefmt='grid')

print(table)

+-----------------------+-------+-------+-------+
| Algorithm             |   MAE |   MSE |    R2 |
+=======================+=======+=======+=======+
| Logistic Regression   | 0     | 1.162 | 0.955 |
+-----------------------+-------+-------+-------+
| Random Forest         | 0     | 1.114 | 0.956 |
+-----------------------+-------+-------+-------+
| DecisionTreeRegressor | 0.001 | 2.068 | 0.919 |
+-----------------------+-------+-------+-------+

# Feature Engineering

In [67]:
import pandas as pd 
df=pd.read_csv('Warehouse_and_Retail_Sales.csv')

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 307645 entries, 0 to 307644
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307645 non-null  int64
 1   MONTH             307645 non-null  int64
 2   SUPPLIER          307478 non-null  str
 3   ITEM CODE         307645 non-null  str
 4   ITEM DESCRIPTION  307645 non-null  str
 5   ITEM TYPE         307644 non-null  str
 6   RETAIL SALES      307642 non-null  float64
 7   RETAIL TRANSFERS  307645 non-null  float64
 8   WAREHOUSE SALES   307645 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 21.1 MB

In [69]:
df['SUPPLIER'] = df['SUPPLIER'].fillna('Unknown')
df['RETAIL SALES'] = df['RETAIL SALES'].fillna(df['RETAIL SALES'].mean())
df.dropna(subset=['ITEM TYPE'], inplace=True)

In [71]:
df.info()

<class 'pandas.DataFrame'>
Index: 307644 entries, 0 to 307644
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307644 non-null  int64
 1   MONTH             307644 non-null  int64
 2   SUPPLIER          307644 non-null  str
 3   ITEM CODE         307644 non-null  str
 4   ITEM DESCRIPTION  307644 non-null  str
 5   ITEM TYPE         307644 non-null  str
 6   RETAIL SALES      307644 non-null  float64
 7   RETAIL TRANSFERS  307644 non-null  float64
 8   WAREHOUSE SALES   307644 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 23.5 MB

In [72]:
df.isnull().sum()

YEAR                0
MONTH               0
SUPPLIER            0
ITEM CODE           0
ITEM DESCRIPTION    0
ITEM TYPE           0
RETAIL SALES        0
RETAIL TRANSFERS    0
WAREHOUSE SALES     0
dtype: int64

In [73]:
df['TOTAL_SALES'] = df['RETAIL SALES'] + df['WAREHOUSE SALES']
df['SALE_RATIO'] = df['WAREHOUSE SALES'] / (df['RETAIL SALES'] + 0.1) 
df['IS_HOLIDAY_SEASON'] = df['MONTH'].apply(lambda x: 1 if x in [12, 1] else 0)

In [74]:
df.info()

<class 'pandas.DataFrame'>
Index: 307644 entries, 0 to 307644
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   YEAR               307644 non-null  int64
 1   MONTH              307644 non-null  int64
 2   SUPPLIER           307644 non-null  str
 3   ITEM CODE          307644 non-null  str
 4   ITEM DESCRIPTION   307644 non-null  str
 5   ITEM TYPE          307644 non-null  str
 6   RETAIL SALES       307644 non-null  float64
 7   RETAIL TRANSFERS   307644 non-null  float64
 8   WAREHOUSE SALES    307644 non-null  float64
 9   TOTAL_SALES        307644 non-null  float64
 10  SALE_RATIO         307643 non-null  float64
 11  IS_HOLIDAY_SEASON  307644 non-null  int64
dtypes: float64(5), int64(3), str(4)
memory usage: 30.5 MB

# Encoding

In [76]:
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [77]:
df=encodla(df)

In [78]:
df.info()

<class 'pandas.DataFrame'>
Index: 307644 entries, 0 to 307644
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   YEAR               307644 non-null  int64
 1   MONTH              307644 non-null  int64
 2   SUPPLIER           307644 non-null  int64
 3   ITEM CODE          307644 non-null  int64
 4   ITEM DESCRIPTION   307644 non-null  int64
 5   ITEM TYPE          307644 non-null  int64
 6   RETAIL SALES       307644 non-null  float64
 7   RETAIL TRANSFERS   307644 non-null  float64
 8   WAREHOUSE SALES    307644 non-null  float64
 9   TOTAL_SALES        307644 non-null  float64
 10  SALE_RATIO         307643 non-null  float64
 11  IS_HOLIDAY_SEASON  307644 non-null  int64
dtypes: float64(5), int64(7)
memory usage: 30.5 MB

# Scaling

In [79]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col = df.select_dtypes(include=['int64','float64']).columns
    df[num_col]=scaler.fit_transform(df[num_col]) 
    return df

In [81]:
df=scaling_qil(df)

In [82]:
df.sample(8)

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES,TOTAL_SALES,SALE_RATIO,IS_HOLIDAY_SEASON
197792,0.666667,0.272727,0.633838,0.262025,0.813584,0.428571,0.002510,0.018967,0.298656,0.285823,0.597930,0.0
259400,0.666667,0.727273,0.550505,0.145122,0.210712,1.000000,0.002364,0.018967,0.298962,0.286102,0.598544,0.0
76878,0.000000,0.727273,0.613636,0.114700,0.697731,0.000000,0.002364,0.018967,0.304226,0.291138,0.609081,0.0
20921,1.000000,0.545455,0.419192,0.875433,0.996669,0.428571,0.006735,0.025373,0.298656,0.286248,0.597930,0.0
17452,1.000000,0.545455,0.709596,0.564603,0.188742,1.000000,0.002364,0.018967,0.298694,0.285845,0.598007,0.0
207370,0.666667,0.272727,0.037879,0.986551,0.147013,0.000000,0.002364,0.018967,0.301757,0.288777,0.604140,0.0
97324,0.000000,0.818182,0.265152,0.699918,0.546180,0.428571,0.002983,0.020362,0.298656,0.285871,0.597930,0.0
205262,0.666667,0.272727,0.603535,0.890879,0.115279,0.428571,0.002542,0.018967,0.298656,0.285826,0.597930,0.0

# AI dan foydalanganman buyog'iga

In [83]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

X = df.drop(['RETAIL SALES', 'TOTAL_SALES', 'SALE_RATIO', 'RETAIL TRANSFERS'], axis=1)
y = df['RETAIL SALES']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

lr = LinearRegression()
lr.fit(X_train, y_train)
lr_score = lr.score(X_test, y_test)

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
dt_score = dt.score(X_test, y_test)

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
rf_score = rf.score(X_test, y_test)

print(f"Linear Regression: {lr_score:.2f}")
print(f"Decision Tree: {dt_score:.2f}")
print(f"Random Forest: {rf_score:.2f}")

Linear Regression: 0.30
Decision Tree: 0.72
Random Forest: 0.83

In [84]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from tabulate import tabulate

# Modellar ro'yxati
models = [
    ('Linear Regression', lr),
    ('Decision Tree', dt),
    ('Random Forest', rf)
]

result = []

for name, model in models:
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    result.append([name, f"{mae:.3f}", f"{mse:.3f}", f"{r2:.3f}"])

headers = ['Algorithm', 'MAE', 'MSE', 'R2']
table = tabulate(result, headers=headers, tablefmt='grid')

print(table)

+-------------------+-------+-------+-------+
| Algorithm         |   MAE |   MSE |    R2 |
+===================+=======+=======+=======+
| Linear Regression | 0.003 |     0 | 0.303 |
+-------------------+-------+-------+-------+
| Decision Tree     | 0.001 |     0 | 0.721 |
+-------------------+-------+-------+-------+
| Random Forest     | 0.001 |     0 | 0.826 |
+-------------------+-------+-------+-------+

# Feature Engineering siz ! tabulate

In [85]:
from tabulate import tabulate

result = [
    ['Logistic Regression',0.000,1.162,0.955],
    ['Random Forest',0.000,1.114,0.956],
    ['DecisionTreeRegressor',0.001,2.068,0.919]
]

headers = ['Algorithm', 'MAE','MSE','R2']

table = tabulate(result, headers=headers, tablefmt='grid')

print(table)

+-----------------------+-------+-------+-------+
| Algorithm             |   MAE |   MSE |    R2 |
+=======================+=======+=======+=======+
| Logistic Regression   | 0     | 1.162 | 0.955 |
+-----------------------+-------+-------+-------+
| Random Forest         | 0     | 1.114 | 0.956 |
+-----------------------+-------+-------+-------+
| DecisionTreeRegressor | 0.001 | 2.068 | 0.919 |
+-----------------------+-------+-------+-------+

# About My salfe

In [88]:
class AboutMe:
    def __init__(self, ism, yosh, boy, manzil):
        self.ism = ism
        self.yosh = yosh
        self.boy = boy
        self.manzil = manzil

    def tanishtir(self):
        return f"Ismim {self.ism}, yoshim {self.yosh}da. {self.manzil}da tug'ilganman."

    def add(self):
        return self.yosh + self.boy

    def kop(self):
        return self.yosh * self.boy

    def orta(self):
        return (self.yosh + self.boy) / 2

me = AboutMe(ism="Muhammadyusuf", yosh=18, boy=1.68, manzil="Uzb")

print(me.tanishtir())
print(f"Yig'indi: {me.add()}")
print(f"Ko'paytma: {me.kop()}")
print(f"O'rtacha: {me.orta()}")

Ismim Muhammadyusuf, yoshim 18da. Uzbda tug'ilganman.
Yig'indi: 19.68
Ko'paytma: 30.24
O'rtacha: 9.84