    What we learnt over the course:

    - Data preprocessing
    - Baseline algorithms 
    - Cross validation
    - Tabulate
    - Joblib 
    - data visualisation 
    - matplotlib
    - seaborn 
    - plotly.express
    - Klib
    - datacleaner
    - os library
    - Lasso | Ridge regression
    - feature engineering

In [9]:
from preprocessing import Preprocessing
import pandas as pd
import os

In [2]:
df = pd.read_csv("../data/raw/Teen_Mental_Health_Dataset.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB

In [4]:
df.isnull().sum()

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

## **Data preprocessing using modular programming**

In [ ]:
from preprocessing import Preprocessing

cleaned_data = Preprocessing(df)
cleaned_data.handling_missing_values().encoding().scaling()
df_cleaned = cleaned_data.df

In [6]:
df_cleaned.isnull().sum()

age                                0
daily_social_media_hours           0
sleep_hours                        0
screen_time_before_sleep           0
academic_performance               0
physical_activity                  0
stress_level                       0
anxiety_level                      0
addiction_level                    0
depression_label                   0
gender_female                      0
gender_male                        0
platform_usage_Both                0
platform_usage_Instagram           0
platform_usage_TikTok              0
social_interaction_level_high      0
social_interaction_level_low       0
social_interaction_level_medium    0
dtype: int64

In [7]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   age                              1200 non-null   float64
 1   daily_social_media_hours         1200 non-null   float64
 2   sleep_hours                      1200 non-null   float64
 3   screen_time_before_sleep         1200 non-null   float64
 4   academic_performance             1200 non-null   float64
 5   physical_activity                1200 non-null   float64
 6   stress_level                     1200 non-null   float64
 7   anxiety_level                    1200 non-null   float64
 8   addiction_level                  1200 non-null   float64
 9   depression_label                 1200 non-null   float64
 10  gender_female                    1200 non-null   int32
 11  gender_male                      1200 non-null   int32
 12  platform_usage_Both              1200 non-null   int32
 13  platform_usage_Instagram         1200 non-null   int32
 14  platform_usage_TikTok            1200 non-null   int32
 15  social_interaction_level_high    1200 non-null   int32
 16  social_interaction_level_low     1200 non-null   int32
 17  social_interaction_level_medium  1200 non-null   int32
dtypes: float64(10), int32(8)
memory usage: 131.4 KB

## **Saving preprocessed data into new folder**

In [12]:
output_folder = "../data/preprocessed"
os.makedirs(output_folder, exist_ok=True)
output_path = os.path.join(output_folder, "preprocessed_df.csv")
df_cleaned.to_csv(output_path, index=False)

In [13]:
df_cleaned.sample(10)

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_female,gender_male,platform_usage_Both,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_high,social_interaction_level_low,social_interaction_level_medium
871,0.530238,-0.165948,0.589833,1.200047,3.20,-1.399624,0.535536,-1.622199,-0.906537,-0.162845,0,1,0,0,1,1,0,0
901,1.519796,0.869171,-0.519679,-0.475086,2.03,0.146922,-0.498206,0.127117,-1.613389,-0.162845,0,1,0,0,1,0,1,0
683,-0.459320,-0.412404,-1.698535,-1.173058,3.00,0.662437,-1.531947,0.826843,1.567444,-0.162845,0,1,1,0,0,0,0,1
1121,1.025017,-1.348940,-0.242301,1.339641,2.86,0.146922,-0.498206,-1.272335,-0.553111,-0.162845,1,0,0,0,1,0,1,0
553,-0.459320,-0.018073,0.867210,-1.173058,2.61,0.146922,1.224696,1.526569,-0.553111,-0.162845,1,0,0,1,0,0,0,1
186,-0.459320,-0.510987,-0.103612,-1.312653,2.71,1.349791,0.535536,-0.572609,-1.259963,-0.162845,1,0,0,1,0,1,0,0
289,1.519796,-0.067365,-0.034268,-1.173058,2.72,-1.399624,0.190955,1.176706,0.860592,-0.162845,0,1,1,0,0,0,0,1
620,1.519796,1.214211,-1.351813,0.781263,3.26,1.177953,1.224696,1.526569,-0.906537,6.140821,0,1,0,0,1,1,0,0
252,-1.448878,0.524131,-1.282468,0.222886,2.54,-1.571463,-0.153625,-0.222746,0.153740,-0.162845,0,1,0,1,0,0,1,0
1151,0.530238,0.228383,0.589833,-0.754275,3.39,-0.540432,1.224696,1.526569,0.860592,-0.162845,1,0,0,1,0,0,0,1

## **Random Forest Regressor**

In [16]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np


x = df_cleaned.drop("academic_performance", axis=1)
y = df_cleaned["academic_performance"]

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

rf = RandomForestRegressor()

rf.fit(x_train, y_train)

y_pred = rf.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(mae)
print(mse)
print(rmse)
print(r2)

0.4956104166666666
0.3425789218749999
0.5853024191603857
-0.04682565322034016

##  **Random Forest Regressor without scaling**

In [17]:
df = pd.read_csv("../data/raw/Teen_Mental_Health_Dataset.csv")

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB

In [20]:
from preprocessing import Preprocessing

cleaned_data = Preprocessing(df)
cleaned_data.handling_missing_values().encoding()
df = cleaned_data.df

In [22]:
df.sample(10)

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_female,gender_male,platform_usage_Both,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_high,social_interaction_level_low,social_interaction_level_medium
176,15,6.2,6.3,1.7,2.26,1.1,9,6,2,0,0,1,0,0,1,1,0,0
204,17,1.1,6.8,2.0,3.45,1.3,7,1,2,0,0,1,0,1,0,0,0,1
462,13,7.9,6.0,2.7,2.85,0.3,9,10,3,0,0,1,0,0,1,0,1,0
262,15,3.6,4.3,2.9,2.20,1.0,10,9,7,0,0,1,0,0,1,1,0,0
522,16,4.7,8.2,2.7,3.04,0.3,1,3,4,0,0,1,0,1,0,1,0,0
828,17,4.4,8.2,2.7,3.13,0.3,3,1,2,0,0,1,1,0,0,0,0,1
279,14,7.0,7.8,1.1,3.81,1.4,10,4,2,0,1,0,0,0,1,0,0,1
949,18,2.4,6.8,1.0,2.86,1.5,9,10,8,0,0,1,1,0,0,1,0,0
979,18,7.7,6.6,1.6,4.00,1.9,3,3,9,0,0,1,1,0,0,1,0,0
852,14,1.5,6.8,0.8,3.14,0.0,4,5,8,0,0,1,1,0,0,0,0,1

In [25]:

x = df.drop("academic_performance", axis=1)
y = df["academic_performance"]

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

rf = RandomForestRegressor()

rf.fit(x_train, y_train)

y_pred = rf.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(mae)
print(mse)
print(rmse)
print(r2)

0.4974516666666667
0.34662879566666666
0.5887518965291464
-0.05920093817429439

## **K-fold cross validation**

In [26]:
from sklearn.model_selection import KFold, cross_val_score

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(rf, x,y,cv=kf, scoring="r2")
print(scores.mean())

from sklearn.metrics import make_scorer

mae=make_scorer(mean_absolute_error,greater_is_better=False)
scores=cross_val_score(rf,x,y,cv=kf,scoring=mae)
print(-scores)

-0.06574841855486246
[0.49953042 0.50564125 0.53825875 0.53453542 0.50066125]