# Algorithm

In [1]:
import pandas as pd

In [18]:
df=pd.read_csv('/Users/a1/Desktop/MLFoundation/Bank_Personal_Loan_Modelling(1).csv')

In [112]:
# Reload the data fresh
df=pd.read_csv('/Users/a1/Desktop/MLFoundation/Bank_Personal_Loan_Modelling(1).csv')
print(f"Data reloaded. Shape: {df.shape}")

# Check CCAvg values BEFORE any conversion
print("\nSample CCAvg values (first 10):")
for i, val in enumerate(df['CCAvg'].head(10)):
    print(f"  {i}: {repr(val)} (type: {type(val).__name__})")

Data reloaded. Shape: (5000, 14)

Sample CCAvg values (first 10):
  0: '1/60' (type: str)
  1: '1/50' (type: str)
  2: '1/00' (type: str)
  3: '2/70' (type: str)
  4: '1/00' (type: str)
  5: '0/40' (type: str)
  6: '1/50' (type: str)
  7: '0/30' (type: str)
  8: '0/60' (type: str)
  9: '8/90' (type: str)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: int64(13), object(1)
memory usage: 547.0+ KB

In [13]:
from sklearn.preprocessing import LabelEncoder
 
encoder = LabelEncoder()

In [11]:
from sklearn.linear_model import LinearRegression, LogisticRegression

In [15]:
lr = LinearRegression()

In [14]:
encoder

LabelEncoder()

In [16]:
lr

LinearRegression()

In [9]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: int64(13), object(1)
memory usage: 547.0+ KB

In [20]:
df.dropna(inplace=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: int64(13), object(1)
memory usage: 547.0+ KB

In [23]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1/60,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1/50,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1/00,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2/70,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1/00,2,0,0,0,0,0,1

In [24]:
 from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler = MinMaxScaler()

In [26]:
scaler

MinMaxScaler()

In [32]:
for col in df.columns:
    if df[col].dtype != 'object':
        df[col] = scaler.fit_transform(df[[col]])

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   float64
 1   Age                 5000 non-null   float64
 2   Experience          5000 non-null   float64
 3   Income              5000 non-null   float64
 4   ZIP Code            5000 non-null   float64
 5   Family              5000 non-null   float64
 6   CCAvg               5000 non-null   object
 7   Education           5000 non-null   float64
 8   Mortgage            5000 non-null   float64
 9   Personal Loan       5000 non-null   float64
 10  Securities Account  5000 non-null   float64
 11  CD Account          5000 non-null   float64
 12  Online              5000 non-null   float64
 13  CreditCard          5000 non-null   float64
dtypes: float64(13), object(1)
memory usage: 547.0+ KB

In [35]:
from sklearn.linear_model import LogisticRegression

In [39]:
log_reg = LogisticRegression()

In [40]:
log_reg

LogisticRegression()

x---- inputlar
y---- outputlar

In [ ]:
# Convert CCAvg: Replace '/' with '.' to convert '1/60' -> '1.60'
df['CCAvg'] = df['CCAvg'].astype(str).str.replace('/', '.')

# Convert to numeric
df['CCAvg'] = pd.to_numeric(df['CCAvg'], errors='coerce')

# Fill any remaining NaN values with the mean
df['CCAvg'].fillna(df['CCAvg'].mean(), inplace=True)

# Verify conversion
print(f"CCAvg dtype: {df['CCAvg'].dtype}")
print(f"Sample values:\n{df['CCAvg'].head(10)}")
print(f"NaN count: {df['CCAvg'].isnull().sum()}")

Sample CCAvg values:
Series([], Name: CCAvg, dtype: float64)

Data type: float64

Unique values sample: []

In [89]:
num_col=df.select_dtypes(include=['float64']).columns

In [90]:
num_col

Index(['ID', 'Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Personal Loan', 'Securities Account',
       'CD Account', 'Online', 'CreditCard'],
      dtype='object')

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   float64
 1   Age                 5000 non-null   float64
 2   Experience          5000 non-null   float64
 3   Income              5000 non-null   float64
 4   ZIP Code            5000 non-null   float64
 5   Family              5000 non-null   float64
 6   CCAvg               0 non-null      float64
 7   Education           5000 non-null   float64
 8   Mortgage            5000 non-null   float64
 9   Personal Loan       5000 non-null   float64
 10  Securities Account  5000 non-null   float64
 11  CD Account          5000 non-null   float64
 12  Online              5000 non-null   float64
 13  CreditCard          5000 non-null   float64
dtypes: float64(14)
memory usage: 547.0 KB

In [113]:
x = df.drop('Personal Loan', axis=1)

In [114]:
# Check for remaining NaN values
print("NaN count by column:")
print(df.isnull().sum())

# Drop any rows with remaining NaN values
df.dropna(inplace=True)
print(f"\nDataframe shape after removing NaN: {df.shape}")

NaN count by column:
ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

Dataframe shape after removing NaN: (5000, 14)

In [135]:
y = df['Personal Loan'].astype(int)

In [136]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    0
4997    0
4998    0
4999    0
Name: Personal Loan, Length: 5000, dtype: int64

In [137]:
x

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,29,3,40,92697,1,1.9,3,0,0,0,1,0
4996,4997,30,4,15,92037,4,0.4,1,85,0,0,1,0
4997,4998,63,39,24,93023,2,0.3,3,0,0,0,0,0
4998,4999,65,40,49,90034,3,0.5,2,0,0,0,1,0
4999,5000,28,4,83,92612,3,0.8,1,0,0,0,1,1

In [138]:
x.dtypes

ID                      int64
Age                     int64
Experience              int64
Income                  int64
ZIP Code                int64
Family                  int64
CCAvg                 float64
Education               int64
Mortgage                int64
Securities Account      int64
CD Account              int64
Online                  int64
CreditCard              int64
dtype: object

In [139]:
from sklearn.model_selection import train_test_split

In [140]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [141]:
x_train.shape

(3500, 13)

In [142]:
x_test.shape

(1500, 13)

In [143]:
from sklearn.linear_model import LogisticRegression

In [144]:
log_reg=LogisticRegression()

In [145]:
log_reg

LogisticRegression()

In [146]:
# 1. Convert CCAvg
df['CCAvg'] = df['CCAvg'].astype(str).str.replace('/', '.')
df['CCAvg'] = pd.to_numeric(df['CCAvg'], errors='coerce')
df['CCAvg'] = df['CCAvg'].fillna(df['CCAvg'].mean())

# 2. Recreate x and y
x = df.drop('Personal Loan', axis=1)
y = df['Personal Loan']

# 3. Split again
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

# 4. Fit model
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(x_train, y_train)

/Users/a1/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [147]:
log_reg.fit(x_train,y_train)

/Users/a1/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [133]:
y_pred=log_reg.predict(x_test)

In [134]:
y_pred[0]

np.int64(0)

In [149]:
y_pred[1:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [150]:
from sklearn.metrics import accuracy_score

In [151]:
score=accuracy_score(y_test,y_pred)

In [152]:
print('Modelning aniqlik darajasi:', score)

Modelning aniqlik darajasi: 0.9466666666666667