# Classification uchun

In [2153]:
import pandas as pd
df=pd.read_csv("digital_mental_health_classification.csv")

In [2154]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          9704 non-null   float64
 1   Gender                       9727 non-null   str
 2   Country                      9718 non-null   str
 3   Avg_Daily_Usage_Hours        9690 non-null   float64
 4   Sleep_Hours                  9681 non-null   float64
 5   Physical_Activity_Hours      9721 non-null   float64
 6   Screen_Time_Before_Sleep     9710 non-null   float64
 7   Social_Interactions_Per_Day  9690 non-null   float64
 8   Work_Study_Hours             9706 non-null   float64
 9   Stress_Level                 9678 non-null   float64
 10  Anxiety_Score                9696 non-null   float64
 11  Device_Usage_Type            9682 non-null   str
 12  Internet_Speed_Mbps          9723 non-null   float64
 13  Addiction_Score              9708 non-null   float64
 14  Mental_Health_Risk           10000 non-null  int64
dtypes: float64(11), int64(1), str(3)
memory usage: 1.1 MB

In [2155]:
df.head()

,Age,Gender,Country,Avg_Daily_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Screen_Time_Before_Sleep,Social_Interactions_Per_Day,Work_Study_Hours,Stress_Level,Anxiety_Score,Device_Usage_Type,Internet_Speed_Mbps,Addiction_Score,Mental_Health_Risk
0,20.0,Female,Brazil,5.753150,6.908067,NaN,1.806357,8.0,5.316147,3.0,0.804424,Laptop,58.789070,0.657113,0
1,46.0,Male,Germany,4.048060,6.253570,4.085070,0.866805,9.0,5.209255,3.0,0.572512,Both,47.154311,0.539020,0
2,52.0,Female,India,4.549815,7.338950,0.762743,2.440759,9.0,7.035117,6.0,0.887767,Both,34.702303,0.705674,0
3,56.0,Male,Germany,5.433350,6.352877,2.048137,1.466693,NaN,8.960371,4.0,0.713194,Laptop,171.102216,0.294997,0
4,35.0,Female,Uzbekistan,7.366173,7.254718,1.403123,2.276993,2.0,4.322121,1.0,0.428122,Mobile,120.121032,0.493070,0

In [2156]:
df.tail()

,Age,Gender,Country,Avg_Daily_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Screen_Time_Before_Sleep,Social_Interactions_Per_Day,Work_Study_Hours,Stress_Level,Anxiety_Score,Device_Usage_Type,Internet_Speed_Mbps,Addiction_Score,Mental_Health_Risk
9995,51.0,Male,Canada,6.906596,5.178995,2.888871,0.523894,3.0,4.440833,4.0,0.579295,Laptop,114.948314,0.951122,0
9996,39.0,Male,Italy,7.097467,6.514204,1.145627,NaN,6.0,7.157604,8.0,0.570082,Laptop,NaN,0.584942,1
9997,41.0,Female,Italy,7.594177,5.514995,1.290211,1.237875,9.0,NaN,2.0,0.626469,Mobile,104.272335,0.843821,0
9998,46.0,Female,France,3.366823,5.046844,2.668035,0.787322,8.0,5.114317,10.0,0.642993,Mobile,99.985113,0.672870,1
9999,47.0,Female,Canada,5.058187,7.052499,2.243011,2.775855,2.0,6.582840,2.0,NaN,Laptop,160.496012,0.548822,0

In [2157]:
# Missing value
df.isna().sum()

Age                            296
Gender                         273
Country                        282
Avg_Daily_Usage_Hours          310
Sleep_Hours                    319
Physical_Activity_Hours        279
Screen_Time_Before_Sleep       290
Social_Interactions_Per_Day    310
Work_Study_Hours               294
Stress_Level                   322
Anxiety_Score                  304
Device_Usage_Type              318
Internet_Speed_Mbps            277
Addiction_Score                292
Mental_Health_Risk               0
dtype: int64

In [2158]:
def fulla(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=="str":
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return df
df=fulla(df)

In [2159]:
df.isna().any()

Age                            False
Gender                         False
Country                        False
Avg_Daily_Usage_Hours          False
Sleep_Hours                    False
Physical_Activity_Hours        False
Screen_Time_Before_Sleep       False
Social_Interactions_Per_Day    False
Work_Study_Hours               False
Stress_Level                   False
Anxiety_Score                  False
Device_Usage_Type              False
Internet_Speed_Mbps            False
Addiction_Score                False
Mental_Health_Risk             False
dtype: bool

In [2160]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          10000 non-null  float64
 1   Gender                       10000 non-null  str
 2   Country                      10000 non-null  str
 3   Avg_Daily_Usage_Hours        10000 non-null  float64
 4   Sleep_Hours                  10000 non-null  float64
 5   Physical_Activity_Hours      10000 non-null  float64
 6   Screen_Time_Before_Sleep     10000 non-null  float64
 7   Social_Interactions_Per_Day  10000 non-null  float64
 8   Work_Study_Hours             10000 non-null  float64
 9   Stress_Level                 10000 non-null  float64
 10  Anxiety_Score                10000 non-null  float64
 11  Device_Usage_Type            10000 non-null  str
 12  Internet_Speed_Mbps          10000 non-null  float64
 13  Addiction_Score              10000 non-null  float64
 14  Mental_Health_Risk           10000 non-null  int64
dtypes: float64(11), int64(1), str(3)
memory usage: 1.1 MB

In [2161]:
# Encoding jarayoni
from sklearn.preprocessing import LabelEncoder

In [2162]:
df.nunique()

Age                              43
Gender                            2
Country                          12
Avg_Daily_Usage_Hours          9672
Sleep_Hours                    9652
Physical_Activity_Hours        9628
Screen_Time_Before_Sleep       9571
Social_Interactions_Per_Day      11
Work_Study_Hours               9707
Stress_Level                     11
Anxiety_Score                  9652
Device_Usage_Type                 3
Internet_Speed_Mbps            9479
Addiction_Score                9461
Mental_Health_Risk                2
dtype: int64

In [2163]:
def raqamla(df, Mental_Health_Risk):
    encoder=LabelEncoder()
    for col in df.columns:
        if col == Mental_Health_Risk:
            continue

        if df[col].dtype=="str":
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [2164]:
df=raqamla(df, "Mental_Health_Risk")

In [2165]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          10000 non-null  float64
 1   Country                      10000 non-null  int64
 2   Avg_Daily_Usage_Hours        10000 non-null  float64
 3   Sleep_Hours                  10000 non-null  float64
 4   Physical_Activity_Hours      10000 non-null  float64
 5   Screen_Time_Before_Sleep     10000 non-null  float64
 6   Social_Interactions_Per_Day  10000 non-null  float64
 7   Work_Study_Hours             10000 non-null  float64
 8   Stress_Level                 10000 non-null  float64
 9   Anxiety_Score                10000 non-null  float64
 10  Internet_Speed_Mbps          10000 non-null  float64
 11  Addiction_Score              10000 non-null  float64
 12  Mental_Health_Risk           10000 non-null  int64
 13  Gender_Female                10000 non-null  int64
 14  Gender_Male                  10000 non-null  int64
 15  Device_Usage_Type_Both       10000 non-null  int64
 16  Device_Usage_Type_Laptop     10000 non-null  int64
 17  Device_Usage_Type_Mobile     10000 non-null  int64
dtypes: float64(11), int64(7)
memory usage: 1.4 MB

In [2166]:
df.head()

,Age,Country,Avg_Daily_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Screen_Time_Before_Sleep,Social_Interactions_Per_Day,Work_Study_Hours,Stress_Level,Anxiety_Score,Internet_Speed_Mbps,Addiction_Score,Mental_Health_Risk,Gender_Female,Gender_Male,Device_Usage_Type_Both,Device_Usage_Type_Laptop,Device_Usage_Type_Mobile
0,20.0,0,5.753150,6.908067,2.311490,1.806357,8.000000,5.316147,3.0,0.804424,58.789070,0.657113,0,1,0,0,1,0
1,46.0,3,4.048060,6.253570,4.085070,0.866805,9.000000,5.209255,3.0,0.572512,47.154311,0.539020,0,0,1,1,0,0
2,52.0,4,4.549815,7.338950,0.762743,2.440759,9.000000,7.035117,6.0,0.887767,34.702303,0.705674,0,1,0,1,0,0
3,56.0,3,5.433350,6.352877,2.048137,1.466693,4.511249,8.960371,4.0,0.713194,171.102216,0.294997,0,0,1,0,1,0
4,35.0,11,7.366173,7.254718,1.403123,2.276993,2.000000,4.322121,1.0,0.428122,120.121032,0.493070,0,1,0,0,0,1

In [2167]:
# Scaling jarayoni
from sklearn.preprocessing import MinMaxScaler

In [2168]:
def ritimla(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=["float64","int64"]).columns.drop("Mental_Health_Risk")
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [2169]:
df=ritimla(df)

In [2170]:
df.head()

,Age,Country,Avg_Daily_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Screen_Time_Before_Sleep,Social_Interactions_Per_Day,Work_Study_Hours,Stress_Level,Anxiety_Score,Internet_Speed_Mbps,Addiction_Score,Mental_Health_Risk,Gender_Female,Gender_Male,Device_Usage_Type_Both,Device_Usage_Type_Laptop,Device_Usage_Type_Mobile
0,0.048780,0.000000,0.432105,0.568011,0.357624,0.313249,0.888889,0.385092,0.222222,0.804424,0.164345,0.657113,0,1.0,0.0,0.0,1.0,0.0
1,0.682927,0.272727,0.277096,0.458928,0.632025,0.150317,1.000000,0.375258,0.222222,0.572512,0.128797,0.539020,0,0.0,1.0,1.0,0.0,0.0
2,0.829268,0.363636,0.322710,0.639825,0.118008,0.423263,1.000000,0.543236,0.555556,0.887767,0.090751,0.705674,0,1.0,0.0,1.0,0.0,0.0
3,0.926829,0.272727,0.403032,0.475480,0.316879,0.254346,0.501250,0.720357,0.333333,0.713194,0.507503,0.294997,0,0.0,1.0,0.0,1.0,0.0
4,0.414634,1.000000,0.578743,0.625786,0.217085,0.394864,0.222222,0.293643,0.000000,0.428122,0.351737,0.493070,0,1.0,0.0,0.0,0.0,1.0

In [2171]:
# Target(output) va Feature(input) ga ajratish
from sklearn.model_selection import train_test_split

In [2172]:
x=df.drop("Mental_Health_Risk",axis=1).astype(int)
y=df["Mental_Health_Risk"].astype(int)

In [2173]:
x_train,x_test, y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# `Algorithm(model) tanlash`

# Logistic Regression

In [2174]:
from sklearn.linear_model import LogisticRegression
lgr=LogisticRegression()

In [2175]:
lgr

LogisticRegression()

In [2176]:
# Fitting(algorithmni o'qitish)
lgr.fit(x_train,y_train)

LogisticRegression()

In [2177]:
# Predict(baxolash)
y_pred=lgr.predict(x_test)

In [2178]:
# Evaluation
from sklearn.metrics import classification_report, accuracy_score

In [2180]:
class_report=classification_report(y_test,y_pred)
acc_score=accuracy_score(y_test,y_pred)

In [2181]:
print(f'class_report: {class_report}')
print("acc_score: ", acc_score)

class_report:               precision    recall  f1-score   support

           0       0.56      0.96      0.71      1006
           1       0.85      0.24      0.37       994

    accuracy                           0.60      2000
   macro avg       0.71      0.60      0.54      2000
weighted avg       0.71      0.60      0.54      2000

acc_score:  0.6

# `K-Fold` -> Logistic Regression

In [2182]:
from sklearn.model_selection import KFold, cross_val_score

In [2183]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [2184]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [2185]:
scores=cross_val_score(lgr,x,y,cv=kf,scoring="accuracy")

In [2186]:
print("scores: ", scores)

scores:  [0.6    0.601  0.5995 0.6    0.575 ]

In [2187]:
for i in scores:
    print(i)

0.6
0.601
0.5995
0.6
0.575

In [2188]:
import numpy as np

In [2189]:
np.mean(scores)

np.float64(0.5951000000000001)

In [2190]:
np.std(scores)

np.float64(0.010061808982484226)

# Decision Tree Classifier

In [2191]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()

In [2192]:
dtc

DecisionTreeClassifier()

In [2193]:
# Fitting
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [2194]:
# Predict
y_pred=dtc.predict(x_test)

In [2195]:
# Evaluation(metrics)
from sklearn.metrics import classification_report, accuracy_score

In [2196]:
class_report_dtc=classification_report(y_test,y_pred)
acc_score_dtc=accuracy_score(y_test,y_pred)

In [2197]:
print(f'dtc_class_report: {class_report_dtc}')
print("dtc_acc_score: ", acc_score_dtc)

dtc_class_report:               precision    recall  f1-score   support

           0       0.56      0.97      0.71      1006
           1       0.89      0.22      0.36       994

    accuracy                           0.60      2000
   macro avg       0.73      0.60      0.53      2000
weighted avg       0.72      0.60      0.53      2000

dtc_acc_score:  0.6005

# `K-Fold` -> Decision Tree Classifier

In [2198]:
from sklearn.model_selection import KFold, cross_val_score

In [2199]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [2200]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [2201]:
scores=cross_val_score(dtc,x,y,cv=kf,scoring='accuracy')

In [2202]:
print("dtc_scores: ", scores)

dtc_scores:  [0.6005 0.605  0.599  0.5985 0.5765]

In [2203]:
for i in scores:
    print(i)

0.6005
0.605
0.599
0.5985
0.5765

In [2204]:
import numpy as np

In [2205]:
np.mean(scores)

np.float64(0.5959)

In [2206]:
np.std(scores)

np.float64(0.009966945369570353)

# Random Forest Classifier

In [2207]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(random_state=30)

In [2208]:
rfc

RandomForestClassifier(random_state=30)

In [2209]:
# Fitting
rfc.fit(x_train,y_train)

RandomForestClassifier(random_state=30)

In [2210]:
# Predict
y_pred=rfc.predict(x_test)

In [2211]:
# Evaluation(metrics)
from sklearn.metrics import classification_report, accuracy_score

In [2212]:
class_report_rfc=classification_report(y_test,y_pred)
acc_score_rfc=accuracy_score(y_test,y_pred)

In [2213]:
print(f'rfc_class_report: {class_report_rfc}')
print("rfc_acc_score: ", acc_score_rfc)

rfc_class_report:               precision    recall  f1-score   support

           0       0.56      0.97      0.71      1006
           1       0.88      0.23      0.36       994

    accuracy                           0.60      2000
   macro avg       0.72      0.60      0.54      2000
weighted avg       0.72      0.60      0.54      2000

rfc_acc_score:  0.602

# `K-Fold` -> Random Forest Classifier

In [2214]:
from sklearn.model_selection import KFold, cross_val_score

In [2215]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [2216]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [2217]:
scores=cross_val_score(rfc,x,y,cv=kf,scoring="accuracy")

In [2218]:
print("rfc_scores: ", scores)

rfc_scores:  [0.596  0.6045 0.5985 0.5985 0.577 ]

In [2219]:
for i in scores:
    print(i)

0.596
0.6045
0.5985
0.5985
0.577

In [2220]:
import numpy as np

In [2221]:
np.mean(scores)

np.float64(0.5949)

In [2222]:
np.std(scores)

np.float64(0.00937763296360017)

# Support Vector Machine (Classifier)

In [2223]:
from sklearn.svm import SVC
svc=SVC(kernel="linear",C=1.0)

In [2224]:
svc

SVC(kernel='linear')

In [2225]:
# Fitting
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [2226]:
# Predict
y_pred=svc.predict(x_test)

In [2227]:
# Evaluation(metrics)
from sklearn.metrics import classification_report, accuracy_score

In [2228]:
class_report_svc=classification_report(y_test,y_pred)
acc_score_svc=accuracy_score(y_test,y_pred)

In [2229]:
print(f'svc_class_report: {class_report_svc}')
print("svc_acc_score: ", acc_score_svc)

# svc=SVC(kernel="rbf",C=1.0) qilganimda accuracy=0.5995 chiqdi...

svc_class_report:               precision    recall  f1-score   support

           0       0.56      0.98      0.71      1006
           1       0.91      0.21      0.34       994

    accuracy                           0.60      2000
   macro avg       0.73      0.60      0.53      2000
weighted avg       0.73      0.60      0.53      2000

svc_acc_score:  0.5975

# `K-Fold` -> Support Vector Machine (Classifier)

In [2230]:
from sklearn.model_selection import KFold, cross_val_score

In [2232]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [2233]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [2234]:
scores=cross_val_score(rfc,x,y,cv=kf,scoring="accuracy")

In [2235]:
print("rfc_scores: ", scores)

rfc_scores:  [0.596  0.6045 0.5985 0.5985 0.577 ]

In [2236]:
for i in scores:
    print(i)

0.596
0.6045
0.5985
0.5985
0.577

In [2237]:
import numpy as np

In [2238]:
np.mean(scores)

np.float64(0.5949)

In [2239]:
np.std(scores)

np.float64(0.00937763296360017)

# Tabulate

In [2241]:
from tabulate import tabulate

In [2246]:
results=[
    ["Logistic Regression",0.6],
    ["Decision Tree Classifier",0.6005],
    ["Random Forest Classifier",0.602],
    ["Support Vector Classifier",0.5975]
]

In [2261]:
headers = ["Model","Accuracy"]
table=tabulate(results,headers=headers,tablefmt="grid",floatfmt=".3f")

In [2263]:
print(table)

+---------------------------+------------+
| Model                     |   Accuracy |
+===========================+============+
| Logistic Regression       |      0.600 |
+---------------------------+------------+
| Decision Tree Classifier  |      0.601 |
+---------------------------+------------+
| Random Forest Classifier  |      0.602 |
+---------------------------+------------+
| Support Vector Classifier |      0.598 |
+---------------------------+------------+