imtihonga tayorgallik + 4 ta algorithmga data + code

In [9]:
import pandas as pd 
df = pd.read_csv("/Users/sherzodbeksharobiddinov/MLFoundation/Sherzod_dev/2-oy_Model_Building/Data/bank-full.csv")
df.head()

   age           job  marital  education  ... pdays  previous poutcome   y
0   58    management  married   tertiary  ...    -1         0  unknown  no
1   44    technician   single  secondary  ...    -1         0  unknown  no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown  no
3   47   blue-collar  married    unknown  ...    -1         0  unknown  no
4   33       unknown   single    unknown  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [10]:
# Preprocessing

def datalarni_toldirsin(df):
    df = df.copy()
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype == "object":
                df[col] = df[col].fillna(df[col].mode()[0])
            else:
                df[col] = df[col].fillna(df[col].mean())
    return df


df = datalarni_toldirsin(df)
print("Null count:", df.isnull().sum().sum())

Null count: 0

In [11]:
# Encoding
from sklearn.preprocessing import LabelEncoder

def encoding_qilsin(df):
    df = df.copy()
    label_encoder = LabelEncoder()
    for col in df.columns:
        if df[col].dtype == "object":
            df[col] = label_encoder.fit_transform(df[col])
    return df


df = encoding_qilsin(df)
df.head()

   age  job  marital  education  ...  pdays  previous  poutcome  y
0   58    4        1          2  ...     -1         0         3  0
1   44    9        2          1  ...     -1         0         3  0
2   33    2        1          1  ...     -1         0         3  0
3   47    1        1          3  ...     -1         0         3  0
4   33   11        2          3  ...     -1         0         3  0

[5 rows x 17 columns]

In [12]:
# Train test split

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop("y", axis=1)
y = df["y"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train:", X_train.shape, "X_test:", X_test.shape)

X_train: (36168, 16) X_test: (9043, 16)

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

decision_tree_model = DecisionTreeClassifier(random_state=42)
decision_tree_model.fit(X_train, y_train)

y_pred_tree = decision_tree_model.predict(X_test)
acc_tree = accuracy_score(y_test, y_pred_tree)
print("=== Decision Tree Classifier ===")
print("Accuracy:", round(acc_tree, 4))
print(classification_report(y_test, y_pred_tree))

=== Decision Tree Classifier ===
Accuracy: 0.8784
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      7985
           1       0.48      0.49      0.48      1058

    accuracy                           0.88      9043
   macro avg       0.71      0.71      0.71      9043
weighted avg       0.88      0.88      0.88      9043

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

logistic_model = LogisticRegression(max_iter=2000, random_state=42)
logistic_model.fit(X_train_scaled, y_train)

y_pred_logistic = logistic_model.predict(X_test_scaled)
acc_logistic = accuracy_score(y_test, y_pred_logistic)
print("=== Logistic Regression ===")
print("Accuracy:", round(acc_logistic, 4))
print(classification_report(y_test, y_pred_logistic))

=== Logistic Regression ===
Accuracy: 0.8914
              precision    recall  f1-score   support

           0       0.91      0.98      0.94      7985
           1       0.59      0.23      0.33      1058

    accuracy                           0.89      9043
   macro avg       0.75      0.60      0.63      9043
weighted avg       0.87      0.89      0.87      9043

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_predict_RF = rf.predict(X_test)
acc_logistic = accuracy_score(y_test, y_predict_RF)
print("=== Logistic Regression ===")
print("Accuracy:", round(acc_logistic, 4))
print(classification_report(y_test, y_predict_RF))

=== Logistic Regression ===
Accuracy: 0.9069
              precision    recall  f1-score   support

           0       0.93      0.97      0.95      7985
           1       0.66      0.41      0.51      1058

    accuracy                           0.91      9043
   macro avg       0.80      0.69      0.73      9043
weighted avg       0.90      0.91      0.90      9043

In [28]:
from tabulate import tabulate

results = [
    ['Decision Tree Classifier',0.8784],
    ['Logistic Regression1',0.8914],
    ["RandomForest",0.9069]
]

headers = ['Algirithms','Accuary_Score']

table = tabulate(results,headers=headers, tablefmt='grid')
print(table)

+--------------------------+-----------------+
| Algirithms               |   Accuary_Score |
+==========================+=================+
| Decision Tree Classifier |          0.8784 |
+--------------------------+-----------------+
| Logistic Regression1     |          0.8914 |
+--------------------------+-----------------+
| RandomForest             |          0.9069 |
+--------------------------+-----------------+