# Model Review

In [408]:
import pandas as pd

In [409]:
df=pd.read_csv('/Users/a1/Desktop/MLFoundation/df_merged.csv')

In [410]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8499 entries, 0 to 8498
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8499 non-null   object
 1   T           8499 non-null   float64
 2   T_a         8499 non-null   float64
 3   Ff          8499 non-null   float64
 4   N           8491 non-null   float64
 5   Nh          6727 non-null   float64
 6   Cl          8499 non-null   int64
 7   Po          8496 non-null   float64
 8   U           8488 non-null   float64
 9   Ch          3019 non-null   object
 10  Cm          5181 non-null   object
 11  H           6739 non-null   object
 12  RRR         2141 non-null   object
 13  DD_         8499 non-null   object
 14  diff        8499 non-null   float64
 15  abs_diff    8499 non-null   float64
 16  T_kal       8488 non-null   float64
 17  T_sher      8494 non-null   float64
 18  T_sar       6675 non-null   float64
 19  three_mean  6666 non-null   float64
 20  diff_3      6666 non-null   float64
 21  abs_diff_3  6666 non-null   float64
dtypes: float64(15), int64(1), object(6)
memory usage: 1.4+ MB

In [411]:
df.dropna(inplace=True)

In [412]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 644 entries, 11 to 8476
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  644 non-null    object
 1   T           644 non-null    float64
 2   T_a         644 non-null    float64
 3   Ff          644 non-null    float64
 4   N           644 non-null    float64
 5   Nh          644 non-null    float64
 6   Cl          644 non-null    int64
 7   Po          644 non-null    float64
 8   U           644 non-null    float64
 9   Ch          644 non-null    object
 10  Cm          644 non-null    object
 11  H           644 non-null    object
 12  RRR         644 non-null    object
 13  DD_         644 non-null    object
 14  diff        644 non-null    float64
 15  abs_diff    644 non-null    float64
 16  T_kal       644 non-null    float64
 17  T_sher      644 non-null    float64
 18  T_sar       644 non-null    float64
 19  three_mean  644 non-null    float64
 20  diff_3      644 non-null    float64
 21  abs_diff_3  644 non-null    float64
dtypes: float64(15), int64(1), object(6)
memory usage: 115.7+ KB

In [413]:
df.head()

,Unnamed: 0,T,T_a,Ff,N,Nh,Cl,Po,U,Ch,...,RRR,DD_,diff,abs_diff,T_kal,T_sher,T_sar,three_mean,diff_3,abs_diff_3
11,2012-11-02 09:00:00,-1.6,-1.0,2.0,100.0,75.0,7,760.1,62.0,"Перистые нитевидные, иногда когтевидные, не ра...",...,Следы осадков,South,-0.6,0.6,-1.7,-2.6,0.2,-1.366667,-0.233333,0.233333
15,2012-11-02 21:00:00,1.4,1.0,2.0,100.0,25.0,7,754.0,52.0,"Перистые нитевидные, иногда когтевидные, не ра...",...,Осадков нет,South,0.4,0.4,1.6,1.4,0.6,1.200000,0.200000,0.200000
39,2012-11-05 21:00:00,-4.5,-4.0,1.0,90.0,60.0,0,756.2,96.0,"Перистых, перисто-кучевых или перисто-слоистых...",...,2.0,East,-0.5,0.5,-4.0,-3.1,-6.9,-4.666667,0.166667,0.166667
47,2012-11-06 21:00:00,-14.0,-13.0,3.0,100.0,75.0,6,755.8,80.0,"Перистые нитевидные, иногда когтевидные, не ра...",...,4.0,North,-1.0,1.0,-14.1,-12.7,-13.0,-13.266667,-0.733333,0.733333
59,2012-11-08 09:00:00,-21.6,-19.0,0.0,100.0,0.0,7,764.2,80.0,"Перистые нитевидные, иногда когтевидные, не ра...",...,Осадков нет,Calm,-2.6,2.6,-24.6,-22.8,-22.6,-23.333333,1.733333,1.733333

In [414]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [415]:
encoder = LabelEncoder()

In [416]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

encoder = LabelEncoder()

# First, drop rows with NaN values
df.dropna(inplace=True)

# Encode categorical columns
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = encoder.fit_transform(df[col])

# Scale numeric columns (but NOT the target columns 'diff' and 'Ch')
scaler = MinMaxScaler()
for col in df.columns:
    if df[col].dtype != 'object' and col not in ['diff', 'Ch']:
        df[col] = scaler.fit_transform(df[[col]])

In [417]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 644 entries, 11 to 8476
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  644 non-null    float64
 1   T           644 non-null    float64
 2   T_a         644 non-null    float64
 3   Ff          644 non-null    float64
 4   N           644 non-null    float64
 5   Nh          644 non-null    float64
 6   Cl          644 non-null    float64
 7   Po          644 non-null    float64
 8   U           644 non-null    float64
 9   Ch          644 non-null    int64
 10  Cm          644 non-null    float64
 11  H           644 non-null    float64
 12  RRR         644 non-null    float64
 13  DD_         644 non-null    float64
 14  diff        644 non-null    float64
 15  abs_diff    644 non-null    float64
 16  T_kal       644 non-null    float64
 17  T_sher      644 non-null    float64
 18  T_sar       644 non-null    float64
 19  three_mean  644 non-null    float64
 20  diff_3      644 non-null    float64
 21  abs_diff_3  644 non-null    float64
dtypes: float64(21), int64(1)
memory usage: 115.7 KB

In [418]:
from sklearn.model_selection import train_test_split

In [419]:
x=df.drop('diff',axis=1)

In [420]:
y=df['diff']

In [421]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [422]:
from sklearn.linear_model import LinearRegression

In [423]:
lr_model=LinearRegression()

In [424]:
lr_model

LinearRegression()

In [425]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 644 entries, 11 to 8476
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  644 non-null    float64
 1   T           644 non-null    float64
 2   T_a         644 non-null    float64
 3   Ff          644 non-null    float64
 4   N           644 non-null    float64
 5   Nh          644 non-null    float64
 6   Cl          644 non-null    float64
 7   Po          644 non-null    float64
 8   U           644 non-null    float64
 9   Ch          644 non-null    int64
 10  Cm          644 non-null    float64
 11  H           644 non-null    float64
 12  RRR         644 non-null    float64
 13  DD_         644 non-null    float64
 14  diff        644 non-null    float64
 15  abs_diff    644 non-null    float64
 16  T_kal       644 non-null    float64
 17  T_sher      644 non-null    float64
 18  T_sar       644 non-null    float64
 19  three_mean  644 non-null    float64
 20  diff_3      644 non-null    float64
 21  abs_diff_3  644 non-null    float64
dtypes: float64(21), int64(1)
memory usage: 115.7 KB

In [426]:
df.isnull().sum()

Unnamed: 0    0
T             0
T_a           0
Ff            0
N             0
Nh            0
Cl            0
Po            0
U             0
Ch            0
Cm            0
H             0
RRR           0
DD_           0
diff          0
abs_diff      0
T_kal         0
T_sher        0
T_sar         0
three_mean    0
diff_3        0
abs_diff_3    0
dtype: int64

In [427]:
lr_model.fit(x_train, y_train)
print("Model trained successfully!")

Model trained successfully!

In [428]:
y_pred=lr_model.predict(x_test) 
print("Model trained successfully")

Model trained successfully

In [429]:
y_pred

array([ 5.00000000e-01,  1.70000000e+00, -4.00000000e-01,  9.00000000e-01,
        6.00000000e-01,  2.00000000e-01, -5.00000000e-01,  2.10000000e+00,
        8.00000000e-01, -3.00000000e-01,  2.20000000e+00,  6.00000000e-01,
        1.40000000e+00,  4.00000000e-01,  8.00000000e-01,  4.50000000e+00,
       -3.00000000e-01, -4.50000000e+00,  2.40000000e+00,  1.40000000e+00,
        1.10000000e+00, -1.30000000e+00,  5.00000000e-01, -2.00000000e-01,
        1.00000000e-01,  6.00000000e-01,  1.60000000e+00,  2.00000000e+00,
        2.60000000e+00, -4.00000000e-01,  9.00000000e-01,  2.70000000e+00,
        1.50000000e+00, -1.00000000e-01, -1.10000000e+00,  2.00000000e-01,
       -1.00000000e-01,  9.00000000e-01, -2.00000000e-01,  2.60000000e+00,
        1.00000000e-01,  9.00000000e-01, -3.00000000e-01,  2.00000000e+00,
       -8.00000000e-01, -5.00000000e-01, -1.90000000e+00, -2.00000000e-01,
        1.10000000e+00, -4.00000000e-01,  6.00000000e-01,  1.60000000e+00,
       -8.00000000e-01,  5.00000000e-01, -1.50000000e+00,  1.30000000e+00,
        3.00000000e-01,  1.40000000e+00,  1.00000000e-01, -5.00000000e-01,
       -2.00000000e+00,  5.00000000e-01, -2.00000000e+00,  2.80000000e+00,
        5.32907052e-15,  1.00000000e-01,  3.00000000e+00,  3.00000000e-01,
       -2.00000000e-01,  1.50000000e+00,  3.00000000e-01,  5.00000000e-01,
        1.80000000e+00,  2.00000000e-01,  1.10000000e+00, -2.70000000e+00,
        1.70000000e+00,  1.00000000e+00,  4.00000000e-01,  8.00000000e-01,
       -6.00000000e-01,  6.00000000e-01,  2.60000000e+00,  1.00000000e-01,
       -1.60000000e+00, -1.70000000e+00, -4.00000000e-01, -1.70000000e+00,
       -1.00000000e-01,  5.00000000e-01, -1.60000000e+00,  1.00000000e+00,
        4.00000000e-01, -4.08562073e-14,  1.60000000e+00,  3.00000000e-01,
        2.00000000e-01, -2.00000000e-01, -7.00000000e-01,  5.00000000e-01,
       -5.00000000e-01, -1.80000000e+00,  4.00000000e-01, -1.60000000e+00,
        5.00000000e-01,  1.20000000e+00, -2.00000000e-01, -2.00000000e-01,
        2.66453526e-14,  2.30000000e+00,  7.00000000e-01, -8.00000000e-01,
        3.90000000e+00,  5.00000000e-01,  2.00000000e-01,  3.30000000e+00,
        8.88178420e-15,  1.70000000e+00,  2.00000000e-01,  1.10000000e+00,
        8.00000000e-01, -1.10000000e+00,  2.00000000e-01,  1.40000000e+00,
       -7.00000000e-01,  2.70000000e+00,  7.00000000e-01, -7.00000000e-01,
       -3.19744231e-14])

In [430]:
y_pred=lr_model.predict(x_train)

In [431]:
y_pred

array([ 2.00000000e-01, -7.00000000e-01,  2.00000000e-01,  3.00000000e-01,
        7.00000000e-01,  4.00000000e-01,  1.20000000e+00, -1.10000000e+00,
        2.30000000e+00, -1.60000000e+00,  1.42108547e-14,  3.00000000e-01,
        1.40000000e+00,  1.00000000e-01, -3.00000000e-01,  2.90000000e+00,
        1.00000000e-01, -4.00000000e-01,  1.50000000e+00,  1.50000000e+00,
        3.73034936e-14,  5.00000000e-01, -4.00000000e-01, -1.59872116e-14,
       -5.00000000e-01,  4.00000000e-01,  2.90000000e+00, -2.00000000e-01,
        3.00000000e-01,  1.40000000e+00,  1.60000000e+00, -1.00000000e+00,
        1.60000000e+00, -8.00000000e-01,  1.20000000e+00,  3.00000000e-01,
       -5.00000000e-01,  2.00000000e-01, -5.00000000e-01,  1.00000000e+00,
       -1.30000000e+00,  1.80000000e+00,  2.60000000e+00,  5.00000000e-01,
       -9.00000000e-01, -3.00000000e-01, -1.10000000e+00,  2.10000000e+00,
       -2.30000000e+00,  1.00000000e+00,  2.00000000e-01,  3.00000000e-01,
       -1.00000000e-01, -1.00000000e-01, -1.50000000e+00,  2.00000000e-01,
        5.00000000e-01,  1.00000000e-01,  8.00000000e-01, -8.00000000e-01,
       -1.00000000e-01, -3.40000000e+00,  1.40000000e+00, -1.10000000e+00,
        2.00000000e+00,  6.00000000e-01,  7.00000000e-01,  0.00000000e+00,
        5.00000000e-01,  1.00000000e-01,  1.30000000e+00,  1.50000000e+00,
        2.00000000e+00,  4.00000000e-01,  1.10000000e+00, -1.10000000e+00,
        2.00000000e-01, -1.00000000e+00, -2.00000000e-01,  1.00000000e+00,
        3.90000000e+00, -2.00000000e+00,  1.40000000e+00,  2.00000000e-01,
       -1.60000000e+00,  5.00000000e-01,  2.60000000e+00,  1.00000000e+00,
        1.30000000e+00,  5.00000000e-01,  2.70000000e+00,  3.20000000e+00,
        2.00000000e+00, -8.00000000e-01,  1.00000000e+00,  1.60000000e+00,
       -2.00000000e-01,  1.90000000e+00,  4.00000000e-01,  9.00000000e-01,
        1.90000000e+00,  1.90000000e+00,  1.70000000e+00, -2.00000000e-01,
        1.10000000e+00,  1.30000000e+00, -6.00000000e-01, -3.00000000e-01,
        2.00000000e-01,  1.50000000e+00,  1.80000000e+00, -1.20000000e+00,
        7.00000000e-01,  9.00000000e-01, -1.10000000e+00,  1.50000000e+00,
        9.00000000e-01,  1.10000000e+00, -1.00000000e-01,  2.00000000e-01,
        5.00000000e-01, -1.70000000e+00,  9.00000000e-01,  8.00000000e-01,
       -2.00000000e-01,  1.70000000e+00,  2.00000000e+00,  2.50000000e+00,
        1.30000000e+00,  3.50000000e+00,  8.00000000e-01, -2.00000000e-01,
        4.00000000e-01,  2.40000000e+00,  5.00000000e-01,  2.90000000e+00,
       -2.13162821e-14,  2.50000000e+00,  3.10000000e+00,  8.00000000e-01,
        9.00000000e-01, -7.00000000e-01,  2.30000000e+00,  1.30000000e+00,
       -2.50000000e+00, -2.00000000e-01, -4.00000000e-01, -6.00000000e-01,
        1.30000000e+00, -1.00000000e+00, -6.00000000e-01,  9.00000000e-01,
        2.60000000e+00,  4.00000000e+00, -1.10000000e+00, -1.70000000e+00,
       -7.00000000e-01,  8.00000000e-01,  5.86197757e-14,  1.90000000e+00,
        2.00000000e+00, -1.90000000e+00,  9.00000000e-01, -5.00000000e-01,
        1.00000000e+00,  7.00000000e-01,  3.00000000e-01,  2.10000000e+00,
       -6.00000000e-01, -2.90000000e+00,  9.00000000e-01,  2.60000000e+00,
        5.15143483e-14,  1.20000000e+00, -8.00000000e-01, -5.00000000e-01,
       -3.00000000e-01, -4.00000000e-01,  2.00000000e-01, -9.00000000e-01,
        5.00000000e-01,  3.10000000e+00,  1.60000000e+00,  2.80000000e+00,
        5.00000000e-01,  8.00000000e-01, -3.00000000e-01,  1.80000000e+00,
        2.60000000e+00,  1.60000000e+00, -4.60000000e+00,  3.00000000e-01,
       -9.70000000e+00, -3.00000000e-01,  1.00000000e+00,  8.00000000e-01,
       -7.00000000e-01,  2.00000000e-01,  3.20000000e+00,  1.20000000e+00,
        1.00000000e+00,  1.50000000e+00, -4.00000000e-01, -1.40000000e+00,
       -2.00000000e-01, -1.00000000e+00,  4.00000000e-01,  2.13162821e-14,
        1.00000000e-01,  1.10000000e+00,  4.00000000e-01,  3.30000000e+00,
       -6.00000000e-01,  2.00000000e-01, -7.00000000e-01,  8.00000000e-01,
        9.00000000e-01,  5.00000000e-01, -2.00000000e-01,  5.00000000e-01,
       -7.00000000e-01,  2.10000000e+00,  9.00000000e-01, -1.00000000e+00,
        3.00000000e-01,  1.40000000e+00, -1.50000000e+00,  7.00000000e-01,
        3.00000000e-01,  6.00000000e-01,  7.00000000e-01, -5.00000000e-01,
       -1.10000000e+00, -1.20000000e+00,  5.00000000e-01, -9.00000000e-01,
        1.00000000e+00,  8.00000000e-01,  3.00000000e-01,  5.70000000e+00,
        1.60000000e+00,  2.20000000e+00, -1.00000000e-01,  1.80000000e+00,
       -8.00000000e-01,  1.60000000e+00,  2.70000000e+00, -8.00000000e-01,
        2.10000000e+00, -4.00000000e-01, -6.57252031e-14,  2.00000000e-01,
        2.00000000e-01, -2.00000000e-01, -1.00000000e-01,  1.20000000e+00,
        4.00000000e-01, -2.00000000e-01, -2.70000000e+00,  5.00000000e-01,
        1.20000000e+00,  1.00000000e-01,  4.00000000e-01,  1.10000000e+00,
        8.00000000e-01, -2.00000000e-01,  6.00000000e-01, -3.00000000e-01,
       -2.50000000e+00,  1.00000000e+00,  6.00000000e-01,  1.00000000e+00,
        1.00000000e+00,  7.00000000e-01,  2.30000000e+00,  8.00000000e-01,
        2.90000000e+00, -3.00000000e-01, -1.30000000e+00,  1.80000000e+00,
       -5.00000000e-01,  2.00000000e-01,  6.00000000e-01, -4.00000000e-01,
        4.00000000e-01, -1.06581410e-14, -5.00000000e-01,  1.80000000e+00,
        1.70000000e+00,  7.00000000e-01,  6.00000000e-01, -2.00000000e-01,
       -5.00000000e-01, -9.00000000e-01,  1.00000000e-01, -1.70000000e+00,
        2.40000000e+00,  8.00000000e-01,  1.00000000e-01, -1.60000000e+00,
       -3.00000000e-01,  2.00000000e-01,  2.00000000e-01,  2.70000000e+00,
        1.80000000e+00,  1.10000000e+00,  1.20000000e+00, -1.00000000e-01,
        2.80000000e+00,  1.00000000e-01, -3.00000000e-01,  2.00000000e-01,
        1.00000000e-01, -1.10000000e+00, -6.00000000e-01,  7.00000000e-01,
        1.30000000e+00, -4.00000000e-01, -1.40000000e+00,  3.30000000e+00,
        5.00000000e-01, -1.70000000e+00,  2.30000000e+00,  5.00000000e-01,
        5.00000000e-01,  1.00000000e-01, -3.55271368e-15,  6.00000000e-01,
        6.00000000e-01, -3.00000000e-01,  5.00000000e-01, -8.88178420e-15,
       -1.00000000e-01, -6.00000000e-01, -2.00000000e-01, -2.20000000e+00,
        3.10000000e+00, -5.00000000e-01,  2.40000000e+00,  1.60000000e+00,
        5.00000000e-01, -1.20000000e+00,  8.00000000e-01, -5.00000000e-01,
        1.42108547e-14, -1.00000000e-01,  1.60000000e+00,  1.70000000e+00,
        1.10000000e+00, -1.30000000e+00, -8.00000000e-01, -1.50000000e+00,
       -1.10000000e+00,  7.00000000e-01,  1.00000000e-01,  4.00000000e-01,
        3.00000000e-01,  9.00000000e-01, -3.70000000e+00,  2.10000000e+00,
       -9.00000000e-01,  1.00000000e-01, -2.84217094e-14,  1.20000000e+00,
       -1.80000000e+00, -1.00000000e-01,  1.50000000e+00,  1.20000000e+00,
       -7.00000000e-01, -1.77635684e-15,  3.00000000e-01, -2.00000000e-01,
        5.00000000e-01,  1.00000000e-01,  1.00000000e+00,  2.00000000e+00,
        1.30000000e+00,  1.00000000e+00, -8.00000000e-01, -7.00000000e-01,
       -1.00000000e-01, -4.00000000e-01, -6.00000000e-01,  1.10000000e+00,
        1.70000000e+00,  1.30000000e+00,  2.00000000e-01,  2.20000000e+00,
       -1.60000000e+00,  2.40000000e+00, -1.80000000e+00, -1.20000000e+00,
        2.00000000e+00, -1.00000000e+00,  8.00000000e-01,  7.00000000e-01,
        2.00000000e-01,  1.20000000e+00,  1.30000000e+00, -1.00000000e-01,
        7.00000000e-01,  6.00000000e-01,  2.20000000e+00,  1.80000000e+00,
       -8.00000000e-01, -1.30000000e+00, -2.60000000e+00, -1.60000000e+00,
       -5.00000000e-01, -6.00000000e-01,  1.30000000e+00, -2.00000000e-01,
       -2.00000000e+00, -2.00000000e-01,  2.00000000e-01,  7.00000000e-01,
       -3.00000000e+00, -6.00000000e-01,  4.00000000e-01, -2.10000000e+00,
       -1.80000000e+00, -2.00000000e-01,  2.60000000e+00,  2.00000000e-01,
        1.40000000e+00, -4.00000000e-01,  7.00000000e-01, -2.00000000e-01,
        5.00000000e-01,  8.00000000e-01, -5.00000000e-01,  3.00000000e+00,
       -1.10000000e+00, -4.00000000e-01,  1.00000000e-01,  3.70000000e+00,
       -6.00000000e-01,  9.00000000e-01, -4.00000000e-01,  3.00000000e-01,
       -2.00000000e-01, -8.00000000e-01,  1.70000000e+00, -2.70000000e+00,
        1.40000000e+00,  7.00000000e-01, -4.00000000e-01,  1.20000000e+00,
        8.00000000e-01,  2.00000000e-01,  3.00000000e+00,  1.60000000e+00,
        6.21724894e-14,  6.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        2.00000000e-01, -1.00000000e-01,  1.10000000e+00, -5.00000000e-01,
        4.00000000e-01,  2.20000000e+00,  1.90000000e+00,  2.10000000e+00,
        2.20000000e+00,  1.80000000e+00,  3.00000000e-01, -1.70000000e+00,
        2.40000000e+00, -4.70000000e+00,  1.20000000e+00, -5.00000000e-01,
       -1.30000000e+00,  2.50000000e+00, -2.00000000e-01,  1.50000000e+00,
        9.00000000e-01,  3.00000000e-01, -3.30000000e+00,  2.00000000e-01,
       -1.00000000e-01,  5.00000000e-01,  2.40000000e+00,  1.80000000e+00,
        1.00000000e+00,  1.00000000e-01,  2.70000000e+00,  2.60000000e+00,
       -2.30000000e+00,  1.40000000e+00, -8.00000000e-01,  2.30926389e-14,
        3.00000000e-01, -1.40000000e+00,  6.00000000e-01,  1.90000000e+00,
       -2.00000000e-01,  4.00000000e-01,  1.95399252e-14,  1.50000000e+00,
       -4.00000000e-01, -1.50000000e+00,  1.40000000e+00, -4.00000000e-01,
        1.10000000e+00,  8.00000000e-01,  7.00000000e-01,  1.59872116e-14,
       -1.20000000e+00, -3.00000000e-01, -1.80000000e+00, -1.00000000e-01,
        3.00000000e-01,  3.00000000e-01,  8.00000000e-01])

In [432]:
from sklearn.metrics import r2_score, mean_absolute_error

In [433]:
# Make predictions on test data
y_pred = lr_model.predict(x_test)

# Calculate metrics
r2 = r2_score(y_test, y_pred)
mean= mean_absolute_error(y_test, y_pred)

print(f"R² Score: {r2:.4f}")
print(f"Mean Absolute Error: {mae:.4f}")

R² Score: 1.0000
Mean Absolute Error: 0.0000

In [434]:
print(r2)
print(mean)

1.0
2.2558182711976726e-14

# Logistic Regression

In [435]:
df.head()

,Unnamed: 0,T,T_a,Ff,N,Nh,Cl,Po,U,Ch,...,RRR,DD_,diff,abs_diff,T_kal,T_sher,T_sar,three_mean,diff_3,abs_diff_3
11,0.000000,0.817181,0.826087,0.333333,1.000000,0.75,0.777778,0.520576,0.296296,4,...,1.000000,0.75,-0.6,0.061856,0.749495,0.832200,0.852883,0.826840,0.641766,0.018182
15,0.001555,0.883260,0.869565,0.333333,1.000000,0.25,0.777778,0.395062,0.111111,4,...,0.933333,0.75,0.4,0.041237,0.816162,0.922902,0.860835,0.882395,0.663837,0.015584
39,0.003110,0.753304,0.760870,0.166667,0.888889,0.60,0.000000,0.440329,0.925926,7,...,0.600000,0.25,-0.5,0.051546,0.703030,0.820862,0.711730,0.755411,0.662139,0.012987
47,0.004666,0.544053,0.565217,0.500000,1.000000,0.75,0.666667,0.432099,0.629630,4,...,0.733333,0.50,-1.0,0.103093,0.498990,0.603175,0.590457,0.569264,0.616299,0.057143
59,0.006221,0.376652,0.434783,0.000000,1.000000,0.00,0.777778,0.604938,0.629630,4,...,0.933333,0.00,-2.6,0.268041,0.286869,0.374150,0.399602,0.351371,0.741935,0.135065

In [436]:
df['Ch'].nunique()

8

In [437]:
x=df.drop('Ch',axis=1)

In [438]:
y=df['Ch']

In [439]:
# Check y values
print("Unique values in y:")
print(y.unique())
print(f"\nNumber of unique classes: {y.nunique()}")
print(f"y dtype: {y.dtype}")

Unique values in y:
[4 7 1 2 5 0 3 6]

Number of unique classes: 8
y dtype: int64

In [440]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [441]:
from sklearn.linear_model import LogisticRegression

In [442]:
log_model = LogisticRegression()

In [443]:
log_model.fit(x_train, y_train)
print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!

/Users/a1/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [444]:
log_model

LogisticRegression()

In [445]:
y_pred=log_model.predict(x_test)

In [447]:
from sklearn.metrics import accuracy_score

In [449]:
score=accuracy_score(y_test,y_pred)

In [450]:
print(score)

0.7906976744186046