ENCODING 
ONE-HOT,
LABEL USULLARINI MASHQ QILISH

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('netflix_titles.csv')

In [4]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

Birinchi tushib qolgan qiymalarni to'ldirib chiqamiz

In [5]:
# directorda 2634ta qiymat tushib qolibdi va bu strda ekan 
df['director']=df['director'].fillna(df['director'].mode()[0])

In [24]:
# director cast  country  date_added  rating  duration qiymat tushib qolgan bularni hammasi categorical bo'lgani uchun mode usulidan foydalandim

df['director']=df['director'].fillna(df['director'].mode()[0])

df['cast']=df['cast'].fillna(df['cast'].mode()[0])

df['country']=df['country'].fillna(df['country'].mode()[0])

df['date_added']=df['date_added'].fillna(df['date_added'].mode()[0])

df['rating']=df['rating'].fillna(df['rating'].mode()[0])

df['duration']=df['duration'].fillna(df['duration'].mode()[0])

Tushib qolgan qiymatlar to'ldirildi

In [7]:
df.nunique()

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

ENCODING

Encodingdan oldingi holati

In [8]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,David Attenborough,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Rajiv Chilaka,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Rajiv Chilaka,David Attenborough,United States,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Rajiv Chilaka,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Bu encodingdan keyini holati

In [23]:
df.head()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,ustun_Movie,ustun_TV Show
0,0,1975,2295,1699,603,1711,2020,7,210,274,2577,1,0
1,1111,1091,3392,409,426,1706,2021,11,110,414,1762,0,1
2,2222,2651,2105,6296,603,1706,2021,11,0,242,7341,0,1
3,3333,3506,3392,1699,603,1706,2021,11,0,297,3617,0,1
4,4444,3861,3392,4815,251,1706,2021,11,110,393,4416,0,1

Bu yerda release_year mana shu ustundan tashqari hammasi categorical

one-hot usuliga TYPE ustuni tushishi mumkin ekan qoganlari juda ko'p klaslar bo'gani uchun

In [9]:
dummies=pd.get_dummies(df['type'],prefix='ustun',dtype=int)

In [10]:
dummies

      ustun_Movie  ustun_TV Show
0               1              0
1               0              1
2               0              1
3               0              1
4               0              1
...           ...            ...
8802            1              0
8803            0              1
8804            1              0
8805            1              0
8806            1              0

[8807 rows x 2 columns]

In [11]:
df=pd.concat([df.drop(columns=['type']),dummies],axis=1)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   show_id        8807 non-null   str
 1   title          8807 non-null   str
 2   director       8807 non-null   str
 3   cast           8807 non-null   str
 4   country        8807 non-null   str
 5   date_added     8807 non-null   str
 6   release_year   8807 non-null   int64
 7   rating         8807 non-null   str
 8   duration       8807 non-null   str
 9   listed_in      8807 non-null   str
 10  description    8807 non-null   str
 11  ustun_Movie    8807 non-null   int64
 12  ustun_TV Show  8807 non-null   int64
dtypes: int64(3), str(10)
memory usage: 894.6 KB

Endi LABEL usulidan foydalanib qolgan ustunlarni numericalga o'tkazamiz

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
encoder=LabelEncoder

In [15]:
encoder

sklearn.preprocessing._label.LabelEncoder

In [20]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df['show_id'] = encoder.fit_transform(df['show_id'])
df['title'] = encoder.fit_transform(df['title'])
df['director'] = encoder.fit_transform(df['director'])
df['cast']=encoder.fit_transform(df['cast'])
df['country']=encoder.fit_transform(df['country'])
df['date_added']=encoder.fit_transform(df['date_added'])
df['rating']=encoder.fit_transform(df['rating'])
df['duration']=encoder.fit_transform(df['duration'])
df['listed_in']=encoder.fit_transform(df['listed_in'])
df['description']=encoder.fit_transform(df['description'])

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   show_id        8807 non-null   int64
 1   title          8807 non-null   int64
 2   director       8807 non-null   int64
 3   cast           8807 non-null   int64
 4   country        8807 non-null   int64
 5   date_added     8807 non-null   int64
 6   release_year   8807 non-null   int64
 7   rating         8807 non-null   int64
 8   duration       8807 non-null   int64
 9   listed_in      8807 non-null   int64
 10  description    8807 non-null   int64
 11  ustun_Movie    8807 non-null   int64
 12  ustun_TV Show  8807 non-null   int64
dtypes: int64(13)
memory usage: 894.6 KB

In [22]:
df.head()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,ustun_Movie,ustun_TV Show
0,0,1975,2295,1699,603,1711,2020,7,210,274,2577,1,0
1,1111,1091,3392,409,426,1706,2021,11,110,414,1762,0,1
2,2222,2651,2105,6296,603,1706,2021,11,0,242,7341,0,1
3,3333,3506,3392,1699,603,1706,2021,11,0,297,3617,0,1
4,4444,3861,3392,4815,251,1706,2021,11,110,393,4416,0,1

Datadagi tushib qolgan qiymatlar to'ldirildi va hammasi numerical qiymatlarga aylantirildi