# Data Prperocessing + function

In [313]:
import pandas as pd 
df=pd.read_csv('student_mental_health_burnout.csv')

In [314]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   student_id               150000 non-null  int64
 1   age                      149999 non-null  float64
 2   gender                   149999 non-null  str
 3   course                   124897 non-null  str
 4   year                     112378 non-null  str
 5   daily_study_hours        148358 non-null  float64
 6   daily_sleep_hours        149999 non-null  float64
 7   screen_time_hours        148566 non-null  float64
 8   stress_level             149998 non-null  str
 9   anxiety_score            150000 non-null  int64
 10  depression_score         150000 non-null  int64
 11  academic_pressure_score  149999 non-null  float64
 12  financial_stress_score   150000 non-null  int64
 13  social_support_score     149999 non-null  float64
 14  physical_activity_hours  135008 non-null  float64
 15  sleep_quality            149998 non-null  str
 16  attendance_percentage    150000 non-null  float64
 17  cgpa                     149996 non-null  float64
 18  internet_quality         149999 non-null  str
 19  burnout_level            150000 non-null  str
dtypes: float64(9), int64(4), str(7)
memory usage: 22.9 MB

In [315]:
df.drop('student_id',axis=1,inplace=True)

In [316]:
df.isnull().sum()

age                            1
gender                         1
course                     25103
year                       37622
daily_study_hours           1642
daily_sleep_hours              1
screen_time_hours           1434
stress_level                   2
anxiety_score                  0
depression_score               0
academic_pressure_score        1
financial_stress_score         0
social_support_score           1
physical_activity_hours    14992
sleep_quality                  2
attendance_percentage          0
cgpa                           4
internet_quality               1
burnout_level                  0
dtype: int64

# Missing value + function

In [317]:
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype== 'str':
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return df

In [318]:
toldir(df)

,age,gender,course,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,sleep_quality,attendance_percentage,cgpa,internet_quality,burnout_level
0,23.0,Male,BTech,1st,4.300000,6.8,6.1,High,10,3,4.0,2,6.0,1.8,Average,66.5,9.63,Good,High
1,20.0,Male,BTech,3rd,5.553334,4.7,3.0,High,2,10,8.0,5,9.0,1.9,Poor,55.8,6.04,Poor,Low
2,24.0,Female,BCA,1st,3.700000,4.8,1.5,Low,2,7,8.0,6,3.0,0.8,Good,85.0,8.31,Good,High
3,21.0,Male,BSc,1st,1.600000,6.7,7.0,High,3,3,4.0,9,9.0,0.7,Poor,89.1,5.95,Good,High
4,23.0,Other,BSc,1st,2.000000,6.7,5.4,High,7,7,6.0,4,4.0,1.7,Good,58.7,8.51,Good,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,24.0,Female,BSc,3rd,1.600000,8.2,11.3,Medium,9,9,5.0,3,10.0,2.0,Good,54.2,7.82,Good,Low
149996,25.0,Male,BCA,3rd,9.900000,4.8,1.6,High,10,3,10.0,10,2.0,0.1,Poor,53.6,7.19,Average,High
149997,22.0,Male,BTech,1st,5.553334,4.4,4.6,High,10,8,6.0,4,7.0,1.6,Good,90.7,9.78,Average,High
149998,19.0,Male,BSc,3rd,1.500000,4.3,1.1,Medium,8,6,5.0,7,4.0,1.1,Average,83.9,9.88,Average,Medium
149999,20.0,Male,MCA,3rd,3.700000,6.6,2.6,Medium,5,1,5.0,7,6.0,1.8,Good,89.8,7.00,Poor,High

In [319]:
df.isnull().sum()

age                        0
gender                     0
course                     0
year                       0
daily_study_hours          0
daily_sleep_hours          0
screen_time_hours          0
stress_level               0
anxiety_score              0
depression_score           0
academic_pressure_score    0
financial_stress_score     0
social_support_score       0
physical_activity_hours    0
sleep_quality              0
attendance_percentage      0
cgpa                       0
internet_quality           0
burnout_level              0
dtype: int64

# Encoding

In [320]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 19 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      150000 non-null  float64
 1   gender                   150000 non-null  str
 2   course                   150000 non-null  str
 3   year                     150000 non-null  str
 4   daily_study_hours        150000 non-null  float64
 5   daily_sleep_hours        150000 non-null  float64
 6   screen_time_hours        150000 non-null  float64
 7   stress_level             150000 non-null  str
 8   anxiety_score            150000 non-null  int64
 9   depression_score         150000 non-null  int64
 10  academic_pressure_score  150000 non-null  float64
 11  financial_stress_score   150000 non-null  int64
 12  social_support_score     150000 non-null  float64
 13  physical_activity_hours  150000 non-null  float64
 14  sleep_quality            150000 non-null  str
 15  attendance_percentage    150000 non-null  float64
 16  cgpa                     150000 non-null  float64
 17  internet_quality         150000 non-null  str
 18  burnout_level            150000 non-null  str
dtypes: float64(9), int64(3), str(7)
memory usage: 21.7 MB

In [321]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

# Encoding + Function

In [322]:
def raqamliga(df):
    for col in df.columns:
        if df[col].dtype=='str':
            df[col]=encoder.fit_transform(df[col])
    return(df)

In [323]:
raqamliga(df)

,age,gender,course,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,sleep_quality,attendance_percentage,cgpa,internet_quality,burnout_level
0,23.0,1,2,0,4.300000,6.8,6.1,0,10,3,4.0,2,6.0,1.8,0,66.5,9.63,1,0
1,20.0,1,2,2,5.553334,4.7,3.0,0,2,10,8.0,5,9.0,1.9,2,55.8,6.04,2,1
2,24.0,0,0,0,3.700000,4.8,1.5,1,2,7,8.0,6,3.0,0.8,1,85.0,8.31,1,0
3,21.0,1,1,0,1.600000,6.7,7.0,0,3,3,4.0,9,9.0,0.7,2,89.1,5.95,1,0
4,23.0,2,1,0,2.000000,6.7,5.4,0,7,7,6.0,4,4.0,1.7,1,58.7,8.51,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,24.0,0,1,2,1.600000,8.2,11.3,2,9,9,5.0,3,10.0,2.0,1,54.2,7.82,1,1
149996,25.0,1,0,2,9.900000,4.8,1.6,0,10,3,10.0,10,2.0,0.1,2,53.6,7.19,0,0
149997,22.0,1,2,0,5.553334,4.4,4.6,0,10,8,6.0,4,7.0,1.6,1,90.7,9.78,0,0
149998,19.0,1,1,2,1.500000,4.3,1.1,2,8,6,5.0,7,4.0,1.1,0,83.9,9.88,0,2
149999,20.0,1,4,2,3.700000,6.6,2.6,2,5,1,5.0,7,6.0,1.8,1,89.8,7.00,2,0

In [324]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 19 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      150000 non-null  float64
 1   gender                   150000 non-null  int64
 2   course                   150000 non-null  int64
 3   year                     150000 non-null  int64
 4   daily_study_hours        150000 non-null  float64
 5   daily_sleep_hours        150000 non-null  float64
 6   screen_time_hours        150000 non-null  float64
 7   stress_level             150000 non-null  int64
 8   anxiety_score            150000 non-null  int64
 9   depression_score         150000 non-null  int64
 10  academic_pressure_score  150000 non-null  float64
 11  financial_stress_score   150000 non-null  int64
 12  social_support_score     150000 non-null  float64
 13  physical_activity_hours  150000 non-null  float64
 14  sleep_quality            150000 non-null  int64
 15  attendance_percentage    150000 non-null  float64
 16  cgpa                     150000 non-null  float64
 17  internet_quality         150000 non-null  int64
 18  burnout_level            150000 non-null  int64
dtypes: float64(9), int64(10)
memory usage: 21.7 MB

# Scaling

In [325]:
df.head()

,age,gender,course,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,sleep_quality,attendance_percentage,cgpa,internet_quality,burnout_level
0,23.0,1,2,0,4.300000,6.8,6.1,0,10,3,4.0,2,6.0,1.8,0,66.5,9.63,1,0
1,20.0,1,2,2,5.553334,4.7,3.0,0,2,10,8.0,5,9.0,1.9,2,55.8,6.04,2,1
2,24.0,0,0,0,3.700000,4.8,1.5,1,2,7,8.0,6,3.0,0.8,1,85.0,8.31,1,0
3,21.0,1,1,0,1.600000,6.7,7.0,0,3,3,4.0,9,9.0,0.7,2,89.1,5.95,1,0
4,23.0,2,1,0,2.000000,6.7,5.4,0,7,7,6.0,4,4.0,1.7,1,58.7,8.51,1,1

In [326]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
scaler=MinMaxScaler()

# Scalimg + function

In [327]:
def scaling_qil(df):
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop('cgpa')
    for col in num_col:
        df[col]=scaler.fit_transform(df[[col]])
    return df

In [328]:
scaling_qil(df)

,age,gender,course,year,daily_study_hours,daily_sleep_hours,screen_time_hours,stress_level,anxiety_score,depression_score,academic_pressure_score,financial_stress_score,social_support_score,physical_activity_hours,sleep_quality,attendance_percentage,cgpa,internet_quality,burnout_level
0,0.750,0.5,0.50,0.0,0.366667,0.56,0.463636,0.0,1.000000,0.222222,0.333333,0.111111,0.555556,0.90,0.0,0.647368,9.63,0.5,0.0
1,0.375,0.5,0.50,1.0,0.505926,0.14,0.181818,0.0,0.111111,1.000000,0.777778,0.444444,0.888889,0.95,1.0,0.534737,6.04,1.0,0.5
2,0.875,0.0,0.00,0.0,0.300000,0.16,0.045455,0.5,0.111111,0.666667,0.777778,0.555556,0.222222,0.40,0.5,0.842105,8.31,0.5,0.0
3,0.500,0.5,0.25,0.0,0.066667,0.54,0.545455,0.0,0.222222,0.222222,0.333333,0.888889,0.888889,0.35,1.0,0.885263,5.95,0.5,0.0
4,0.750,1.0,0.25,0.0,0.111111,0.54,0.400000,0.0,0.666667,0.666667,0.555556,0.333333,0.333333,0.85,0.5,0.565263,8.51,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,0.875,0.0,0.25,1.0,0.066667,0.84,0.936364,1.0,0.888889,0.888889,0.444444,0.222222,1.000000,1.00,0.5,0.517895,7.82,0.5,0.5
149996,1.000,0.5,0.00,1.0,0.988889,0.16,0.054545,0.0,1.000000,0.222222,1.000000,1.000000,0.111111,0.05,1.0,0.511579,7.19,0.0,0.0
149997,0.625,0.5,0.50,0.0,0.505926,0.08,0.327273,0.0,1.000000,0.777778,0.555556,0.333333,0.666667,0.80,0.5,0.902105,9.78,0.0,0.0
149998,0.250,0.5,0.25,1.0,0.055556,0.06,0.009091,1.0,0.777778,0.555556,0.444444,0.666667,0.333333,0.55,0.0,0.830526,9.88,0.0,1.0
149999,0.375,0.5,1.00,1.0,0.300000,0.52,0.145455,1.0,0.444444,0.000000,0.444444,0.666667,0.555556,0.90,0.5,0.892632,7.00,1.0,0.0

# Model Training

In [329]:
x=df.drop('burnout_level',axis=1)

In [330]:
y=df['burnout_level'].astype(int)

In [331]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [333]:
x_train.shape

(120000, 18)

In [334]:
x_test.shape

(30000, 18)

In [335]:
y_train.shape

(120000,)

In [336]:
y_test.shape

(30000,)

In [337]:
from sklearn.linear_model import LogisticRegression

In [338]:
log_reg=LogisticRegression()

In [339]:
log_reg

LogisticRegression()

In [340]:
log_reg.fit(x_train,y_train)

LogisticRegression()

In [341]:
y_pred=log_reg.predict(x_test)

In [342]:
from sklearn.metrics import accuracy_score

In [343]:
score=accuracy_score(y_test,y_pred)

In [312]:
print('Modelning aniqlik darajasi:',score) # bu hamma structurelarni ishlatgan holatidagi natija

Modelning aniqlik darajasi: 0.6690222222222222

In [ ]:
print('Modelning aniqlik darajasi:',score) # bu splitda 20% testga berganimdagi natija

Modelning aniqlik darajasi: 0.6681666666666667