# Data yuklash

In [128]:
import pandas as pd
df=pd.read_csv("Social_media_impact_on_life.csv")

In [129]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    1704 non-null   float64
 1   Age                           1705 non-null   int64
 2   Gender                        1703 non-null   str
 3   Academic_Level                1704 non-null   str
 4   Country                       1704 non-null   str
 5   Avg_Daily_Usage_Hours         1705 non-null   float64
 6   Most_Used_Platform            1705 non-null   str
 7   Affects_Academic_Performance  1704 non-null   str
 8   Sleep_Hours_Per_Night         1705 non-null   float64
 9   Mental_Health_Score           1705 non-null   float64
 10  Overall_Impact                1705 non-null   str
dtypes: float64(4), int64(1), str(6)
memory usage: 146.7 KB

# Data preprocessing

In [130]:
df.isnull().sum()

Student_ID                      1
Age                             0
Gender                          2
Academic_Level                  1
Country                         1
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    1
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Overall_Impact                  0
dtype: int64

In [131]:
# Missing
def toldir(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=="str":
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return df

In [132]:
df=toldir(df)

In [133]:
df.isna().any()

Student_ID                      False
Age                             False
Gender                          False
Academic_Level                  False
Country                         False
Avg_Daily_Usage_Hours           False
Most_Used_Platform              False
Affects_Academic_Performance    False
Sleep_Hours_Per_Night           False
Mental_Health_Score             False
Overall_Impact                  False
dtype: bool

In [134]:
# Encoding
df.nunique()

Student_ID                      1001
Age                                7
Gender                             2
Academic_Level                     3
Country                          111
Avg_Daily_Usage_Hours             71
Most_Used_Platform                12
Affects_Academic_Performance       2
Sleep_Hours_Per_Night             59
Mental_Health_Score               51
Overall_Impact                     3
dtype: int64

In [135]:
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=="str":
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [136]:
df=encodla(df)

In [137]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 17 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Student_ID                        1705 non-null   float64
 1   Age                               1705 non-null   int64
 2   Country                           1705 non-null   int64
 3   Avg_Daily_Usage_Hours             1705 non-null   float64
 4   Most_Used_Platform                1705 non-null   int64
 5   Sleep_Hours_Per_Night             1705 non-null   float64
 6   Mental_Health_Score               1705 non-null   float64
 7   Gender_Female                     1705 non-null   int64
 8   Gender_Male                       1705 non-null   int64
 9   Academic_Level_Graduate           1705 non-null   int64
 10  Academic_Level_High School        1705 non-null   int64
 11  Academic_Level_Undergraduate      1705 non-null   int64
 12  Affects_Academic_Performance_No   1705 non-null   int64
 13  Affects_Academic_Performance_Yes  1705 non-null   int64
 14  Overall_Impact_Negative           1705 non-null   int64
 15  Overall_Impact_Neutral            1705 non-null   int64
 16  Overall_Impact_Positive           1705 non-null   int64
dtypes: float64(4), int64(13)
memory usage: 226.6 KB

In [138]:
df.head()

,Student_ID,Age,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score,Gender_Female,Gender_Male,Academic_Level_Graduate,Academic_Level_High School,Academic_Level_Undergraduate,Affects_Academic_Performance_No,Affects_Academic_Performance_Yes,Overall_Impact_Negative,Overall_Impact_Neutral,Overall_Impact_Positive
0,232.000000,21,73,4.0,0,6.7,6.8,0,1,0,0,1,1,0,0,1,0
1,564.000000,23,73,1.6,4,8.6,7.6,1,0,0,0,1,1,0,0,0,1
2,788.000000,22,18,4.6,1,6.7,7.0,0,1,1,0,0,1,0,0,1,0
3,686.000000,18,73,7.0,5,5.4,5.3,0,1,0,0,1,0,1,1,0,0
4,439.411385,24,73,7.5,0,5.0,4.4,0,1,0,1,0,0,1,1,0,0

In [139]:
df.tail()

,Student_ID,Age,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score,Gender_Female,Gender_Male,Academic_Level_Graduate,Academic_Level_High School,Academic_Level_Undergraduate,Affects_Academic_Performance_No,Affects_Academic_Performance_Yes,Overall_Impact_Negative,Overall_Impact_Neutral,Overall_Impact_Positive
1700,701.0,20,44,4.7,6,7.2,7.0,1,0,0,0,1,1,0,0,0,1
1701,702.0,23,83,6.8,1,5.9,4.0,0,1,1,0,0,0,1,1,0,0
1702,703.0,21,20,5.6,9,6.7,6.0,1,0,0,0,1,0,1,1,0,0
1703,704.0,24,46,4.3,7,7.5,8.0,0,1,1,0,0,1,0,0,0,1
1704,705.0,19,79,6.2,0,6.3,5.0,1,0,0,0,1,0,1,1,0,0

In [140]:
# Scaling
from sklearn.preprocessing import MinMaxScaler
def scalqil(df):
    scaler=MinMaxScaler()
    num_col=df.select_dtypes(include=['int64','float64']).columns.drop("Affects_Academic_Performance_Yes")
    df[num_col]=scaler.fit_transform(df[num_col])
    return df

In [141]:
df=scalqil(df)

In [142]:
df.head()

,Student_ID,Age,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Sleep_Hours_Per_Night,Mental_Health_Score,Gender_Female,Gender_Male,Academic_Level_Graduate,Academic_Level_High School,Academic_Level_Undergraduate,Affects_Academic_Performance_No,Affects_Academic_Performance_Yes,Overall_Impact_Negative,Overall_Impact_Neutral,Overall_Impact_Positive
0,0.231231,0.500000,0.663636,0.357143,0.000000,0.500000,0.56,0.0,1.0,0.0,0.0,1.0,1.0,0,0.0,1.0,0.0
1,0.563564,0.833333,0.663636,0.014286,0.363636,0.827586,0.72,1.0,0.0,0.0,0.0,1.0,1.0,0,0.0,0.0,1.0
2,0.787788,0.666667,0.163636,0.442857,0.090909,0.500000,0.60,0.0,1.0,1.0,0.0,0.0,1.0,0,0.0,1.0,0.0
3,0.685686,0.000000,0.663636,0.785714,0.454545,0.275862,0.26,0.0,1.0,0.0,0.0,1.0,0.0,1,1.0,0.0,0.0
4,0.438850,1.000000,0.663636,0.857143,0.000000,0.206897,0.08,0.0,1.0,0.0,1.0,0.0,0.0,1,1.0,0.0,0.0

# Training

In [143]:
x=df.drop(columns=['Affects_Academic_Performance_Yes','Affects_Academic_Performance_No'])
y=df['Affects_Academic_Performance_Yes']

In [144]:
# LogisticRegression uchun
#y=df['Affects_Academic_Performance_Yes']
#x=df.drop(columns=['Affects_Academic_Performance_Yes','Affects_Academic_Performance_No']) #'Affects_Academic_Performance_No' buni drop qilyapmiz chunki target value bilan o'xshashligi uchun
# Biz scaling qilayotgan ochilgan sun'iy ustunlarni ham drop qilib yuborsak bo'ladimi? 2 ta ustun bir xil ma'no berayotgani uchun
# Misol: Gender_Female va Gender_Male holatida Gender_Female -> 0 holatida Gender_Male ekanligini bildirmaydimi?
#x=df.drop('Affects_Academic_Performance_Yes',axis=1)

# Eski usulda o`zimiz topish orqali

In [145]:
from sklearn.model_selection import train_test_split

In [146]:
# x_train,x_test=x
# y_train,y_test=y
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42
    )

In [147]:
# Model(algorithm chaqirish)
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()

In [148]:
log_reg

LogisticRegression()

In [149]:
log_reg.fit(x_train,y_train)

LogisticRegression()

In [150]:
# Predict qilish (modelning natijasini taxmin qilish)
y_pred=log_reg.predict(x_test)

In [151]:
# Metricslar orqali baholash (Evaluation)
from sklearn.metrics import accuracy_score

In [152]:
accuracy=accuracy_score(y_test,y_pred)

In [153]:
print(accuracy)

0.8123167155425219

In [154]:
# K-Fold cross validation
from sklearn.model_selection import KFold, cross_val_score

In [155]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [156]:
kf

KFold(n_splits=5, random_state=42, shuffle=True)

In [157]:
scores=cross_val_score(log_reg,x,y,cv=kf,scoring='accuracy')

In [158]:
print(scores)

[0.81231672 0.84457478 0.82111437 0.81818182 0.82404692]

In [159]:
for i in scores:
    print(i)

0.8123167155425219
0.844574780058651
0.8211143695014663
0.8181818181818182
0.8240469208211144

In [160]:
import numpy as np

In [161]:
np.mean(scores) # accuracy -> 0.8123167155425219

np.float64(0.8240469208211143)

In [162]:
np.std(scores)

np.float64(0.010972602307254973)