# Data bilan Ishlash

In [2]:
import pandas as pd

In [3]:
#1. install pandas

In [4]:
pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sunnatabdurayimov/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/sunnatabdurayimov/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
%pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sunnatabdurayimov/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/sunnatabdurayimov/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
!pip install pandas

zsh:1: command not found: pip

In [7]:
df=pd.read_csv("Restaurant - Customers (1).csv")

In [13]:
#1. df.head
df.head(5)

   ID First Name Last Name  Gender  Company                     Occupation
0   1     Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
1   2   Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
2   3      Roger     Black    Male  Tagfeed              Account Executive
3   4     Steven     Evans    Male     Fatz               Registered Nurse
4   5       Judy  Morrison  Female  Demivee                Legal Assistant

In [14]:
df.tail(5)

,ID,First Name,Last Name,Gender,Company,Occupation
995,996,Debra,Garcia,Female,Dazzlesphere,Structural Engineer
996,997,Douglas,Bishop,Male,Livepath,Developer I
997,998,Frank,Franklin,Male,Brainverse,Nurse Practicioner
998,999,Jessica,Burns,Female,Babbleblab,Financial Advisor
999,1000,Brian,Daniels,Male,Tazzy,Physical Therapy Assistant

In [ ]:
df.nunique() #har bir ustundagi classlar soni

ID            1000
First Name     198
Last Name      248
Gender           2
Company        353
Occupation     181
dtype: int64

In [19]:
df['Gender']

0        Male
1      Female
2        Male
3        Male
4      Female
        ...
995    Female
996      Male
997      Male
998    Female
999      Male
Name: Gender, Length: 1000, dtype: str

In [20]:
df['Company'].nunique()

353

In [21]:
df[['First Name','Last Name']]

    First Name Last Name
0       Joseph   Perkins
1     Jennifer   Alvarez
2        Roger     Black
3       Steven     Evans
4         Judy  Morrison
..         ...       ...
995      Debra    Garcia
996    Douglas    Bishop
997      Frank  Franklin
998    Jessica     Burns
999      Brian   Daniels

[1000 rows x 2 columns]

In [ ]:
df.info() #data haqida umumiy malumot olish

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          1000 non-null   int64
 1   First Name  1000 non-null   str
 2   Last Name   1000 non-null   str
 3   Gender      1000 non-null   str
 4   Company     1000 non-null   str
 5   Occupation  1000 non-null   str
dtypes: int64(1), str(5)
memory usage: 47.0 KB

In [23]:
df.isnull().sum()

ID            0
First Name    0
Last Name     0
Gender        0
Company       0
Occupation    0
dtype: int64

In [24]:
df.isnull()

        ID  First Name  Last Name  Gender  Company  Occupation
0    False       False      False   False    False       False
1    False       False      False   False    False       False
2    False       False      False   False    False       False
3    False       False      False   False    False       False
4    False       False      False   False    False       False
..     ...         ...        ...     ...      ...         ...
995  False       False      False   False    False       False
996  False       False      False   False    False       False
997  False       False      False   False    False       False
998  False       False      False   False    False       False
999  False       False      False   False    False       False

[1000 rows x 6 columns]

In [25]:
df.isnull().any()

ID            False
First Name    False
Last Name     False
Gender        False
Company       False
Occupation    False
dtype: bool

# Conditions

In [26]:
#agar son musbat bo'lsa yaxshi aks holda yomon degan so'zni ekranga chiqaring

In [36]:
a=-6
if a>0:
    print('Yaxshi')
elif a<0:
    print('Yomon')

Yomon

In [40]:
baho=5
if baho==5:
   print('Alo')
elif baho==4:
   print('Yaxshi')
elif baho==3:
   print('urtacha')
elif baho==2:
   print('Yomon')
else:
   print('Xatolik bor yoki juda yomon')

Alo

# Vazifalar

In [57]:
ball=94
if 85>=ball>=70:
   print("O'rtacha")
elif 95>=ball>=85:
   print('Yaxshi')
elif 100>= ball>=95:
   print("A'lo")
elif ball<=69:
   print('Imtihondan yiqildiz,qayta topshirish')
else:
   print('Xatolik bor')

Yaxshi

In [44]:
age=30
if age>=18:
   print('Pasport olsa boladi')
else:
   print('Xatolik bor yoki yosh kichik')

Pasport olsa boladi