In [1]:
import pandas as pd
df = pd.read_csv('data.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2017 non-null   int64
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   int64
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   int64
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   int64
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   int64
 15  song_title        2017 non-null   object
 16  artist            2017 non-null   object
dtypes: float64(10), int64(5), object(2)
memory usage: 268.0+ KB

In [3]:
df.drop('song_title',axis=1, inplace=True)
df.drop('artist',axis=1, inplace=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2017 non-null   int64
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   int64
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   int64
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   int64
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   int64
dtypes: float64(10), int64(5)
memory usage: 236.5 KB

In [8]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()

In [9]:
encoder

LabelEncoder()

In [12]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression() 

lr

LinearRegression()

In [13]:
from sklearn.tree import DecisionTreeClassifier , DecisionTreeRegressor

In [14]:
from sklearn.ensemble import RandomForestRegressor , RandomForestClassifier

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2017 non-null   int64
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   int64
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   int64
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   int64
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   int64
dtypes: float64(10), int64(5)
memory usage: 236.5 KB

In [16]:
df.dropna(inplace=True)

In [17]:
df.head()

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target
0,0,0.0102,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1
1,1,0.1990,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1
2,2,0.0344,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1
3,3,0.6040,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1
4,4,0.1800,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [19]:
for col in df.columns:
    df[col]=scaler.fit_transform(df[[col]])

In [ ]:
df.head()

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target
0,0.000000,0.010248,0.824826,0.190735,0.426363,0.022439,0.181818,0.153862,0.741141,1.0,0.514441,0.596033,0.75,0.262432,1.0
1,0.000496,0.199998,0.720418,0.314481,0.350081,0.006260,0.090909,0.124395,0.692162,1.0,0.071005,0.654474,0.75,0.577936,1.0
2,0.000992,0.034570,0.830626,0.171624,0.403987,0.000240,0.181818,0.147548,0.791369,1.0,0.335351,0.158539,0.75,0.144379,1.0
3,0.001488,0.607034,0.431555,0.185488,0.328723,0.522541,0.454545,0.077247,0.544709,1.0,0.003784,0.225162,0.75,0.203928,1.0
4,0.001984,0.180902,0.645012,0.381202,0.555533,0.524590,0.454545,0.442223,0.654132,0.0,0.058393,0.735659,0.75,0.908065,1.0

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2017 non-null   float64
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   float64
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   float64
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   float64
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   float64
dtypes: float64(15)
memory usage: 236.5 KB

In [22]:
num_col=df.select_dtypes(include=['float64']).columns

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2017 non-null   float64
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   float64
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   float64
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   float64
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   float64
dtypes: float64(15)
memory usage: 236.5 KB

In [24]:
x = df.drop('liveness', axis=1)

In [26]:
x

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,loudness,mode,speechiness,tempo,time_signature,valence,target
0,0.000000,0.010248,0.824826,0.190735,0.426363,0.022439,0.181818,0.741141,1.0,0.514441,0.596033,0.75,0.262432,1.0
1,0.000496,0.199998,0.720418,0.314481,0.350081,0.006260,0.090909,0.692162,1.0,0.071005,0.654474,0.75,0.577936,1.0
2,0.000992,0.034570,0.830626,0.171624,0.403987,0.000240,0.181818,0.791369,1.0,0.335351,0.158539,0.75,0.144379,1.0
3,0.001488,0.607034,0.431555,0.185488,0.328723,0.522541,0.454545,0.544709,1.0,0.003784,0.225162,0.75,0.203928,1.0
4,0.001984,0.180902,0.645012,0.381202,0.555533,0.524590,0.454545,0.654132,0.0,0.058393,0.735659,0.75,0.908065,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,0.998016,0.001062,0.535963,0.261345,0.932872,0.002756,0.090909,0.902592,1.0,0.390844,0.158142,0.75,0.184079,0.0
2013,0.998512,0.088138,0.895592,0.168058,0.892189,0.001711,0.090909,0.928149,1.0,0.136083,0.362636,0.75,0.869411,0.0
2014,0.999008,0.008610,0.597448,0.193365,0.935924,0.004088,0.000000,0.934126,1.0,0.105814,0.596150,0.75,0.454659,0.0
2015,0.999504,0.001645,0.504640,0.171516,0.993897,0.693648,0.090909,0.925953,1.0,0.138605,0.595736,0.75,0.614501,0.0
2016,1.000000,0.002821,0.375870,0.190654,0.915582,0.000040,0.818182,0.819640,1.0,0.148695,0.829022,0.75,0.383619,0.0

In [30]:
y = df['liveness'].astype(int)

In [28]:
from sklearn.model_selection import train_test_split

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42)

In [32]:
x_train

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,loudness,mode,speechiness,tempo,time_signature,valence,target
701,0.347718,0.019394,0.729698,0.198044,0.882018,0.000000,0.090909,0.838426,1.0,0.074158,0.537954,0.75,0.650021,1.0
1164,0.577381,0.075374,0.665893,0.202681,0.815907,0.000000,0.090909,0.891583,1.0,0.108336,0.292788,0.75,0.777476,0.0
1357,0.673115,0.219093,0.305104,0.219176,0.395850,0.000002,0.727273,0.795913,1.0,0.007441,0.573091,0.75,0.037087,0.0
1170,0.580357,0.239194,0.740139,0.163396,0.293124,0.000008,0.181818,0.662855,1.0,0.006684,0.304026,0.75,0.127664,0.0
1740,0.863095,0.008027,0.653132,0.195753,0.871847,0.000000,0.636364,0.797743,1.0,0.011351,0.362666,0.75,0.805683,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,0.560516,0.004017,0.305104,0.214770,0.865745,0.000000,0.363636,0.923452,0.0,0.058772,0.747381,0.75,0.536147,0.0
1294,0.641865,0.157787,0.103248,0.239659,0.645037,0.000000,0.000000,0.787344,1.0,0.020431,0.596313,0.75,0.265566,0.0
860,0.426587,0.519597,0.660093,0.434141,0.711147,0.016803,0.090909,0.713724,1.0,0.028881,0.251855,0.75,0.966569,1.0
1459,0.723710,0.158792,0.592807,0.141537,0.965419,0.016291,0.181818,0.900396,1.0,0.008450,0.444172,0.75,0.079607,0.0
1126,0.558532,0.052761,0.762181,0.152296,0.655207,0.000000,0.000000,0.843001,1.0,0.072771,0.274937,0.75,0.928959,0.0

In [33]:
x_test.shape

(606, 14)

In [34]:
y_train.shape

(1411,)

In [36]:
y_test.shape

(606,)

In [37]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()

In [38]:
log_reg

LogisticRegression()

In [39]:
log_reg.fit(x_train, y_train)

LogisticRegression()

In [40]:
y_pred=log_reg.predict(x_test)

In [41]:
y_pred[1:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

# Evaluation

In [42]:
from sklearn.metrics import accuracy_score

In [43]:
score= accuracy_score(y_test, y_pred)

In [44]:
print('Modelning aniqlik darajasi: ', score)

Modelning aniqlik darajasi:  1.0

In [45]:
print('Modelning aniqlik darajasi: ', score)

Modelning aniqlik darajasi:  1.0

In [46]:
print('Modelning aniqlik darajasi: ', score)

Modelning aniqlik darajasi:  1.0