# Data bilan tanishuv

In [168]:
import pandas as pd 
df=pd.read_csv('Premier_League_Player_Statistics_2023-24_20260207_050947.csv')

In [169]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Player                     52 non-null     str
 1   Team                       52 non-null     str
 2   Position                   52 non-null     str
 3   Position_Group             52 non-null     str
 4   Appearances                52 non-null     int64
 5   Minutes                    52 non-null     int64
 6   Minutes_Per_Appearance     52 non-null     int64
 7   Goals                      52 non-null     int64
 8   Assists                    52 non-null     int64
 9   Goal_Contributions         52 non-null     int64
 10  Goals_Per_90               52 non-null     float64
 11  Assists_Per_90             52 non-null     float64
 12  Goal_Contributions_Per_90  52 non-null     float64
 13  Minutes_Per_Goal           52 non-null     int64
 14  Minutes_Per_Assist         52 non-null     int64
 15  Yellow_Cards               52 non-null     int64
 16  Red_Cards                  52 non-null     int64
 17  Discipline_Score           52 non-null     int64
 18  Clean_Sheets               52 non-null     int64
 19  Clean_Sheet_Percentage     52 non-null     float64
 20  Goals_Rank                 52 non-null     int64
 21  Assists_Rank               52 non-null     int64
 22  Goal_Contributions_Rank    52 non-null     int64
 23  Clean_Sheets_Rank          52 non-null     int64
 24  Efficiency_Rank            52 non-null     int64
 25  Performance_Category       52 non-null     str
 26  Discipline_Category        52 non-null     str
 27  Efficiency_Rating          52 non-null     float64
 28  Season                     52 non-null     str
 29  Competition                52 non-null     str
 30  Country                    52 non-null     str
 31  League_Name                52 non-null     str
 32  League_Level               52 non-null     int64
 33  Data_Collection_Date       52 non-null     str
dtypes: float64(5), int64(18), str(11)
memory usage: 13.9 KB

In [170]:
df.sample(5)

,Player,Team,Position,Position_Group,Appearances,Minutes,Minutes_Per_Appearance,Goals,Assists,Goal_Contributions,...,Efficiency_Rank,Performance_Category,Discipline_Category,Efficiency_Rating,Season,Competition,Country,League_Name,League_Level,Data_Collection_Date
48,Pedro Neto,Wolves,Forward,FWD,20,1380,69,2,9,11,...,26,Excellent (10-14),Excellent,1.15,2023/24,Premier League,England,English Premier League,1,2026-02-07
8,Dominic Solanke,Bournemouth,Forward,FWD,38,3250,86,19,3,22,...,13,Elite (15-24),Good,1.58,2023/24,Premier League,England,English Premier League,1,2026-02-07
6,Bukayo Saka,Arsenal,Forward,FWD,35,2980,85,16,9,25,...,10,World Class (25+),Good,1.83,2023/24,Premier League,England,English Premier League,1,2026-02-07
1,Cole Palmer,Chelsea,Midfielder,MID,33,2880,87,22,11,33,...,2,World Class (25+),Good,2.61,2023/24,Premier League,England,English Premier League,1,2026-02-07
4,Mohamed Salah,Liverpool,Forward,FWD,32,2750,86,18,10,28,...,4,World Class (25+),Excellent,2.28,2023/24,Premier League,England,English Premier League,1,2026-02-07

In [171]:
df.isnull().sum()

Player                       0
Team                         0
Position                     0
Position_Group               0
Appearances                  0
Minutes                      0
Minutes_Per_Appearance       0
Goals                        0
Assists                      0
Goal_Contributions           0
Goals_Per_90                 0
Assists_Per_90               0
Goal_Contributions_Per_90    0
Minutes_Per_Goal             0
Minutes_Per_Assist           0
Yellow_Cards                 0
Red_Cards                    0
Discipline_Score             0
Clean_Sheets                 0
Clean_Sheet_Percentage       0
Goals_Rank                   0
Assists_Rank                 0
Goal_Contributions_Rank      0
Clean_Sheets_Rank            0
Efficiency_Rank              0
Performance_Category         0
Discipline_Category          0
Efficiency_Rating            0
Season                       0
Competition                  0
Country                      0
League_Name                  0
League_Level                 0
Data_Collection_Date         0
dtype: int64

# Drop

In [172]:
df = df.drop(['Player', 'Team', 'Position', 'Position_Group', 'Data_Collection_Date'], axis=1)

In [173]:
df.sample(5)

,Appearances,Minutes,Minutes_Per_Appearance,Goals,Assists,Goal_Contributions,Goals_Per_90,Assists_Per_90,Goal_Contributions_Per_90,Minutes_Per_Goal,...,Clean_Sheets_Rank,Efficiency_Rank,Performance_Category,Discipline_Category,Efficiency_Rating,Season,Competition,Country,League_Name,League_Level
17,36,3240,90,3,2,5,0.08,0.06,0.14,1080,...,4,40,Good (5-9),Excellent,0.76,2023/24,Premier League,England,English Premier League,1
12,35,2950,84,8,10,18,0.24,0.31,0.55,369,...,12,25,Elite (15-24),Good,1.20,2023/24,Premier League,England,English Premier League,1
25,37,3250,88,7,8,15,0.19,0.22,0.42,464,...,12,34,Elite (15-24),Fair,0.91,2023/24,Premier League,England,English Premier League,1
45,34,2230,66,14,0,14,0.57,0.00,0.57,159,...,12,24,Excellent (10-14),Excellent,1.21,2023/24,Premier League,England,English Premier League,1
13,28,2100,75,4,9,13,0.17,0.39,0.56,525,...,12,31,Excellent (10-14),Excellent,1.02,2023/24,Premier League,England,English Premier League,1

# Data preprocessing

In [174]:
df.isnull().sum()

Appearances                  0
Minutes                      0
Minutes_Per_Appearance       0
Goals                        0
Assists                      0
Goal_Contributions           0
Goals_Per_90                 0
Assists_Per_90               0
Goal_Contributions_Per_90    0
Minutes_Per_Goal             0
Minutes_Per_Assist           0
Yellow_Cards                 0
Red_Cards                    0
Discipline_Score             0
Clean_Sheets                 0
Clean_Sheet_Percentage       0
Goals_Rank                   0
Assists_Rank                 0
Goal_Contributions_Rank      0
Clean_Sheets_Rank            0
Efficiency_Rank              0
Performance_Category         0
Discipline_Category          0
Efficiency_Rating            0
Season                       0
Competition                  0
Country                      0
League_Name                  0
League_Level                 0
dtype: int64

# Encoding

In [175]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Appearances                52 non-null     int64
 1   Minutes                    52 non-null     int64
 2   Minutes_Per_Appearance     52 non-null     int64
 3   Goals                      52 non-null     int64
 4   Assists                    52 non-null     int64
 5   Goal_Contributions         52 non-null     int64
 6   Goals_Per_90               52 non-null     float64
 7   Assists_Per_90             52 non-null     float64
 8   Goal_Contributions_Per_90  52 non-null     float64
 9   Minutes_Per_Goal           52 non-null     int64
 10  Minutes_Per_Assist         52 non-null     int64
 11  Yellow_Cards               52 non-null     int64
 12  Red_Cards                  52 non-null     int64
 13  Discipline_Score           52 non-null     int64
 14  Clean_Sheets               52 non-null     int64
 15  Clean_Sheet_Percentage     52 non-null     float64
 16  Goals_Rank                 52 non-null     int64
 17  Assists_Rank               52 non-null     int64
 18  Goal_Contributions_Rank    52 non-null     int64
 19  Clean_Sheets_Rank          52 non-null     int64
 20  Efficiency_Rank            52 non-null     int64
 21  Performance_Category       52 non-null     str
 22  Discipline_Category        52 non-null     str
 23  Efficiency_Rating          52 non-null     float64
 24  Season                     52 non-null     str
 25  Competition                52 non-null     str
 26  Country                    52 non-null     str
 27  League_Name                52 non-null     str
 28  League_Level               52 non-null     int64
dtypes: float64(5), int64(18), str(6)
memory usage: 11.9 KB

In [176]:
from sklearn.preprocessing import LabelEncoder

In [177]:
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [178]:
df=encodla(df)

In [179]:
df.sample(5)

,Appearances,Minutes,Minutes_Per_Appearance,Goals,Assists,Goal_Contributions,Goals_Per_90,Assists_Per_90,Goal_Contributions_Per_90,Minutes_Per_Goal,...,Clean_Sheets_Rank,Efficiency_Rank,Performance_Category,Discipline_Category,Efficiency_Rating,League_Level,Season_2023/24,Competition_Premier League,Country_England,League_Name_English Premier League
34,35,2920,83,17,10,27,0.52,0.31,0.83,172,...,12,8,4,0,2.00,1,1,1,1,1
28,36,2420,67,11,8,19,0.41,0.30,0.71,220,...,12,22,1,2,1.29,1,1,1,1,1
41,37,2900,78,7,11,18,0.22,0.34,0.56,414,...,12,30,1,2,1.09,1,1,1,1,1
21,28,2520,90,0,1,1,0.00,0.04,0.04,2520,...,8,44,0,3,0.54,1,1,1,1,1
13,28,2100,75,4,9,13,0.17,0.39,0.56,525,...,12,31,2,0,1.02,1,1,1,1,1

In [180]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Appearances                         52 non-null     int64
 1   Minutes                             52 non-null     int64
 2   Minutes_Per_Appearance              52 non-null     int64
 3   Goals                               52 non-null     int64
 4   Assists                             52 non-null     int64
 5   Goal_Contributions                  52 non-null     int64
 6   Goals_Per_90                        52 non-null     float64
 7   Assists_Per_90                      52 non-null     float64
 8   Goal_Contributions_Per_90           52 non-null     float64
 9   Minutes_Per_Goal                    52 non-null     int64
 10  Minutes_Per_Assist                  52 non-null     int64
 11  Yellow_Cards                        52 non-null     int64
 12  Red_Cards                           52 non-null     int64
 13  Discipline_Score                    52 non-null     int64
 14  Clean_Sheets                        52 non-null     int64
 15  Clean_Sheet_Percentage              52 non-null     float64
 16  Goals_Rank                          52 non-null     int64
 17  Assists_Rank                        52 non-null     int64
 18  Goal_Contributions_Rank             52 non-null     int64
 19  Clean_Sheets_Rank                   52 non-null     int64
 20  Efficiency_Rank                     52 non-null     int64
 21  Performance_Category                52 non-null     int64
 22  Discipline_Category                 52 non-null     int64
 23  Efficiency_Rating                   52 non-null     float64
 24  League_Level                        52 non-null     int64
 25  Season_2023/24                      52 non-null     int64
 26  Competition_Premier League          52 non-null     int64
 27  Country_England                     52 non-null     int64
 28  League_Name_English Premier League  52 non-null     int64
dtypes: float64(5), int64(24)
memory usage: 11.9 KB

# Scaling

In [181]:
from sklearn.preprocessing import MinMaxScaler

In [182]:
def scaling_qil(df):
    scaler=MinMaxScaler()
    num_col = df.select_dtypes(include=['int64','float64']).columns.drop('Goals')
    df[num_col]=scaler.fit_transform(df[num_col]) 
    return df

In [183]:
df=scaling_qil(df)
df.sample(4)

,Appearances,Minutes,Minutes_Per_Appearance,Goals,Assists,Goal_Contributions,Goals_Per_90,Assists_Per_90,Goal_Contributions_Per_90,Minutes_Per_Goal,...,Clean_Sheets_Rank,Efficiency_Rank,Performance_Category,Discipline_Category,Efficiency_Rating,League_Level,Season_2023/24,Competition_Premier League,Country_England,League_Name_English Premier League
41,0.972222,0.839506,0.666667,7,0.846154,0.545455,0.234043,0.523077,0.500000,0.095668,...,1.0,0.568627,0.25,0.5,0.387755,0.0,0.0,0.0,0.0,0.0
6,0.916667,0.864198,0.861111,16,0.692308,0.757576,0.510638,0.415385,0.678571,0.027076,...,1.0,0.176471,1.00,0.5,0.639456,0.0,0.0,0.0,0.0,0.0
27,0.972222,0.836420,0.666667,13,0.538462,0.606061,0.425532,0.338462,0.553571,0.037906,...,1.0,0.392157,0.25,0.5,0.486395,0.0,0.0,0.0,0.0,0.0
49,0.777778,0.546296,0.305556,12,0.153846,0.424242,0.585106,0.138462,0.580357,0.019856,...,1.0,0.431373,0.50,0.0,0.452381,0.0,0.0,0.0,0.0,0.0

# Training

In [184]:
X=df.drop('Goals',axis=1)

In [185]:
y=df['Goals']

In [186]:
from sklearn.model_selection import train_test_split

In [187]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [188]:
X_train.shape

(41, 28)

In [189]:
X_test.shape

(11, 28)

In [190]:
y_train.shape

(41,)

In [191]:
y_test.shape

(11,)

In [192]:
from sklearn.linear_model import LogisticRegression 
from sklearn.linear_model import LinearRegression

In [193]:
logr = LogisticRegression()
logr.fit(X_train, y_train)

LogisticRegression()

In [194]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

# Prediction

In [195]:
y_predection=lr.predict(X_test)
y_predection

array([ 1.,  7.,  8.,  8., 12., 19.,  3.,  3., 19., 10.,  4.])

In [196]:
y_pred=lr.predict(X_test)
y_pred

array([ 1.,  7.,  8.,  8., 12., 19.,  3.,  3., 19., 10.,  4.])

# Evaluation

In [197]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [198]:
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=pow(mse,(1/2))
mae=mean_absolute_error(y_test,y_pred)

In [199]:
print(r2)
print(mse)
print(rmse)
print(mae)

1.0
8.291465973580939e-28
2.8794905753589366e-14
2.5636058932253614e-14