In [3]:
import pandas as pd
df=pd.read_csv('fullGas.csv')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40494 entries, 0 to 40493
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Make                          40494 non-null  int32
 1   Model                         40494 non-null  int32
 2   Body                          40494 non-null  int32
 3   Mileage_km                    40494 non-null  int64
 4   Price                         40494 non-null  int64
 5   Year                          38799 non-null  float64
 6   Country                       40494 non-null  int32
 7   Fuel_Type                     40494 non-null  int32
 8   Fuel_Consumption_l            12773 non-null  float64
 9   Gears                         25115 non-null  float64
 10  Power_hp                      40494 non-null  int64
 11  Engine_Size_cc                34564 non-null  float64
 12  Cylinders                     30332 non-null  float64
 13  Seats                         38697 non-null  float64
 14  Doors                         39517 non-null  float64
 15  Color                         40494 non-null  int32
 16  Upholstery                    40494 non-null  int32
 17  Full_Service_History          40494 non-null  bool
 18  Non_Smoker_Vehicle            40494 non-null  bool
 19  Previous_Owners               22271 non-null  float64
 20  Image_url                     40494 non-null  int32
 21  Condition_New                 40494 non-null  int32
 22  Condition_Used                40494 non-null  int32
 23  Drivetrain_4WD                40494 non-null  int32
 24  Drivetrain_Front Wheel Drive  40494 non-null  int32
 25  Drivetrain_Rear Wheel Drive   40494 non-null  int32
 26  Gearbox_Automatic             40494 non-null  int32
 27  Gearbox_Manual                40494 non-null  int32
 28  Gearbox_Semi-automatic        40494 non-null  int32
 29  Seller_Dealer                 40494 non-null  int32
 30  Seller_PrivateSeller          40494 non-null  int32
dtypes: bool(2), float64(8), int32(18), int64(3)
memory usage: 6.3 MB

In [10]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object':
            df[col].fillna(df[col].mode()[0],inplace=True)
        else:
            df[col].fillna(df[col].mean(),inplace=True)

C:\Users\윈도우10\AppData\Local\Temp\ipykernel_3080\2187856909.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(),inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40494 entries, 0 to 40493
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Make                          40494 non-null  int32
 1   Model                         40494 non-null  int32
 2   Body                          40494 non-null  int32
 3   Mileage_km                    40494 non-null  int64
 4   Price                         40494 non-null  int64
 5   Year                          40494 non-null  float64
 6   Country                       40494 non-null  int32
 7   Fuel_Type                     40494 non-null  int32
 8   Fuel_Consumption_l            40494 non-null  float64
 9   Gears                         40494 non-null  float64
 10  Power_hp                      40494 non-null  int64
 11  Engine_Size_cc                40494 non-null  float64
 12  Cylinders                     40494 non-null  float64
 13  Seats                         40494 non-null  float64
 14  Doors                         40494 non-null  float64
 15  Color                         40494 non-null  int32
 16  Upholstery                    40494 non-null  int32
 17  Full_Service_History          40494 non-null  bool
 18  Non_Smoker_Vehicle            40494 non-null  bool
 19  Previous_Owners               40494 non-null  float64
 20  Image_url                     40494 non-null  int32
 21  Condition_New                 40494 non-null  int32
 22  Condition_Used                40494 non-null  int32
 23  Drivetrain_4WD                40494 non-null  int32
 24  Drivetrain_Front Wheel Drive  40494 non-null  int32
 25  Drivetrain_Rear Wheel Drive   40494 non-null  int32
 26  Gearbox_Automatic             40494 non-null  int32
 27  Gearbox_Manual                40494 non-null  int32
 28  Gearbox_Semi-automatic        40494 non-null  int32
 29  Seller_Dealer                 40494 non-null  int32
 30  Seller_PrivateSeller          40494 non-null  int32
dtypes: bool(2), float64(8), int32(18), int64(3)
memory usage: 6.3 MB

In [12]:
df.isnull().sum()

Make                            0
Model                           0
Body                            0
Mileage_km                      0
Price                           0
Year                            0
Country                         0
Fuel_Type                       0
Fuel_Consumption_l              0
Gears                           0
Power_hp                        0
Engine_Size_cc                  0
Cylinders                       0
Seats                           0
Doors                           0
Color                           0
Upholstery                      0
Full_Service_History            0
Non_Smoker_Vehicle              0
Previous_Owners                 0
Image_url                       0
Condition_New                   0
Condition_Used                  0
Drivetrain_4WD                  0
Drivetrain_Front Wheel Drive    0
Drivetrain_Rear Wheel Drive     0
Gearbox_Automatic               0
Gearbox_Manual                  0
Gearbox_Semi-automatic          0
Seller_Dealer                   0
Seller_PrivateSeller            0
dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
encoder = LabelEncoder()

In [15]:
for col in df.columns:
    if df[col].dtype=='object':
        if df[col].nunique()<=5:
            dummies=pd.get_dummies(df[col], prefix=col, dtype=int)
            df=pd.concat([df.drop(columns=col), dummies], axis=1)

        else:
            df[col]=encoder.fit_transform(df[col])

In [16]:
df.head()

,Make,Model,Body,Mileage_km,Price,Year,Country,Fuel_Type,Fuel_Consumption_l,Gears,...,Condition_New,Condition_Used,Drivetrain_4WD,Drivetrain_Front Wheel Drive,Drivetrain_Rear Wheel Drive,Gearbox_Automatic,Gearbox_Manual,Gearbox_Semi-automatic,Seller_Dealer,Seller_PrivateSeller
0,0,124,0,98000,16900,2020.0,5,6,6.700000,5.899024,...,0,1,0,1,0,1,0,0,1,0
1,0,124,5,91500,12500,2017.0,5,6,6.000000,5.000000,...,0,1,0,1,0,0,1,0,1,0
2,0,124,0,40000,17990,2015.0,5,6,6.500000,5.000000,...,0,1,0,1,0,0,1,0,1,0
3,0,100,0,133000,9300,2008.0,5,6,6.500000,5.000000,...,0,1,0,1,0,0,1,0,1,0
4,0,124,0,61019,14990,2021.0,1,6,6.727151,6.000000,...,0,1,0,1,0,0,1,0,1,0

In [17]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [18]:
num_col = df.select_dtypes(include=['int64', 'float64']).columns.drop('Year')

In [19]:
num_col

Index(['Mileage_km', 'Price', 'Fuel_Consumption_l', 'Gears', 'Power_hp',
       'Engine_Size_cc', 'Cylinders', 'Seats', 'Doors', 'Previous_Owners'],
      dtype='object')

In [20]:
scaler=StandardScaler()

In [21]:
df['Mileage_km']=scaler.fit_transform(df[['Mileage_km']])

In [22]:
df.head()

,Make,Model,Body,Mileage_km,Price,Year,Country,Fuel_Type,Fuel_Consumption_l,Gears,...,Condition_New,Condition_Used,Drivetrain_4WD,Drivetrain_Front Wheel Drive,Drivetrain_Rear Wheel Drive,Gearbox_Automatic,Gearbox_Manual,Gearbox_Semi-automatic,Seller_Dealer,Seller_PrivateSeller
0,0,124,0,0.064576,16900,2020.0,5,6,6.700000,5.899024,...,0,1,0,1,0,1,0,0,1,0
1,0,124,5,0.044366,12500,2017.0,5,6,6.000000,5.000000,...,0,1,0,1,0,0,1,0,1,0
2,0,124,0,-0.115757,17990,2015.0,5,6,6.500000,5.000000,...,0,1,0,1,0,0,1,0,1,0
3,0,100,0,0.173398,9300,2008.0,5,6,6.500000,5.000000,...,0,1,0,1,0,0,1,0,1,0
4,0,124,0,-0.050405,14990,2021.0,1,6,6.727151,6.000000,...,0,1,0,1,0,0,1,0,1,0

In [23]:
scaler=MinMaxScaler()

In [24]:
df['Price']=scaler.fit_transform(df[['Price']])

In [25]:
df.head()

,Make,Model,Body,Mileage_km,Price,Year,Country,Fuel_Type,Fuel_Consumption_l,Gears,...,Condition_New,Condition_Used,Drivetrain_4WD,Drivetrain_Front Wheel Drive,Drivetrain_Rear Wheel Drive,Gearbox_Automatic,Gearbox_Manual,Gearbox_Semi-automatic,Seller_Dealer,Seller_PrivateSeller
0,0,124,0,0.064576,0.001690,2020.0,5,6,6.700000,5.899024,...,0,1,0,1,0,1,0,0,1,0
1,0,124,5,0.044366,0.001250,2017.0,5,6,6.000000,5.000000,...,0,1,0,1,0,0,1,0,1,0
2,0,124,0,-0.115757,0.001799,2015.0,5,6,6.500000,5.000000,...,0,1,0,1,0,0,1,0,1,0
3,0,100,0,0.173398,0.000930,2008.0,5,6,6.500000,5.000000,...,0,1,0,1,0,0,1,0,1,0
4,0,124,0,-0.050405,0.001499,2021.0,1,6,6.727151,6.000000,...,0,1,0,1,0,0,1,0,1,0

In [26]:
scaler=RobustScaler()

In [27]:
df['Previous_Owners']=scaler.fit_transform(df[['Previous_Owners']])

In [28]:
df.head()

,Make,Model,Body,Mileage_km,Price,Year,Country,Fuel_Type,Fuel_Consumption_l,Gears,...,Condition_New,Condition_Used,Drivetrain_4WD,Drivetrain_Front Wheel Drive,Drivetrain_Rear Wheel Drive,Gearbox_Automatic,Gearbox_Manual,Gearbox_Semi-automatic,Seller_Dealer,Seller_PrivateSeller
0,0,124,0,0.064576,0.001690,2020.0,5,6,6.700000,5.899024,...,0,1,0,1,0,1,0,0,1,0
1,0,124,5,0.044366,0.001250,2017.0,5,6,6.000000,5.000000,...,0,1,0,1,0,0,1,0,1,0
2,0,124,0,-0.115757,0.001799,2015.0,5,6,6.500000,5.000000,...,0,1,0,1,0,0,1,0,1,0
3,0,100,0,0.173398,0.000930,2008.0,5,6,6.500000,5.000000,...,0,1,0,1,0,0,1,0,1,0
4,0,124,0,-0.050405,0.001499,2021.0,1,6,6.727151,6.000000,...,0,1,0,1,0,0,1,0,1,0

In [29]:
scaler=MinMaxScaler()
for col in df.columns:
    if df[col].dtype != 'object':
        df[col]=scaler.fit_transform(df[[col]])

In [30]:
df.head()

,Make,Model,Body,Mileage_km,Price,Year,Country,Fuel_Type,Fuel_Consumption_l,Gears,...,Condition_New,Condition_Used,Drivetrain_4WD,Drivetrain_Front Wheel Drive,Drivetrain_Rear Wheel Drive,Gearbox_Automatic,Gearbox_Manual,Gearbox_Semi-automatic,Seller_Dealer,Seller_PrivateSeller
0,0.0,0.098726,0.000000,0.005841,0.001690,0.942308,0.625,0.6,0.120219,0.085493,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,0.098726,0.555556,0.005454,0.001250,0.913462,0.625,0.6,0.107468,0.072464,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,0.098726,0.000000,0.002384,0.001799,0.894231,0.625,0.6,0.116576,0.072464,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.079618,0.000000,0.007927,0.000930,0.826923,0.625,0.6,0.116576,0.072464,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,0.098726,0.000000,0.003637,0.001499,0.951923,0.125,0.6,0.120713,0.086957,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [31]:
num_col=df.select_dtypes(include=['int64', 'float64']).columns.drop('Full_Service_History')

In [32]:
num_col

Index(['Make', 'Model', 'Body', 'Mileage_km', 'Price', 'Year', 'Country',
       'Fuel_Type', 'Fuel_Consumption_l', 'Gears', 'Power_hp',
       'Engine_Size_cc', 'Cylinders', 'Seats', 'Doors', 'Color', 'Upholstery',
       'Non_Smoker_Vehicle', 'Previous_Owners', 'Image_url', 'Condition_New',
       'Condition_Used', 'Drivetrain_4WD', 'Drivetrain_Front Wheel Drive',
       'Drivetrain_Rear Wheel Drive', 'Gearbox_Automatic', 'Gearbox_Manual',
       'Gearbox_Semi-automatic', 'Seller_Dealer', 'Seller_PrivateSeller'],
      dtype='object')

In [33]:
num_col=df.select_dtypes(include=['int64', 'float64']).columns.drop('Full_Service_History')
for col in num_col:
    df[col]=scaler.fit_transform(df[[col]])

In [34]:
df.head()

,Make,Model,Body,Mileage_km,Price,Year,Country,Fuel_Type,Fuel_Consumption_l,Gears,...,Condition_New,Condition_Used,Drivetrain_4WD,Drivetrain_Front Wheel Drive,Drivetrain_Rear Wheel Drive,Gearbox_Automatic,Gearbox_Manual,Gearbox_Semi-automatic,Seller_Dealer,Seller_PrivateSeller
0,0.0,0.098726,0.000000,0.005841,0.001690,0.942308,0.625,0.6,0.120219,0.085493,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,0.098726,0.555556,0.005454,0.001250,0.913462,0.625,0.6,0.107468,0.072464,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,0.098726,0.000000,0.002384,0.001799,0.894231,0.625,0.6,0.116576,0.072464,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.079618,0.000000,0.007927,0.000930,0.826923,0.625,0.6,0.116576,0.072464,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,0.098726,0.000000,0.003637,0.001499,0.951923,0.125,0.6,0.120713,0.086957,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40494 entries, 0 to 40493
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Make                          40494 non-null  float64
 1   Model                         40494 non-null  float64
 2   Body                          40494 non-null  float64
 3   Mileage_km                    40494 non-null  float64
 4   Price                         40494 non-null  float64
 5   Year                          40494 non-null  float64
 6   Country                       40494 non-null  float64
 7   Fuel_Type                     40494 non-null  float64
 8   Fuel_Consumption_l            40494 non-null  float64
 9   Gears                         40494 non-null  float64
 10  Power_hp                      40494 non-null  float64
 11  Engine_Size_cc                40494 non-null  float64
 12  Cylinders                     40494 non-null  float64
 13  Seats                         40494 non-null  float64
 14  Doors                         40494 non-null  float64
 15  Color                         40494 non-null  float64
 16  Upholstery                    40494 non-null  float64
 17  Full_Service_History          40494 non-null  float64
 18  Non_Smoker_Vehicle            40494 non-null  float64
 19  Previous_Owners               40494 non-null  float64
 20  Image_url                     40494 non-null  float64
 21  Condition_New                 40494 non-null  float64
 22  Condition_Used                40494 non-null  float64
 23  Drivetrain_4WD                40494 non-null  float64
 24  Drivetrain_Front Wheel Drive  40494 non-null  float64
 25  Drivetrain_Rear Wheel Drive   40494 non-null  float64
 26  Gearbox_Automatic             40494 non-null  float64
 27  Gearbox_Manual                40494 non-null  float64
 28  Gearbox_Semi-automatic        40494 non-null  float64
 29  Seller_Dealer                 40494 non-null  float64
 30  Seller_PrivateSeller          40494 non-null  float64
dtypes: float64(31)
memory usage: 9.6 MB