# Foundation oyligi uchun  oxirgi yakuniy loyiha

# Linear Regression

In [39]:
import pandas as pd

In [40]:
df=pd.read_csv('autos.csv')

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  str
 2   name                 371528 non-null  str
 3   seller               371528 non-null  str
 4   offerType            371528 non-null  str
 5   price                371528 non-null  int64
 6   abtest               371528 non-null  str
 7   vehicleType          333659 non-null  str
 8   yearOfRegistration   371528 non-null  int64
 9   gearbox              351319 non-null  str
 10  powerPS              371528 non-null  int64
 11  model                351044 non-null  str
 12  kilometer            371528 non-null  int64
 13  monthOfRegistration  371528 non-null  int64
 14  fuelType             338142 non-null  str
 15  brand                371528 non-null  str
 16  notRepairedDamage    299468 non-null  str
 17  dateCreated          371528 non-null  str
 18  nrOfPictures         371528 non-null  int64
 19  postalCode           371528 non-null  int64
 20  lastSeen             371528 non-null  str
dtypes: int64(8), str(13)
memory usage: 59.5 MB

In [42]:
# index          → shunchaki ID (foydasiz)
# dateCrawled    → e’lon qachon yig‘ib olingan
# name           → e’lon sarlavhasi (text, ko‘p noise)
# seller         → sotuvchi turi (private/dealer)
# offerType      → e’lon turi (deyarli o‘zgarmaydi)
# price          → mashina narxi 💰
# abtest         → A/B test guruhi (keraksiz)
# vehicleType    → sedan, suv, hatchback
# yearOfRegistration  → ishlab chiqarilgan/yoki ro‘yxatdan o‘tgan yil
# gearbox        → manual yoki automatic
# powerPS        → ot kuchi (engine power)
# model          → mashina modeli
# kilometer      → yurgan masofa
# monthOfRegistration  → oy
# fuelType       → benzin, diesel va h.k.
# brand          → ishlab chiqaruvchi (BMW, Audi...)
# notRepairedDamage  → avariyadan keyin tuzatilganmi
# dateCreated    → e’lon yaratilgan sana
# nrOfPictures   → rasmlar soni (ko‘pincha 0)
# postalCode     → hudud kodi
# lastSeen       → oxirgi ko‘rilgan vaqt

# Data Preprocessing

In [43]:

df.drop(['index'],axis=1,inplace=True)
df.drop(['dateCrawled'],axis=1,inplace=True)
df.drop(['lastSeen'],axis=1,inplace=True)
df.drop(['name'],axis=1,inplace=True)
df.drop(['seller'],axis=1,inplace=True)
df.drop(['offerType'],axis=1,inplace=True)
df.drop(['postalCode'],axis=1,inplace=True)
df.drop(['nrOfPictures'],axis=1,inplace=True)

In [44]:
df.isnull().sum()

price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dateCreated                0
dtype: int64

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   price                371528 non-null  int64
 1   abtest               371528 non-null  str
 2   vehicleType          333659 non-null  str
 3   yearOfRegistration   371528 non-null  int64
 4   gearbox              351319 non-null  str
 5   powerPS              371528 non-null  int64
 6   model                351044 non-null  str
 7   kilometer            371528 non-null  int64
 8   monthOfRegistration  371528 non-null  int64
 9   fuelType             338142 non-null  str
 10  brand                371528 non-null  str
 11  notRepairedDamage    299468 non-null  str
 12  dateCreated          371528 non-null  str
dtypes: int64(5), str(8)
memory usage: 36.8 MB

In [46]:
df.nunique(
    
)

price                  5597
abtest                    2
vehicleType               8
yearOfRegistration      155
gearbox                   2
powerPS                 794
model                   251
kilometer                13
monthOfRegistration      13
fuelType                  7
brand                    40
notRepairedDamage         2
dateCreated             114
dtype: int64

In [47]:
for col in df.columns:
    if df[col].isnull().sum():
         if df[col].dtype == 'str':
              df[col]=df[col].fillna(df[col].mode()[0])

In [48]:
df.isnull().sum()

price                  0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dateCreated            0
dtype: int64

# Encoding

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   price                371528 non-null  int64
 1   abtest               371528 non-null  str
 2   vehicleType          371528 non-null  str
 3   yearOfRegistration   371528 non-null  int64
 4   gearbox              371528 non-null  str
 5   powerPS              371528 non-null  int64
 6   model                371528 non-null  str
 7   kilometer            371528 non-null  int64
 8   monthOfRegistration  371528 non-null  int64
 9   fuelType             371528 non-null  str
 10  brand                371528 non-null  str
 11  notRepairedDamage    371528 non-null  str
 12  dateCreated          371528 non-null  str
dtypes: int64(5), str(8)
memory usage: 36.8 MB

In [50]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

for col in df.columns:
    if df[col].dtype=='str':
        df[col]=encoder.fit_transform(df[col])

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   price                371528 non-null  int64
 1   abtest               371528 non-null  int64
 2   vehicleType          371528 non-null  int64
 3   yearOfRegistration   371528 non-null  int64
 4   gearbox              371528 non-null  int64
 5   powerPS              371528 non-null  int64
 6   model                371528 non-null  int64
 7   kilometer            371528 non-null  int64
 8   monthOfRegistration  371528 non-null  int64
 9   fuelType             371528 non-null  int64
 10  brand                371528 non-null  int64
 11  notRepairedDamage    371528 non-null  int64
 12  dateCreated          371528 non-null  int64
dtypes: int64(13)
memory usage: 36.8 MB

# Scaling

In [52]:
df.head()

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated
0,480,1,6,1993,1,0,118,150000,0,1,38,1,99
1,18300,1,3,2011,1,190,118,125000,5,3,1,0,99
2,9800,1,7,2004,0,163,119,125000,8,3,14,1,89
3,1500,1,4,2001,1,75,118,150000,6,1,38,1,92
4,3600,1,4,2008,1,69,103,90000,7,3,31,1,106

In [54]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [56]:
num_col=df.select_dtypes(include=['int64']).columns.drop('price')
for col in num_col:
    df[num_col]=scaler.fit_transform(df[num_col])

In [57]:
df.head()

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated
0,480,1.0,0.857143,0.110346,1.0,0.00000,0.472,1.000000,0.000000,0.166667,0.974359,1.0,0.876106
1,18300,1.0,0.428571,0.112346,1.0,0.00950,0.472,0.827586,0.416667,0.500000,0.025641,0.0,0.876106
2,9800,1.0,1.000000,0.111568,0.0,0.00815,0.476,0.827586,0.666667,0.500000,0.358974,1.0,0.787611
3,1500,1.0,0.571429,0.111235,1.0,0.00375,0.472,1.000000,0.500000,0.166667,0.974359,1.0,0.814159
4,3600,1.0,0.571429,0.112012,1.0,0.00345,0.412,0.586207,0.583333,0.500000,0.794872,1.0,0.938053

# Model selection

# Linear Regression

In [58]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [59]:
lr

LinearRegression()

In [60]:
x=df.drop('price',axis=1)

In [64]:
y=df['price'].astype(int)

In [65]:
from sklearn.model_selection import train_test_split

In [68]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   price                371528 non-null  int64
 1   abtest               371528 non-null  float64
 2   vehicleType          371528 non-null  float64
 3   yearOfRegistration   371528 non-null  float64
 4   gearbox              371528 non-null  float64
 5   powerPS              371528 non-null  float64
 6   model                371528 non-null  float64
 7   kilometer            371528 non-null  float64
 8   monthOfRegistration  371528 non-null  float64
 9   fuelType             371528 non-null  float64
 10  brand                371528 non-null  float64
 11  notRepairedDamage    371528 non-null  float64
 12  dateCreated          371528 non-null  float64
dtypes: float64(12), int64(1)
memory usage: 36.8 MB

In [70]:
lr.fit(x_train,y_train)

LinearRegression()

In [72]:
y_pred=lr.predict(x_test)

# Evaluation

In [74]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [75]:
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [76]:
print('mae:',mae)
print('mse:',mse)
print('r2:',r2)

mae: 35441.707120317216
mse: 420359536218.9522
r2: -0.005397236091450708