# Foundation oyligi uchun  oxirgi yakuniy loyiha

# Logistic Regression

In [112]:
import pandas as pd

In [113]:
df=pd.read_csv('autos.csv')

In [114]:
df.head()

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21

In [115]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   index                371528 non-null  int64
 1   dateCrawled          371528 non-null  str
 2   name                 371528 non-null  str
 3   seller               371528 non-null  str
 4   offerType            371528 non-null  str
 5   price                371528 non-null  int64
 6   abtest               371528 non-null  str
 7   vehicleType          333659 non-null  str
 8   yearOfRegistration   371528 non-null  int64
 9   gearbox              351319 non-null  str
 10  powerPS              371528 non-null  int64
 11  model                351044 non-null  str
 12  kilometer            371528 non-null  int64
 13  monthOfRegistration  371528 non-null  int64
 14  fuelType             338142 non-null  str
 15  brand                371528 non-null  str
 16  notRepairedDamage    299468 non-null  str
 17  dateCreated          371528 non-null  str
 18  nrOfPictures         371528 non-null  int64
 19  postalCode           371528 non-null  int64
 20  lastSeen             371528 non-null  str
dtypes: int64(8), str(13)
memory usage: 59.5 MB

Bu yerda Logistic Regressionga uchun loyiha qilayotgaimiz uchun qiymatlari chegaralangan ustunni target qilib olishimiz kerk ekan men bu yerda notRepairedDamage mana shu ustunni target qilib oldim

In [116]:
df.drop(['index'],axis=1,inplace=True)
df.drop(['dateCrawled'],axis=1,inplace=True)
df.drop(['dateCreated'],axis=1,inplace=True)
df.drop(['lastSeen'],axis=1,inplace=True)
df.drop(['postalCode'],axis=1,inplace=True)
df.drop(['nrOfPictures'],axis=1,inplace=True)
df.drop(['name'],axis=1,inplace=True)
df.drop(['seller'],axis=1,inplace=True)

In [117]:
df.isnull().sum()

offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dtype: int64

# Data preprocessing

Handling Missing values

In [118]:
df.isnull().sum()

offerType                  0
price                      0
abtest                     0
vehicleType            37869
yearOfRegistration         0
gearbox                20209
powerPS                    0
model                  20484
kilometer                  0
monthOfRegistration        0
fuelType               33386
brand                      0
notRepairedDamage      72060
dtype: int64

In [119]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='str':
            df[col]=df[col].fillna(df[col].mode()[0])

In [120]:
df.isnull().sum()

offerType              0
price                  0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dtype: int64

# Encoding

In [121]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   offerType            371528 non-null  str
 1   price                371528 non-null  int64
 2   abtest               371528 non-null  str
 3   vehicleType          371528 non-null  str
 4   yearOfRegistration   371528 non-null  int64
 5   gearbox              371528 non-null  str
 6   powerPS              371528 non-null  int64
 7   model                371528 non-null  str
 8   kilometer            371528 non-null  int64
 9   monthOfRegistration  371528 non-null  int64
 10  fuelType             371528 non-null  str
 11  brand                371528 non-null  str
 12  notRepairedDamage    371528 non-null  str
dtypes: int64(5), str(8)
memory usage: 36.8 MB

In [122]:
df.nunique()

offerType                 2
price                  5597
abtest                    2
vehicleType               8
yearOfRegistration      155
gearbox                   2
powerPS                 794
model                   251
kilometer                13
monthOfRegistration      13
fuelType                  7
brand                    40
notRepairedDamage         2
dtype: int64

In [123]:

from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in df.columns:
    if df[col].dtype=='str':
        df[col]=encoder.fit_transform(df[col])

In [124]:
df.info(
    
)

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   offerType            371528 non-null  int64
 1   price                371528 non-null  int64
 2   abtest               371528 non-null  int64
 3   vehicleType          371528 non-null  int64
 4   yearOfRegistration   371528 non-null  int64
 5   gearbox              371528 non-null  int64
 6   powerPS              371528 non-null  int64
 7   model                371528 non-null  int64
 8   kilometer            371528 non-null  int64
 9   monthOfRegistration  371528 non-null  int64
 10  fuelType             371528 non-null  int64
 11  brand                371528 non-null  int64
 12  notRepairedDamage    371528 non-null  int64
dtypes: int64(13)
memory usage: 36.8 MB

# Scaling

In [125]:
df.head()

,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,0,480,1,6,1993,1,0,118,150000,0,1,38,1
1,0,18300,1,3,2011,1,190,118,125000,5,3,1,0
2,0,9800,1,7,2004,0,163,119,125000,8,3,14,1
3,0,1500,1,4,2001,1,75,118,150000,6,1,38,1
4,0,3600,1,4,2008,1,69,103,90000,7,3,31,1

In [126]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [127]:
scaler=MinMaxScaler()

In [128]:
num_col=df.select_dtypes(include=['int64']).columns.drop('notRepairedDamage')
for col in num_col:
    df[num_col]=scaler.fit_transform(df[num_col])

In [129]:
df.head()

,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,0.0,2.235174e-07,1.0,0.857143,0.110346,1.0,0.00000,0.472,1.000000,0.000000,0.166667,0.974359,1
1,0.0,8.521602e-06,1.0,0.428571,0.112346,1.0,0.00950,0.472,0.827586,0.416667,0.500000,0.025641,0
2,0.0,4.563481e-06,1.0,1.000000,0.111568,0.0,0.00815,0.476,0.827586,0.666667,0.500000,0.358974,1
3,0.0,6.984919e-07,1.0,0.571429,0.111235,1.0,0.00375,0.472,1.000000,0.500000,0.166667,0.974359,1
4,0.0,1.676381e-06,1.0,0.571429,0.112012,1.0,0.00345,0.412,0.586207,0.583333,0.500000,0.794872,1

# Model selection

# Logistic Regression

In [130]:
from sklearn.linear_model import LogisticRegression

In [131]:
log_reg=LogisticRegression()

In [132]:
log_reg

LogisticRegression()

# Training

In [133]:
x=df.drop('notRepairedDamage',axis=1)

In [134]:
y=df['notRepairedDamage'].astype(int)

In [135]:
from sklearn.model_selection import train_test_split

In [136]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [137]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   offerType            371528 non-null  float64
 1   price                371528 non-null  float64
 2   abtest               371528 non-null  float64
 3   vehicleType          371528 non-null  float64
 4   yearOfRegistration   371528 non-null  float64
 5   gearbox              371528 non-null  float64
 6   powerPS              371528 non-null  float64
 7   model                371528 non-null  float64
 8   kilometer            371528 non-null  float64
 9   monthOfRegistration  371528 non-null  float64
 10  fuelType             371528 non-null  float64
 11  brand                371528 non-null  float64
 12  notRepairedDamage    371528 non-null  int64
dtypes: float64(12), int64(1)
memory usage: 36.8 MB

In [138]:
log_reg.fit(x_train,y_train)

LogisticRegression()

In [139]:
y_pred=log_reg.predict(x_test)

# Evaluation

In [140]:
from sklearn.metrics import accuracy_score

In [141]:
score=accuracy_score(y_test,y_pred)

In [ ]:
print('Modelning aniqlik darajasi:',score)  # drop qilinmagan holatidagi

Modelning aniqlik darajasi: 0.9039108551126424

In [111]:
print('Modelning aniqlik darajasi:',score) # splitda testga 20% bergandagi holat

Modelning aniqlik darajasi: 0.9033187091217398

In [142]:
print('Modelning aniqlik darajasi:',score) # bu hamma structurelar ishlatilayotgan splitda 30% testga bergandagi holat

Modelning aniqlik darajasi: 0.9039108551126424