## **ENSEMBLE METHODS**

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [2]:
df = pd.read_csv("../data/ev_market_2026.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand                  2000 non-null   object
 1   model                  2000 non-null   object
 2   year                   2000 non-null   int64
 3   variant                2000 non-null   object
 4   price_usd              2000 non-null   float64
 5   battery_capacity_kwh   2000 non-null   float64
 6   range_miles            2000 non-null   float64
 7   charging_speed_kw      2000 non-null   float64
 8   acceleration_0_60_mph  2000 non-null   float64
 9   top_speed_mph          2000 non-null   float64
 10  horsepower             2000 non-null   float64
 11  torque_nm              2000 non-null   float64
 12  drive_type             2000 non-null   object
 13  seating_capacity       2000 non-null   int64
 14  body_type              2000 non-null   object
 15  cargo_volume_cubic_ft  2000 non-null   float64
 16  weight_kg              2000 non-null   float64
 17  safety_rating          2000 non-null   int64
 18  autopilot_level        2000 non-null   int64
 19  country_of_origin      2000 non-null   object
 20  market_segment         2000 non-null   object
 21  annual_sales_units     2000 non-null   int64
 22  customer_rating        2000 non-null   float64
 23  warranty_years         2000 non-null   int64
dtypes: float64(11), int64(6), object(7)
memory usage: 375.1+ KB

## **Data Preprocessing**

In [4]:
# Handling missing values

df.isnull().sum()

brand                    0
model                    0
year                     0
variant                  0
price_usd                0
battery_capacity_kwh     0
range_miles              0
charging_speed_kw        0
acceleration_0_60_mph    0
top_speed_mph            0
horsepower               0
torque_nm                0
drive_type               0
seating_capacity         0
body_type                0
cargo_volume_cubic_ft    0
weight_kg                0
safety_rating            0
autopilot_level          0
country_of_origin        0
market_segment           0
annual_sales_units       0
customer_rating          0
warranty_years           0
dtype: int64

In [5]:
# Encoding

def encoding(df):
    for col in df.columns:
        encoder = LabelEncoder()
        if df[col].dtype == "object":
            df[col] = encoder.fit_transform(df[col])
    return df

df = encoding(df)
df

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
0,17,29,2023,2,104880.80,118.7,400.0,234.5,3.04,195.0,...,4,54.2,2015.0,4,2,1,1,202182,4.00,4
1,16,64,2022,3,48217.41,58.8,219.0,148.1,5.77,159.0,...,2,69.0,1709.0,4,0,2,2,7146,3.56,3
2,5,7,2024,3,49651.12,58.2,225.0,104.9,6.84,148.0,...,5,77.0,1533.0,4,1,5,2,16590,3.70,3
3,8,59,2024,1,38131.56,102.5,349.0,66.5,4.66,176.0,...,2,65.8,1935.0,4,2,3,2,127201,3.81,3
4,15,40,2022,1,144079.87,93.9,314.0,298.5,5.64,165.0,...,2,38.3,2229.0,4,2,5,1,196401,3.83,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1,70,2023,1,122665.71,102.1,360.0,92.0,4.21,190.0,...,1,38.3,1500.0,5,2,1,1,66187,3.78,7
1996,16,65,2024,2,66816.55,110.6,367.0,236.3,4.25,181.0,...,1,23.1,1863.0,4,0,2,3,11062,3.79,4
1997,15,40,2025,1,49281.26,90.6,325.0,325.6,5.55,167.0,...,4,74.6,2920.0,3,3,5,2,224804,4.10,6
1998,15,42,2026,3,139665.73,70.7,248.0,330.7,5.07,175.0,...,0,34.8,1500.0,3,2,5,1,165373,3.66,4
1999,2,50,2025,3,47547.88,67.4,246.0,67.2,6.76,156.0,...,0,28.5,1512.0,4,0,0,2,214113,3.41,4

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand                  2000 non-null   int32
 1   model                  2000 non-null   int32
 2   year                   2000 non-null   int64
 3   variant                2000 non-null   int32
 4   price_usd              2000 non-null   float64
 5   battery_capacity_kwh   2000 non-null   float64
 6   range_miles            2000 non-null   float64
 7   charging_speed_kw      2000 non-null   float64
 8   acceleration_0_60_mph  2000 non-null   float64
 9   top_speed_mph          2000 non-null   float64
 10  horsepower             2000 non-null   float64
 11  torque_nm              2000 non-null   float64
 12  drive_type             2000 non-null   int32
 13  seating_capacity       2000 non-null   int64
 14  body_type              2000 non-null   int32
 15  cargo_volume_cubic_ft  2000 non-null   float64
 16  weight_kg              2000 non-null   float64
 17  safety_rating          2000 non-null   int64
 18  autopilot_level        2000 non-null   int64
 19  country_of_origin      2000 non-null   int32
 20  market_segment         2000 non-null   int32
 21  annual_sales_units     2000 non-null   int64
 22  customer_rating        2000 non-null   float64
 23  warranty_years         2000 non-null   int64
dtypes: float64(11), int32(7), int64(6)
memory usage: 320.4 KB

In [7]:
# Scaling 

def scaling(df):
    scaler = MinMaxScaler()
    num_cols = df.select_dtypes(include=["float64", "int32", "int64"]).columns.drop("price_usd")
    df[num_cols] = scaler.fit_transform(df[num_cols])
    return df

df = scaling(df)
df

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
0,0.894737,0.386667,0.500000,0.50,104880.80,0.984981,0.841751,0.615205,0.098182,0.939024,...,0.8,0.603077,0.343333,0.5,0.666667,0.2,0.333333,0.403810,0.662252,0.2
1,0.842105,0.853333,0.333333,0.75,48217.41,0.235294,0.232323,0.327109,0.594545,0.500000,...,0.4,0.830769,0.139333,0.5,0.000000,0.4,0.666667,0.013004,0.370861,0.0
2,0.263158,0.093333,0.666667,0.75,49651.12,0.227785,0.252525,0.183061,0.789091,0.365854,...,1.0,0.953846,0.022000,0.5,0.333333,1.0,0.666667,0.031928,0.463576,0.0
3,0.421053,0.786667,0.666667,0.25,38131.56,0.782228,0.670034,0.055018,0.392727,0.707317,...,0.4,0.781538,0.290000,0.5,0.666667,0.6,0.666667,0.253566,0.536424,0.0
4,0.789474,0.533333,0.333333,0.25,144079.87,0.674593,0.552189,0.828610,0.570909,0.573171,...,0.4,0.358462,0.486000,0.5,0.666667,1.0,0.333333,0.392227,0.549669,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.052632,0.933333,0.500000,0.25,122665.71,0.777222,0.707071,0.140047,0.310909,0.878049,...,0.2,0.358462,0.000000,1.0,0.666667,0.2,0.333333,0.131309,0.516556,0.8
1996,0.842105,0.866667,0.666667,0.50,66816.55,0.883605,0.730640,0.621207,0.318182,0.768293,...,0.2,0.124615,0.242000,0.5,0.000000,0.4,1.000000,0.020851,0.523179,0.2
1997,0.789474,0.533333,0.833333,0.25,49281.26,0.633292,0.589226,0.918973,0.554545,0.597561,...,0.8,0.916923,0.946667,0.0,1.000000,1.0,0.666667,0.449139,0.728477,0.6
1998,0.789474,0.560000,1.000000,0.75,139665.73,0.384230,0.329966,0.935979,0.467273,0.695122,...,0.0,0.304615,0.000000,0.0,0.666667,1.0,0.333333,0.330054,0.437086,0.2
1999,0.105263,0.666667,0.833333,0.75,47547.88,0.342929,0.323232,0.057352,0.774545,0.463415,...,0.0,0.207692,0.008000,0.5,0.000000,0.0,0.666667,0.427717,0.271523,0.2

## **Random Forest Regressor**

In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

x = df.drop("price_usd", axis=1)
y = df["price_usd"]

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

model = RandomForestRegressor()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)


mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(mae)
print(mse)
print(rmse)
print(r2)

4616.38347275
51438235.870871946
7172.045445399237
0.9548846488585874

In [9]:
# K-fold cross validation
from sklearn.model_selection import KFold, cross_val_score

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(model, x,y,cv=kf, scoring="r2")
print(scores.mean())

from sklearn.metrics import make_scorer

mae=make_scorer(mean_absolute_error,greater_is_better=False)
scores=cross_val_score(model,x,y,cv=kf,scoring=mae)
print(-scores)

0.9527104521914834
[4601.07155275 4742.0878015  5343.76312575 4860.403344   4105.04008225]

## **AdaBoostRegressor**

In [10]:
from sklearn.ensemble import AdaBoostRegressor

ada = AdaBoostRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

ada.fit(x_train, y_train)
y_pred = ada.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(mae)
print(mse)
print(rmse)
print(r2)

10931.82909786311
205373976.91737947
14330.874952960112
0.8198709787171615

In [11]:
# K-fold cross validation
from sklearn.model_selection import KFold, cross_val_score

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(ada, x,y,cv=kf, scoring="r2")
print(scores.mean())

from sklearn.metrics import make_scorer

mae=make_scorer(mean_absolute_error,greater_is_better=False)
scores=cross_val_score(ada,x,y,cv=kf,scoring=mae)
print(-scores)

0.8399571761891254
[10958.02342361 10408.87669373 11432.75876908 11303.29171342
  9709.20917594]

## **Gradient Boosting**

In [12]:
from sklearn.ensemble import GradientBoostingRegressor

gb = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,    
    max_depth=3,
    subsample=0.8,        
    random_state=42
)

gb.fit(x_train, y_train)
y_pred = gb.predict(x_test)

ada.fit(x_train, y_train)
y_pred = ada.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(mae)
print(mse)
print(rmse)
print(r2)

10931.82909786311
205373976.91737947
14330.874952960112
0.8198709787171615

In [13]:
# K-fold cross validation
from sklearn.model_selection import KFold, cross_val_score

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(gb, x,y,cv=kf, scoring="r2")
print(scores.mean())

from sklearn.metrics import make_scorer

mae=make_scorer(mean_absolute_error,greater_is_better=False)
scores=cross_val_score(gb,x,y,cv=kf,scoring=mae)
print(-scores)

0.9335876320981363
[6154.72298499 5869.54114385 6151.30431365 6261.29545867 4956.67184649]

## **XGboost**

In [14]:
import xgboost as xgb

xgb_model = xgb.XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,  # features per tree
    reg_alpha=0.1,         # L1 regularization
    reg_lambda=1.0,        # L2 regularization
    random_state=42
)

xgb_model.fit(x_train, y_train)

y_pred = xgb_model.predict(x_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(mae)
print(mse)
print(rmse)
print(r2)

4706.6462769531245
57982540.35970341
7614.626738041951
0.9491447825900176

In [15]:
# K-fold cross validation
from sklearn.model_selection import KFold, cross_val_score

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(xgb_model, x,y,cv=kf, scoring="r2")
print(scores.mean())

from sklearn.metrics import make_scorer

mae=make_scorer(mean_absolute_error,greater_is_better=False)
scores=cross_val_score(xgb_model,x,y,cv=kf,scoring=mae)
print(-scores)

0.9546655741570766
[4396.16662734 4530.92378398 4631.28329785 4600.7834084  3990.73571699]