# Feature Engineeringsiz holatda o'tilgan barcha algoritmlar bilan model yasaymiz

In [408]:
import pandas as pd

In [409]:
df = pd.read_csv('cars_dataset.csv')

In [410]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72435 entries, 0 to 72434
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         72435 non-null  str
 1   year          72435 non-null  int64
 2   price         72435 non-null  int64
 3   transmission  72435 non-null  str
 4   mileage       72435 non-null  int64
 5   fuelType      72435 non-null  str
 6   tax           72435 non-null  float64
 7   mpg           72435 non-null  float64
 8   engineSize    72435 non-null  float64
 9   Make          72435 non-null  str
dtypes: float64(3), int64(3), str(4)
memory usage: 5.5 MB

In [411]:
df.isnull().sum()
# bu holatda bizda bironta ham qiymat tushib qolmagani sabab
# biz Handling Missing Values qismini tashlab ketamiz.

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
Make            0
dtype: int64

In [412]:
df.nunique()

model             146
year               25
price           10418
transmission        4
mileage         35743
fuelType            5
tax                47
mpg               177
engineSize         32
Make                7
dtype: int64

In [413]:
df.head(10)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,Make
0,A1,2017,12500,Manual,15735,Petrol,150.0,55.4,1.4,audi
1,A6,2016,16500,Automatic,36203,Diesel,20.0,64.2,2.0,audi
2,A1,2016,11000,Manual,29946,Petrol,30.0,55.4,1.4,audi
3,A4,2017,16800,Automatic,25952,Diesel,145.0,67.3,2.0,audi
4,A3,2019,17300,Manual,1998,Petrol,145.0,49.6,1.0,audi
5,A1,2016,13900,Automatic,32260,Petrol,30.0,58.9,1.4,audi
6,A6,2016,13250,Automatic,76788,Diesel,30.0,61.4,2.0,audi
7,A4,2016,11750,Manual,75185,Diesel,20.0,70.6,2.0,audi
8,A3,2015,10200,Manual,46112,Petrol,20.0,60.1,1.4,audi
9,A1,2016,12000,Manual,22451,Petrol,30.0,55.4,1.4,audi

# Encoding

In [414]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
class Encoding_Scaling:
    def __init__(self, df):
        self.df = df
    def encodla(self):
        le = LabelEncoder()
        df = self.df

        for col in df.columns:
            if df[col].dtype == 'str':
                if df[col].nunique() <=5:
                    dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                    df = pd.concat([df.drop(columns=col), dummies], axis=1)
                else:
                    df[col] = le.fit_transform(df[col])

        self.df = df
        return df
    def scale_qil(self):
        scaler = MinMaxScaler()
        df = self.df
        num_cols = df.select_dtypes(include=['int64', 'float64']).columns
        for col in num_cols:
            df[col] = scaler.fit_transform(df[[col]])

        self.df = df
        return df

result = Encoding_Scaling(df)
df = result.encodla()
df = result.df

In [415]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72435 entries, 0 to 72434
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   model                   72435 non-null  int64
 1   year                    72435 non-null  int64
 2   price                   72435 non-null  int64
 3   mileage                 72435 non-null  int64
 4   tax                     72435 non-null  float64
 5   mpg                     72435 non-null  float64
 6   engineSize              72435 non-null  float64
 7   Make                    72435 non-null  int64
 8   transmission_Automatic  72435 non-null  int64
 9   transmission_Manual     72435 non-null  int64
 10  transmission_Other      72435 non-null  int64
 11  transmission_Semi-Auto  72435 non-null  int64
 12  fuelType_Diesel         72435 non-null  int64
 13  fuelType_Electric       72435 non-null  int64
 14  fuelType_Hybrid         72435 non-null  int64
 15  fuelType_Other          72435 non-null  int64
 16  fuelType_Petrol         72435 non-null  int64
dtypes: float64(3), int64(14)
memory usage: 9.4 MB

In [416]:
x = df.drop('tax',axis=1)
y = df['tax']

In [417]:
df = result.scale_qil()
df = result.df

In [418]:
df.head()

,model,year,price,mileage,tax,mpg,engineSize,Make,transmission_Automatic,transmission_Manual,transmission_Other,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,0.055172,0.875000,0.083077,0.048712,0.258621,0.117109,0.212121,0.5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.089655,0.833333,0.110757,0.112081,0.034483,0.135813,0.303030,0.5,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.055172,0.833333,0.072696,0.092709,0.051724,0.117109,0.212121,0.5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.075862,0.875000,0.112833,0.080344,0.250000,0.142402,0.303030,0.5,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.068966,0.958333,0.116294,0.006183,0.250000,0.104782,0.151515,0.5,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

# Model Selection

In [419]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size=0.2, random_state=42
)

# Linear Regression

In [420]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [421]:
lr = LinearRegression()
lasso = Lasso(alpha=2)
ridge = Ridge(alpha=5)

In [422]:
# Linear Regresionda bilan sinab ko'ramiz birinchi
lr.fit(x_train, y_train)

LinearRegression()

In [423]:
y_lr_pred = lr.predict(x_test)

In [424]:
y_lr_pred[0:10]

array([ 90.61321355, 164.36577884,  76.09336829, 125.23592701,
       121.76337743, 177.39997465,  94.91656488, 131.9593157 ,
        63.38791906, 162.51689927])

# Evaluation

In [425]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

r2 = r2_score(y_test, y_lr_pred)
mae = mean_absolute_error(y_test, y_lr_pred)
mse = mean_squared_error(y_test, y_lr_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: 0.2796552827831099
mae: 42.77756274168484
mse: 2968.065704195022

# Losso

In [426]:
lasso.fit(x_train, y_train)

Lasso(alpha=2)

In [427]:
y_lasso_pred = lasso.predict(x_test)

# Lassoda Evaluation

In [428]:

r2 = r2_score(y_test, y_lasso_pred)
mae = mean_absolute_error(y_test, y_lasso_pred)
mse = mean_squared_error(y_test, y_lasso_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: 0.25294989794416045
mae: 42.777661222625966
mse: 3078.100990028804

# Ridge

In [429]:
ridge.fit(x_train, y_train)

Ridge(alpha=5)

In [430]:
y_ridge_pred = ridge.predict(x_test)

# Ridge Evaluation

In [431]:
r2 = r2_score(y_test, y_ridge_pred)
mae = mean_absolute_error(y_test, y_ridge_pred)
mse = mean_squared_error(y_test, y_ridge_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: 0.28508198470509816
mae: 42.773782462363904
mse: 2945.7058430388624

# Decision Tree Regressor

In [432]:
from sklearn.tree import DecisionTreeRegressor

In [433]:
dt = DecisionTreeRegressor()

In [434]:
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [435]:
y_dt_pred = dt.predict(x_test)

# Decision Tree Regressor Evaluation

In [436]:
r2 = r2_score(y_test, y_dt_pred)
mae = mean_absolute_error(y_test, y_dt_pred)
mse = mean_squared_error(y_test, y_dt_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: 0.7513953442270385
mae: 9.382319780953038
mse: 1024.3358978931303

# Random Forest Regressor

In [437]:
from sklearn.ensemble import RandomForestRegressor

In [438]:
rf = RandomForestRegressor()
rf.fit(x_train, y_train)
y_rf_pred = rf.predict(x_test)

# Random Forest Regressor Evaluation

In [439]:
r2 = r2_score(y_test, y_rf_pred)
mae = mean_absolute_error(y_test, y_rf_pred)
mse = mean_squared_error(y_test, y_rf_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: 0.8501615744548483
mae: 9.54273252797378
mse: 617.3853731438404

# Support Vector Machine Regressor

In [440]:
from sklearn.svm import SVR

In [441]:
svr = SVR(kernel='rbf', C=0.5, max_iter=10000)  # kernel='rbf'

In [442]:
svr.fit(x_train,y_train)

/Users/murodjongafforov/.local/share/virtualenvs/lesson-1-YtM2ZKiC/lib/python3.13/site-packages/sklearn/svm/_base.py:313: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(

SVR(C=0.5, max_iter=10000)

In [443]:
y_svr_pred = svr.predict(x_test)

# Support Vector Machine Evaluation

In [444]:
r2 = r2_score(y_test, y_svr_pred)
mae = mean_absolute_error(y_test, y_svr_pred)
mse = mean_squared_error(y_test, y_svr_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: -0.43982608346823726
mae: 71.46256561602206
mse: 5932.574108211024

# KFold Cross Validation

In [445]:
from sklearn.model_selection import KFold, cross_val_score

In [446]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)
scores_lr = cross_val_score(lr, x, y, cv=kf, scoring='r2')
print(f"scores_lr: {scores_lr}")

scores_lr: [0.27965528 0.30022728 0.29605064 0.2935975  0.28506608]

In [447]:
# Decsion Tree uchun KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)
scores_dt = cross_val_score(dt, x, y, cv=kf, scoring='r2')
print(f"scores_dt: {scores_dt}")

scores_dt: [0.75179657 0.74367984 0.74681717 0.73773748 0.74885247]

In [448]:
# Random Forest uchun KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)
scores_rf = cross_val_score(rf, x, y, cv=kf, scoring='r2')
print(f"scores_rf: {scores_rf}")

scores_rf: [0.85088148 0.85048655 0.85149116 0.84536049 0.86002529]

In [449]:
# SVM uchun KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)
scores_svr = cross_val_score(svr, x, y, cv=kf, scoring='r2')
print(f"scores_svr: {scores_svr}")

/Users/murodjongafforov/.local/share/virtualenvs/lesson-1-YtM2ZKiC/lib/python3.13/site-packages/sklearn/svm/_base.py:313: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/Users/murodjongafforov/.local/share/virtualenvs/lesson-1-YtM2ZKiC/lib/python3.13/site-packages/sklearn/svm/_base.py:313: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/Users/murodjongafforov/.local/share/virtualenvs/lesson-1-YtM2ZKiC/lib/python3.13/site-packages/sklearn/svm/_base.py:313: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/Users/murodjongafforov/.local/share/virtualenvs/lesson-1-YtM2ZKiC/lib/python3.13/site-packages/sklearn/svm/_base.py:313: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
/Users/murodjongafforov/.local/share/virtualenvs/lesson-1-YtM2ZKiC/lib/python3.13/site-packages/sklearn/svm/_base.py:313: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(

scores_svr: [-0.43982608 -0.45604184 -0.44277008 -0.44600843 -0.43620536]

# Feature Engineering qilingan holat bilan qilib ko'ramiz.

In [450]:
"""
Eng avvalo Feature Engineering bu yangi featurelar yaratish, ularni bir turdan boshqa turga transform qilish
va muhim featurelarni tanlash deganidir.
Bu model performancesini yaxshilaydi, va yangi featurelar model generalizationini oshiradi.
"""

'\nEng avvalo Feature Engineering bu yangi featurelar yaratish, ularni bir turdan boshqa turga transform qilish\nva muhim featurelarni tanlash deganidir.\nBu model performancesini yaxshilaydi, va yangi featurelar model generalizationini oshiradi.\n'

In [512]:
import pandas as pd
df = pd.read_csv('cars_dataset.csv')

In [452]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72435 entries, 0 to 72434
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         72435 non-null  str
 1   year          72435 non-null  int64
 2   price         72435 non-null  int64
 3   transmission  72435 non-null  str
 4   mileage       72435 non-null  int64
 5   fuelType      72435 non-null  str
 6   tax           72435 non-null  float64
 7   mpg           72435 non-null  float64
 8   engineSize    72435 non-null  float64
 9   Make          72435 non-null  str
dtypes: float64(3), int64(3), str(4)
memory usage: 5.5 MB

In [453]:
"""
bizda demak year, mileage va mpg bor --
year- bu chiqarilgan yili
mileage -- bu umumiy bosib o'tkan masofasi
mpg -- esa 1 gallonda bilan nechchi km yurishidir. --> 1 gallon ≈ 3.785 litr

"""

"\nbizda demak year, mileage va mpg bor --\nyear- bu chiqarilgan yili\nmileage -- bu umumiy bosib o'tkan masofasi\nmpg -- esa 1 gallonda bilan nechchi km yurishidir. --> 1 gallon ≈ 3.785 litr\n\n"

In [513]:
df['moshina_yoshi'] = 2026 - df['year']  # bu moshinaning yoshi
df['bir_yildagi_masofa'] = df['mileage'] / df['moshina_yoshi'] # bu esa bir yilda nechchi km masofa bosib o'tkani
df['total_gallon_usage'] = df['mileage'] / df['mpg']  # bu esa umumiy masofani nechcha gallon bilan bosib o'tkanligi

In [455]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72435 entries, 0 to 72434
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   model               72435 non-null  str
 1   year                72435 non-null  int64
 2   price               72435 non-null  int64
 3   transmission        72435 non-null  str
 4   mileage             72435 non-null  int64
 5   fuelType            72435 non-null  str
 6   tax                 72435 non-null  float64
 7   mpg                 72435 non-null  float64
 8   engineSize          72435 non-null  float64
 9   Make                72435 non-null  str
 10  moshina_yoshi       72435 non-null  int64
 11  bir_yildagi_masofa  72435 non-null  float64
 12  total_gallon_usage  72435 non-null  float64
dtypes: float64(5), int64(4), str(4)
memory usage: 7.2 MB

# Klibdan foydalangan holatda endi qilib ko'ramiz: Bunda natijaga qay darajada tasir qilishini 
# Analiz qilamiz

In [514]:
import klib  # bu bizga ustun nomlarini ham standart holatga keltirib beradi.

In [500]:
klib.missingval_plot(df)  # missing valuelarni vizualniy ko'rsatib beradi.

No missing values found in the dataset.

In [458]:
klib.corr_interactive_plot(df, annot=True, figsize=(10,6))

ValueError: underlying array is read-only

In [515]:
klib.data_cleaning(df, drop_duplicates=True)

Shape of cleaned data: (71593, 13) - Remaining NAs: 0


Dropped rows: 842
     of which 842 duplicates. (Rows (first 150 shown): [273, 764, 784, 967, 990, 1133, 1137, 1146, 1162, 1563, 1564, 1874, 1875, 2287, 2307, 2500, 3222, 3833, 4037, 4039, 4077, 4115, 4124, 4169, 4219, 4220, 4266, 4450, 4478, 4483, 4502, 4504, 4508, 4514, 4522, 4566, 4567, 4668, 4676, 4777, 4803, 4826, 4827, 4829, 4843, 4937, 4947, 4996, 4999, 5000, 5001, 5012, 5036, 5087, 5089, 5093, 5100, 5106, 5154, 5169, 5220, 5314, 5486, 5499, 5523, 5530, 5558, 5561, 5563, 5791, 5877, 5951, 6099, 6603, 6754, 6770, 6798, 6893, 7002, 7431, 7587, 7614, 7616, 7626, 7645, 7659, 7662, 7669, 7694, 8279, 8280, 8297, 8298, 8299, 8601, 8652, 9292, 9479, 9508, 9521, 9529, 9550, 9597, 10842, 11061, 11377, 11625, 11841, 11943, 11944, 11945, 11964, 12030, 12031, 12039, 12040, 12041, 12042, 12043, 12044, 12045, 12046, 12051, 12052, 12053, 12054, 12055, 12056, 12057, 12058, 12059, 12067, 12068, 12069, 12070, 12073, 12074, 12105, 12113, 12115, 12116, 12120, 12121, 12127, 12128, 12129, 12130, 12131, 12132, 12133])

Dropped columns: 0
     of which 0 single valued.     Columns: []
Dropped missing values: 0
Reduced memory by at least: 4.45 MB (-61.98%)

,model,year,price,transmission,mileage,fuel_type,tax,mpg,engine_size,make,moshina_yoshi,bir_yildagi_masofa,total_gallon_usage
0,A1,2017,12500,Manual,15735,Petrol,150.0,55.400002,1.4,audi,9,1748.333333,284.025269
1,A6,2016,16500,Automatic,36203,Diesel,20.0,64.199997,2.0,audi,10,3620.300000,563.909668
2,A1,2016,11000,Manual,29946,Petrol,30.0,55.400002,1.4,audi,10,2994.600000,540.541504
3,A4,2017,16800,Automatic,25952,Diesel,145.0,67.300003,2.0,audi,9,2883.555556,385.616638
4,A3,2019,17300,Manual,1998,Petrol,145.0,49.599998,1.0,audi,7,285.428571,40.282257
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71588,I30,2016,8680,Manual,25906,Diesel,0.0,78.400002,1.6,Hyundai,10,2590.600000,330.433685
71589,I40,2015,7830,Manual,59508,Diesel,30.0,65.699997,1.7,Hyundai,11,5409.818182,905.753418
71590,I10,2017,6830,Manual,13810,Petrol,20.0,60.099998,1.0,Hyundai,9,1534.444444,229.783691
71591,Tucson,2018,13994,Manual,23313,Petrol,145.0,44.799999,1.6,Hyundai,8,2914.125000,520.379456
71592,Tucson,2016,15999,Automatic,11472,Diesel,125.0,57.599998,1.7,Hyundai,10,1147.200000,199.166672

In [460]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72435 entries, 0 to 72434
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   model               72435 non-null  str
 1   year                72435 non-null  int64
 2   price               72435 non-null  int64
 3   transmission        72435 non-null  str
 4   mileage             72435 non-null  int64
 5   fuelType            72435 non-null  str
 6   tax                 72435 non-null  float64
 7   mpg                 72435 non-null  float64
 8   engineSize          72435 non-null  float64
 9   Make                72435 non-null  str
 10  moshina_yoshi       72435 non-null  int64
 11  bir_yildagi_masofa  72435 non-null  float64
 12  total_gallon_usage  72435 non-null  float64
dtypes: float64(5), int64(4), str(4)
memory usage: 7.2 MB

In [518]:
df = klib.clean_column_names(df)  # Ustun nomlarini go'zal holatga keltirib beradi.

In [519]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72435 entries, 0 to 72434
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   model               72435 non-null  str
 1   year                72435 non-null  int64
 2   price               72435 non-null  int64
 3   transmission        72435 non-null  str
 4   mileage             72435 non-null  int64
 5   fuel_type           72435 non-null  str
 6   tax                 72435 non-null  float64
 7   mpg                 72435 non-null  float64
 8   engine_size         72435 non-null  float64
 9   make                72435 non-null  str
 10  moshina_yoshi       72435 non-null  int64
 11  bir_yildagi_masofa  72435 non-null  float64
 12  total_gallon_usage  72435 non-null  float64
dtypes: float64(5), int64(4), str(4)
memory usage: 7.2 MB

In [520]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
def encodla(df):
        le = LabelEncoder()
        for col in df.columns:
            if df[col].dtype == 'str':
                if df[col].nunique() <=5:
                    dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
                    df = pd.concat([df.drop(columns=col), dummies], axis=1)
                else:
                    df[col] = le.fit_transform(df[col])    
        return df
df = encodla(df)

In [521]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72435 entries, 0 to 72434
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   model                   72435 non-null  int64
 1   year                    72435 non-null  int64
 2   price                   72435 non-null  int64
 3   mileage                 72435 non-null  int64
 4   tax                     72435 non-null  float64
 5   mpg                     72435 non-null  float64
 6   engine_size             72435 non-null  float64
 7   make                    72435 non-null  int64
 8   moshina_yoshi           72435 non-null  int64
 9   bir_yildagi_masofa      72435 non-null  float64
 10  total_gallon_usage      72435 non-null  float64
 11  transmission_Automatic  72435 non-null  int64
 12  transmission_Manual     72435 non-null  int64
 13  transmission_Other      72435 non-null  int64
 14  transmission_Semi-Auto  72435 non-null  int64
 15  fuel_type_Diesel        72435 non-null  int64
 16  fuel_type_Electric      72435 non-null  int64
 17  fuel_type_Hybrid        72435 non-null  int64
 18  fuel_type_Other         72435 non-null  int64
 19  fuel_type_Petrol        72435 non-null  int64
dtypes: float64(5), int64(15)
memory usage: 11.1 MB

In [522]:
def scale_qil(df):
        scaler = MinMaxScaler()
        num_cols = df.select_dtypes(include=['int64', 'float64']).columns
        for col in num_cols:
            df[col] = scaler.fit_transform(df[[col]])
        return df
df = scale_qil(df)

# Train Test Split

In [523]:
x = df.drop('bir_yildagi_masofa', axis=1)
y = df['bir_yildagi_masofa']

In [524]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,y,test_size=0.2, random_state=42
)

In [525]:
# Linear Regression
from sklearn.linear_model import LinearRegression, Lasso, Ridge
lr = LinearRegression()
lasso = Lasso(alpha=0.1)
ridge = Ridge(alpha=0.1)

In [526]:
df.head()

,model,year,price,mileage,tax,mpg,engine_size,make,moshina_yoshi,bir_yildagi_masofa,total_gallon_usage,transmission_Automatic,transmission_Manual,transmission_Other,transmission_Semi-Auto,fuel_type_Diesel,fuel_type_Electric,fuel_type_Hybrid,fuel_type_Other,fuel_type_Petrol
0,0.055172,0.875000,0.083077,0.048712,0.258621,0.117109,0.212121,0.5,0.125000,0.092263,0.038777,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.089655,0.833333,0.110757,0.112081,0.034483,0.135813,0.303030,0.5,0.166667,0.191052,0.076990,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.055172,0.833333,0.072696,0.092709,0.051724,0.117109,0.212121,0.5,0.166667,0.158032,0.073800,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.075862,0.875000,0.112833,0.080344,0.250000,0.142402,0.303030,0.5,0.125000,0.152172,0.052647,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.068966,0.958333,0.116294,0.006183,0.250000,0.104782,0.151515,0.5,0.041667,0.015061,0.005498,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [527]:
df.head()

,model,year,price,mileage,tax,mpg,engine_size,make,moshina_yoshi,bir_yildagi_masofa,total_gallon_usage,transmission_Automatic,transmission_Manual,transmission_Other,transmission_Semi-Auto,fuel_type_Diesel,fuel_type_Electric,fuel_type_Hybrid,fuel_type_Other,fuel_type_Petrol
0,0.055172,0.875000,0.083077,0.048712,0.258621,0.117109,0.212121,0.5,0.125000,0.092263,0.038777,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.089655,0.833333,0.110757,0.112081,0.034483,0.135813,0.303030,0.5,0.166667,0.191052,0.076990,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.055172,0.833333,0.072696,0.092709,0.051724,0.117109,0.212121,0.5,0.166667,0.158032,0.073800,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.075862,0.875000,0.112833,0.080344,0.250000,0.142402,0.303030,0.5,0.125000,0.152172,0.052647,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.068966,0.958333,0.116294,0.006183,0.250000,0.104782,0.151515,0.5,0.041667,0.015061,0.005498,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [528]:
lr.fit(x_train, y_train)
y_lr_pred = lr.predict(x_test)

# Linear Regression Evaluation after being done with FE

In [529]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

r2 = r2_score(y_test, y_lr_pred)
mae = mean_absolute_error(y_test, y_lr_pred)
mse = mean_squared_error(y_test, y_lr_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: 0.954344267219613
mae: 0.013594175151261172
mse: 0.0004198652074851093

# Lasso after being done with FE

In [530]:

lasso.fit(x_train, y_train)
y_lasso_pred = lasso.predict(x_test)

# Lasso Evaluation after being done with FE

In [531]:
r2 = r2_score(y_test, y_lasso_pred)
mae = mean_absolute_error(y_test, y_lasso_pred)
mse = mean_squared_error(y_test, y_lasso_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: -1.5558682656235945e-05
mae: 0.07407026211939674
mse: 0.00919647357439855

# Ridge Regression after being done with FE

In [532]:
ridge.fit(x_train, y_train)
y_ridge_pred = ridge.predict(x_test)

# Ridge Regression Evaluation after being done with FE

In [533]:
r2 = r2_score(y_test, y_ridge_pred)
mae = mean_absolute_error(y_test, y_ridge_pred)
mse = mean_squared_error(y_test, y_ridge_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: 0.9542954098816301
mae: 0.013594808681785892
mse: 0.0004203145157121405

# Decision Tree Regressor after being done with FE

In [534]:
# Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)
y_dt_pred = dt.predict(x_test)

# Decision Tree Regressor Evaluation after being done with FE

In [535]:
r2 = r2_score(y_test, y_dt_pred)
mae = mean_absolute_error(y_test, y_dt_pred)
mse = mean_squared_error(y_test, y_dt_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: 0.9988138370979187
mae: 0.0002502731103128553
mse: 1.0908346064427902e-05

# Random Forest Regressor after being done with FE

In [536]:
# Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor
rf_fe = RandomForestRegressor()
rf_fe.fit(x_train, y_train)
y_rf_pred_fe = rf_fe.predict(x_test)

# Random Forest Regressor Evaluation after being done with FE

In [537]:
r2 = r2_score(y_test, y_rf_pred_fe)
mae = mean_absolute_error(y_test, y_rf_pred_fe)
mse = mean_squared_error(y_test, y_rf_pred_fe)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: 0.9985170796218323
mae: 0.00018815336023884614
mse: 1.3637425890374237e-05

# Support Vector Machine Regressor after being done with FE

In [538]:
# Support Vector Machine Regressor 
from sklearn.svm import SVR
svr = SVR(kernel='rbf', C=1, max_iter=2000)  # kernel='rbf'

svr.fit(x_train,y_train)
y_svr_pred = svr.predict(x_test)

# Support Vector Machine Regressor Evaluation after being done with FE

In [539]:
r2 = r2_score(y_test, y_svr_pred)
mae = mean_absolute_error(y_test, y_svr_pred)
mse = mean_squared_error(y_test, y_svr_pred)

print(f"r2: {r2}")
print(f"mae: {mae}")
print(f"mse: {mse}")

r2: 0.6603018587837168
mae: 0.05131534678495306
mse: 0.003123976374010826

# Using Tabulate to show which model is the best one

In [540]:
from tabulate import tabulate

In [541]:
results = [
    ['Linear Regression', 0.9543, 0.0135, 0.0004],
    ['Lasso', -1.5558, 0.0740, 0.0091],
    ['Ridge', 0.9542, 0.0135, 0.0004],
    ['Decision Tree', 0.9988, 0.0002, 1.0908],
    ['Random Forest', 0.9985, 0.0001, 1.3637],
    ['Support Vector', 0.6603, 0.5513, 0.0031]
]

headers = ['Modellar', 'r2_score', 'mae', 'mse']
table = tabulate(results, headers=headers, tablefmt='grid', floatfmt='.4f')
print(table)

+-------------------+------------+--------+--------+
| Modellar          |   r2_score |    mae |    mse |
+===================+============+========+========+
| Linear Regression |     0.9543 | 0.0135 | 0.0004 |
+-------------------+------------+--------+--------+
| Lasso             |    -1.5558 | 0.0740 | 0.0091 |
+-------------------+------------+--------+--------+
| Ridge             |     0.9542 | 0.0135 | 0.0004 |
+-------------------+------------+--------+--------+
| Decision Tree     |     0.9988 | 0.0002 | 1.0908 |
+-------------------+------------+--------+--------+
| Random Forest     |     0.9985 | 0.0001 | 1.3637 |
+-------------------+------------+--------+--------+
| Support Vector    |     0.6603 | 0.5513 | 0.0031 |
+-------------------+------------+--------+--------+

# Measuring the best models with evaluation metrics.

In [542]:
"""

Tabledan ko'rib turibmizki, bu yerda Random Forestda juda yaxshi r2_score 
mae va mse ham juda yaxshi va balansni ushlagan qolgan modellarimizda esa balansni
bu qadar ushlagani mavjud emas.

"""
model_nomi = ['Decision Tree', 0.9988, 0.0002, 1.0908 ]
best_model, r2_score, mae, mse = model_nomi

print(f"Eng yaxshi modellardan biri: {best_model}")
print(f"Eng yaxshi r2_scorelardan biri Random Forestdagi: {r2_score}")
print(f"Eng balansli Random Forestdagi mae'dir: {mae}")
print(f"Eng balansli Random Forestdagi mse'dir: {mse}")

Eng yaxshi modellardan biri: Decision Tree
Eng yaxshi r2_scorelardan biri Random Forestdagi: 0.9988
Eng balansli Random Forestdagi mae'dir: 0.0002
Eng balansli Random Forestdagi mse'dir: 1.0908

# Joblib orqali biz endi modelni saqlaymiz

In [543]:
from joblib import dump, load

dump(dt, 'eng_yaxsh_va_eng_balansli_model.joblib' )

['eng_yaxsh_va_eng_balansli_model.joblib']