# DATA bilan Ishlash

In [37]:
import pandas as pd

In [38]:
df=pd.read_csv('/Users/sunnatabdurayimov/Library/Mobile Documents/com~apple~Numbers/Documents/iphone_sales_dataset.csv')

In [39]:
df.head()

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,1001,Customer_1,USA,iPhone 13,256GB,Purple,5.0,1817.0,2025-05-01,Debit Card
1,1002,Customer_2,Canada,iPhone 12,256GB,Blue,1.0,998.0,2025-03-05,PayPal
2,1003,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.0,876.0,2025-01-25,Credit Card
3,1004,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2.0,1290.0,2025-03-24,Debit Card
4,1005,Customer_5,USA,iPhone 15,128GB,Blue,3.0,1092.0,2025-02-01,Debit Card

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    int64
 1   Customer_Name   99 non-null     str
 2   Country         99 non-null     str
 3   iPhone_Model    99 non-null     str
 4   Storage         97 non-null     str
 5   Color           100 non-null    str
 6   Quantity        98 non-null     float64
 7   Price           98 non-null     float64
 8   Sale_Date       100 non-null    str
 9   Payment_Method  99 non-null     str
dtypes: float64(2), int64(1), str(7)
memory usage: 7.9 KB

In [41]:

df['Order_ID']

0     1001
1     1002
2     1003
3     1004
4     1005
      ...
95    1096
96    1097
97    1098
98    1099
99    1100
Name: Order_ID, Length: 100, dtype: int64

In [42]:
#Keraksiz ustunlarni tashlab yuborish
df.drop('Order_ID',axis=1,inplace=True)

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_Name   99 non-null     str
 1   Country         99 non-null     str
 2   iPhone_Model    99 non-null     str
 3   Storage         97 non-null     str
 4   Color           100 non-null    str
 5   Quantity        98 non-null     float64
 6   Price           98 non-null     float64
 7   Sale_Date       100 non-null    str
 8   Payment_Method  99 non-null     str
dtypes: float64(2), str(7)
memory usage: 7.2 KB

In [44]:
df.head()

,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,Customer_1,USA,iPhone 13,256GB,Purple,5.0,1817.0,2025-05-01,Debit Card
1,Customer_2,Canada,iPhone 12,256GB,Blue,1.0,998.0,2025-03-05,PayPal
2,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.0,876.0,2025-01-25,Credit Card
3,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2.0,1290.0,2025-03-24,Debit Card
4,Customer_5,USA,iPhone 15,128GB,Blue,3.0,1092.0,2025-02-01,Debit Card

In [45]:
df.isnull().sum()

Customer_Name     1
Country           1
iPhone_Model      1
Storage           3
Color             0
Quantity          2
Price             2
Sale_Date         0
Payment_Method    1
dtype: int64

In [46]:
#mean
df.fillna({'Price':df['Price'].mean()},inplace=True)

,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,Customer_1,USA,iPhone 13,256GB,Purple,5.0,1817.0,2025-05-01,Debit Card
1,Customer_2,Canada,iPhone 12,256GB,Blue,1.0,998.0,2025-03-05,PayPal
2,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.0,876.0,2025-01-25,Credit Card
3,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2.0,1290.0,2025-03-24,Debit Card
4,Customer_5,USA,iPhone 15,128GB,Blue,3.0,1092.0,2025-02-01,Debit Card
...,...,...,...,...,...,...,...,...,...
95,Customer_96,UAE,iPhone 14 Pro,256GB,Blue,1.0,1743.0,2025-03-09,Credit Card
96,Customer_97,UK,iPhone 15 Pro Max,512GB,White,3.0,1671.0,2025-02-08,Credit Card
97,Customer_98,UK,iPhone 15 Pro Max,512GB,White,4.0,1125.0,2025-01-08,Debit Card
98,Customer_99,Germany,iPhone 15 Pro Max,512GB,Purple,5.0,1540.0,2025-02-04,Debit Card
99,Customer_100,UK,iPhone 15,512GB,Blue,3.0,1549.0,2025-03-28,Debit Card

In [47]:
df.isnull().sum()

Customer_Name     1
Country           1
iPhone_Model      1
Storage           3
Color             0
Quantity          2
Price             0
Sale_Date         0
Payment_Method    1
dtype: int64

In [48]:
#mode
df.fillna({'Storage':df['Storage'].mode()[0]},inplace=True)

,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,Customer_1,USA,iPhone 13,256GB,Purple,5.0,1817.0,2025-05-01,Debit Card
1,Customer_2,Canada,iPhone 12,256GB,Blue,1.0,998.0,2025-03-05,PayPal
2,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.0,876.0,2025-01-25,Credit Card
3,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2.0,1290.0,2025-03-24,Debit Card
4,Customer_5,USA,iPhone 15,128GB,Blue,3.0,1092.0,2025-02-01,Debit Card
...,...,...,...,...,...,...,...,...,...
95,Customer_96,UAE,iPhone 14 Pro,256GB,Blue,1.0,1743.0,2025-03-09,Credit Card
96,Customer_97,UK,iPhone 15 Pro Max,512GB,White,3.0,1671.0,2025-02-08,Credit Card
97,Customer_98,UK,iPhone 15 Pro Max,512GB,White,4.0,1125.0,2025-01-08,Debit Card
98,Customer_99,Germany,iPhone 15 Pro Max,512GB,Purple,5.0,1540.0,2025-02-04,Debit Card
99,Customer_100,UK,iPhone 15,512GB,Blue,3.0,1549.0,2025-03-28,Debit Card

In [49]:
df.isnull().sum()

Customer_Name     1
Country           1
iPhone_Model      1
Storage           0
Color             0
Quantity          2
Price             0
Sale_Date         0
Payment_Method    1
dtype: int64

In [50]:
#Median
df.fillna({'Quantity':df['Quantity'].median()},inplace=True)

,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,Customer_1,USA,iPhone 13,256GB,Purple,5.0,1817.0,2025-05-01,Debit Card
1,Customer_2,Canada,iPhone 12,256GB,Blue,1.0,998.0,2025-03-05,PayPal
2,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.0,876.0,2025-01-25,Credit Card
3,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2.0,1290.0,2025-03-24,Debit Card
4,Customer_5,USA,iPhone 15,128GB,Blue,3.0,1092.0,2025-02-01,Debit Card
...,...,...,...,...,...,...,...,...,...
95,Customer_96,UAE,iPhone 14 Pro,256GB,Blue,1.0,1743.0,2025-03-09,Credit Card
96,Customer_97,UK,iPhone 15 Pro Max,512GB,White,3.0,1671.0,2025-02-08,Credit Card
97,Customer_98,UK,iPhone 15 Pro Max,512GB,White,4.0,1125.0,2025-01-08,Debit Card
98,Customer_99,Germany,iPhone 15 Pro Max,512GB,Purple,5.0,1540.0,2025-02-04,Debit Card
99,Customer_100,UK,iPhone 15,512GB,Blue,3.0,1549.0,2025-03-28,Debit Card

In [53]:
df.isnull().sum()

Customer_Name     1
Country           1
iPhone_Model      1
Storage           0
Color             0
Quantity          0
Price             0
Sale_Date         0
Payment_Method    1
dtype: int64

In [52]:
df.describe()

         Quantity        Price
count  100.000000   100.000000
mean     3.290000  1468.632653
std      1.465392   388.031561
min      1.000000   718.000000
25%      2.000000  1123.750000
50%      3.000000  1565.000000
75%      5.000000  1794.250000
max      5.000000  1992.000000

In [57]:
#Fixed
df.fillna({'Customer_Name': 'Unknown'}, inplace=True)

,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,Customer_1,USA,iPhone 13,256GB,Purple,5.0,1817.0,2025-05-01,Debit Card
1,Customer_2,Canada,iPhone 12,256GB,Blue,1.0,998.0,2025-03-05,PayPal
2,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.0,876.0,2025-01-25,Credit Card
3,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2.0,1290.0,2025-03-24,Debit Card
4,Customer_5,USA,iPhone 15,128GB,Blue,3.0,1092.0,2025-02-01,Debit Card
...,...,...,...,...,...,...,...,...,...
95,Customer_96,UAE,iPhone 14 Pro,256GB,Blue,1.0,1743.0,2025-03-09,Credit Card
96,Customer_97,UK,iPhone 15 Pro Max,512GB,White,3.0,1671.0,2025-02-08,Credit Card
97,Customer_98,UK,iPhone 15 Pro Max,512GB,White,4.0,1125.0,2025-01-08,Debit Card
98,Customer_99,Germany,iPhone 15 Pro Max,512GB,Purple,5.0,1540.0,2025-02-04,Debit Card
99,Customer_100,UK,iPhone 15,512GB,Blue,3.0,1549.0,2025-03-28,Debit Card

In [58]:
df.isnull().sum()

Customer_Name     0
Country           1
iPhone_Model      1
Storage           0
Color             0
Quantity          0
Price             0
Sale_Date         0
Payment_Method    1
dtype: int64

In [61]:
#Fixed
df.fillna({'Country':'USA'},inplace=True)

,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,Customer_1,USA,iPhone 13,256GB,Purple,5.0,1817.0,2025-05-01,Debit Card
1,Customer_2,Canada,iPhone 12,256GB,Blue,1.0,998.0,2025-03-05,PayPal
2,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.0,876.0,2025-01-25,Credit Card
3,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2.0,1290.0,2025-03-24,Debit Card
4,Customer_5,USA,iPhone 15,128GB,Blue,3.0,1092.0,2025-02-01,Debit Card
...,...,...,...,...,...,...,...,...,...
95,Customer_96,UAE,iPhone 14 Pro,256GB,Blue,1.0,1743.0,2025-03-09,Credit Card
96,Customer_97,UK,iPhone 15 Pro Max,512GB,White,3.0,1671.0,2025-02-08,Credit Card
97,Customer_98,UK,iPhone 15 Pro Max,512GB,White,4.0,1125.0,2025-01-08,Debit Card
98,Customer_99,Germany,iPhone 15 Pro Max,512GB,Purple,5.0,1540.0,2025-02-04,Debit Card
99,Customer_100,UK,iPhone 15,512GB,Blue,3.0,1549.0,2025-03-28,Debit Card

In [62]:
df.isnull().sum()

Customer_Name     0
Country           0
iPhone_Model      1
Storage           0
Color             0
Quantity          0
Price             0
Sale_Date         0
Payment_Method    1
dtype: int64

In [65]:
#Drop
#qatorlar bo'yicha
#1-xolat
df.dropna(inplace=True)

In [66]:
df.info()

<class 'pandas.DataFrame'>
Index: 98 entries, 0 to 99
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_Name   98 non-null     str
 1   Country         98 non-null     str
 2   iPhone_Model    98 non-null     str
 3   Storage         98 non-null     str
 4   Color           98 non-null     str
 5   Quantity        98 non-null     float64
 6   Price           98 non-null     float64
 7   Sale_Date       98 non-null     str
 8   Payment_Method  98 non-null     str
dtypes: float64(2), str(7)
memory usage: 7.7 KB

In [67]:
#Ustun boyicha (50%yuqori qiymat bolmasa)
df.drop('Payment_Method',axis=1,inplace=True)

In [68]:
df.info()

<class 'pandas.DataFrame'>
Index: 98 entries, 0 to 99
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_Name  98 non-null     str
 1   Country        98 non-null     str
 2   iPhone_Model   98 non-null     str
 3   Storage        98 non-null     str
 4   Color          98 non-null     str
 5   Quantity       98 non-null     float64
 6   Price          98 non-null     float64
 7   Sale_Date      98 non-null     str
dtypes: float64(2), str(6)
memory usage: 6.9 KB

In [69]:
df.head()

,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date
0,Customer_1,USA,iPhone 13,256GB,Purple,5.0,1817.0,2025-05-01
1,Customer_2,Canada,iPhone 12,256GB,Blue,1.0,998.0,2025-03-05
2,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5.0,876.0,2025-01-25
3,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2.0,1290.0,2025-03-24
4,Customer_5,USA,iPhone 15,128GB,Blue,3.0,1092.0,2025-02-01

In [70]:
df.isnull().sum()

Customer_Name    0
Country          0
iPhone_Model     0
Storage          0
Color            0
Quantity         0
Price            0
Sale_Date        0
dtype: int64