# Data bian Tanishuv

In [67]:
import pandas as pd
df=pd.read_csv('/Users/sunnatabdurayimov/Library/Mobile Documents/com~apple~Numbers/Documents/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [68]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0.0,Yes,No,1.0,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0.0,No,No,34.0,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0.0,No,No,2.0,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0.0,No,No,45.0,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0.0,No,No,2.0,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7040 non-null   float64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7042 non-null   float64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7042 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7041 non-null   float64
 19  TotalCharges      7040 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(3), str(18)
memory usage: 1.1 MB

In [49]:
#keraksiz ustunlarni tashlab yuborish
df.drop('customerID',axis=1,inplace=True)

In [70]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       3
Partner             0
Dependents          0
tenure              1
PhoneService        0
MultipleLines       1
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      2
TotalCharges        3
Churn               0
dtype: int64

In [75]:
#mean
df['MonthlyCharges'].fillna(df['MonthlyCharges'].mean(),inplace=True)

/var/folders/gj/51m09vr94mn4rflykkzl_yfm0000gn/T/ipykernel_2787/2560137535.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['MonthlyCharges'].fillna(df['MonthlyCharges'].mean(),inplace=True)

0        29.85
1        56.95
2        53.85
3        42.30
4        70.70
         ...
7038     84.80
7039    103.20
7040     29.60
7041     74.40
7042    105.65
Name: MonthlyCharges, Length: 7043, dtype: float64

In [73]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       3
Partner             0
Dependents          0
tenure              1
PhoneService        0
MultipleLines       1
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      2
TotalCharges        3
Churn               0
dtype: int64

In [77]:
df['tenure'].fillna(df['tenure'].mode()[0],inplace=True)

/var/folders/gj/51m09vr94mn4rflykkzl_yfm0000gn/T/ipykernel_2787/3178106987.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['tenure'].fillna(df['tenure'].mode()[0],inplace=True)

0        1.0
1       34.0
2        2.0
3       45.0
4        2.0
        ...
7038    24.0
7039    72.0
7040    11.0
7041     4.0
7042    66.0
Name: tenure, Length: 7043, dtype: float64

In [78]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7040.000000  7042.000000     7041.000000
mean        0.162216    32.372621       64.751214
std         0.368675    24.560914       30.087260
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7040 non-null   float64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7042 non-null   float64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7042 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7041 non-null   float64
 19  TotalCharges      7040 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(3), str(18)
memory usage: 1.1 MB

In [80]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0.0,Yes,No,1.0,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0.0,No,No,34.0,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0.0,No,No,2.0,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0.0,No,No,45.0,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0.0,No,No,2.0,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [81]:
#fixed
df['SeniorCitizen'].fillna('Yes,inplace=True')

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
7038    0.0
7039    0.0
7040    0.0
7041    1.0
7042    0.0
Name: SeniorCitizen, Length: 7043, dtype: object

In [82]:
#Drop,qator bo'yicha
#1-xolat
df.dropna(inplace=True)

In [83]:
df.info()

<class 'pandas.DataFrame'>
Index: 7033 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7033 non-null   str
 1   gender            7033 non-null   str
 2   SeniorCitizen     7033 non-null   float64
 3   Partner           7033 non-null   str
 4   Dependents        7033 non-null   str
 5   tenure            7033 non-null   float64
 6   PhoneService      7033 non-null   str
 7   MultipleLines     7033 non-null   str
 8   InternetService   7033 non-null   str
 9   OnlineSecurity    7033 non-null   str
 10  OnlineBackup      7033 non-null   str
 11  DeviceProtection  7033 non-null   str
 12  TechSupport       7033 non-null   str
 13  StreamingTV       7033 non-null   str
 14  StreamingMovies   7033 non-null   str
 15  Contract          7033 non-null   str
 16  PaperlessBilling  7033 non-null   str
 17  PaymentMethod     7033 non-null   str
 18  MonthlyCharges    7033 non-null   float64
 19  TotalCharges      7033 non-null   str
 20  Churn             7033 non-null   str
dtypes: float64(3), str(18)
memory usage: 1.2 MB

In [86]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [87]:
#drop,ustunlar bo'yicha,malum bir ustunda juda ko'p(50%dan yuqori) qiymatlar tushib qolganda tashlab yuboramiz butunlay bu ustunni
df.drop('MonthlyCharges',axis=1,inplace=True)

In [88]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
TotalCharges        0
Churn               0
dtype: int64