preprocessed_youtube_comments data setini tahlil qilish

In [3]:
pip install pandas

Requirement already satisfied: pandas in c:\users\javohir\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\javohir\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\javohir\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\javohir\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\javohir\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [6]:
df=pd.read_csv('preprocessed_youtube_comments.csv')

In [7]:
df.tail()

,video_id,video_title,comment,cleaned_comment,processed_comment,sentiment
64203,mcjjPpd5s1A,Squid Game Trailer,hey bro without gi hun squid game is alone 😔😔😭😭,hey bro without gi hun squid game is alone,hey bro without gi hun squid game alone,-1
64204,mcjjPpd5s1A,Squid Game Trailer,"Wow, epic! Maybe now the plot won’t have rando...",wow epic maybe now the plot wont have random g...,wow epic maybe plot wont random gap character ...,1
64205,mcjjPpd5s1A,Squid Game Trailer,No way! Amaizing work dude. I really hope they...,no way amaizing work dude i really hope they m...,no way amaizing work dude really hope make seq...,1
64206,mcjjPpd5s1A,Squid Game Trailer,Simply incredible work bravo! 🎉,simply incredible work bravo,simply incredible work bravo,1
64207,mcjjPpd5s1A,Squid Game Trailer,Wow! What a trailer!\r\nLooks really cool\r\nI...,wow what a trailer\r\nlooks really cool\r\nit ...,wow trailer look really cool well done great job,1

In [8]:
df.head()

,video_id,video_title,comment,cleaned_comment,processed_comment,sentiment
0,TcMBFSGVi1c,Avengers Endgame Trailer,Furei a boca com espinho de peixe,furei a boca com espinho de peixe,furei boca com espinho de peixe,0
1,TcMBFSGVi1c,Avengers Endgame Trailer,Sou budista Jesus Cristo,sou budista jesus cristo,sou budista jesus cristo,0
2,TcMBFSGVi1c,Avengers Endgame Trailer,Is there any chance of iron man returning back...,is there any chance of iron man returning back...,chance iron man returning back present,1
3,TcMBFSGVi1c,Avengers Endgame Trailer,TOMORROW. DOOM COMES FOR US ALL.,tomorrow doom comes for us all,tomorrow doom come u,-1
4,TcMBFSGVi1c,Avengers Endgame Trailer,saw this movie again today,saw this movie again today,saw movie today,0

In [11]:
df.nunique()

video_id               114
video_title              9
comment              64205
cleaned_comment      61023
processed_comment    56981
sentiment                3
dtype: int64

In [ ]:
df[['video_title','sentiment']] # BULAR MULTI CLASSLI USTUNLAR

                    video_title  sentiment
0      Avengers Endgame Trailer          0
1      Avengers Endgame Trailer          0
2      Avengers Endgame Trailer          1
3      Avengers Endgame Trailer         -1
4      Avengers Endgame Trailer          0
...                         ...        ...
64203        Squid Game Trailer         -1
64204        Squid Game Trailer          1
64205        Squid Game Trailer          1
64206        Squid Game Trailer          1
64207        Squid Game Trailer          1

[64208 rows x 2 columns]

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64208 entries, 0 to 64207
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   video_id           64208 non-null  str
 1   video_title        64208 non-null  str
 2   comment            64208 non-null  str
 3   cleaned_comment    64208 non-null  str
 4   processed_comment  64208 non-null  str
 5   sentiment          64208 non-null  int64
dtypes: int64(1), str(5)
memory usage: 2.9 MB

In [17]:
df.isnull().sum()

video_id             0
video_title          0
comment              0
cleaned_comment      0
processed_comment    0
sentiment            0
dtype: int64

In [18]:
df.isnull().any()

video_id             False
video_title          False
comment              False
cleaned_comment      False
processed_comment    False
sentiment            False
dtype: bool