STUDENTLARNI DATASETI

In [3]:
import pandas as pd

In [5]:
pip install pandas

Requirement already satisfied: pandas in c:\users\javohir\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\javohir\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\javohir\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\javohir\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\javohir\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
df=pd.read_csv('student_dataset.csv')

In [ ]:
import os # BU KOD HOZIR QAYSI PAPKADA TURGANIMNI KO'RSATADI
print(os.getcwd())

c:\Users\Javohir\Desktop\ML\3-dars\3-dars_uchun_practice

In [15]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Final_Exam_Score
0,23.5,84.2,Low,Low,Yes,7.4,50.3,Medium,Yes,1,54.3
1,19.7,63.6,Medium,High,Yes,6.7,83.1,Low,Yes,2,59.4
2,24.4,98.4,Medium,Medium,Yes,8.0,63.5,Medium,Yes,0,63.8
3,29.6,88.6,Medium,High,Yes,6.3,57.5,Medium,Yes,2,61.0
4,19.1,91.5,High,Medium,Yes,6.2,66.0,Medium,Yes,2,60.7

In [23]:
df.tail()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Final_Exam_Score
6602,26.0,69.5,High,Medium,No,7.0,80.1,Medium,Yes,1,58.8
6603,23.0,75.9,High,Low,No,6.4,93.2,Low,No,2,67.0
6604,20.1,90.3,High,Low,Yes,7.7,79.4,Medium,Yes,0,58.5
6605,10.3,86.0,High,High,No,6.8,72.1,Medium,Yes,1,58.7
6606,15.6,67.1,Low,Medium,Yes,6.9,78.9,Medium,Yes,4,52.3

In [22]:
df.nunique()

Hours_Studied                 352
Attendance                    401
Parental_Involvement            3
Access_to_Resources             3
Extracurricular_Activities      2
Sleep_Hours                    61
Previous_Scores               501
Motivation_Level                3
Internet_Access                 2
Tutoring_Sessions               9
Final_Exam_Score              477
dtype: int64

In [21]:
df['Hours_Studied'].nunique()

352

In [20]:
df['Hours_Studied']

0       23.5
1       19.7
2       24.4
3       29.6
4       19.1
        ...
6602    26.0
6603    23.0
6604    20.1
6605    10.3
6606    15.6
Name: Hours_Studied, Length: 6607, dtype: float64

In [19]:
df[['Hours_Studied','Tutoring_Sessions','Final_Exam_Score']]

      Hours_Studied  Tutoring_Sessions  Final_Exam_Score
0              23.5                  1              54.3
1              19.7                  2              59.4
2              24.4                  0              63.8
3              29.6                  2              61.0
4              19.1                  2              60.7
...             ...                ...               ...
6602           26.0                  1              58.8
6603           23.0                  2              67.0
6604           20.1                  0              58.5
6605           10.3                  1              58.7
6606           15.6                  4              52.3

[6607 rows x 3 columns]

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   float64
 1   Attendance                  6607 non-null   float64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   float64
 6   Previous_Scores             6607 non-null   float64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Final_Exam_Score            6607 non-null   float64
dtypes: float64(5), int64(1), str(5)
memory usage: 567.9 KB

In [17]:
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Final_Exam_Score              0
dtype: int64

In [24]:
df.isnull().any()

Hours_Studied                 False
Attendance                    False
Parental_Involvement          False
Access_to_Resources           False
Extracurricular_Activities    False
Sleep_Hours                   False
Previous_Scores               False
Motivation_Level              False
Internet_Access               False
Tutoring_Sessions             False
Final_Exam_Score              False
dtype: bool

DATA HAQIDA YAKUNIY XULOSAM HECH QAYSI QATORDA TUSHIB QOLGAN QIYMAT YO'Q DATA TOZA VA ISHLATSA BO'LADI DEB O'YLAYMAN