Youtube Comments

In [1]:
import pandas as pd

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\javohir\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\javohir\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\javohir\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\javohir\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\javohir\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
df=pd.read_csv('youtube_comments.csv')

In [5]:
df.head()

,video_id,video_title,comment
0,TcMBFSGVi1c,Avengers Endgame Trailer,Furei a boca com espinho de peixe
1,TcMBFSGVi1c,Avengers Endgame Trailer,Sou budista Jesus Cristo
2,TcMBFSGVi1c,Avengers Endgame Trailer,Is there any chance of iron man returning back...
3,TcMBFSGVi1c,Avengers Endgame Trailer,TOMORROW. DOOM COMES FOR US ALL.
4,TcMBFSGVi1c,Avengers Endgame Trailer,saw this movie again today

In [6]:
df.tail()

,video_id,video_title,comment
66798,mcjjPpd5s1A,Squid Game Trailer,hey bro without gi hun squid game is alone 😔😔😭😭
66799,mcjjPpd5s1A,Squid Game Trailer,"Wow, epic! Maybe now the plot won’t have rando..."
66800,mcjjPpd5s1A,Squid Game Trailer,No way! Amaizing work dude. I really hope they...
66801,mcjjPpd5s1A,Squid Game Trailer,Simply incredible work bravo! 🎉
66802,mcjjPpd5s1A,Squid Game Trailer,Wow! What a trailer!\r\nLooks really cool\r\nI...

In [9]:
df.nunique() # xar bir ustundagi classlar soni

video_id         115
video_title        9
comment        66799
dtype: int64

In [10]:
df['video_id'].nunique() # BU KOD ALOHIDA BIR USTUNDA NECHTA KLASSLAR BORLIGINI KO'RSATADI

115

In [12]:
df['video_id'] # BU KOD BITTA USTUNNI ALOHIDA CHIQARIB BERADI

0        TcMBFSGVi1c
1        TcMBFSGVi1c
2        TcMBFSGVi1c
3        TcMBFSGVi1c
4        TcMBFSGVi1c
            ...
66798    mcjjPpd5s1A
66799    mcjjPpd5s1A
66800    mcjjPpd5s1A
66801    mcjjPpd5s1A
66802    mcjjPpd5s1A
Name: video_id, Length: 66803, dtype: str

In [13]:
df['video_id'] # BU KOD BITTA USTUNNI ALOHIDA CHIQARIB BERADI

0        TcMBFSGVi1c
1        TcMBFSGVi1c
2        TcMBFSGVi1c
3        TcMBFSGVi1c
4        TcMBFSGVi1c
            ...
66798    mcjjPpd5s1A
66799    mcjjPpd5s1A
66800    mcjjPpd5s1A
66801    mcjjPpd5s1A
66802    mcjjPpd5s1A
Name: video_id, Length: 66803, dtype: str

In [14]:
df.info() # DATA HAQIDA UMUMIY MALUMOT

<class 'pandas.DataFrame'>
RangeIndex: 66803 entries, 0 to 66802
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   video_id     66803 non-null  str
 1   video_title  66803 non-null  str
 2   comment      66802 non-null  str
dtypes: str(3)
memory usage: 1.5 MB

In [15]:
df.isnull().sum() # BU SON ORQALI ANIQLASH

video_id       0
video_title    0
comment        1
dtype: int64

In [17]:
df.isnull().any() # BU BOOLEON ORQALI ANIQLASH

video_id       False
video_title    False
comment         True
dtype: bool