# SVM

In [103]:
import pandas as pd 
df=pd.read_csv('finalgolddata.csv')

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6399 entries, 0 to 6398
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6399 non-null   str
 1   Open    6399 non-null   float64
 2   High    6399 non-null   float64
 3   Low     6399 non-null   float64
 4   Close   6399 non-null   float64
 5   Volume  6399 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 300.1 KB

In [105]:
df.head()

       Date        Open        High         Low       Close  Volume
0  30-08-00  273.899994  273.899994  273.899994  273.899994       0
1  31-08-00  274.799988  278.299988  274.799988  278.299988       0
2  01-09-00  277.000000  277.000000  277.000000  277.000000       0
3  05-09-00  275.799988  275.799988  275.799988  275.799988       2
4  06-09-00  274.200012  274.200012  274.200012  274.200012       0

In [106]:
df.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [107]:
df.head()

       Date        Open        High         Low       Close  Volume
0  30-08-00  273.899994  273.899994  273.899994  273.899994       0
1  31-08-00  274.799988  278.299988  274.799988  278.299988       0
2  01-09-00  277.000000  277.000000  277.000000  277.000000       0
3  05-09-00  275.799988  275.799988  275.799988  275.799988       2
4  06-09-00  274.200012  274.200012  274.200012  274.200012       0

In [108]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6399 entries, 0 to 6398
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6399 non-null   str
 1   Open    6399 non-null   float64
 2   High    6399 non-null   float64
 3   Low     6399 non-null   float64
 4   Close   6399 non-null   float64
 5   Volume  6399 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 300.1 KB

# Enciding

In [109]:
from sklearn.preprocessing import LabelEncoder 
encoder=LabelEncoder()

In [110]:
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [111]:
df=encodla(df)

In [112]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6399 entries, 0 to 6398
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6399 non-null   int64
 1   Open    6399 non-null   float64
 2   High    6399 non-null   float64
 3   Low     6399 non-null   float64
 4   Close   6399 non-null   float64
 5   Volume  6399 non-null   int64
dtypes: float64(4), int64(2)
memory usage: 300.1 KB

# Scaling

In [113]:
from sklearn.preprocessing import MinMaxScaler

In [114]:
scaling=MinMaxScaler()

In [115]:
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('Volume')
df[num_col]=scaling.fit_transform(df[num_col])

In [116]:
df.sample(5)

          Date      Open      High       Low     Close  Volume
5572  0.493435  0.293720  0.284741  0.298215  0.296494      57
4231  0.611754  0.190943  0.184818  0.193921  0.192515       3
1365  0.858081  0.058345  0.056284  0.058564  0.058490      24
5220  0.776180  0.295289  0.287105  0.299337  0.296845      78
2380  0.301344  0.165249  0.163412  0.167700  0.166471      21

In [117]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6399 entries, 0 to 6398
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6399 non-null   float64
 1   Open    6399 non-null   float64
 2   High    6399 non-null   float64
 3   Low     6399 non-null   float64
 4   Close   6399 non-null   float64
 5   Volume  6399 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 300.1 KB

# Train

In [118]:
X = df.drop(columns='Volume')

In [119]:
y = df['Volume']

In [120]:
from sklearn.model_selection import train_test_split

In [121]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# Model selection

In [122]:
from sklearn.linear_model import LinearRegression

In [123]:
lr=LinearRegression()

In [124]:
lr.fit(X_train, y_train)

LinearRegression()

In [125]:
y_predection=lr.predict(X_test)

# EVALUATION

In [126]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [127]:
r2=r2_score(y_test,y_predection)
mse=mean_squared_error(y_test,y_predection)
rmse=pow(mse,(1/2))
mae=mean_absolute_error(y_test,y_predection)

In [128]:
print(r2)
print(mse)
print(rmse)
print(mae)

0.052557238721301025
693898091.0004408
26341.945467266476
9024.25853112146

# Decision Tree

In [129]:
from sklearn.tree import DecisionTreeRegressor

In [130]:
dr=DecisionTreeRegressor()

In [131]:
dr.fit(X_train,y_train)

DecisionTreeRegressor()

In [132]:
y_pred=dr.predict(X_test)

In [133]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [134]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [135]:
print('r2:',r2)
print('mae:',mae)
print('mse:',mse)

r2: 0.19390735065241027
mae: 4570.94765625
mse: 590374609.8570312

# Random F

In [136]:
from sklearn.ensemble import  RandomForestRegressor

In [137]:
rd=RandomForestRegressor()

In [138]:
rd.fit(X_train,y_train)

RandomForestRegressor()

In [139]:
y_pred=rd.predict(X_test)

In [140]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [141]:
print('r2:',r2)
print('mae:',mae)
print('mse:',mse)

r2: 0.4129910077376371
mae: 4973.262328125
mse: 429919817.6164311

In [142]:
from tabulate import tabulate

result = [
    ['Logistic Regression', 0.0525, 9024.25, 693898091.0004],
    ['Decision Tree', 0.2056, 4584.30, 581791013.2],
    ['Random Forest', 0.4358, 4760.15, 413196921.70],
    ['SVM',-0.030,4821.66,754605453.61]
]

headers = ['Algorithm', 'R2_score', 'MAE', 'MSE','SVM']

table = tabulate(result, headers=headers, tablefmt='grid')

print(table)

+---------------------+------------+---------+-------------+
| Algorithm           |   R2_score |     MAE |         MSE |
+=====================+============+=========+=============+
| Logistic Regression |     0.0525 | 9024.25 | 6.93898e+08 |
+---------------------+------------+---------+-------------+
| Decision Tree       |     0.2056 | 4584.3  | 5.81791e+08 |
+---------------------+------------+---------+-------------+
| Random Forest       |     0.4358 | 4760.15 | 4.13197e+08 |
+---------------------+------------+---------+-------------+
| SVM                 |    -0.03   | 4821.66 | 7.54605e+08 |
+---------------------+------------+---------+-------------+

# SVM

In [143]:
from sklearn.svm import SVR

In [144]:
svr=SVR(kernel='rbf',C=0.5)

In [145]:
svr.fit(X_train,y_train)

SVR(C=0.5)

In [146]:
y_pred=svr.predict(X_test)

In [147]:
from sklearn.metrics  import r2_score, mean_absolute_error

In [148]:
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

In [149]:
print('r2:',r2)
print('mae:',mae)
print('mse:',mse)

r2: -0.030332096200847092
mae: 4821.666183939366
mse: 754605453.6163611