In [144]:
import pandas as pd

In [145]:
df=pd.read_csv('/Users/a1/Desktop/MLFoundation/cleaned_merged_seasons.csv')

/var/folders/5h/9l3v88x94dgfs7159k0nvb2w0000gn/T/ipykernel_14050/174375154.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/Users/a1/Desktop/MLFoundation/cleaned_merged_seasons.csv')

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96169 entries, 0 to 96168
Data columns (total 37 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   season_x           96169 non-null  object
 1   name               96169 non-null  object
 2   position           96169 non-null  object
 3   team_x             76317 non-null  object
 4   assists            96169 non-null  int64
 5   bonus              96169 non-null  int64
 6   bps                96169 non-null  int64
 7   clean_sheets       96169 non-null  int64
 8   creativity         96169 non-null  float64
 9   element            96169 non-null  int64
 10  fixture            96169 non-null  int64
 11  goals_conceded     96169 non-null  int64
 12  goals_scored       96169 non-null  int64
 13  ict_index          96169 non-null  float64
 14  influence          96169 non-null  float64
 15  kickoff_time       96169 non-null  object
 16  minutes            96169 non-null  int64
 17  opponent_team      96169 non-null  int64
 18  opp_team_name      96169 non-null  object
 19  own_goals          96169 non-null  int64
 20  penalties_missed   96169 non-null  int64
 21  penalties_saved    96169 non-null  int64
 22  red_cards          96169 non-null  int64
 23  round              96169 non-null  int64
 24  saves              96169 non-null  int64
 25  selected           96169 non-null  int64
 26  team_a_score       96169 non-null  float64
 27  team_h_score       96169 non-null  float64
 28  threat             96169 non-null  float64
 29  total_points       96169 non-null  int64
 30  transfers_balance  96169 non-null  int64
 31  transfers_in       96169 non-null  int64
 32  transfers_out      96169 non-null  int64
 33  value              96169 non-null  int64
 34  was_home           96169 non-null  bool
 35  yellow_cards       96169 non-null  int64
 36  GW                 96169 non-null  int64
dtypes: bool(1), float64(6), int64(24), object(6)
memory usage: 26.5+ MB

# data bn tanishuv

In [147]:
df.head()

,season_x,name,position,team_x,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2016-17,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,454,...,2.0,0.0,0,0,0,0,55,False,0,1
1,2016-17,Aaron Lennon,MID,NaN,0,0,6,0,0.3,142,...,1.0,0.0,1,0,0,0,60,True,0,1
2,2016-17,Aaron Ramsey,MID,NaN,0,0,5,0,4.9,16,...,3.0,23.0,2,0,0,0,80,True,0,1
3,2016-17,Abdoulaye Doucouré,MID,NaN,0,0,0,0,0.0,482,...,1.0,0.0,0,0,0,0,50,False,0,1
4,2016-17,Adam Forshaw,MID,NaN,0,0,3,0,1.3,286,...,1.0,0.0,1,0,0,0,45,True,1,1

In [148]:
df.drop(columns=['season_x', 'name'], axis=1, inplace=True)

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96169 entries, 0 to 96168
Data columns (total 35 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   position           96169 non-null  object
 1   team_x             76317 non-null  object
 2   assists            96169 non-null  int64
 3   bonus              96169 non-null  int64
 4   bps                96169 non-null  int64
 5   clean_sheets       96169 non-null  int64
 6   creativity         96169 non-null  float64
 7   element            96169 non-null  int64
 8   fixture            96169 non-null  int64
 9   goals_conceded     96169 non-null  int64
 10  goals_scored       96169 non-null  int64
 11  ict_index          96169 non-null  float64
 12  influence          96169 non-null  float64
 13  kickoff_time       96169 non-null  object
 14  minutes            96169 non-null  int64
 15  opponent_team      96169 non-null  int64
 16  opp_team_name      96169 non-null  object
 17  own_goals          96169 non-null  int64
 18  penalties_missed   96169 non-null  int64
 19  penalties_saved    96169 non-null  int64
 20  red_cards          96169 non-null  int64
 21  round              96169 non-null  int64
 22  saves              96169 non-null  int64
 23  selected           96169 non-null  int64
 24  team_a_score       96169 non-null  float64
 25  team_h_score       96169 non-null  float64
 26  threat             96169 non-null  float64
 27  total_points       96169 non-null  int64
 28  transfers_balance  96169 non-null  int64
 29  transfers_in       96169 non-null  int64
 30  transfers_out      96169 non-null  int64
 31  value              96169 non-null  int64
 32  was_home           96169 non-null  bool
 33  yellow_cards       96169 non-null  int64
 34  GW                 96169 non-null  int64
dtypes: bool(1), float64(6), int64(24), object(4)
memory usage: 25.0+ MB

# Data Preprocessing

In [150]:
df.isnull().sum()

position                 0
team_x               19852
assists                  0
bonus                    0
bps                      0
clean_sheets             0
creativity               0
element                  0
fixture                  0
goals_conceded           0
goals_scored             0
ict_index                0
influence                0
kickoff_time             0
minutes                  0
opponent_team            0
opp_team_name            0
own_goals                0
penalties_missed         0
penalties_saved          0
red_cards                0
round                    0
saves                    0
selected                 0
team_a_score             0
team_h_score             0
threat                   0
total_points             0
transfers_balance        0
transfers_in             0
transfers_out            0
value                    0
was_home                 0
yellow_cards             0
GW                       0
dtype: int64

# Encoding

In [151]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
cols_to_process = [col for col in df.columns if df[col].dtype == 'object']

for col in cols_to_process:
    if df[col].nunique() <= 5:
        dummies = pd.get_dummies(df[col], prefix=col, dtype=int)
        df = pd.concat([df.drop(columns=col), dummies], axis=1)
    else:
        df[col] = encoder.fit_transform(df[col])

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96169 entries, 0 to 96168
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   team_x             96169 non-null  int64
 1   assists            96169 non-null  int64
 2   bonus              96169 non-null  int64
 3   bps                96169 non-null  int64
 4   clean_sheets       96169 non-null  int64
 5   creativity         96169 non-null  float64
 6   element            96169 non-null  int64
 7   fixture            96169 non-null  int64
 8   goals_conceded     96169 non-null  int64
 9   goals_scored       96169 non-null  int64
 10  ict_index          96169 non-null  float64
 11  influence          96169 non-null  float64
 12  kickoff_time       96169 non-null  int64
 13  minutes            96169 non-null  int64
 14  opponent_team      96169 non-null  int64
 15  opp_team_name      96169 non-null  int64
 16  own_goals          96169 non-null  int64
 17  penalties_missed   96169 non-null  int64
 18  penalties_saved    96169 non-null  int64
 19  red_cards          96169 non-null  int64
 20  round              96169 non-null  int64
 21  saves              96169 non-null  int64
 22  selected           96169 non-null  int64
 23  team_a_score       96169 non-null  float64
 24  team_h_score       96169 non-null  float64
 25  threat             96169 non-null  float64
 26  total_points       96169 non-null  int64
 27  transfers_balance  96169 non-null  int64
 28  transfers_in       96169 non-null  int64
 29  transfers_out      96169 non-null  int64
 30  value              96169 non-null  int64
 31  was_home           96169 non-null  bool
 32  yellow_cards       96169 non-null  int64
 33  GW                 96169 non-null  int64
 34  position_DEF       96169 non-null  int64
 35  position_FWD       96169 non-null  int64
 36  position_GK        96169 non-null  int64
 37  position_GKP       96169 non-null  int64
 38  position_MID       96169 non-null  int64
dtypes: bool(1), float64(6), int64(32)
memory usage: 28.0 MB

# Scaling

In [153]:
df.head()

,team_x,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,...,transfers_out,value,was_home,yellow_cards,GW,position_DEF,position_FWD,position_GK,position_GKP,position_MID
0,25,0,0,0,0,0.0,454,10,0,0,...,0,55,False,0,1,1,0,0,0,0
1,25,0,0,6,0,0.3,142,3,0,0,...,0,60,True,0,1,0,0,0,0,1
2,25,0,0,5,0,4.9,16,8,3,0,...,0,80,True,0,1,0,0,0,0,1
3,25,0,0,0,0,0.0,482,7,0,0,...,0,50,False,0,1,0,0,0,0,1
4,25,0,0,3,0,1.3,286,6,1,0,...,0,45,True,1,1,0,0,0,0,1

In [154]:
 from sklearn.preprocessing import MinMaxScaler
 scaler = MinMaxScaler()

In [155]:
num_col = df.select_dtypes(include=['int64','float64']).columns.drop('goals', errors='ignore')

In [156]:
df[num_col] = scaler.fit_transform(df[num_col])

In [157]:
df.head()

,team_x,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,...,transfers_out,value,was_home,yellow_cards,GW,position_DEF,position_FWD,position_GK,position_GKP,position_MID
0,1.0,0.0,0.0,0.140940,0.0,0.000000,0.583012,0.023747,0.000000,0.0,...,0.0,0.187500,False,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.181208,0.0,0.001755,0.181467,0.005277,0.000000,0.0,...,0.0,0.239583,True,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.174497,0.0,0.028672,0.019305,0.018470,0.333333,0.0,...,0.0,0.447917,True,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.140940,0.0,0.000000,0.619048,0.015831,0.000000,0.0,...,0.0,0.135417,False,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.161074,0.0,0.007607,0.366795,0.013193,0.111111,0.0,...,0.0,0.083333,True,1.0,0.0,0.0,0.0,0.0,0.0,1.0

# Model Selection

In [158]:
from sklearn.linear_model import LinearRegression

In [159]:
lr=LinearRegression()

In [160]:
lr

LinearRegression()

# Training

In [167]:
x = df.drop('goals_scored', axis=1)
y = df['goals_scored']

print("Features shape:", x.shape)
print("Target shape:", y.shape)

Features shape: (96169, 38)
Target shape: (96169,)

In [168]:
x = df.drop('goals_scored', axis=1)
y = df['goals_scored']

In [169]:
from sklearn.model_selection import train_test_split

In [170]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [172]:
lr.fit(x_train, y_train)

LinearRegression()

# Prediction

In [173]:
y_pred = lr.predict(x_test)

In [175]:
y_pred[1]

np.float64(0.0012432176933902528)

# Evaluation

In [177]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [178]:
mae = mean_absolute_error(y_test, y_pred)

In [179]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [180]:
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Absolute Error: 0.013865095932638577
Mean Squared Error: 0.0005080592693511028
R-squared: 0.8456803046680481